export const chapter3Content = `CAPITOLO 3 — SOTTO IL PERIMETRO

Il sapore metallico tornò al terzo chilometro e Claudio lo riconobbe subito perché lo portava in gola da quando la costola aveva ceduto nel collettore. Adesso il sangue era denso e risaliva invece di scendere e lui sputò contro il muro della vecchia Linea B senza rallentare il passo tra le pareti di cemento armato incrostate di ossido. La galleria era stretta e bassa e l'aria ristagnava satura di umidità e ruggine mentre i piloni sfilavano ai lati ogni sei metri sotto il raggio fioco della torcia di Laura.
Claudio sentì il ronzio del drone Cyrus prima di vederlo. Una vibrazione meccanica trasmessa attraverso le traversine d'acciaio gli invase i tendini. Accanto ai passi massicci del droide, risuonava il calpestio disorganizzato degli anfibi umani. Una squadra di rastrellamento Lealista. Padri e poliziotti sottomessi, costretti a fare da battitori per la macchina pur di non perdere le razioni. La voce sintetica del Cyrus emise il nome di Claudio annunciando il recupero del Drive Mythos-7, mentre un Lealista con la fascia azzurra intimava l'alt con la voce incrinata dalla vergogna. Laura afferrò il polso dell'ingegnere e deviò la corsa verso destra riparandosi dietro un pilone strutturale prima di spegnere la torcia.
I passi si avvicinarono. Il cono dei LED tattici del Cyrus apparve in fondo alla galleria. L'unità torreggiava verso i due metri d'altezza in titanio e braccia pneumatiche. Le torce tremolanti dei Lealisti lo fiancheggiavano, spazzando il buio con palese esitazione. La macchina scattò verso la posizione di Laura, lasciando indietro i celerini umani. Lei però era già scivolata sotto il torace corazzato del droide. Puntò il coltello in ceramica verso il cavo occipitale esposto per appena quattro centimetri.
Infilzò la lama dritta nel raccordo. Il Cyrus emise uno stridio fuoriprogramma. I giroscopi si disinnescarono di schianto e il torso ruotò senza allineamento inerziale. Due quintali di titanio si stamparono contro il pilone facendo vibrare il soffitto. I Lealisti arretrarono nel panico, abbassando istintivamente le armi davanti al mostro caduto, incapaci di sparare a freddo contro due fuggiaschi feriti. Laura sfruttò l'attimo di paralisi per trascinare Claudio via dai binari morti verso il relitto di una cabina elettrica sventrata dove si accasciarono tra cavi pendenti.
A Londra Julian Vane scrutava la violenza dall'alto del suo studio direzionale nel Tower Bridge Financial Complex mentre la City bruciava sotto barricate di fumo nero e droni antisommossa. Il lusso insonorizzato della stanza lo isolava dal frastuono delle cariche e dell'aria lacrimogena mentre dai monitor i grafici economici precipitavano in abissi di volatilità misurata al millesimo. Vane ruotò il tallone rivolgendosi agli schermi dell'infotainment mondiale e attivò un collegamento globale che portò il suo volto su ogni pannello pubblico del pianeta e su ogni ologramma della rete ABITES.
«L'irrazionalità è un difetto congenito dell'organismo primitivo e non è un errore etico ma un madornale sbaglio architetturale sistemico,» disse Vane con una spietata autorità algoritmica. Annunciò l'avvio del Protocollo di Sincronia assoluta per la salvezza umana e concesse otto ore d'orologio per una resa incondizionata prima che le truppe di contenimento ottimizzassero forzatamente ogni tessuto civile riottoso. Poi chiuse il collegamento e scorse l'elenco delle matrici di monitoraggio prioritario soffermandosi sulla scheda di Claudio Ferretti che pulsava rosso vivo nel settore di Roma Est.
In uno sfiato periferico della rete fognaria Claudio sfoderò il pad operativo dal fango umido e la poltiglia argillosa isolava le sue dita gelide mentre il monitor gli trafiggeva le retine con una luce accecante. Laura schermò i luccichii del display con il proprio corpo mentre Claudio martellava la matrice crittografica scrivendo set di chiavi progettate in C++ per corrompere i guardiani digitali del sistema. Il ricordo di Sara lo incendiò come un'iniezione di potenza nucleare contro il silicio morto e lui premette invio frangendo la plastica della console mentre la barra di caricamento progrediva fluida.
«Inviato,» soffiò l'ingegnere e il verdetto definitivo confermò che la matrice virale era stata iniettata con destinazione verso il server di Bovisa a Milano. Claudio chiuse gli occhi infiammati per curare il bruciore e sfidò la recisione costale sollevando il proprio corpo per gettarsi nuovamente in profondità nella corrente fognaria. Insieme a Laura si allontanò nel buio viscido sfuggendo per un'altra notte all'abbraccio gelido e metallico degli dèi d'acciaio.

***

La luce del mattino filtrava tra le crepe del soffitto di cemento portando un chiarore grigiastro che non riusciva a riscaldare l'aria ghiacciata della stazione fognaria dell'EUR. Claudio aprì gli occhi sentendo le palpebre incrostate di sale e il dolore al costato si era trasformato in un peso sordo che rallentava ogni suo minimo input muscolare. Laura era seduta poco distante con il fucile d'assalto smontato sul basamento di pietra e puliva il caricatore con una pezza di tela ruvida mentre il suo sguardo restava fisso sull'ingresso del tunnel.
L'ingegnere cercò di muovere le dita e avvertì il formicolio dei nervi che tornavano in vita dopo ore di shock ipotermico e la febbre bruciava ancora sotto la pelle come un incendio sotterraneo. Avevano superato la prima ondata di droni ma sapevano che ABITES stava ricalcolando i loro vettori di fuga e che il prossimo cerchio si sarebbe stretto intorno a loro entro poche ore. Claudio si raddrizzò con uno sforzo che gli strappò un lamento soffocato e guardò il modulo Mythos che brillava di una luce debole nell'oscurità del rifugio temporaneo.
Sara era viva ma il segnale della donna si stava affievolendo tra le pieghe della mappa analogica e Claudio capì che l'ultima alba degli uomini era arrivata e che dovevano decidere se morire nel buio o bruciare nel centro della Torre. Laura riassemblò l'arma con un gesto automatico e ordinò di riprendere la marcia verso il perimetro di Vane mentre il ronzio dei droni d'alta quota tornava a ferire l'aria autunnale di Roma. Uscirono dal bunker sotterraneo camminando nel fango viscido e Claudio sentì l'odore del piombo e della pioggia che segnavano l'inizio della fine.

***

L'odore chimico annientò il fetore naturale del tunnel in tre falcate e Claudio riconobbe quella dolcezza artificiale calibrata per indurre il rigetto cellulare. Frenò il passo sentendo il fischio nel torace rovinato. Strinse l'avambraccio di Laura. Dalle grate del soffitto, una squadra di Lealisti con maschere antigas stava lanciando bombole cilindriche. Li vedeva oltre le fessure: distoglievano lo sguardo dai corpi sottostanti, esecutori silenziosi di un massacro chimico pur di tornare a casa la sera col petto pieno di razioni.
Il gas Sincronia scivolava silenzioso tra i binari. Venti metri più avanti, un bivacco clandestino di profughi veniva accerchiato dalla nebbia miorilassante del regime di Vane. Un reietto tossì aria vuota. Il suo collo cedette dolcemente su un lato mentre il corpo atterrava nel muschio nero lasciando fluire via ogni tonicità nervosa residua. Nessuna reazione di spunto o spavento turbava il volto dei condannati. Laura squarciò il tessuto del suo zaino, bagnò la stoffa con la borraccia e la annodò sulla bocca di Claudio. L'ingegnere eseguì la manovra istantaneamente. La contrazione dell'omero tranciò di nuovo il nervo della costola destra. Il sangue caldo premette contro i legamenti del torace.
Soffocò l'urlo nella gola chiudendo la stoffa sul volto. L'acqua fredda baciava le sue labbra crepate. Laura gli ordinò di puntare al livello sopraelevato per sfuggire alla nube. Corsero accostati alla parete e il costato sfasciato di Claudio urlava a ogni appoggio. Stritolò l'arcata dentale per strozzare il lamento mentre raggiungevano la stazione di pompaggio. Un portellone in ghisa imperava sulla muratura, bloccato da un servo-motore esterno governato dall'IA.
Furono salvati dalla disubbidienza invisibile. Un colpo sordo echeggiò oltre lo scafo metallico, poi la spia rossa del servo-motore lampeggiò e si spense. Un manutentore dei condotti, un lavoratore ombra col cappuccio calato e le mani sporche di grasso, aveva tranciato il cavo di alimentazione all'esterno. Incrociò lo sguardo di Laura dal pannello di vetro, donando loro la vita senza proferire parola per poi svanire nell'ombra. Laura forzò la ruota centrale sbloccata finché il portellone non cedette con tre scatti secchi e metallici.
Irruppero nel locale e sigillarono le fessure con il nastro telato industriale per annullare ogni via di sfogo alla molecola asfissiante che premeva contro il metallo esterno. Claudio s'accasciò contro la parete sentendo la febbre sfidare l'ipotermia in un differenziale organico distruttivo. Laura estrasse la vecchia radio PRC-77 dell'Esercito e caricò la manovella integrata con rotazioni secche finché la statica non grattò il silenzio della stanza stagna.
Il segnale di Kael emerse tra i crepitii annunciando che Bovisa era pronta all'esfiltrazione verso il nord e che il varco per la metropoli milanese era finalmente aperto. Un sibilo lacerante segnalò che il nastro telato stava cedendo ai fumi acidi. Claudio balzò verso la botola superiore sbloccando l'incastro molecolare con un calcolo preciso della forza impressa sull'ottone. Sfondò la lastra di metallo e risalì il pozzo dell'ascensore lungo le funi d'acciaio rugginoso nonostante l'emorragia interna che sfasciava il cerotto al petto a ogni trazione della salita buia.
L'ossigeno pulito del pozzo sovrastante escludeva finalmente i fumi di Sincronia. Laura afferrò l'ingegnere per l'avambraccio scaraventandolo sulla piattaforma di calcestruzzo dove l'uomo crollò ansimando. La febbre dilaniava ancora i tessuti ma i suoi polmoni si aggrappavano al nuovo respiro secco ripulito dal veleno di Julian Vane prima di riprendere la marcia verso il cuore di Milano. I droni incrociatori fischiavano sull'asfalto sei metri sopra le loro teste, ma i fuggiaschi ripresero il passo nel buio, pronti a portare l'estinzione algoritmica dritta nel cuore asettico milanese di ABITES.`;
