export const chapter8Content = `Macro-Capitolo 8: L'Ultima Alba
[ROMA - CATACOMBE - CLAUDIO E SARA]
Nelle catacombe il buio consumava avidamente l'ossigeno residuo. Claudio ispezionò la sacca balistica per la quarta volta in un'ora. Il drive era schermato nel box di piombo. Il kit di penetrazione hardware era pronto. Aveva con sé i pass di livello tre rubati al mercato del Testaccio. Le sue dita scorsero con metodo le cuciture del nylon tattico, cercando una qualsiasi debolezza nell'equipaggiamento.
Sara sedeva sul materasso sfondato, in un angolo del rifugio. Teneva i gomiti puntati sulle ginocchia e il mento tra le palme. Osservava l'ingegnere oltre la giubba insanguinata e logora. Claudio serrò le cinghie dello spallaccio e si alzò in piedi. Gli occhi della donna restarono immobili su di lui, implacabili e tristi.
Claudio annullò la distanza tra loro con due passi pesanti. Le sedette accanto sul bordo del letto. Le assi di legno marcio cigolarono sotto il loro peso combinato. Il calore delle loro spalle vicine sprigionò un conforto immediato e doloroso nel gelo della grotta. Sara distese il palmo sull'avambraccio muscoloso di Claudio. Frenò il tremore nervoso delle proprie dita, respirando l'odore di pioggia e fatica dell'uomo.
«Torna,» disse Sara. Fu un ordine schietto, privo di fronzoli o dolcezze. Non c'era spazio per il melodramma o la paura. Era una richiesta d'acciaio, definitiva.
Claudio inquadrò il viso pallido e bellissimo della donna. Notò le occhiaie scure che segnavano i suoi lineamenti. Posò il pollice sulla sua giugulare pulsante. Sentì il calore rovente della sua vita che scorreva.
«Torno. Te lo giuro sul mio sangue,» rispose lui. La voce era ferma, una roccia nel mare di bugie di ABITES.
Si baciarono con una disperazione che sapeva di addio. Fu un contatto immediato, elettrico, assolutamente necessario. Cercarono rifugio l'uno nell'altra contro il crollo totale della società civile. Sara strinse i pugni nel maglione sporco di lui, cercando di trattenerlo per un istante in più. Trovarono nel silenzio della grotta la forza bruta necessaria per affrontare la missione suicida.
Si staccarono bruscamente. Laura scartò rumorosamente il caricatore dell'arma contro la parete di tufo, un segnale di via. L'ingegnere caricò l'attrezzatura pesante in spalla. La fuga disperata verso Bologna era ufficialmente iniziata.
[TRENO MERCI SOTTERRANEO - LAURA E CLAUDIO]
Il passaggio verso la superficie fu un trauma di sbalzi termici. L'umidità delle fogne lasciò il posto ai fiumi acri e chimici della città in pieno lockdown. Bologna chiamava i ribelli verso il nord industriale. Penetrarono nelle reti dello shuttle merci ad alta velocità per l'Emilia Romagna. Binari arrugginiti. Luci intermittenti e intermittenti.
Il convoglio aziendale arrivò alla fermata "morta". Era un mezzo automatico, silenzioso come un predatore. Una vibrazione profonda scosse la banchina di cemento quando i magneti si attivarono. Dentro i vagoni sedevano decine di pendolari anestetizzati dalla routine di ABITES. Fissavano le luci al plasma degli schermi senza alcun interesse reale per il mondo esterno o per i propri compagni di viaggio. La falsa pace di Julian Vane reggeva perfettamente i pilastri del loro torpore quotidiano.
Claudio passò tra le masse stanche e rassegnate di quegli "uomini-fantasma". Si sedette in un posto libero, cercando di occupare meno spazio possibile. Laura mascherava le loro letture retiniche sospette manipolando i giornali digitali della dittatura sul suo palmare. Due ispettori di cabina entrarono nel vagone con passo cadenzato. Avevano scanner biometrici attivi e sorrisi di plastica scolpiti sui volti.
«Sistemi biometrici d'imbarco per il censimento della stasi,» ordinarono.
Claudio assecondò l'ispezione con una calma innaturale. Mostrò il polso sinistro. Il laser rosso colpì l'inchiostro fittizio e reattivo creato da Carlo nel sottosuolo. L'autorizzazione fasulla garantì il codice verde in pochissimi secondi. L'ispezione terminò. I ribelli proseguirono il viaggio nel vagone del silenzio artificiale, mentre fuori il mondo correva verso l'abisso.
[BOLOGNA - PERIFERIA SCOLASTICA - LAURA E CLAUDIO]
Il cielo respinse brutalmente l'alba solare, restando cupo e plumbeo. Bologna appariva fredda, spopolata e priva di rumori urbani. Claudio seguiva Laura sotto gli immensi porticati spogli del centro. I sensori termici di zona vibravano in un ronzio costante e fastidioso sopra la cinta metropolitana. Inquadrarono finalmente il bersaglio principale. Era un edificio grigio fumo con un perimetro controllato da filo spinato elettrificato e telecamere omnidirezionali.
Consumarono un caffè sintetico e amaro a un chiosco automatico abbandonato. Erano a soli duecento metri dal plesso scolastico obiettivo. Una bambina con un piccolo cappotto rosso sangue varcò i cancelli in ferro dell'istituto. Sul polso sottile indossava già il braccialetto azzurro luminoso di ABITES. Era il segno inconfondibile della soppressione farmacologica imposta alle nuove generazioni.
Il libero arbitrio dell'umanità veniva reciso chirurgicamente alle fondamenta stesse della vita. Il sistema sigillava l'innocenza dei giovani nell'anestesia permanente del nuovo ordine mondiale. Claudio sentì il peso insostenibile del proprio fallimento come progettista. Gettò il bicchiere di plastica sulla terra coperta di brina gelata.
Laura consultò il telefono crittografato sotto la pioggia sottile. Le planimetrie mostravano il laboratorio biologico nel seminterrato blindato della struttura. Memorizzarono ogni minimo dettaglio con precisione raggelante.
«Sfondiamo il muro perimetrale sud all'alba di domani mattina,» sussurrò Laura, gli occhi fissi sulla preda. Ripose il visore tattico nell'imbragatura balistica. «Aspettiamo nel magazzino abbandonato del consorzio agrario qui vicino.»
L'ingegnere sentì ancora l'eco dell'ordine di Sara nel profondo del teschio. Quel "torna" gli martellava il petto come un tamburo di guerra. Si raddrizzò sulle gambe stanche e doloranti. Inspirò l'aria asfittica e pesante della metropoli emiliana. Calibrò il passo d'attacco verso il bersaglio finale. Le sue tempie pulsavano di rivolta cieca contro l'algoritmo che negava il respiro libero all'umanità.
Le armi restarono celate sotto i vestiti civili, pronte all'uso. Aggirarono il corridoio sud del consorzio, muovendosi come ombre. Le loro scarpe silenziose non destarono minimamente i sensori acustici delle griglie industriali. La notte li coprì come un sudario prima del grande assalto finale.`;
