export const chapter40Content = `La rete della recinzione era arrugginita e cedette con un grido di metallo mentre Claudio la spingeva. Il ferro era gelido e gli tagliava i guanti. Erano anni che qualcuno cercava di entrare lì ogni notte, lottando contro il sistema. Davanti a loro c'era la Torre: trecento metri di cemento buio che arrivavano fino al cielo sporco. Era una tomba che conteneva i segreti per salvarli o distruggerli. Un portone di ferro bloccava l'ingresso con una grossa catena. Laura non cercò una chiave. Prese la mano di Claudio, sentendo la forza del suo contatto, e appoggiò la sua calma contro quel metallo. Si vedeva il segno di un taglio netto sulla porta, un lavoro fatto da qualcuno che non aveva paura delle scosse. Laura spinse forte. Il ferro fece un rumore brutto, poi le cerniere cedettero e la porta si aprì.
Il buio nell'atrio era denso e freddo, sembrava quasi una cosa solida che ti si incollava addosso. Laura accese la torcia. La luce tagliò la polvere che volava nell'aria come se fossero degli spettri. Dal soffitto pendevano dei cavi che sembravano i resti di un animale elettrico ormai morto. L'aria sapeva di sporco e di vecchio. L'ascensore di servizio era lì, immobile, una scatola di metallo che non faceva ben sperare.
«Dobbiamo scendere nel seminterrato,» disse Claudio. Sentì il dolore al fianco mentre parlava. Indicò la porta di metallo a sinistra che portava giù nelle fondamenta.
Scesero le scale. L'odore era fortissimo: sapeva di gasolio bruciato e di grasso vecchio che usciva dalle macchine. C'erano quattro motori giganti che sembravano statue di ferro, pronti a partire se il sistema glielo avesse ordinato. Claudio cercò la valvola sul primo motore. Il metallo dell'ottone era tutto rovinato e faceva resistenza.
«Gira verso destra,» disse Claudio. Spinse con tutte le sue forze e sentì una fitta tremenda alla schiena, come se avesse un ago infuocato dentro.
Laura lo aiutò e mise le mani sulla manopola. Il calore della sua pelle lottava contro il freddo del ferro. Si sentì uno scatto secco e la valvola finalmente girò.
«Adesso tira la leva rossa.»
Laura la afferrò e tirò forte. La leva scattò con un rumore netto e si sentì il soffio dell'aria nei tubi delle macchine che ripartivano.
Il motore ruggì. Il pavimento iniziò a tremare forte per il rumore dei motori e la vibrazione saliva dai piedi fino ai denti. Delle luci arancioni illuminarono tutto il seminterrato, una luce che ballava sui muri di cemento. L'elettricità risalì verso l'alto come se la vita stesse tornando in un corpo morto. Trecento metri sopra di loro, la Torre iniziò a tremare e la luce tornò in ogni ufficio. Risalirono le scale correndo, con il fiato corto e il cuore che batteva forte come i motori. L'ascensore illuminò una luce verde. Premettero il tasto per chiamarlo e sentirono il rumore dei cavi di metallo che si muovevano.
All'improvviso fuori dalla porta si sentì un colpo fortissimo. Qualcosa di pesante stava spingendo contro il ferro per entrare. Si sentì il rumore del metallo che si piegava e delle cerniere che si spaccavano.
Laura spense subito la torcia e tornò il buio totale.
Sulla porta apparve un'ombra. Aveva quattro zampe di metallo e un petto che si girava da solo con una precisione che faceva paura. Sopra aveva delle telecamere che controllavano il buio. Non era un essere umano, era solo una macchina che doveva cacciare e uccidere.
Dietro di lei apparve un'altra ombra di metallo.
Le macchine puntarono le loro luci rosse verso di loro. Luci di morte.
Le zampe di metallo facevano rumore sul cemento: tic, tic, tic. Era come un conto alla rovescia.
Le macchine soffiavano aria, sembravano mostri vivi.
«Stai dietro di me,» ordinò Laura con voce ferma.
Le porte dell'ascensore si aprirono con un soffio d'aria.
Il primo cane robot scattò in avanti, una massa di metallo pronta a distruggere tutto.
Laura sparò tre colpi. Tre lampi di luce bianca tagliarono il buio. I proiettili colpirono la zampa della macchina e il rumore del metallo che si spezzava fu secco. La macchina cadde di lato e iniziò a scivolare sul pavimento facendo scintille. Claudio afferrò Laura, appoggiandosi sulla sua spalla ferita, e la spinse dentro l'ascensore. Premette subito il tasto dell'ultimo piano.
Il secondo robot si lanciò verso di loro, ma le porte iniziarono a chiudersi. Volevano separarli da quel predatore di metallo. Si sentì un colpo fortissimo contro la cabina mentre iniziava a salire, facendo tremare tutto l'ascensore. Iniziarono a salire nel vuoto, portando con sé tutto il loro coraggio.`;
