export const chapter32Content = `Macro-Capitolo 32: L'Intercapedine
[TORRE ABITES - INTERCAPEDINE - CLAUDIO E LAURA]
Claudio strisciò nello scavo clandestino tra il muro di fondazione e la struttura interna della Torre. Avanzava nel buio assoluto del vuoto tecnico. Premette la spalla sinistra contro la roccia viva dell'altura romana, mentre il palmo della mano sana cercava la parete opposta di cemento grezzo. Guadagnava centimetri contro la materia, spingendo il corpo esausto con piccoli scatti dei piedi.
La strettoia misurava ottanta centimetri nel punto più largo. La polvere di calce, sollevata dal loro passaggio, saturava ogni respiro. Aveva un sapore aspro, minerale, che gli seccava la gola e i polmoni già provati. Laura lo seguiva a brevissima distanza. I suoi fruscii minimi, il suono del kevlar che sfregava contro la pietra, definivano la sua posizione in quel vuoto senza fine.
Il braccio ustionato dell'ingegnere sfiorò la roccia ruvida per errore. Claudio soppresse un grido, mordendosi il labbro fino a farlo sanguinare. Spostò tutto il peso sul fianco destro, forzando le articolazioni dolenti.
Voci radio codificate risuonarono improvvisamente oltre la parete di cemento, a non più di due metri da loro. Erano ordini secchi, militari. Passi pesanti e ritmati delle truppe lealiste avanzavano nel corridoio parallelo. La squadra di ricerca tattica stava braccando la loro posizione termica. Claudio accelerò il movimento, ignorando il rischio di fare rumore.
Il passaggio si restrinse ulteriormente a sessanta centimetri. Una curva brusca dello scavo costrinse l'uomo a schiacciare entrambi i lati del corpo contro la materia fredda. Si fermò, bloccato. Laura premette con forza contro la sua schiena per spingerlo oltre. Fu un contatto fisico forzato dal perimetro angusto, caldo e spaventosamente reale in quel sepolcro tecnologico.
Laura afferrò le mani di lui nel buio. Con un movimento rapido, versò del disinfettante residuo sulla ferita aperta del deltoide. Il liquido bruciò come fuoco vivo nella polvere. Claudio serrò la mascella fino a sentire i denti scricchiolare. Isolò il dolore chimico, trasformandolo in energia per l'ultima risalita. I soldati all'esterno si fermarono, perlustrando l'area con i visori termici. Il silenzio nell'intercapedine divenne assoluto.
Un rumore metallico scese all'improvviso dal soffitto tecnico. Un drone aracnoide, un modello di ispezione condutture a otto zampe, si calava in verticale tra i tubi. Era un predatore termico progettato per scovare le fughe di calore.
Laura strappò la propria giacca termica. Avvolse Claudio e lo premette con una forza disperata contro la pietra geologica gelida, cercando di dissipare il calore dei loro corpi. Impose un ritmo nullo al respiro, bloccando l'espansione del torace.
Il ragno meccanico si fermò esattamente sopra le loro teste. Il suo raggio laser di scansione esplorò il vuoto circostante, una lama rossa sottile che tagliava l'oscurità come un rasoio. Il raggio sfiorò le pupille spalancate di Claudio. L'uomo non sbatté le palpebre. Restò immobile, un riflesso di marmo nel buio. Dopo lunghi secondi di tensione insostenibile, l'aracnoide scivolò via lungo un tubo orizzontale, allontanandosi verso i livelli inferiori.
Laura allentò la presa sul corpo dell'uomo. Claudio sentì il freddo bruciante dell'aria sulla pelle sudata del viso. Ripresero a muoversi, risalendo lentamente verso il punto di accesso al settore dell'EUR. Ogni centimetro conquistato era un passo in meno verso la fine di ABITES. Erano i fantasmi dentro la macchina, i virus organici che la Torre non riusciva più a digerire.`;
