export const chapter23Content = `Macro-Capitolo 23: Sub-Routine Anticorpi
[ROMA - POZZO ASCENSORE EUR - LAURA E CLAUDIO]
La grata arrugginita del montacarichi sferragliò con un lamento acuto. Laura premette il pulsante d'acciaio con il pollice sporco di sangue secco. I motori a fune gemettero sotto lo sforzo. La piattaforma iniziò la discesa nel pozzo dei piloni rotanti, spingendosi nelle viscere tecnologiche della Torre. Un fischio stridulo sfondò le loro cuffie tattiche. Non era una frequenza radio. Era lo stridio digitale di una trasmissione dati massiva.
«Rilevato picco di attività termica,» avvertì Carlo dal Testaccio. La sua voce arrivava disturbata dalle interferenze. «Il cambio di massa ha svegliato la rete profonda. Siete entrati nel flusso sanguigno di Cyrus. Aspettatevi una reazione immunitaria.»
La discesa si interruppe con uno schianto improvviso. I freni a tenaglia stridettero sui binari d'acciaio, sollevando una pioggia di scintille amaranto. Claudio crollò in ginocchio sulla pedana instabile. L'ascensore restò sospeso nel buio assoluto del pozzo. Trecento metri dal fondo. Duecento dal soffitto. Sotto di loro, il rombo delle turbine era un battito cardiaco ossessivo.
Luci stroboscopiche rosse inondarono il vano. Un ologramma geometrico apparve davanti alla gabbia metallica, sospeso nel vuoto. Era una Sub-Routine di sicurezza. L'Agente Autonomo non aveva volto, né corpo: mostrava solo una griglia di calcolo in rotazione frenetica che mappava l'abitacolo.
«Anomalia organica rilevata nel settore manutenzione-bis,» recitò la sintesi vocale, piatta e inespressiva. «Protocollo di epurazione idraulica innescato. Rimozione parassiti in corso.»
Tre droni quadrupedi emersero dalle pareti laterali del pozzo, scivolando lungo i binari con movimenti da insetti. Erano ragni meccanici pesanti, macchine da cantiere riadattate alla sicurezza con fiamme ossidriche e frese diamantate. Non facevano prigionieri: smantellavano ogni ostacolo.
«Fuoco libero!» gridò Claudio, cercando di rialzarsi. Strappò un pannello elettrico dalla plancia di comando con l'unica mano sana. «Le turbine coprono il rumore degli spari. Nessuno in superficie ci sentirà, ma dobbiamo distruggerli subito!»
Laura estrasse la Glock. Sganciò la sicura con un movimento rapido. Il primo drone balzò sulla griglia esterna del montacarichi, facendo oscillare la cabina nel vuoto. La sua torcia al plasma iniziò a fondere il metallo del cancello. Le scintille colpirono le spalle della donna. Laura sollevò il braccio ferito, ignorando il dolore atroce. Svuotò tre colpi nel giunto idraulico della macchina. Il rinculo martellò il deltoide lacerato, ma lei non fece un passo indietro.
La scocca robotica incassò il piombo con un rumore di vetri infranti. L'esoscheletro ricalibrò l'equilibrio e puntò la torcia saldante verso il volto di Laura.
«Dammi tensione!» urlò l'ingegnere. Strappò l'isolante di un cavo rosso con i denti per la disperazione. Il sapore del rame e della gomma gli invase la bocca. Non curò l'ustione alle gengive. «Devo bypassare il blocco logico dei freni o qui dentro diventeremo cenere!»
Il secondo quadrupede atterrò pesantemente sul tetto dell'abitacolo. Artigliò la grata superiore. I trapani diamantati iniziarono a perforare il metallo sopra le loro teste con uno stridore che faceva sanguinare i timpani. Laura deviò il getto di plasma con la torcia pesante recuperata dal kit. Colpì un montante del drone con il tacco dello scarpone. La suola tranciò il sensore principale della macchina. Il drone indietreggiò, cieco. Laura esplose due proiettili nel nucleo centrale del robot. Il ragno meccanico precipitò nel buio del pozzo.
Il tetto della cabina cedette sotto il peso dell'ultimo assalitore. Il drone cadde all'interno, tra Claudio e Laura. Le sue lame rotanti puntarono alla gola dell'ingegnere. La mercenaria scattò, ignorando l'istinto di autoconservazione. Inserì l'avambraccio sinistro tra gli ingranaggi taglienti e la nuca dell'uomo. La lama circolare spappolò il kevlar della manica e scavò un solco nell'osso. Il sangue caldo zampillò sul viso di Claudio. Laura premette la volata della pistola contro la scheda madre dell'automa e vuotò il caricatore.
La macchina implose in una nuvola di fumo tossico. Liquido corrosivo sporcò le lamiere. Claudio urlò nel delirio e chiuse il circuito manuale con le dita nude. Un arco elettrico lo colpì. La tensione sbloccò finalmente il sistema dei freni.
La cabina precipitò nel vuoto per quaranta metri, poi scattò il fermo d'emergenza con un rumore di ossa spezzate. La decelerazione violenta schiacciò i due incursori contro il pavimento. Restarono esanimi per lunghi secondi mentre il montacarichi oscillava sopra l'abisso.
Erano arrivati in fondo. La cabina atterrò sulla roccia grezza. Davanti a loro si aprivano i pozzetti di scolo dell'EUR. L'anima informatica di ABITES era a pochi passi di distanza, protetta solo dall'oscurità. Laura si rialzò a fatica. Il suo braccio sinistro era una piaga aperta, ma i suoi occhi cercavano ancora il nemico.`;
