export const chapter1Content = `Capitolo 1: Piazza Vittorio
L'odore di pioggia sui sanpietrini e di terra bagnata anticipava il resto. Il vento girava e l'aria diventava pesante, carica di uno smog denso che lasciava un retrogusto aspro in fondo alla gola. Claudio deglutiva, riconoscendo quel sapore familiare.
Si stringeva nel bavero del cappotto mentre entrava nella fila sotto i portici. Facce grigie spiccavano sotto un cielo altrettanto spento. Uomini e donne rattoppavano i giubbotti alla meglio e fasciavano le scarpe in sacchetti di plastica. Tutti affondavano le mani nelle tasche per difendersi dall'umidità.
Un vecchio si appoggiava a una colonna scrostata. Stringeva un pezzo di cartone con lettere tracciate in vernice nera, ormai sbavate dall'acqua: "E vidi, ed ecco un cavallo bianco; e colui che lo cavalcava aveva un arco; e gli fu data una corona". Il vecchio fissava il vuoto, mormorando parole che si perdevano nel rumore dell'acquazzone. «Il falso messia... il marchio... non prendete il marchio...»
Claudio distoglieva lo sguardo, cercando distrazione nel conteggio delle persone. Tre file avanti, un bambino scivolava verso una saracinesca abbassata. La madre lo afferrava per il braccio e lo tirava a sé con violenza, senza staccare gli occhi dal tornello. Il piccolo restava muto, aggrappato alla gamba della donna.
Claudio osservava le scarpe dell'uomo davanti a sé. La pozza d'acqua attorno ai suoi talloni rifletteva una lucentezza iridescente, sporca di residui oleosi scaricati dai filtri di ventilazione della piazza.
Pensava a Sara. La immaginava al sicuro tra le montagne, dove l'aria sapeva di pino e di freddo pulito. Custodiva quel messaggio vocale nel telefono come una bussola. Il suo nord.
Percepiva una presenza alla sua destra. Qualcuno respirava in modo lento e controllato. Claudio si voltava appena. Una donna sui trent'anni, con i capelli scuri appiattiti dalla pioggia e un cappotto anonimo, lo guardava. L'attenzione di Claudio cadeva sul suo polso denudato: niente braccialetto identificativo. Gli occhi di lei fissavano il tornello, ignorando una donna anziana che piangeva dopo il rifiuto dello scanner.
L'enorme schermo del palazzo illuminava il portico a giorno. Il volto di un annunciatore virtuale dalle simmetrie inquietanti scandiva le parole con finta rassicurazione: «La fase tre di ABITES garantisce la sicurezza collettiva dei Nodi Urbani.»
La donna alla sua destra esalava un respiro secco. Claudio notava le sue nocche bianche, serrate attorno a una busta vuota. La folla premeva verso il centro del portico per ripararsi dalla pioggia. Il braccio di lei sfiorava quello di Claudio. Sentiva il tessuto bagnato contro il tessuto bagnato. Claudio serrava la mascella.
«Un passo decisivo verso la rinascita,» proseguiva la voce sintetica dall'alto.
«Rinascita,» mormorava la donna con tono svuotato da ogni emozione.
Claudio lasciava passare qualche istante. «Di cosa.»
Lei girava appena la testa, gli occhi dritti davanti a sé. «La tua busta. Pesa poco.»
Claudio abbassava gli occhi sulla propria sacca di carta riciclata. «Sì.»
Un drone di pattuglia passava a bassa quota sopra il portico. Il ronzio dei rotori scendeva di frequenza, trasmettendo una vibrazione sorda direttamente nello sterno. Claudio stringeva i pugni nelle tasche. Lui e la donna alzavano gli occhi nello stesso momento, per poi riabbassarli in perfetta sincronia.
Il suo turno arrivava. Claudio appoggiava il palmo sullo scanner. Il vetro ghiacciato registrava il battito cardiaco e la temperatura corporea prima che la luce passasse al verde. Ritirava la razione e usciva dalla fila senza voltarsi.
Quella donna non cercava cibo. L'aveva già incontrata in un posto sepolto nella memoria che preferiva dimenticare.
«Se lallero», pensava Claudio, con un'amarezza che gli seccava la bocca.`;
