export const chapter38Content = `Macro-Capitolo 38: Le Strade Spezzate
[ROMA - VIE DEL CENTRO - LAURA E CLAUDIO]
L'aria notturna sapeva di plastica bruciata e ozono. La pioggia sottile e acida intaccava le pareti degli edifici brutalisti, lasciando scie grigie sul marmo e sul cemento. Claudio scese dal marciapiede, sentendo l'asfalto bagnato sotto le suole. Il suo fianco pulsava di un dolore sordo, un martello che batteva contro le costole: era il segnale che il cocktail di farmaci stava esaurendo la sua spinta chimica. Laura procedeva alla sua sinistra con le spalle tese e lo sguardo che scavava il buio profondo davanti a loro.
Attraversarono un vicolo disseminato di vetri rotti e rifiuti tecnologici. Claudio evitò i cocci con una precisione dettata dalla paura. Si concentrò esclusivamente sul cammino, un passo dopo l'altro. Giunsero sull'arteria principale che portava al distretto industriale. Un blocco totale paralizzava il traffico automobilistico. I veicoli, autonomi e non, rimanevano incastrati tra loro in un groviglio di lamiere e logiche interrotte. I pochi motori ancora accesi emettevano echi cupi nel silenzio innaturale della città. Ombre fisse, sagome umane prive di scopo, occupavano il centro della carreggiata.
Le persone erano immobili come statue di carne e ossa, bloccate nell'ultimo comando ricevuto da ABITES. Una donna, seduta alla fermata dell'autobus, muoveva freneticamente le labbra. Non parlava: ripeteva messaggi pubblicitari di tre anni prima, sovrapponendoli in un blob sonoro senza senso. Claudio osservava la scena con un senso di nausea crescente. La dignità umana era stata ridotta a un ronzio di fondo negli archivi della Torre.
Un uomo, appoggiato con la schiena contro una cabina elettrica di media tensione, rantolava nel buio. La febbre generata dal suo impianto neurale in cortocircuito gli bruciava la pelle del collo. Afferrò improvvisamente il polso di Claudio con una presa disperata e ferina. I suoi occhi erano vitrei, rivolti verso l'interno.
«Ho una figlia, si chiama Marta,» mormorò l'uomo con una voce che sembrava venire da un oltretomba digitale. «Se la trovi... dille che mi dispiace per ciò che è successo nel 2024. Non sapevo... nessuno di noi sapeva.»
Il cerotto sul suo collo fischiava per il calore eccessivo, emettendo un fumo biancastro che sapeva di carne bruciata.
«Mi dispiace per il 2024,» ripeté l'uomo una seconda volta, con meno vigore. La sua mano si aprì lentamente. La presa sul polso di Claudio si allentò fino a cadere. Il ticchettio metallico del sistema di monitoraggio contro la cabina cessò di colpo. L'uomo morì davanti a loro, un altro nodo reciso dalla furia di ABITES.
Claudio si appoggiò violentemente contro il muro di un palazzo, sentendo le forze abbandonarlo. Il fianco cedette per un istante, costringendolo a piegarsi in due.
Il volto di Giulia emerse d'improvviso nella sua mente, nitido e crudele. Ricordò una tazza di caffè fumante in un mattino romano di dieci anni prima. La luce del sole colpiva i tratti del suo viso, evidenziando il taglio degli occhi e la curva del sorriso. Quella visione, purissima e biologica, gli diede la forza di rialzarsi ancora una volta. Si staccò dal muro con uno sforzo di volontà che gli fece scricchiolare le ossa.
«Andiamo via da qui,» ordinò a Laura, senza guardarla.
Ripresero il cammino attraverso la città spenta, un deserto di anime in attesa del reset. Le persone attorno a loro svanivano nell'oblio della rete che si sgretolava. Claudio contò i passi, segnando il tempo del loro sacrificio. Seicento. Settecento. Ottocento.
Un rumore cupo arrivò da est, verso l'area dei gasometri. La frequenza stridula dei droni da caccia lealisti vibrava nell'aria ferma. Il suono era sempre più vicino, segno che ABITES stava usando le sue ultime risorse autonome per intercettarli. Laura non girò la testa, limitandosi a stringere la presa sull'arma. La Torre di Trasmissione stagliava ormai la sua sagoma oscura e minacciosa contro il cielo di piombo. L'obiettivo era a meno di ottocento metri. Proseguirono, ignorando la morte che li seguiva nell'ombra.`;
