export const chapter5Content = `CAPITOLO 5 — IL CROLLO FISICO

Le unità tattiche arrivarono senza sirene e quattro veicoli blindati si fermarono lungo il vialetto dell'ex impianto di verniciatura in una sincronia perfetta di motori elettrici. I portelli si aprirono e sedici operatori scesero in formazione cardinale intorno all'edificio con le armature grigie e i visori termici abbassati per la scansione del perimetro. Kael captò l'avanzata sulla telecamera integrata nel cancello e si alzò dalla console indicando a Claudio e Laura la condotta di scolo nascosta dietro il terzo rack metallico della parete ovest.
I droni perforanti scesero dai vani laterali dei blindati come sfere metalliche opache e pesanti e attivarono le trivelle retrattili mordendo il cemento con una vibrazione secca che Claudio percepì fin dentro i denti. Laura raggiunse la parete ovest e spostò il rack con i cavi che si tensero fino a saltare dai morsetti rivelando il pannello d'acciaio bloccato da grossi bulloni esagonali che l'ossido aveva parzialmente saldato. Il soffitto smise di vibrare e colpi sordi risuonarono sul portello stagna mentre i droni puntavano il calore dei server per scendere direttamente nella sala comando.
Laura rimosse l'ultimo bullone e aprì il varco su un buio che sapeva di cemento bagnato e fango stagnante proprio mentre il primo cardine del portello principale cedeva sotto la pressione pneumatica di Cyrus. Un braccio meccanico infilò la testa prensile nella fessura contorcendo il metallo e Claudio lo colpì con un frammento di tubo in ghisa strappato dalla parete est sentendo l'urto risalire lungo le braccia. Il braccio robotico arretrò e Laura infilò la custodia di neoprene con il virus Mythos sotto il giubbotto afferrando Claudio per i vestiti mentre lui restava a fissare Kael immobile davanti ai monitor.
L'hacker non smetteva di scrivere e apriva finestre di comando collegate ai detonatori sotto i rack mentre i soldati di ABITES sfondavano il portello stagna entrando con le armi spianate nel bunker. Laura sparò alcuni colpi con la pistola assemblata per coprire la ritirata e Claudio s'infilò nella condotta di ghisa fredda spingendo con forza nel tunnel stretto nonostante il dolore alla costola che bruciava a ogni respiro. Laura chiuse il pannello dall'interno e la detonazione termica innescata da Kael sollevò il soffitto della fabbrica cancellando la sala comando sotto una pioggia di fumo e detriti.
L'onda di pressione percorse la condotta spingendo i fuggiaschi in avanti per inerzia verso il collettore fognario dove l'odore di solfuri saturava l'aria densa di umidità. Raggiunsero la cloaca centrale e Laura trascinò Claudio mentre il silenzio di Bovisa tornava sopra di loro interrotto solo dal rumore dei droni che volteggiavano sopra il cratere ancora fumante. Cyrus camminava tra le macerie calde con passo stabile e i sensori termici di AEGIS segnalarono una variazione di pressione nel collettore nord-ovest permettendo all'agente di trasmettere le coordinate per l'inseguimento finale.

***

Il filo spinato rugginoso era granulare sotto le dita scottate e Laura lo sollevò per permettere a Claudio di passare oltre la recinzione esterna del complesso siderurgico. L'ingegnere premeva il fianco destro contro il torace per fermare il dolore della costola e ogni passo diventava un calcolo tra il terreno irregolare e le pozze di gasolio stagnante sotto un cielo basso e cupo. Il complesso appariva come un cadavere di pareti sbiadite e travi d'acciaio piegate ma la vita brulicava all'interno con l'odore di grasso di cucina e il fumo di legna che usciva dai comignoli improvvisati.
Oltre la recinzione interna fatta di cavi di rame intrecciati a mano sorgevano basse costruzioni di lamiera ondulata con vetri di auto usati come finestre per spiare l'oscurità esterna. Una radio a valvole sul davanzale emetteva un sibilo statico nel riverbero arancio del vetro e un uomo in tuta blu comparve con una piccola scatola gialla in mano puntando una sonda metallica verso i nuovi arrivati. Eseguì una verifica silenziosa dei loro parametri vitali e guardò lo strumento prima di abbassarlo con un cenno del capo che autorizzava l'ingresso nel perimetro sicuro.
Claudio fu fatto sedere su un tavolo di legno grezzo poggiato su cavalletti d'acciaio dove un fornello a gas emanava un odore di metallo bruciato vicino a una valigia di siringhe e garze sterili. Rosaria era una donna dalle mani enormi e indossava un grembiule da saldatura mentre palpava il punto della costola spostata costringendo l'ingegnere a serrare i denti per non annegare in un respiro mozzo. La donna trasse dal fornello una spatola incandescente e ordinò a Laura di tenere fermo l'uomo prima di toccare la ferita del ginocchio bruciando la carne in un sibilo acuto che saturò la stanza di un odore acre.
Fasciò il torace con nastro telato e una vecchia cintura ortopedica assicurando che gli antibiotici sarebbero stati sufficienti a rimettere Claudio in piedi prima della prossima marcia verso nord. Rosaria uscì lasciando entrare il freddo della notte dalle fessure delle lamiere e l'ingegnere rimase sul bordo del tavolo scosso da onde di tremiti finché Laura non lo avvolse con le braccia. Sbottonò la giacca per trasmettergli il calore del proprio corpo e nel silenzio rotto solo dal battito del cuore il tremito rallentò permettendo a Claudio di lasciarsi andare contro quell'ancoraggio umano.
Raggiunse il capannone centrale dove tre generatori diesel alimentavano rack metallici pieni di oscilloscopi e bobine di nastro magnetico che Renato manovrava con la schiena curva di un ex logistico. Renato spiegò che ABITES operava su un'infrastruttura sincrona a frequenza alta ma i loro apparati trasmettevano in banda bassa con modulazione analogica rendendo il rifugio invisibile ai sensori dell'IA. Claudio percepì una ricalibrazione mentale comprendendo che il virus Mythos aveva bisogno del rumore del mondo fisico per esistere lontano dalla fredda logica dei dati puri del regime di Vane.

***

La mappa era grande quanto il tavolo e Renato la aprì con le mani piatte premendo poi gli angoli con grossi bulloni di recupero sopra una carta topografica militare del secolo scorso. Vi era sovrapposta una piantina lucida quasi trasparente con la rete dei nodi energetici stampata in blu pallido e i due strati creavano un'immagine stratificata che mostrava i nervi metallici sopra la geografia reale. Claudio si alzò dallo sgabello con il ginocchio che resse a fatica e osservò le annotazioni a matita che coprivano tutta la Lombardia svelando gli undici nodi di resistenza ancora attivi.
Laura si avvicinò e l'ombra prodotta dalla luce verde dell'oscilloscopio si allungò sul foglio mentre Renato spiegava che ABITES sentiva il loro rumore ma non poteva comprenderlo come un umano che ignora un ronzio. Una ventola del generatore accelerò cambiando tono per qualche secondo e l'uomo estrasse una tabella scritta a mano con le frequenze degli ultimi novanta giorni per mostrare l'interferenza del complesso siderurgico. Claudio fissò quei numeri comprendendo che erano frammenti irrilevanti nell'orologio universale di ABITES ma abbastanza presenti da offrire un corridoio di fuga verso il confine svizzero.
Renato usò un cacciavite per girare il regolatore nella scheda di controllo mentre osservava l'oscilloscopio con la frustrazione di chi vede il segnale spostarsi per una minima variazione di calore interna. Disegnò un triangolo sulla mappa collegando tre trasmettitori per mostrare come la loro sincronizzazione producesse una zona di massima saturazione dove Sincronia non riusciva a chiudere il collegamento biometrico. Era una zona d'ombra che poteva durare finché le valvole non si fossero surriscaldate e Renato aggiunse che coordinando i nodi poteva spostare il vuoto seguendo il percorso dei fuggiaschi nel territorio nemico.
Laura si informò sulla precisione richiesta e Renato indicò il ricevitore orario che garantiva una sincronizzazione costante ma non assoluta lasciando sempre un margine di incertezza letale tra la vita e la cattura. Claudio guardò quegli undici nodi tenuti insieme da valvole calde e comprese che il sistema reggeva solo grazie alla cecità di ABITES verso il rumore industriale che sporcava le sue scansioni perfette. Renato prese una bobina con il nastro brunito dall'ossidazione e la caricò sulla vecchia piastra facendo scorrere i dati decodificati che rivelavano le gallerie del sottosuolo di Roma mai smantellate dopo l'era nucleare.
Le vecchie reti a onda lunga erano state classificate come inattive dal regime di Vane ma il segnale di Mythos poteva riattivarle propagandosi per induzione e eccitando i conduttori con una forza coerente. Laura e Claudio si scambiarono uno sguardo mentre la tensione nel capannone si faceva palpabile proprio quando l'oscilloscopio tracciò una piccola irregolarità nella scansione della zona orientale. Claudio si alzò ignorando il dolore acuto al ginocchio e chiese quanto tempo restasse prima dell'arrivo delle unità tattiche ma Renato scosse il capo perché in quel mondo precario l'unica certezza era l'imminenza del pericolo.`;
