export const chapter4Content = `La botola di ferro giaceva sepolta da fanghiglia e radici asfittiche. Renato strappò il terriccio con i guanti e sferrò un colpo di leva col piede di porco. Il metallo frizionò rilasciando scaglie di ruggine e gemiti stridenti. Claudio inciampò sulle rocce umide, trafitto dagli acufeni di una febbre che gli bruciava le vene e gli martellava il cranio.
Il perno spezzò la resistenza strutturale in un colpo secco e la botola collassò. Zaffate di olio esausto e marciume invasero le narici dei tre. Claudio scavalcò il bordo. Scendevano in una trincea cieca ai satelliti orbitanti e dimenticata dal catasto. Renato frizionò una lampada chimica, inondando di giallo acido il cosiddetto Fiume Nero.
In una voragine squadrata nel basalto scorrevano dorsali intrecciate di polimeri neri, cavi spessi come tronchi d'albero. Sudavano lubrificante. Renato indicò i giunti scoperti con la torcia, vietando categoricamente di appoggiarsi alle paratie laterali. Tensione killer. Due metri più sotto, il cadavere di un esploratore Sincronia pendeva sciolto sopra i nodi rameici. La corazza era un grumo plastico fuso sui tendini cotti e l'elmetto nerofumo raccontava il fallimento della sua missione.
Presero la griglia sospesa in filo d'acciaio intrecciato. Sobbalzava a ogni appoggio. La chiavetta nascosta nei vestiti di Claudio vibrò come morsa da un tremito elettromagnetico all'ingresso della zona trasformatori. I led d'emergenza in pulsazione rubina si sincronizzavano con i flussi di corrente. Laura stese una mano calda sul braccio di Claudio, stringendolo in un patto silenzioso: dovevano calarsi nell'abisso puro.
Superarono una console divelta: un bisturi meccanico aveva sventrato la tubatura principale. Sopra la trancia, vergato col sangue rappreso, capeggiava un Omega rudimentale. I ribelli deceduti avevano sacrificato il respiro pur di sabotare l'approvvigionamento periferico dei droni Sincronia, sigillando la loro morte.
La condotta si restrinse drasticamente. Claudio slittò rasente i muri gelidi, trascinando il piede infermo con movimenti strazianti. L'alta tensione friggeva nell'aria carica di statica infiammando la pelle. Gocce amare di sudore bruciavano la sclera, ma non poteva levare le mani dai fianchi per asciugarsi: un passo falso l'avrebbe fatto precipitare nei trasformatori a seimila volt.
Renato premeva i passi sulle travi portanti per testare le saldature marce. Uno scocco metallico spezzò la linea acustica e i tre s'irrigidirono. Una ventata rovente carica di miasmi ustionati risalì la corrente, accompagnata da uno sfiato artificiale grave e asmatico. Claudio bloccò il respiro, posò i polpastrelli su un pluviale e incassò vibrazioni secche, del tutto asincrone rispetto ai rotori ambientali.
Il tiraggio della ventilazione era intasato da scorie aliene. Avanzarono assorbendo i rumori delle turbine, fino all'incrocio con un cunicolo in pendenza sbarrato da una scala a chiocciola verso lo sfiatatoio superiore. Renato si bloccò puntando la torcia. Trucioli freschi di trapanatura brillavano vicini ai tasselli: esplosivo a pressione. Chi tentava la ritirata veniva diviso in pezzi dal vuoto decompresso. 
Schivarono l'esca. La griglia sfregava, stretta in un abbraccio asfissiante. La costola di Claudio lo impalava da dentro, stritolando il polmone a ogni contrazione, tanto che lui arrestò la marcia, le gambe scosse da tremori crudi. I led della chievatta sfavillarono sotto la stoffa, brucianti. Ripresero il cammino pestando l'acciaio vibrante diretti verso i motori.

          · · ·          

La blindata della sala controlli non ospitava scanner retinali. Vantava una tastiera alfa-numerica e un albero di relais consunti, con un diodo rosso in lampeggio letargico circondato dal muschio. Claudio frenò quando il sintetizzatore vocale emise la stringa di riconoscimento automatica. Renato estrasse uno sblocco frequenze artigianale e lo innescò tenendo il respiro.
Un clic svuotò l'aria. Le spie morirono e i bulloni a espansione si ritrassero di schianto. Oltre la soglia, temperatura e miasmi polimerici mozzavano la gola. Accasciato sotto un monolite server, un operatore Invisibile smaltiva la disidratazione, con le ossa che solcavano la maglietta sporca di cenere. Le sue pupille erano assenti.
Claudio sfiorò le pareti, si calò accanto a lui e gli porse un sacchetto asettico in alluminio denso di estratto proteico e paracetamolo: valuta d'oro nei sotterranei. L'uomo scattò, sbranò l'angolo e deglutì stringendo gli occhi. Terminata l'ultima goccia inforcò la tastiera, sbattendo combinazioni alfanumeriche finché la dashboard non emise un bagliore candido. 
Claudio estrasse la chiavetta rovente e l'innestò nel connettore dati primario. Il metallo graffiò le sue dita. Dalle casse gracchianti si liberò un disturbo d'onda, poi la voce spezzata di Sara fendette il bunker. Debole, cruda, viva. Era in attesa al punto prestabilito. Il tecnico staccò l'hardware con un movimento violento, troncando la connessione prima degli spider ABITES. S'incamminarono. Poi, un tuono cieco scosse il soffitto. Proiettili scavarono buche nel muro. Laura ruotò sul perno, le ginocchia sbatterono a terra e il sangue colò scuro dal suo fianco sulla soletta di cemento, mentre la pattuglia Sincronia riversava piombo nel tunnel cieco.
Il sangue evaporava formando fiocchi neri nell'aria stagnante. Laura perdeva ossigeno. Claudio la caricò addosso a sé. Affondò il pugno nel buco aperto dalla palla blindata e lei sibilò, schiacciando la mandibola per soffocare il dolore atroce, con i muscoli facciali tesi all'estremo.
L'odore ferroso di mattatoio impregnava i mattoni. Un disertore vestito di tessuti sintetici scoloriti li indirizzò attraverso la rete eurina, voltando loro sempre le spalle sfregiate da una vecchia colata di piombo. Gli scarponi battevano veloci, sporchi di melma biologica. Raggiunsero l'intersezione morta con un arco latino inciso sulla pietra. L'uomo sferrò colpi cadenzati e due battenti si schiusero sibilando vapori saturi d'incenso.
Il tempio-deposito si estendeva in volte gigantesche sorrette da pilastri portanti. Sagome rigide sostavano nei perimetri, individui annullati dai chip lobotomizzanti del sistema. Una suora di nome Maria sedeva dritta sopra un bancone da falegname. Ordinò di ribaltare Laura sulle assi piallate con voce inappellabile. La ragazza trasudava gelo. 
Maria divelse a forbiciate i tessuti marci di coaguli ed estrasse fiale di nitrato. Lo sparò senza anestetico sulla ferita aperta d'arma da fuoco. Laura artigliò i bordi lignei flettendo i fasci nervosi, le nocche decolorate in pura resistenza umana; soffocò un urlo lacerante nel palato. Maria fasciò le bende in lino sferrando strattoni spietati. Claudio si abbatté contro la trave di ghisa e abbracciò la propria schiena stanca: capì che quell'agonia mortale segnava l'unica vera forza contro la macchina.
Laura incassò il rilascio di fumi, tese la canna termica con un braccio ed esplose il proiettile di testa. La fitta infuocata la sventrò di nuovo, ma non abbassò la linea di mira. Il drone si sfondò su se stesso spezzando i rotori sul pavimento, in uno zampillo nero-olio e schegge. Claudio brandì una cassa in abete piena di cavi metallici e la scagliò nel mezzo della navata.
Un secondo tracciante laser scansionò i paramenti sporchi di Laura. Lei strisciò appoggiando la cicatrice alla colonna e staccò due scariche a bruciapelo. Il drone rovinò contro il generatore e la frizione sputò pioggia di scintille tra i bancali bruciati.
Le sacche di reietti si svegliarono dal coma artificiale. I lobotomizzati sorsero in difesa del loro asilo sconsacrato. Un vecchio con cranio fasciato e mazza d'acciaio arpionò un costrutto Sincronia a mani nude. Distrusse l'alimentazione primaria, ma l'elica sfilò il collo del disperato in un fiotto rubino istantaneo, coprendo il distacco tattico di Claudio e Laura.
Maria ghermì gli spallacci tattici dei fuggitivi e sollevò una lastra nel retroterra buio. Calciò l'asse da lavoro con spinta immane, barricando il tracciato. Sfoderò granate fumogene ai fosfori, avvelenando l'ambiente in una coltre calcarea impenetrabile ai visori standard.
L'uomo in grigio coprì l'accesso sputando raffiche cieche per spezzare il passo miliziano e sventagliò la mano chiamando la fuga. Inghiottirono fumo inerpicandosi sulla scalinata di travertino grezzo. Laura strappava a stento i respiri. Claudio raschiava la gola arsa dai vapori grigi. Sfilarono il chiusino blindato uscendo nell'acqua scrosciante di Roma ovest, e il nubifragio gelido strappò via sudore e disperazione.

          · · ·          

Il tracciato dei convogli merci abortiva nel fango dove l'erba spezzata si mischiava al nichel sventrato. Era una necropoli ferro-tramviaria. Claudio inspirava rauchi morsi d'aria tagliente, le spalle bloccate da un'ansia cinetica pura. Locomotive rugginose affondavano decine di metri in fosse acquitrinose. Un tanfo crudo d'olio rancido e ferite metalliche stagnava nella gola.
Avanzavano allineati al fuggiasco in grigio. Gocce di temporale scoccavano frustate rigide sulle capote dei convogli. Laura si spostava scaricando il peso sulla gamba di forza, risparmiando il fianco imbottito di emostatico. Giunsero davanti a una E-656 morta: trenta tonnellate di acciaio spaccato nel bosco.
Forzarono la cabina direzionale ed i cristalli incisi restituirono i riflessi porpora delle torce tattiche di ricerca. Calarono i bacini sulle pedane fradice ed i loro aliti appannarono le paratie industriali. La chiave criptata scuoiava il petto di Claudio per il sovrariscaldamento: la disinnestò e la fermò sul volantino dei freni di emergenza, liberando il calore in eccesso.
Un corto circuito interno usò il massiccio corpo della locomotiva come trasmettitore in bassa frequenza saltando il registro Sincronia. Sull'auricolare piovve il timbro logoro di Sara. Rumore bianco, distorsione. «Sono dentro. Coordinate agganciate. Sbrigati.»  Claudio ammutolì. Il vagone deflagrò in una violenta luminosità ultravioletta: sensori da caccia ABITES li avevano siglati.
Il fascio luminoso scavò le ossa e smascherò la faccia dura di Aris tra gli ingranaggi a terra. I cuori battevano contro i petti tesi. Il cordone Sincronia serrava il cerchio operativo. Aris fissò Claudio, scolpito sotto il prisma alogeno sceso dal cielo artificiale.
L'uomo in grigio mormorò un diktat asciutto. L'esfiltrazione sussisteva unicamente deviando l'aggancio verso l'ala sud. Aris ostentò un distacco marziale inequivocabile e prese la sua strada.
Allungò la mano sul fumogeno di segnale, strappò l'anello, calciò a terra il vetro in frantumi e fiondò tra le radici della sterpaglia. Uno schianto tra il fango e la furia. Abbaiò ordini selvaggi calamitando le ottiche ABITES su di sé. L'uomo in grigio sbatté le braccia, Claudio e Laura scivolarono fuoribordo verso ovest, rovinando nel torrente di mota congelata.
La corsa di Aris allontanò i droni. Una scarica sonica strappò il silenzio di netto e la compressione sferzò le costole di Claudio mozzandogli l'ossigeno. I timpani rimbombarono la fucilata balistica in ritardo. 
Laura gli incatenò la presa alla spalla, afferrandolo per tirarlo dentro lo scontro vitale. Un secondo bang esplosivo tuonò freddo. Il fiato umano di Aris cessò per sempre. Restò il piovasco sui rottami. Claudio ingoiò la saliva ramata di rabbia. Si divincolò verso il chiusino di sfiato e sparì nei tunnel fognari bui per fuggire la carneficina.
L'alveo era di proporzioni tombali, pareti strette come fosse asfittiche. I gomiti si escoriavano l'epidermide. Il rantolo della marcia scavava i polmoni di tutti. Laura precedeva, Claudio tallonava sulle orme d'acqua. La lampada alogena dell'uomo grigio baluginava ritmi sfacciati. La valigetta si abbarbicò sulla cassa toracica esalando il responso disperato di Sara tra le ombre.
Il corso incurvò verso l'imboccatura inquinata di giallo chimico. Estrazione catacombale, fortino sotterraneo ribelle. Agganciarono i montanti flettendo i tricipiti allo stremo. Olio esausto, catrame, motori a scoppio logorati iniettavano cancro nell'aria. Mira manovrava una parata di tubi catodici d'epoca, la cicatrice che sbrecciava il naso. Non mosse un muscolo.
Claudio sbatté il report sull'esecuzione di Aris battendo le tempie gelide. I tremiti scuotevano le sue palpebre, ma Mira abbassò lo sguardo, azzerando le reazioni organiche. Nessun segnale termo-satellitare per Aris. Laura si abbandonò in caduta misurata contro una balla di spago per ammortizzare i tendini feriti. Claudio prese posto sui talloni. Mira allungò gavette ammaccate zeppe di scorte idriche, confermando le tattiche di ABITES: chiusura periferica attiva prima del solstizio.
Smontarono i sigilli e infilarono i plug nei computer isolati ad alta resistenza. La grotta sprizzò toni di blu nucleare divorando l'oscurità con righe di crittografia Sincronia abbattute dalle istruzioni della chiavetta. Salirono a galla i decimali operativi di Sara. Riparata in avamposto sterile, allineata per l'offensiva core. Laura incatenò i suoi occhi a quelli di Claudio, connettendo nervi saldi e furia. Mira tese le matasse in fibra ottica in direzione del polo calcolatore ABITES centrale. Il nucleo malvagio distava due chilometri appena.`;
