export const chapter21Content = `Macro-Capitolo 21: Polvere e Ruggine
[ROMA SOTTERRANEA - PERIMETRO EUR - LAURA E CLAUDIO]
Laura si accasciò contro la parete fredda in calcestruzzo. Il sangue arterioso pulsava fuori dal taglio sul deltoide destro con una cadenza ritmica e letale. La donna premeva la mano sinistra sulla carne lacerata, ma il liquido denso sfuggiva tra le dita inzuppando la mimetica tattica e il fango sottostante. Il respiro le usciva corto, spezzato dai brividi.
«L'ossigenazione sta crollando nei tuoi parametri,» avvertì Sara nell'auricolare. Il suo tono non ammetteva repliche. «Lo shock emorragico subentrerà entro quindici minuti. Se non blocchi il flusso, il tuo cuore andrà in arresto prima di raggiungere la breccia.»
Laura sputò saliva amara.
«Il perimetro acquatico è in sicurezza,» rispose lei con voce rauca.
«La sicurezza biologica è frantumata,» intervenne Carlo. Il ticchettio frenetico della sua tastiera arrivava fin lì. «I filtri di ABITES fiutano l'ossidazione del ferro ematico nell'aria. Se varchi la soglia della Torre grondando sangue, i sensori chimici scateneranno le sentinelle automatiche. Devi sigillare quella ferita. Ora.»
Laura annuì nel buio profondo. Sbatté le palpebre pesanti per scacciare la nebbia purpurea che le inibiva la vista. Puntò la torcia tattica attorno ai detriti di cemento e mattoni romani. Cercava un modo per strozzare l'emorragia. Il fascio di luce tagliò una cavità ombrosa a pochi metri di distanza. La spalla del tunnel nascondeva una vecchia porta di ferro grezza, dischiusa e scardinata. Sembrava una sentinella morta d'inedia.
La donna obbligò i muscoli a reagire. Si alzò in verticale, barcollando. Raggiunse l'imboccatura fantasma. Infilò le dita nella fessura millimetrica tra l'anta e il muro. Tirò con un urto violento di tutto il peso corporeo. I cardini arrugginiti ruggirono nel silenzio. Una nuvola di polvere secca invase l'aria. L'anta pesantissima si schiantò contro la parete interna.
La torcia illuminò un locale rettangolare, architettura bellica grezza del secolo scorso. Era un magazzino di stoccaggio della Seconda Guerra Mondiale, rimasto sepolto per decenni sotto le colate di bitume della modernità. Grossi ratti di fogna squittirono acuti e sparirono tra le macerie. Era l'unica vita biologica sfuggita ai censimenti digitali di Cyrus.
Casse di legno tarlato giacevano a terra, svuotate di ogni munizione. Laura inspirò l'odore di decomposizione e muffa. Le vertigini la colpirono di nuovo. Cadde sulle ginocchia davanti a un piccolo armadietto di alluminio verde militare, parzialmente corroso dall'umidità. Forzò lo scomparto inferiore con la lama del coltello.
Dentro c'era una cassetta metallica con una croce rossa sbiadita. La mercenaria aprì i ganci con due scatti secchi. Il contenuto era materiale di chirurgia bellica d'altri tempi. Le bende erano ingiallite, ma le fiale di vetro apparivano intatte sotto lo strato di polvere. Laura prese una provetta contenente una polvere ocra. Sulfamidici di prima estrazione. Polvere cicatrizzante per ferite profonde. L'antisettico dei soldati falciati in trincea.
«Sara,» stridette Laura nel microfono. «Ho trovato un vecchio kit medico. Sulfamidici integri.»
«Usali immediatamente. Cauterizza la ferita,» ordinò Sara da Testaccio.
Laura scoprì la spalla incriminata, esponendo il taglio ancora aperto e sanguinante. Aprì la provetta con i denti. Rovesciò la polvere gialla direttamente dentro il foro.
Una fiammata chimica la investì. La reazione bruciò il plasma e i tessuti istantaneamente. Laura si inarcò all'indietro, schiacciando la nuca contro la calce del magazzino. Il dolore era una saldatura rovente che le correva nelle vene. Soffocò un urlo stringendo le mascelle fino a farsi male. Non voleva attirare l'attenzione delle sub-routine acustiche di superficie.
Afferrò un rotolo di garza. Fasciò il deltoide con una forza brutale, stringendo il nodo fino a interrompere ogni afflusso. L'emorragia si spense. La pelle ustionata smise di lacrimare sangue. La donna riemerse dal magazzino con le tasche cariche di bende pulite.
Tornò da Claudio. L'ingegnere era immobile, in uno stato di fermo vitale controllato. Laura ricaricò l'arma. Puntò il raggio della torcia verso la fine del corridoio. Davanti a loro sorgeva il muro posteriore della Torre. Era il momento della breccia finale. Il tempo della fuga era finito. Quello della mattanza stava per cominciare.`;
