export const chapter27Content = `Il vento su Fourvière aveva lame di ghiaccio. Soffiava spietato tra le rovine della basilica e tagliava la pelle nuda. Dubois si fermò dietro un muro di cinta sbrecciato, appiattendo la schiena contro i mattoni freddi. L'antenna svettava davanti a loro. Era un ago imponente di tralicci d'acciaio e ruggine che bucava la coltre di nuvole nere della notte lionese.
La base dell'antenna era diventata un fortino improvvisato. Sacchi di sabbia circondavano il perimetro formando un anello chiuso. Tre uomini in cappotti scuri e piastre balistiche presidiavano stretti l'ingresso. Lealisti umani. C'era un braciere acceso al centro del presidio, e le fiamme arancioni illuminavano le canne dei fucili d'assalto tenuti a tracolla. Sopra di loro, ancorata a una spessa trave di cemento armato, una torretta automatizzata ruotava il suo occhio meccanico. La lente rossa spazzava l'oscurità con scatti precisi, rigidi e spietati.
Dubois strinse il fucile. Le piastre antiproiettile sotto il giubbotto pesavano sulle sue clavicole.
«Sono pesanti», sussurrò Kouassi dalla penombra. «La torretta ha mitragliatori calibro dodici. Copre tutto il piazzale in scatti simmetrici da quindici gradi. Hanno campo aperto.»
«Devo colpire il sensore prima che agganci il calore del nostro corpo», disse Hana.
Sfilò il caricatore e controllò i proiettili a uno a uno. Il rumore dell'ottone sfregato contro l'acciaio era netto. Reinserì il pezzo pesante con un colpo secco del palmo. Kouassi le era accanto. L'uomo grande respirava piano. Posò la mano larga e dura sulla spalla di Hana. La donna sentì la forza solida attraversare il tessuto sporco della giacca. Si guardarono nel buio asfittico. Non c'era bisogno di promesse, né di lunghi discorsi. La guerra, la strada e la polvere avevano fuso le loro vite. Erano fratelli d'armi, schiena contro schiena nelle macerie, legati dal sangue versato.
Hana ricordò le mani ruvide del suo compagno lasciato lontano, a sud. Ricordò la consistenza muscolare delle sue braccia nel letto, l'odore di legna bruciata e sudore vitale sul suo petto. Quel calore fisico la investì. Quel ricordo non le strappò lacrime o paure. Le consegnò un coraggio puro, denso e feroce. L'amore reale divenne una piastra d'acciaio forgiata per reggere l'urto di tutto quel freddo. Il cuore le gonfiò i polmoni di forza. Hana annuì verso Kouassi e si mise in mira col fucile appoggiato alla spalla.
«Adesso», ordinò Dubois.
Hana scattò rapida fuori dal riparo e sparò. Due colpi esplosero in rapida successione. I proiettili centrarono la lente scarlatta della torretta. Il vetro antiproiettile andò in frantumi. Uno sciame di scintille luminose sputò dal meccanismo distrutto, e il motore della mitragliatrice girò a vuoto con un fischio meccanico acuto prima di bloccarsi verso il basso.
I tre lealisti gridarono e alzarono le armi.
Kouassi uscì allo scoperto in carica. Teneva un spesso pezzo di lamiera da carrozzeria piegata davanti al petto. I fucili lealisti sputarono fuoco disordinato. I proiettili martellarono la lamiera con colpi assordanti, sollevando schegge incandescenti di piombo impattato. Kouassi non frenò la falcata. Usò la propria gigantesca mole come ariete. Travolse in pieno il primo lealista. L'impatto fu brutale. Osso e cuoio si scontrarono con violenza inaudita. L'uomo finì schiantato a terra sotto gli scarponi massicci di Kouassi e perse i sensi.
Dubois e Matthieu superarono il blocco di sabbia dai lati opposti. Svuotarono i caricatori puntando al bersaglio grosso. Il secondo lealista prese un colpo grave al petto, vacillò all'indietro e crollò riverso sui sacchi. Il terzo buttò il fucile a terra e fuggì terrorizzato verso l'oscurità oltre le rovine della basilica, inciampando sulle macerie.
Nessuno fiatò per tre secondi. Si sentiva solo il vento gelido e l'odore aspro della polvere da sparo combusta.
«Tenete il perimetro basso e controllate la strada», ordinò Dubois con voce roca. Guardò Gilles, ancora coperto dietro le macerie. «Andiamo. Muovi quel borsone.»
La scala di manutenzione dell'alta antenna era esposta a tutti gli elementi. I pioli di ferro grezzo erano coperti da uno strato infame di brina dura. Dubois saltò sul metallo e afferrò il primo gradino. Il freddo gli morse e bruciò subito la pelle dei palmi attraverso la pelle sottile dei guanti tattici. Iniziò a salire. Gilles lo seguiva a ruota. L'attrezzatura di trasmissione pesava come sassi sulle spalle di Gilles e minacciava di sbilanciarlo verso il baratro a ogni violenta folata di vento.
Salirono senza guardare in basso. Dieci metri. Venti. Cinquanta.
La città di Lione si allargava ostile e sterminata sotto di loro. Un oceano nero senza elettricità né vita visibile, spezzato solo dai rari bagliori arancioni dei bidoni in fiamme all'aperto. Il traliccio intero vibrava e gemeva contro la corrente d'aria letale. I muscoli delle braccia di Dubois bruciavano feroci per lo sforzo prolungato in trazione verticale. L'uomo teneva la mente serrata, le mascelle rigide, lo sguardo puntato unicamente sulla barra di ferro successiva.
Raggiunsero la piattaforma a croce a sessanta metri da terra.
La massiccia scatola di derivazione era avvitata alla trave principale in acciaio zincato. Era protetta da un grosso lucchetto chiuso a scatto e bloccata in modo irrimediabile da anni di pioggia battente e ruggine profonda. Dubois non perse secondi preziosi a cercare i grimaldelli. Impugnò il pesante fucile per la canna e usò lo spigolo duro del calcio balistico come una mazza da demolizione. Colpì con rabbia, due, tre volte. Il metallo del lucchetto si spezzò di netto. Il fermo cadde nel buio e Dubois tirò il pesante sportello tirandoselo sul petto.
L'interno era intatto, ma il vero problema era sopra di loro. Il braccio di allineamento della parabola principale era fuori asse. Il perno di blocco era tranciato. Il vento feroce spingeva l'antenna facendola oscillare nel vuoto.
«Il disco è fuori asse», disse Dubois, scuotendo il capo. «Senza la parabola bloccata, il segnale si perderà.»
Gilles lasciò cadere il borsone verde sulla grata di metallo forato. Tirò con forza e si sfilò via i guanti di lana infeltrita. Si arrampicò per tre metri sui montanti scoperti, raggiungendo la forcella del braccio direzionale.
«Collega il modulo», urlò Gilles dall'alto. Infilò il corpo tra il traliccio portante e la pesante staffa d'acciaio della parabola. Puntò gli scarponi sul bordo scivoloso. «La blocco io. Usa la mia schiena.»
«La spinta del vento ti spezzerà i muscoli!», urlò Dubois.
«Trasmetti!», rispose Gilles, stringendo i denti.
Dubois estrasse il modulo analogico. Era una scatola grezza e artigianale da tre chili, assemblata con vecchi circuiti non quantistici e invisibile alla crittografia di ABITES. Inserì i connettori nella piastra madre. Digitare il codice sui piccoli tasti rigidi, con i nervi intirizziti dal gelo, era fatica pura.
«Pronto», disse Dubois.
Gilles afferrò il metallo ghiacciato con le mani nude e spinse con le gambe. I muscoli della sua schiena si tesero. La colonna vertebrale si inarcò sotto il peso della parabola spinta dal vento. L'acciaio nudo della staffa gli compresse le spalle attraverso la giacca. I tendini del collo si gonfiarono. Gilles strinse la mascella fino a far scricchiolare la radice dei molari. Fissò gli occhi al cielo scuro. Non gridò. Non allentò la presa.
Nel mezzo di quello sforzo muscolare brutale, la memoria lo raggiunse. Vide l'espressione di sua moglie. Sentì il calore del suo abbraccio davanti alla porta di casa, lontana mille chilometri. L'odore della pioggia sui suoi capelli. La promessa di tornare da lei a qualsiasi costo. Quel pensiero pompò sangue e forza nel petto, spingendo via il dolore dei muscoli tirati e del gelo nelle ossa. Gilles restò piantato nel vuoto. Fece del proprio corpo il perno centrale dell'antenna e non cedette un solo millimetro.
Dubois abbassò la testa verso il piccolo schermo tattico integrato nel modulo.
Linee geometriche di codice verde stracciarono lo sfondo nero. Il virus analogico sbriciolò le barriere della rete periferica controllata, ignorando la logica quantistica di ABITES e invadendo le vecchie frequenze radio non presidiate.
Dubois premette i tasti.
[PROTOCOLLO RISVEGLIO. SQUADRE DORMIENTI. DIFFONDERE SUBITO.]
Picchiò il palmo sul tasto fisico di invio. Il segnale codificato rimbalzò sulla grande parabolica allineata dal corpo di Gilles e investì le lunghezze d'onda verso ogni nodo operativo sul territorio. In tutto il continente, decine di vecchie radio e computer nascosti ai margini della civiltà iniziarono a ricevere.
Il contatore alfanumerico dello schermo confermò l'upload.
L'attesa per il riscontro in linea durò quindici secondi. Secondi scanditi dal vento malvagio e dai respiri secchi di Gilles che tentava di incamerare ossigeno sotto la pressione del metallo.
Il monitor tremolò all'improvviso. Una porta di ricezione si era spalancata sul modulo. Stava giungendo una risposta. A causa dello scontro tra i virus difensivi della sorveglianza e le interferenze, le stringhe di messaggio arrivavano spezzettate, caotiche.
[QUI CENTRO. CODICE VERIFICATO E RICEVUTO... UOMINI IN ASCOLTO ATTIVO.]
Dubois aspettò un altro momento, il pollice pronto. La barra di scorrimento sfarfallava in basso.
[PIANI CAMBIATI.]
[ATTACCO NORD EUROPA... ANNULLATO.]
Dubois aggrottò la fronte, stringendo gli occhi davanti ai pixel verdi. Rilesse la seconda stringa due volte. Il piano strategico originale del Fronte prevedeva un assalto totale alle infrastrutture energetiche nel Nord. Non poteva variare a un passo dal via.
Poi, l'ultimo pezzo di comunicazione si sgranò prepotentemente dal rumore di fondo statico.
[MODIFICA IMMEDIATA BERSAGLIO LOGICO PRIMARIO.]
[CONVERGERE TUTTI SU LA CHIESA.]
[ROMA.]
Dubois strappò i cavi dal quadro contatti. Lo schermo si spense all'istante divenendo nuovamente nero.
Gilles crollò in ginocchio sulle grandi grate di metallo. L'acciaio aveva lasciato un solco profondo sulla schiena della sua giacca, ma era vivo. Respirava a fatica, scosso dai brividi del freddo e dallo sforzo sovrumano appena terminato.
Dubois lo afferrò per le spalle e lo tirò via dal bordo esposto, mettendolo al riparo dietro un montante largo. Gilles barcollò e si appoggiò al ferro.
«Cosa...» disse Gilles con la gola secca. «Cosa hanno detto?»
Dubois guardò lontano. Il vento forte li sferzava sul tetto del mondo. Il suo volto duro tradiva la tensione di chi riconosce il crollo di un piano durato anni.
«Le regole del gioco sono saltate», rispose Dubois. «Non puntiamo più alle macchine a nord. Da stanotte, si marcia dritti sul cuore di Roma.»`;
