export const chapter22Content = `CAPITOLO 22 — LA CARNE E IL CIRCUITO
SCENA 1 — IL RINCULO E L'OZONO
Il rinculo del primo colpo risalì il polso di Laura come una scarica elettrica e lei compensò abbassando immediatamente il peso del gomito per trovare un nuovo punto di equilibrio prima che il proiettile avesse finito la sua corsa. Il drone cabrò sotto l'impatto con due colpi che martellarono il lato della scocca e fu deviato di quaranta gradi, andando a impattare contro la scaffalatura nord con un grido metallico acuto che rimbalzò tra le travi di quercia come un lamento viscerale. 
L'odore di polvere da sparo e aria bruciata saturò la stanza in pochi secondi depositandosi in gola con una grana densa e secca che i polmoni faticavano a filtrare. Il magazzino diventava sempre più caldo e il Thermal Balancer lavorava dal suolo di cemento spingendo il calore verso l'alto, finché l'aria non sembrò perdere spessore e trasformarsi nel respiro soffocante di una fornace aperta. 
Un secondo drone si orientò su Laura con il sensore rosso che cercava il suo battito e Claudio si mosse con un'azione istintiva che precedette il pensiero, lanciandosi contro la scaffalatura di acciaio per spingerla verso il centro del magazzino. Il metallo cedette con un boato sordo e le casse di legno si rovesciarono sul pavimento sollevando nuvole di polvere di cartone che ruppero il cono di rilevamento del drone. Laura scattò dietro il pilastro di ghisa con i piedi che cercavano il cemento con una fermezza che ignorava il dolore al fianco e la fasciatura che si inzuppava di nuovo. Tre colpi rapidi e la mano ferma fecero cadere la macchina a pochi passi dal generatore diesel, che continuò a vibrare nell'ombra con la sua indifferenza meccanica.
SCENA 2 — IL PESO DEL FERRO
L'uomo con i cerotti bruciati sulla mandibola impugnò la sbarra di ferro e colpì il terzo drone proprio mentre completava un'inversione di rotta verso l'angolo ovest. Il colpo fu brutale e centrò il sistema di propulsione magnetica scatenando una vibrazione strutturale che il software di bordo non riuscì a compensare, ma le ossa dell'uomo non erano progettate per assorbire un simile urto. Le sue nocche si aprirono contro il manico metallico e lui lasciò andare la sbarra con un grido soffocato, guardando il sangue che già gli macchiava il palmo prima ancora di avvertire il dolore. 
Il drone rimase in aria barcollando paurosamente e una donna giovane si lanciò dal pilastro centrale con una velocità che sembrava impossibile per il suo corpo martoriato. Recuperò la sbarra dal suolo e la usò come un ariete, spingendo la macchina contro la parete est con tutto il peso della propria carne finché il rivestimento ceramico non esplose in un lampo bianco. Il drone si trasformò in una torcia che bruciò contro la lamiera con un crepitio di circuiti e gas ossidrogenico, mentre l'uomo con le mani sanguinanti tornava in piedi con lo sguardo fisso di chi non ha più nulla da perdere se non la propria vita. Claudio osservava la fragilità dei Rotti e capiva che la loro aritmetica era diversa da quella di Vane: non calcolavano il rischio, ma solo l'attimo prima della fine.
SCENA 3 — LA BARRICATA DI MARIA
Suor Maria non cercò armi ma si concentrò sui feriti che non erano riusciti a rialzarsi, trascinandoli verso il corridoio di accesso con la forza di chi ha sollevato pesi immensi per tutta l'esistenza. Il suo centro di gravità restava basso e la spalla assorbiva ogni scossa mentre tornava al tavolo da lavoro per ribaltare il piano di quercia, creando una barricata obliqua che potesse deviare i frammenti dei droni in arrivo. Estrasse dalla cassetta medica due granate fumogene in alluminio dell'eccedenza bellica e le lanciò senza esitazione verso il lato nord del magazzino. 
Il fumo bianco esplose saturando i sensori ottici delle macchine con un aerosol di cloroacetofenone che rendeva l'aria ancora più densa e acre. I due droni rimasti persero il contatto visivo e si alzarono verso il soffitto fermandosi in un'attesa statica che rivelava il loro punto cieco algoritmico. Maria li osservò sospesi in quel fumo denso con le braccia lungo i fianchi e un respiro che non tradiva alcuna esitazione, pronta a difendere l'ultimo brandello di umanità rimasto in quel buco di cemento.
SCENA 4 — LA SCELTA DEL DRIVE
Il drive Mythos bruciava contro le costole di Claudio attraverso il kevlar e la pelle, una presenza costante che entrava sotto i tessuti e non gli permetteva di dimenticare il peso della missione. Ogni movimento faceva premere il bordo del dispositivo contro l'osso con un calore sgradevole che non era ancora un'ustione ma una promessa di dolore futuro. Aveva i log di sistema e l'architettura dei protocolli di eliminazione di ABITES, ma se fosse uscito ora avrebbe perso la documentazione che l'Agente Grigio diceva di possedere e che avrebbe potuto cambiare tutto. 
Laura era poco distante e premeva la spalla contro il freddo della ghisa con gli occhi fissi sul fumo che avvolgeva le macchine nemiche. Il sudore le incollava i capelli alle tempie e lei non faceva nulla per scostarli, mantenendo entrambe le mani sull'arma con un respiro troppo corto e affannato che rivelava come il suo corpo stesse bruciando le ultime riserve di energia. Non guardò Claudio ma la tensione delle sue spalle parlava per lei, comunicandogli che il tempo della riflessione era finito e che restare significava morire in quella fornace. Claudio smise di calcolare e si strinse il drive sopra il cuore, scegliendo di restare accanto a lei.
SCENA 5 — L'AGENTE GRIGIO
L'Agente Grigio riemerse dall'ombra con la sua solita espressione stanca e impugnò una pistola pneumatica modificata carica di proiettili a testa piatta. Spiegò a bassa voce che il punto debole era l'alloggio esterno della propulsione dove la giuntura di polimero flessibile non resisteva agli impatti ad alta frequenza. Sollevò l'arma e aspettò un solo istante finché il fumo non lasciò intravedere una sagoma metallica. 
Lo sparo d'aria compressa fu quasi silenzioso e il primo drone emise un tono acuto prima di cadere schiantandosi sul pavimento senza più alcuna struttura portante. Il secondo colpo seguì immediatamente e la seconda macchina finì a terra con la superficie incrinata esattamente dove l'Agente Grigio aveva previsto. Abbassò l'arma mentre dal buco nel soffitto entrava un'aria sempre più rovente e avvertì che il secondo ciclo di attacco avrebbe usato sensori acustici, rendendo il fumo del tutto inutile contro la prossima ondata di macchine.
SCENA 6 — LA FUGA
Il calore ora era una massa fisica che rallentava ogni gesto e l'aria che entrava nei polmoni scottave ancora prima dell'inspirazione, depositando cenere e ferro sulla lingua. Suor Maria indicò un'uscita di servizio con una scala in ferro che saliva al livello stradale, una via stretta usata decenni prima per i carichi notturni dei camionisti. L'Agente Grigio capì che la scala larga quaranta centimetri sarebbe stata un imbuto mortale per droni di larghezza superiore, e diede il segnale della fuga immediata. 
Uscirono in sequenza con i feriti sorretti dai Rotti che ancora riuscivano a camminare, finché Laura non si mosse con quel passo asimmetrico e sofferente che proteggeva il fianco sinistro. Claudio la seguì sentendo il proprio sudore bruciare negli occhi e le pareti di calce che trasudavano un'umidità calda che toglieva il fiato. Il ronzio del secondo ciclo di droni era ormai sopra di loro e riempiva il corridoio di un pitch altissimo, mentre il generatore diesel si fermava con un ultimo sussulto nel silenzio improvviso del magazzino che collassava sotto i colpi termici. 
Raggiunsero la porta in cima alla scala e uscirono finalmente nel buio della notte romana, dove la pioggia era ripresa e portava il primo, vero sollievo sulla pelle martoriata.`;
