export const chapter11Content = `Il bambino aveva i capelli castani e le mani piccole appoggiate sul petto. Sembrava che dormisse un sonno troppo profondo. La vasca era trasparente e dentro c'era un liquido colorato dalle luci blu dei computer che facevano rumore tutto intorno. Tre cavi uscivano dalla nuca del piccolo, erano di colore rosso, bianco e nero. Erano collegati direttamente alle macchine che pulsavano. Il petto del bambino si alzava a fatica, seguendo il ritmo delle macchine dell'aria che stavano sul fondo della vasca.
Claudio teneva la mano vicino ai comandi e non riusciva a muoverla. Uno schermo lì vicino mostrava il battito del cuore con delle righe verdi sottili. Julian Vane teneva quel bambino prigioniero per far mangiare al sistema il suo cervello.
La chiavetta Mythos serviva a distruggere ABITES, ma colpire il sistema voleva dire fare del male a quel bambino. Caricare il codice avrebbe scatenato delle scariche elettriche capaci di bruciare ogni cosa. Claudio appoggiò le dita sul bordo gelido della vasca e sentì le ossa delle mani che gli facevano male. Aveva i palmi tutti sudati per la tensione.
Dalla balconata sopra di loro, Julian Vane guardava tutto con le mani sul corrimano. Le guardie tenevano i fucili puntati verso il basso, pronte a sparare. Il dittatore aspettava che Claudio facesse un errore e sorrise. Si godeva la paura dell'ingegnere perché sapeva che non aveva il coraggio di agire.
All'improvviso un colpo fortissimo scosse il pavimento. L'Agente Oro atterrò sulla griglia di ferro con un rumore tremendo. Era un colosso di metallo coperto da pelle finta che si muoveva come un orologio. Al posto degli occhi aveva delle telecamere che registravano tutto. Il gigante si lanciò all'attacco e Laura si mise in mezzo. Fu uno scontro tra carne e acciaio. Laura sentì il colpo fin dentro le ossa. Il mostro la colpì forte proprio al fianco ferito. Claudio sentì il rumore secco delle ossa e Laura rimase senza fiato per il dolore atroce.
Laura cadde a terra e sputò sangue sulla grata. Il mostro di metallo non diceva nulla, restava lì in silenzio. Lei si rialzò a fatica e fece finta di colpirlo per confonderlo. Poi gli sputò il sangue proprio in faccia e si buttò a terra colpendo una valvola del vapore. Un getto di fumo bianco invase tutta la stanza.
Il vapore freddo nascose ogni cosa e l'Agente Oro non vedeva più nulla. Laura gli saltò addosso e gli afferrò la testa per sbatterla forte sul pavimento. Claudio allora si concentrò sul bambino perché doveva staccare quei maledetti cavi. Spaccò la plastica che proteggeva i contatti e iniziò a staccare tutto con le mani sudate e il cuore in gola. Strappò i fili di rame e sentì il bruciore delle scintille sulla pelle delle dita.
Sul pannello apparve una luce rossa che lampeggiava in mezzo al fumo. Claudio infilò la chiavetta Mythos e lanciò il virus distruggendo tutte le difese di Vane. Si sentì un boato che scosse tutta la stanza. L'odore di plastica bruciata diventò insopportabile mentre i computer fondevano uno dopo l'altro.
Il fumo faceva bruciare gli occhi a Mira, che si aggrappò a una trave di ferro per non cadere. I soldati neri stavano schiacciando tutto. All'improvviso le macchine si fermarono e le luci si spensero. Il rumore dei motori morì nel silenzio. Il sistema era distrutto e un blackout colpì il mondo intero. Le persone scesero in strada per combattere perché finalmente l'umanità era tornata padrona della terra.`;
