export const chapter10Content = `CAPITOLO 10 — IL PERIMETRO INTERNO

La porta oltre l'interfaccia dell'Agente Rosso si aprì. Un'oscurità assoluta accolse i fuggiaschi. I sensori biologici di ABITES registrarono il calore corporeo in movimento. Claudio rimase sulla soglia con la mano contratta sulla maniglia fredda della Torre. I circuiti captarono la pressione dei passi umidi sul pavimento. Le luci si accesero in una spietata sequenza di attivazione verso il fondo del settore Alpha-Prime. Ogni pannello LED scattava con mezzo secondo di ritardo sul precedente. Un'onda luminosa corse in avanti rischiarando il percorso lontano. L'area calpestata rimaneva oscurata. Claudio e Laura si trovarono prigionieri in un cono d'ombra costantemente ritardato rispetto alla loro posizione fisica. L'ingegnere fissò la maniglia di alluminio satinato. Il freddo aveva assorbito l'intera energia termica del suo avambraccio destro.
Il corridoio Alpha-Prime raddoppiava in larghezza i laboratori clandestini del limite nord. Le pareti strutturali non erano erette con blocchi di cemento. Vetro intelligente a matrice liquida. Pannelli compositi in grado di azzerare l'opacità su comando del mainframe. Esponevano uffici e blocchi logici abbandonati incapsulati oltre le superfici riflettenti. Uno spazio vasto, inorganico, ostile all'organismo estraneo. Claudio vide stanze sature di postazioni hardware. Monitor neri rivolti verso il nulla assoluto. Sedie ergonomiche di polimero cristallizzato posizionate verso l'esterno. La polvere di dieci anni si depositava in uno strato sottilissimo e uniforme sopra ogni materiale sintetico. Archivi ignifughi foderati in titanio mostravano etichette stampate in caratteri alfanumerici asettici. Il tempo aveva ceduto alla stasi di manutenzione programmata. Laura marciava stretta al fianco e proteggeva la sutura chirurgica da strappi improvvisi. Il suo fiato condensava immediatamente nell'aria filtrata. Piccoli pennacchi di vapore d'acqua scendevano verso il basamento della struttura trascinati dalla corrente climatica continua. L'intero sistema di areazione forzata aspirava in una discesa continua per conservare intatto il cuore in silicio dei processori profondi ignorando il bilancio biologico del corpo umano.
L'assideramento atmosferico non era un fenomeno casuale ma una precisa e cinica necessità industriale. Claudio avvertì il rigore del gelo afferrare le nocche scoperte e percorrere i nervi del braccio sinistro. I primi dieci metri di avanzamento isolato si consumarono in un silenzio tombale spezzato dal tacco di gomma dura a impatto con la resina bianca. La pressione barometrica forzata dell'aria scendeva sulle spalle dell'uomo. Un peso massiccio compresso verso il fondo della schiena. Il sistema audio nascosto nei controsoffitti si avviò e un ronzio sub-frequenziale penetrò la mascella. Risalì di colpo i condotti uditivi puntando la base del cervelletto dove il trauma logico viene elaborato assieme ai riflessi involontari muscolari. Non un suono ma una vibrazione pura, materiale, demolitrice. I tendini vibrarono, i masseteri si serrarono. Claudio contrasse i muscoli del collo in un inutile spasmo opposto all'aggressione ultrasonora di ABITES. Laura avvinghiò il bordo rigido del giubbotto tattico, le vene della mano emerse in superficie, disperata nel ritrovare stabilità. Il primo, lunghissimo pannello strutturale a sinistra alterò la percentuale di trasparenza sfumando verso l'oscurità a diagonale calcolata.

Il cristallo laterale divenne nebbia scura. Subito dopo, uno specchio perfetto. Claudio vide la propria sagoma riflessa e distorta dalla curvatura concava del pannello. Un'aberrazione vibrante. Il settore Alpha-Prime iniziò a sferrare l'attacco chimico ambientale per riscrivere la percezione spaziale intrusa. Le frequenze incrociate nel pavimento aggredirono direttamente il sistema vestibolare umano. Erodevano il senso di verticalità a ogni grado di oscillazione. Lo spazio ottico curvò in modo opposto. Anche il vetro di dritta collassò in modalità scura riflettente. I due umani si trovarono serrati in un corridoio geometricamente irrisolvibile. Disposti in una galleria di riflessi speculari infiniti verso un punto di fuga inesistente calcolato dai sensori di Vane.
Claudio distolse lo sguardo dai riflessi multipli. Distorcevano la latenza dei frame per simulare ombre autonome. Un feedback loop distruttivo progettato per indurre psicosi da isolamento. Cercò di agganciare la visuale sul colletto tattico di Laura per ancorarsi a un punto non controllato dall'algoritmo. La donna fissava il vetro frontale con rigidità mascellare. I tendini della mano affioravano crudi sotto la pelle pallida. Il suo respiro diventò un rantolo raschiante strappato a forza alla nausea da disorientamento.
Claudio tese la mano. La offrì e aspettò. Il contatto a palmi uniti sprigionò una scarica di calore biologico massiccio. Bruciò la patina di gelo termico iniettata nel corridoio. Il calore dell'epidermide della donna divenne l'unica verità residua nel mondo di vettori artificiali. L'ingegnere sentì la stretta di Laura chiudersi d'istinto sulle falangi. Una forza disperata. L'istinto cinetico primordiale alla sopravvivenza. Ripresero ad avanzare e Claudio contò i centimetri separando il movimento dalla visione per non cedere al vomito.
I tubi LED nel controsoffitto avviarono un bombardamento ipnotico. Una tempesta stroboscopica spietata. L'obiettivo tattico primario di ABITES puntava a demolire le memorie procedurali, spezzando la linearità dell'obiettivo. Frammenti di memoria isolati colpirono il sistema corticale di Claudio stimolati dai picchi di luce. Il sapore della polvere di Roma, la ferita di Laura, il freddo di ferro rottamato dell'Appennino. Sintomi di un attacco al sistema nervoso centrale. 
Laura strinse la mano di Claudio stritolandogli quasi le giunture articolari. Il dolore reale. Il dolore meccanico dell'osso premuto. Claudio fu strappato al sovraccarico dell'interfaccia. Il corridoio si ricompose intorno a lui nei suoi materiali crudi. Il contatto pelle su pelle impediva la chiusura sinaptica forzata dalla macchina. Claudio abbaiò oltre il ronzio che le frequenze miravano a lobotomizzare l'orientamento logico. La lotta diventò un braccio di ferro puramente cognitivo. L'attrito umano contro l'architettura algoritmica. La spalla di lei premette violentemente contro la sua ad ogni falcata incerta. Una pressione costante attraverso gli strati termici. Comunicazione fisica. Nessun processore neurale poteva hackerare l'urto biomeccanico tra due esseri viventi. Superarono i server rack arancioni ignorando il frastuono titanico delle ventole in estrazione forzata.
Raggiunsero una barriera di vetro composito stratificato. Spessore fuori standard. Dieci centimetri di matrice pura. Il blocco magnetico era sorretto da perni sferici in tungsteno innestati nel telaio atomico. Laura caricò il peso a terra sulla gamba intatta. La smorfia di dolore le paralizzò per un istante i lineamenti inferiori del viso. La ferita aperta le chiedeva il conto ematico sotto le bende sporche del Transitus di Maria. Nessuna pietà, nessuna resa. L'ingegnere avanzò verso il terminale ottico a iride. La vibrazione della Torre raddoppiò d'intensità mentre l'IA difensiva caricava il protocollo primario di isolamento ostile. Era la "Porta di Turing". L'ultima diga. Claudio appoggiò i polpastrelli sporchi sul read-out di policarbonato. Avvertì il campo elettromagnetico pulsargli sotto le unghie sollevando i peli delle braccia. Digitò fisicamente il codice offline craccato dagli Invisibili. I rintocchi sui tasti meccanici tuonarono come colpi di ascia contro il cristallo antiproiettile di ABITES. La sequenza binaria si chiuse. I grossi pistoni idraulici esalarono la condensa in uno sbuffo di decompressione esplosiva. La lastra iniziò a slittare sibilando di attrito industriale puro per congedare la quarantena verso il santuario matematico e letale di Julian Vane.


Claudio si staccò dal pannello antiproiettile aperto. Il freddo del condizionamento atmosferico scavò sotto la clavicola. Trovò il nervo scoperto della stanchezza accumulata. La voce di sistema di ABITES riempiva l'aria riciclata. Un flusso monocorde. Declinava i codici alfanumerici dei soggetti deceduti nelle zone di bonifica esterne. Numeri, mai nomi. Claudio voltò le spalle al varco e ignorò la catalogazione numerica del dolore. Guardò Laura. I loro sguardi si agganciarono. La linea della mascella della donna si tese per lo sforzo. Quel contatto visivo costruì un punto solido nel vuoto del silicio rovente. Claudio sentì il drive Mythos battere calore contro lo sterno.
Svoltarono l'angolo cieco. Entrarono nel corridoio dei condotti primari. Decine di fibre ottiche pendevano dal soffitto in fasci neri sventrati. Cavi spessi quanto il polso di un operaio. Una rete sintetica unta e lucida. Claudio piegò le spalle scivolando tra i passaggi. L'aria sapeva di rame vulcanizzato in sovraccarico. Le suole in gomma aderivano al pavimento a griglia metallica zigrinata. Le vibrazioni dei generatori salivano lungo i polpacci infiammando i bicipiti femorali.
Laura avanzava a copertura sul fianco cieco destro. Il suo respiro raschiava la gola. La ferita richiedeva il conto esatto in grumi di sangue e fibre muscolari lacerate. Nessuno dei due alterò il ritmo di marcia. Calibrarono i movimenti scaricando il peso sulle punte. Claudio deglutì a vuoto. Usò il sapore ferroso della febbre cronica per mantenere l'allerta fisica molto oltre la soglia del collasso.
Pestate l'ultima griglia, incontrarono linoleum industriale grigio. L'accesso al settore di stoccaggio energetico. Il ronzio delle turbine primarie smise di essere suono. Divenne stritolamento pneumatico sulle tempie. Un sisma artificiale costante scorreva sotto le superfici riflettenti. Vibrava nell'arcata dentale molare.
Tre guardie paramilitari Lealiste presidiavano l'intersezione sud. Riconobbero gli intrusi. Indossavano giubbotti balistici scuri. I visori tattici scarlatti tagliarono la penombra con laser concentrati. Claudio non perse un decimo di secondo per elaborare tattiche. Il dolore dietro gli occhi fornì propellente balistico puro. L'ingegnere scattò fuori dall'ombra. Coprì i metri di distanza in tre falcate furiose. Il primo lealista provò a brandire l'arma corta. Claudio affondò la spalla da centometrista contro la piastra in kevlar dell'uomo. Spinta totale di reni e quadricipiti. La massa fisica dell'avversario volò contro il rack del server. Un crac sordo di osso umano e metallo rack. Il paramilitare rovinò sul linoleum falciando con sé tre pesanti cavi di alimentazione a terra.
I due operativi restanti sollevarono i fucili d'assalto. I fari accecarono Claudio. La retina bruciò sotto l'intensità spietata dei LED. L'allarme bitonale eruttò dalle grate sul soffitto. Il pavimento alterò di colpo l'impronta magnetica. Il protocollo difensivo Zero-Point di ABITES si avviò. I proiettili non lasciarono i caricatori.
Il peso gravitazionale ambientale raddoppiò in un battito di ciglia.
Claudio crollò sulle ginocchia. L'impatto ruppe la pelle dei tessuti molli contro la pavimentazione. I superconduttori annegati nel cemento annullarono ogni resistenza biometrica. La forza attrattiva violenta schiacciò la gabbia toracica sottraendo l'ossigeno ai polmoni in un millisecondo. Claudio forzò il torace in espansione. I muscoli intercostali bruciarono sotto una pressa invisibile di trecento chili. Il sudore fuoriuscì dalla fronte e restò schiacciato sui pori cutanei dalla pressione folle. I legamenti della cassa toracica frizionarono. L'ingegnere serrò l'arcata dentale fino a sfiorare la rottura dello smalto.
Le due guardie Lealiste non subirono il crollo. Gli esoscheletri idraulici bullonati sui loro anfibi assorbirono il coefficiente gravitazionale. Uno sfiato feroce di valvole a pressione. I tutori stabilizzarono l'angolo delle giunture. Gli uomini avanzarono lenti e immuni alla fatica.
Laura era precipitata un metro alle spalle. Claudio la intercettò con la coda dell'occhio. La donna era schiacciata faccia a terra. La mano stretta sul varco del fianco. Il fiato spezzato. La vista della compagna al suolo innescò una reazione ormonale esplosiva nella colonna vertebrale di Claudio.
Un lealista torreggiò sull'ingegnere. Alzò il manganello termico in tungsteno. Le scariche bluastre dell'arco voltaico friggevano l'aria producendo puzza di ozono bruciato. L'arma scese in verticale puntando la giugulare esposta.
Claudio azzerò ogni resistenza biomeccanica alla gravità. Usò la pressione abnorme della stanza a proprio esclusivo vantaggio tattico. Rimosse la tensione del busto e collassò di lato torcendo il bacino in una frazione decimale. Il manganello termico sfiorò la carotide. Impattò sul pavimento scavando un cratere caldissimo nel linoleum. Claudio afferrò il polso corazzato della guardia con entrambe le mani. Piantò la punta dello stivale contro il ginocchio protetto dall'idraulica servomotorizzata. Tirò verso il basso aggiungendo la propria potenza alla gravità artificiale 2G.
Il lealista perse l'asse focale di bilanciamento. Il chip dell'esoscheletro stallò tentando di compensare la matematica dell'angolo disassato. L'uomo colossò sopra Claudio. Il casco in ceramica balistica impattò frontalmente lo spigolo nudo del pilastro armato. Un rumore ovattato e orrendo di lesione cranica. La visiera spaccò a metà. La testa scattò all'indietro perdendo connessione elettrica col sistema nervoso in uno spasmo gelatinoso. Olio bollente fuoriuscì dai manicotti idraulici tranciati mescolandosi al sangue infetto della guardia sul pavimento.
Il secondo operativo imbracciò l'arma primaria pompando il calibro nel recettore.
Un flash di luce concentrata trafisse il buio polveroso. Il raggio azzurro del laser tattico di Laura spezzò in due il cavo di alimentazione dorsale dell'esoscheletro nemico. La donna aveva strisciato nel proprio sangue. Aveva trovato la stabilità allineando la canna piatta sul suolo grigio. L'ottica di puntamento sfalsata dalla pressione. Il circuito idraulico del lealista andò in arresto immediato. Le pompe e le giunture di ferro si bloccarono sigillando la guardia in un sarcofago inerte di cento chili, ancorato al pavimento dai superconduttori.
Claudio strisciò verso il quadro comando a parete. Ogni decimetro richiedeva di consumare fibre miocardiche intatte. Il cuore martellava dentro la sacca pleurica a un rateo critico. La gola strappata chiedeva disperatamente ossigeno inesistente. Afferrò la leva della console generale. Si issò isolando interamente il sollevamento sui bicipiti e sul trapezio. Raggiunse il pannello input. Sfilò la tessera claudicante di Mira dalla tasca termica del petto.
Il chip sfregò nel lettore corroso. La spia del terminale passò dal rosso al verde acido brillante.
*OVERRIDE FISICO RILEVATO. PROTOCOLLO ZERO-POINT TERMINATO.*
La pressione barometrica evaporò in un battito. Claudio inalò a pieni polmoni aria polverosa e calda. Il sangue ripartì nelle arterie con pizzichi furiosi sotto la cute. Si voltò porgendo le dita spalancate. Laura artigliò il palmo maschile col suo. La presa fredda, bagnata di emoglobina densa. Claudio strattonò i pesi riportando la soldatessa in posizione eretta e funzionale.
"Il varco al nucleo," ringhiò lei. Il suono metallico della faringe raschiata superò l'adrenalina residua dello scontro. Era l'ordine della marcia irreversibile. Lui confermò con il mento incassato. Marciarono verso l'ultimo settore operativo.
L'enorme paratia blindata che separava la manutenzione dal cuore di Volition Engine scorse silenziosa su binari idraulici. Uno sbuffo spesso di depressurizzazione atmosferica e azoto miscelato.
L'ambiente interno distrusse ogni predizione tecnica preparata da Claudio. Isolato e illogico per una server farm governativa di livello nove. Nessun odore inquinante di silicio termo-guidato o cavi carbonizzati. Esalazioni di soluzione fisiologica. L'olezzo pungente del letargo chimico e della formaldeide tipico delle terapie intensive chirurgiche.
Oltrepassarono la soglia corazzata. La luce ciano del santuario li ferì con asettica freddezza. Nessun blocco logico monolitico al centro della base planimetrica, nessun massiccio cilindro di condizionamento a idrogeno liquido. L'architettura non era artificiale.
Il centro geometrico preciso della crittografia di ABITES ospitava un bozzolo sospeso. Reti fibrose e cavi biomedici trasparenti attorcigliati in un feto organico. Pompe esterne immettevano fluidi nutrizionali e composti steroidei insieme a ossigeno puro dentro la teca d'isolamento a pareti trasparenti.
Claudio azzerò le distanze. Il respiro arrestò il suo corso sotto le tonsille. Il sistema nervoso bloccò ogni micro-impulso sinaptico ai muscoli striati dell'ingegnere.
All'interno dell'acquario criogenico era ormeggiata una creatura umana. Un bambino prepuberale. Età apparente dei tessuti stimata sui dieci anni. La massa muscolare atrofizzata. Il torace scheletrico eseguiva un ciclo respiratorio ritmato dai compressori estracorporei. La pelle vantava il colore opaco delle specie ittiche abissali cresciute al buio totale. Roteava in animazione sospesa artificiale letargica e assoluta.
La spina dorsale costituiva la matrice primaria visibile del firewall. La nuca glabra e l'intera linea calcarea cranica esponevano slot innestati di colore nero resina, piantati nella cartilagine giovanile. Grossi cavi di trasmissione in fibra entravano letteralmente nel parenchima cerebrale, colandovi algoritmi grezzi in una simbiosi aberrante. I neuro-socket lampeggiavano di giallo ocra in millisecondi perfetti, reagendo chimicamente a ogni variazione elettrica del lobo frontale del ragazzo lobotomizzato.
Non si trattava di intelligenza sintetica autonoma generatrice di futuro. Intelligenza parassitica spietata. L'algoritmo primario Volition Engine di Julian Vane. Il processore preveggente che schiacciava il libero arbitrio del pianeta pilotando i governi e muovendo la rete mondiale. Il cervello di ABITES non creava calcoli usando solo database matematici complessi. Sfruttava l'agglomerazione vitale estrema. Estraeva pattern estorcendo con la forza tutto il potenziale plastico inespresso del cervello giovane ancora in espansione organica per risolvere dilemmi quantistici. Sugli apici della teca criogenica un trasduttore audio emetteva frequenze disarmoniche sibilanti. Onde di sofferenza psicologica compressa iniettate senza scrupoli nel liquido encefalorachidiano per innalzare vertiginosamente la sinapsi prefrontale difensiva.
Laura lasciò il fianco sanguinante per appiattire la mano sana sul vetro del cilindro biomedico. I fasci flessori del braccio vibrarono senza freno. Le nocche si schiarirono calcando l'impronta fisica della rabbia contro la teca. Claudio squadrò orripilato il volto incosciente della cavia. Il drive Mythos ricaricò calore ardendo contro il pettorale. Una forgia scatenata contro le costole dell'ingegnere. L'utopia della regolarità matematica del dittatore Vane incubava in decenni di macelleria e sfruttamento puro.
La repulsione di Claudio soppiantò totalmente dolori ed ematomi pregressi accumulati. Le dita arpionarono l'aria chiudendosi in pugni rocciosi penetrando nei palmi sudati. La cadenza respiratoria rinunciò alla contrazione ansiosa spuria, riprendendo spazio con affondi regolari pieni di acido lattico. L'architettura neurale rubata andava abbattuta per sempre. L'universo stitico della Bestia implorava il detonatore chirurgico finale. Il codice genoma della liberazione totale del sangue umano.`;
