export const chapter22Content = `Il fumo arrivava prima dei passi. Era acre e denso, un odore di plastica bruciata che si attaccava ai polmoni. Dubois conosceva bene quell'odore: era la puzza dei droni che andavano a fuoco.
Lione, terzo arrondissement. Le strade strette e i palazzi vecchi rendevano ogni angolo una trappola o una salvezza. Dipendeva da chi arrivava per primo.
— Rue Mercière, avanzate sul lato sinistro! — ordinò Dubois. Non aveva più la radio, quindi urlava a squarciagola. I suoi uomini la sentivano perché il silenzio della città era rotto solo dai loro passi pesanti.
Trenta metri più avanti, un drone da ricognizione giaceva a terra con le eliche spezzate. Il blackout lo aveva fatto cadere come un sasso. Dubois ci passò sopra, sentendo l'alluminio che scricchiolava sotto i suoi stivali. Un rumore secco, quasi piacevole.
Garnier correva alla sua sinistra. Era un vecchio ispettore con un ginocchio malandato e una doppietta calibro dodici sempre pronta. A destra c'era Hana, una ragazza di ventisei anni che prima della guerra gestiva un negozietto. Ora imbracciava un fucile automatico recuperato da un soldato nemico. Non erano professionisti della guerra. Erano persone comuni che avevano deciso di non arrendersi.
All'angolo del vicolo, due soldati lealisti cercavano riparo dietro una barriera di cemento. Senza il supporto dei droni, sembravano persi. Si guardavano intorno nervosi, aspettando ordini che non arrivavano più.
— Garnier, ora! — gridò Dubois.
Il vecchio sparò un colpo che gli scosse l'intera spalla. Un lealista si abbassò, l'altro rimase paralizzato per un secondo di troppo. Hana sparò due raffiche brevi, costringendoli a non alzare la testa. Dubois ne approfittò per scattare in avanti, rasente al muro, ignorando il bruciore ai polmoni. 
Pochi istanti dopo, i due lealisti gettarono le armi e alzarono le mani. Erano poco più che ragazzi. Uno di loro piangeva.
— Seduti lì. Non muovetevi — ordinò Dubois.
Li legarono ai tubi di un vecchio negozio e lasciarono loro un po' d'acqua. Poi proseguirono.
Lione stava cacciando via gli invasori. Dalle finestre la gente non urlava più per la paura. Erano voci roche, grida di chi sta finalmente tirando fuori anni di rabbia repressa. Un bambino correva sul marciapiede portando una scatola di proiettili, come se fosse un tesoro. Dubois non sorrise, ma sentì che le gambe erano diventate più leggere.

***

L’odore fu la prima cosa che avvertirono. Una mistura di candeggina, ferite aperte e medicine scadute. Claudio aprì gli occhi a fatica. Erano in un enorme capannone industriale, un rifugio della resistenza trasformato in ospedale.
Il soffitto era altissimo e le finestre rotte erano state coperte con teloni di plastica nera. Lampade da cantiere illuminavano file di brandine pieghevoli e materassi buttati per terra. C'erano almeno cinquanta persone, ferite in ogni modo.
Laura sorreggeva Claudio, ignorando il dolore alla sua spalla squarciata. Ogni passo era una tortura, ma non si fermò finché non lo vide steso su una brandina. Un uomo in camice verde sporco si avvicinò, controllò le ferite di Claudio e fece un cenno a un'infermiera.
Claudio si addormentò quasi subito, vinto dalla febbre e dalla stanchezza.
Laura si sedette a terra, appoggiata al muro gelido. Teneva il braccio ferito vicino al petto e respirava piano per non far male alle costole. Iniziò a guardarsi intorno, cercando di capire dove si trovassero.
Dall'altra parte del capannone, un uomo lavorava senza sosta. Non era molto alto, ma aveva spalle larghe e movimenti sicuri. Qualcuno lo chiamò Mario.
Laura lo osservò. Mario passava da un paziente all'altro con una calma che sembrava irreale in quel posto. Non correva, ma non stava mai fermo. Si chinava sui feriti, parlava a bassa voce con loro, metteva una mano sulla spalla di chi tremava per il freddo o per la paura. Non sembrava solo un medico che cura ferite, ma un uomo che si prende cura delle persone.
Lo vide curare un vecchio che respirava a fatica. Mario gli sistemò il cuscino, gli pulì la fronte col sudore e gli disse qualcosa che lo fece rilassare. Il vecchio smise di lamentarsi e chiuse gli occhi, ascoltando quella voce tranquilla.
Mario aveva le mani sporche di sangue, ma non sembrava importargli. Le puliva velocemente con una pezza e ricominciava da capo. Curava una gamba rotta, fasciava un braccio ustionato, dava da bere a chi aveva sete. Trattava tutti allo stesso modo, con una pazienza infinita.
Laura, che per tutta la vita aveva visto solo violenza, odio e calcoli glaciali, rimase sorpresa. Era abituata a valutare le persone per la loro utilità o per il pericolo che rappresentavano. Ma quell'uomo era diverso. Non c'era cattiveria in lui, solo un desiderio pulito di aiutare.
Mario si fermò davanti a una donna anziana che stava morendo. Non c'erano più medicine per lei. Mario si sedette vicino a lei, le prese le mani tra le sue e rimase lì in silenzio. Aspettò che la donna stringesse la sua mano, facendole sentire che non era sola.
Laura sentì un calore strano nel petto. Non era rabbia, non era adrenalina. Era qualcosa che non provava da anni.
Aveva visto uomini combattere e morire per una bandiera o per vendetta. Conosceva bene quella forza brutale. Ma la forza di Mario era diversa. Era una forza che non distruggeva, ma costruiva. Nonostante la stanchezza fosse evidente nei suoi occhi, Mario non si fermava. Dava tutto quello che aveva, e sembrava averne sempre dell'altro da offrire.
Il suono di una garza che veniva strappata ruppe il silenzio del capannone. Mario stava bendando il braccio di un ragazzo rimasto ferito durante un'esplosione. Lavorava con attenzione, attento a non fare troppo male. Il ragazzo guardava il soffitto, cercando di non piangere. Mario gli sorrise e gli diede una pacca sulla spalla.
Laura appoggiò la testa al muro e chiuse gli occhi per un secondo. Il braccio le faceva male, le costole bruciavano. La fatica era come un peso enorme sulla schiena.
Eppure, nonostante tutto, si sentiva al sicuro. 
Rimase lì a guardare Mario che si muoveva nell'oscurità tra le lampade accese. Vedere quel modo di fare, così pieno di amore per la vita in mezzo a tanta morte, le diede una spinta inaspettata. Era come un piccolo fuoco acceso in una stanza gelida. Per la prima volta dopo tanto tempo, Laura sentì che forse, dopotutto, valeva la pena continuare a combattere. Non solo per distruggere ABITES, ma per proteggere persone come Mario.`;
