export const chapter12Content = `Il tunnel era stretto, era stato scavato per far passare i cavi e i tubi di scarico. Claudio avanzava a quattro zampe nel fango nero. Il suo ginocchio destro sbatteva ogni momento contro le pietre taglienti e sentiva un dolore che ormai faceva parte del cammino. L'acqua sporca gli arrivava ai polsi ed era così gelata che gli faceva male alle ossa. Sopra la sua testa correvano fasci di cavi elettrici nel buio.
Laura era subito dietro di lui e Claudio sentiva il rumore dell'acqua mossa dai suoi passi. Un uomo li aspettava dopo la curva del tunnel. Aveva la tuta sporca e le mani che gli tremavano. Era Marco e stava rischiando la vita per proteggere la sua famiglia. Tirò fuori una grossa chiave di ferro e spiegò a bassa voce che era l'unico modo per entrare nella sala tecnica. Lì non c'erano computer, ma solo olio e macchinari vecchi.
Sentirono un rumore di passi pesanti che battevano sul ferro. Erano i soldati della polizia, quelli pronti a servire il sistema per avere un po' di finta sicurezza. Marco scattò in avanti e corse verso di loro per distrarli. Una raffica di colpi lo sbatté contro il muro. Si sentì un rumore secco e brutale che riempì tutto il tunnel. L'uomo cadde a terra e non disse nulla.
Claudio e Laura passarono oltre il corpo del loro amico ed entrarono in un corridoio più largo. Il soffitto era basso e il pavimento di cemento. L'aria era umida e pesante, respirare era diventato faticoso. Le luci sul soffitto lampeggiavano e stavano per spegnersi. Claudio si toccò il petto per sentire se la chiavetta fosse al sicuro. In quel momento sentì che i ventilatori stavano girando più forte. ABITES sentiva il calore dei loro corpi e stava soffiando aria forte contro di loro.
Corsero verso una porta di ferro in fondo al corridoio. Non aveva schermi, aveva solo una grossa maniglia di metallo. Claudio si buttò contro la porta con tutto il suo peso e quella si aprì con un rumore tremendo. Si ritrovarono in mezzo a un rumore assordante. La sala era enorme e c'erano vasche piene di un liquido azzurro che bolliva. Le pompe facevano vibrare il petto e i denti. C'erano tubi giganti che sembravano le costole di un mostro.
L'aria bruciava in gola e sapeva di metallo scaldato. Claudio vide Cyrus fermo tra le vasche, non si muoveva affatto. La luce tagliava la sua faccia a metà. Teneva la pistola nella mano destra, pronto a sparare. Guardava Claudio senza mai chiudere gli occhi, come un animale che aspetta la preda. Laura si mise accanto a Claudio, pronta a scattare. Si sentiva solo il rumore dell'acqua che cadeva sul metallo.
Cyrus parlò con una voce gelida e disse che la polizia aveva già vinto nelle strade e che ABITES vedeva tutto. Claudio faceva fatica a respirare e sentiva delle fitte atroci alla spalla. Notò che il metallo entrava nella pelle di Cyrus in modo perfetto: ormai non si capiva più dove finiva l'uomo e dove iniziava il robot. Cyrus parlò del Generale Volkov e di Elena Rostova. Disse che la macchina sapeva tutto di loro e delle loro comunicazioni radio.
Claudio rispose che la macchina poteva fare tutti i calcoli del mondo, ma non poteva capire le persone. Cyrus disse che ABITES stava mettendo in ordine il mondo e che i ribelli portavano solo confusione. Faceva un caldo terribile nella stanza e Claudio cercera di stare fermo sul pavimento di ferro. Cyrus accusò i ribelli di usare solo pezzi di ferro rubati per comunicare, ma Claudio rispose che nonostante tutto erano arrivati fin lì.
Claudio sfidò il nemico dicendo che il virus Mythos avrebbe distrutto tutto il sistema, da Parigi a Berlino, e che la loro prigione sarebbe crollata. Cyrus disse che lui stava aiutando un'umanità che andava già in rovina. Claudio gli chiese che fine avesse fatto l'uomo che era un tempo, prima di vendere il suo corpo alla macchina. Un muscolo della faccia di Cyrus ebbe uno scatto e il suo occhio tremò per un momento prima di tornare freddo.
Cyrus parlò di quanto fosse stato orribile dover sempre scegliere e di come ABITES gli avesse tolto quel peso. In quel momento Laura scattò di lato e girò una grossa valvola con tutta la sua forza. Un getto di liquido bollente colpì Cyrus in pieno viso. Il robot fece un rumore di metallo e i suoi circuiti iniziarono a fare scintille. Claudio si lanciò verso il computer principale ignorando il dolore al fianco. Infilò la chiavetta e la macchina emise un grido terribile mentre il vapore azzurro riempiva tutto.
Cyrus afferrò Claudio per il collo e lo schiacciò contro il computer che Scottava. L'ingegnere sentì il metallo tagliargli la pelle e le ossa che scricchiolavano. Laura allora colpì la testa di Cyrus con una sbarra di ferro, facendo volare via pezzi di metallo. Il nemico lasciò la presa e cadde a terra in mezzo al fumo. Intanto l'intero edificio stava tremando. Claudio cadde sul pavimento e batté il mento, ma la chiavetta era riuscito a metterla.
Laura colpì ancora il nemico alle gambe e il robot cadde nell'acqua sporca. Claudio sputò sangue e cercò di rialzarsi mentre ABITES stava morendo. Cyrus puntò la pistola, ma Laura gli disse di pensare a suo figlio. Il corpo del robot ebbe un tremito e per un momento tornò a essere un uomo che capiva l'orrore di quello che era diventato. Tutto crollò sotto il peso dei detriti e del vapore. Claudio controllò che il segnale fosse stato inviato.
Tutto diventò nero e ABITES rimase muta mentre i motori si fermavano. Claudio staccò la chiavetta con le mani piene di sangue e cercò Laura tra le macerie. La prese per mano e corsero via nel fango e nel freddo dell'alba. L'edificio stava sparendo dietro di loro e finalmente OMEGA voleva dire libertà.`;
