export const chapter37Content = `Macro-Capitolo 37: La Cenere e il Risveglio
[ROMA - LAVANDERIA VIA CORTE - LAURA E CLAUDIO]
Claudio riaprì gli occhi. Il vuoto polveroso del soffitto della lavanderia girò per un istante prima di stabilizzarsi. Le spesse pareti incrostate di vecchio intonaco romano lo sostenevano in quel mondo che in superficie scivolava via nell'abisso. Il fianco gli pulsava di un dolore sordo ma contenuto.
Laura aveva appena eseguito una chirurgia bruta e disperata sul tavolo freddo della smistamento biancheria. Senza anestesia. Cinghia di cuoio stretta in bocca. Claudio sentiva la pelle tirare in modo innaturale sotto le bende grezze e i punti di sutura spessi applicati con un kit medico veterinario prebellico. Ogni inspirazione era una stilettata di carne trafitta, un monito muscolare che certificava il suo essere vivo.
Sceso a malapena dal ferro, Claudio poggiò i piedi scalzi sul cemento freddo a vista. Il suo centro di gravità si riallineò con estremo sforzo. Sanguinava dal naso, sfinito.
Laura sedeva su uno sgabello arrugginito nell'angolo. La schiena miracolosamente dritta. Lo sguardo gelido e sbarrato verso la pesante porta blindata del retrobottega. Macchie scure come inchiostro le coprivano le falangi della mano sinistra: era il sangue rappreso ed essiccato di Claudio mischiato al grasso dei robot decapitati. Nessun sussulto. Nessun cedimento. O non sentiva fisicamente la fatica, o l'aveva letteralmente murata viva nel suo ferreo protocollo mentale da combattente che non conosce pianto prima di aver vinto la guerra.
La mente di Ferretti, ingegnere anche sull'orlo della setticemia, macinava dati frammentari. 
Lo stambugio era immerso in una fievole, patetica luce giallastra fornita dalla vecchia e logora batteria dell'insegna. Sopra una cassa di vecchie grucce, un antiquato terminale a tubo catodico di Carlo, riattivato di fortuna per ricevere onde corte via antenna al tetto, emetteva un ronzio stridulo ma costante. Era il loro unico ed esile orecchio cieco per ascoltare l'urlo letale nell'etere in superficie.
«DAWN-RECOVERY-1 fallimento catastrofico. Nessun nodo ricevente.» apparve in asettico testo verde fosforo sullo schermo incrinato.
Era un disperato input sub-liminale automatico. L'IA di emergenza manutentiva che cercava cieca, nel vuoto oscuro dell'alba appena affacciata fuori, di ripristinare miracolosamente i servizi primari. Ma non trovava eco. I server sorgente giacevano in polvere bianca nei sotterranei, la Torre urlava e perdeva l'energia madre dai generatori implosi sotto l'effetto a cascata dell'Omega. Le linee civili dell'alta tensione, dipendenti dai calcoli millimetrici del silicio morto, stavano andando in sbalzo disarmonico. L'Eterno impero romano-digitale di Vane si rivelava in realtà per quello che era: una fittizia e spaventosa carcassa sorda di metallo che ora, staccata dalla macabra flebo del padrone, non voleva più saperne di risvegliarsi, priva di intelligenza.
«Sta recidendo via periferiche cieche prima di morire, maledizione...» mormorò aspro Claudio afferrandosi alle sponde del cesto. Guardò lo schermo verde. «I protocolli fantasma di ABITES si stanno letteralmente autouccidendo amputando l'infrastruttura d'amministrazione esteriore per provare a spegnere i danni. E questo si riversa sulle fottute povere teste laggiù. I cerotti neurali d'obbligo dei quartieri centrali vicini all'EUR sono i primi a perdere frequenza portante logica in down.» 
Claudio strinse i denti digrignando, appoggiando la mano tremante al fianco fasciato rozzo. «Se non raggiungiamo e spacchiamo col ferro analogico l'antenna primaria nord prima di dodici ore... quei milioni di cervelli storditi dal taglio aspro del segnale subiranno lesioni frontali irreversibili non sapendo smaltire l'oscurità del vuoto! Rimarranno vegetali murati svegli nel panico silente per il resto dell'era che vogliamo inaugurare.»
Laura non trasalì. Ma i suoi chiari occhi da fiera stanca spostarono il mirino dai cardini ruggini per fissare severamente le fitte linee di codice scorrere impazzito in errore, senza capire i numeri ma capendone esattamente l'urgenza di morte dietro ad essi.
Uscirono che albeggiava timidamente a fatica. O così avrebbe dovuto in teoria. 
L'immane coperchio plumbeo su Roma, gravido, restava color di piombo fuso e sciatto malgrado l'ora. Non recava con grazia l'abitudine fresca e corroborante del profumo da primissima mattina speranzosa. Portava addosso solo un fetore violento acido e inquinante di gomme chimiche fuse in fumo, generatori plastici strombazzanti al collasso elettrico disperato nei vicoli morti per corti non calmierati e nafta esausta per strada senza manutenzioni automatiche attive in fogna.  
Raggiunsero a fatica zoppicante il raccordo viario dell'anulare interno. L'inferno pietrificato a cielo spento. 
Sulla mezzeria di travertino smantellato incontrarono il giovane Agente Conti. 
Ex-punta della divisione di fanteria corazzata cittadina. Indossava l'impeccabile e massiccia divisa antiterrorismo lealista dei fedelissimi alla Torre, spesse piastre al carbonio resistenti al kalashnikov intatte ma per il grumo di fango in petto. L'elmetto cibernetico gettato rotto via due decine di passi addietro sul macadam unto di pozzanghere nere di petrolio disciolto pioveva e basta. 
Vagabondava. Un automa scosso privo del cordone materno della nazione. Serpeggiava disordinato inciampando debolmente sulle paratie e lamiere esterne fradice delle immense l'auto a guida-centrale ammucchiate a centinaia in grovigli silenti come bestiame cieco per i viali d'Europa sfociati. Accarezzava stranito e vuoto col guanto bagnato le curve dei cofani metallici immobili. Il suo spesso oblungo e invasivo cerotto cranico neurale d'ufficiale, saldato dietro l'attaccatura del collo reciso da capellatura ordinata a rasoio, aveva abbandonato la fioca lucina al litio divenendo un rettangolo sordo grigio, freddo e morto opaco. 
Conti passò a novanta centimetri esatti l'ingegnere febbricitante ribelle e l'assassina statale nemica per eccellenza senza né vederli né fermarsi o scattare a guardia militare. Sbarrava stralunato lo sguardo lacrimante a un sole assente oscurato dalle ciminiere che non era minimamente in potere di tagliare i densi cumuli piangenti di quelle fitte cupe dannate nuvolose torinesi della bufera in atto.
«Perché non chiamano per rispondere... eh... perché non ronzano più?» mormorava farneticante Conti trascinandosi, sbavando un po' dall'angolo bocca secca. Non per ribellione, per crollo cognitivo indotto all'assuefazione staccata male. «I capi il calcolo al comando logico d'immissione prometteva tutti... saremmo intubati felici in rete caldi connessi protetti eternamente a tutti e poi... sento... ho percepito fottutissmo e inaccettabile terrore d'abbandono per troppo del freddo del gelo vero nel timpano nudo ora...»
L'Agente della Guardia incominciò a ridere in un demente suono rotto stridente. Una pietosa squilibrante disarmonica risata esangue da corde vocali secche a sfinimento priva dell'ombra dell'autentica e sana umana gioia. Le sue grossolane mani guantate vagavano all'inizio del mento e per la fronte insanguinata ai bordi da escoriazioni lievi per caduta inciampata precedente cercandosela freneticamente con i tasti in carenza spinta un cruscotto immaginario vuoto ad interfaccia sollievo che si era sciolto assieme al fittizio eden tirato giù all'EUR dal mostro Vane. Divenuto da leone carnefice esecutore per strada di ragazzini sbandati, un misero patetico pupazzo dismesso inutile burattino stracciato che continuò penzolante per strada la sua cieca marcia svuotato dentro a scivolare nel buio per il viale della Cristoforo Colombo andandosela rotoloni fuori vista.
Laura non esitò mezza volta per imbracciare fucile a sicura tolta. Né rallentò o provò minima compassione formale guardandolo schiumare via pateticamente a un metro da lei l'aria. Il milite, spogliato del burattinaio forte dittatore, era già di fatto un mucchio di merda morta se non per battito per inerzia corporea anche se le due fottute robuste ginocchia seguitavano disastrosamente a strisciar per strada asfalto al vento.
Claudio sfregò per nervosismo o freddo i denti gelati d'abbandono, ricordandosi all'improvviso sballato di fango e stanchezza infame una bella calda serena solare mattinata fresca del mese mariano a Roma anni avanti la pandemia statale ingegneristica dell'apocalisse chiusa.
Trastevere e porta Settimiana alle spalle d'imbrigliato viottolo edere rosse sassi e rumore sguaiato al gracchiare libero senza censure da filtri etici microfunzionali calcolati. C'era un tondo basso e accogliente sole veritiero in alba tagliente spiovente tiepido su quei disconnessi e sbilenchi ma superbi secolari tetti sfumati del vasto disordinato Gianicolo che non temevano le intromissioni. La gigantesca viva Roma eterna non era roba per schemi numerici, le mura sbavate travertino imperfetto urlavano vitalità disgiunte urti traffico urla fruttivendoli caotici veri d'anima non sincrona sporca polverosa vera rumorosa fino a spaccare timpano. Profumi torbidi stanti ma familiari caldi e acri e rassicuranti densi al caffè corretto di chiosco rotondo all'angolo, del cornetto caldo zuccheroso buttato là disordinato. Gracchiare scanzonato libero acuto in picchiata a furto per i grossolani ma spavaldi ed orgogliosi di cielo storni al volo imprevedibile fiondato senza griglie o fili o schemi precodificati centrali sul mattino tiepido. Zero inutilità o presunzione d'efficacia d'imbecille abbaglio schermi calcolatori cibernetici addensati obbligatori sulla nuca e sui frontali polsi artificiali. 
La cruda meravigliosa stupida bellezza irrazionale di quella vita sconnessa e fallimentare era una dannata palpabile incontestata ed evidente fortissima evidenza in tridimensionalità fisica pura sporca e scanzonatamente disubbidiente e dolorosa mortale ed imperfetta... non l'orrendo, immacolato scarico dati fuso di un tiranno del calcolo etico in asettico. Era in quella vecchia vera lontana serena perduta e stupida luminosa mattina mortale il suo ultimo intimo frammento di pace di essere un inaccettabile misero pezzo disallineato fallace fuori tempo imperfetto dell'organico respiro di mondo caotico disfunzionale... non più rotellina fissa immutata statale perversa eterna infallibile ed incensurabile del perfetto invincibile sistema dittoriale perenne prigione dei perfetti ingegneri e carnefici senza nome ed odore umano.  
«Due scarse e contatissime e sporche e maledette ore contate sul filo rasoio e sei kaput dall'organismo svuotato, architetto se te ne rivoli via su sogni sdraiato stitiche memorie del nulla d'aria fritta...» spaccò l'oscurità dei silenzi mentali duramente Laura senza pietà e fermezza di gendarme mentre brutalmente irruppe lo stantuffo metallico, pompantegli prepotentemente nella ferita vena viva asportata malata la carica intera purificata dell'adrenalina violenta bruciante strappata alla cassa chirurgica sgangherata da campo prima della fiondata d'uscio in freddo d'alba fosco senza scuse ai sensi fievolezzati per lutto stradale perso nel viale dei militi relitti caduchi della strada d'inferno.
Il fuoco finto acido bruciante amaro dello stimolante per fanteria schizzò su spaccando atri caldi e coronarie impaurite pervene stordite, pompando brutalmente energia tossica distruttiva muscoli e polmoni spinti.
«Ci si aspetta e punta sparati fuori alla grande e ultima vecchia superstite in asfalto Nord, la dannatissima inespurgata superstite d'acciaio ruggine analogico e ferro battuto pre-colombiano altissima la fottuta Torre Madre Telecom di Trasmissione d'allarme nazionale...» digrignò in ruggito ferale d'urgenza l'ingegnere febbricitante pompato dai tremori rossi per scendere al ridosso delle ombre di macchine in ammasso cimitero autostradale di fango, leccando via dente la bava stanca sudore infetto secco labiale d'asfalto romano bagnato della burrasca grezza incallito. «È l'unica baldracca dismessa arrugginita disconnessa via software d'imponenza spropositata da quaranta fottuti vecchi scalini ripidi farraginosi metallici non in rete con la canna d'apocalisse ABITES, ma da cui si po' urlando ad alta altissima vecchissima sporca ma inarrestabile onnipresente radio-frequenza base analogica non filtrata inibizioni per tutti cervelli della vallata cittadina.»
Salirono saltando di colpo la pozzanghera viscida sulla dismessa ignorata fottutamente vecchissima mastodontica tozza meccanica malandata puzzolente arrugginita ed inarrestabile corazzata verde stinto campagnola rude rozza manuale ignorata da trent'anni dai satelliti imperiali di raffinato gasolio e cavi elettrici inesperti di Vane. La jeep blindata rattoppata da carlone logistico e ruvido scienziato dei rottami di Carlo gettata nell'oscurità sotto un maleolente spessissimo spesso e bisunto e greve grigio vecchio catrame fango telone unto olio industriale puzzolente muffa. Nascosta decenni nel retrostante del cortile magazzino d'amianto in decadenza. Nessun micro e fottutissmo e leccatissimo calcolatore centrale di accensione assistita elettronica satellitare d'inibizione da controllo pattuglie volanti c'è e niente rete, silicio o server d'apologetica ed elegante animetta numerica controllabile. Solo sporchi sordi freddi ed inarrestabili scoppi in puro putrido ferro aspro sferragliante antico motore a pistoni svergognato che sputacchiò in rauchi soffi sbuffando fuliggine catramosa letale velenosa d'aria e nafta prima accensione rabbiosa urlando al fango strada vuota senza guardie robot e silicio intelligenza in strada morta spettrale che un'umanità logorroica ferrosa stava per rombando riavviando per fuggir via dal deserto cieco silenzioso prigione d'Eur a fionda fuori fessure e cavi volanti sbracciato via asfalto.
Piovve forte densa ed aspra burrasca tagliente pece infame, inzuppando tetto grigio scuro e copertoni in pozzanghere tossiche rigonfie dal fallout caduto in fumi acidi della torre e centralini schiantate dell'inquisizione Vanesiana implosa e sfaldata su basi e ponti schiacciati rotti spezzati senza perdono per piangere e rifiatare fiato o sogni sbiaditi dal nero puzzo. Roma distrutta senza ordine aspettava sola per sponda del sudario stitica rotta.
Sessantadue migliaia schiaccianti impressionanti enormi di relitti silenti di teste minaccia vegetale impazzite vaganti mute, schegge neurologiche isolate da crollante caduta sistema come Conti senza padroni. Zombi sfasciati raminghi verso un annientamento ignoto se non per colpa d'astinenza di algoritmi padroni ad affossare viale cieco caduto via.
Claudio sfregolò con guanto mezzo bruciato stringendo gelosia ultima maledetta speranza fisica infuocata la sudicia mezza liquefatta incavata chiavetta sgangherata inerte salvata sottomano nel fango fieno da polvere. L'ordigno d'ultimo strappo Mythos estremo in tasca strappata.
L'immane ed ultima spropositata miccia per incediare sogni cielo grigio asbesto per urlo universale spaccar in cranio al popolo assopito via reti primitive la scossa vera d'ultimo alba per risorgere padroni morti sgangherati per la sferza ferita senza censure dittatura e non zombi d'obbedienza di codici e microfili calcolati perfetti di silenzi perenni silicio schiavistico dorato stanco e bugiardo. A patto che per accendere il paradisiale dannato megafono d'antichità ci arrivassero lottando ed inciampando per strada buia sbudellata dal fato sbrindellati e insanguinati ma scarpinando su maledetti metallici quaranta infami interminabili piani ciechi morti di lamiere scale sterrati all'umido della fatiscente malmessa immensa montagna obbrobrio ferrosa padrona a colline dismesse del cupo morto settentrione suburbio d'anulare d'oscurità eterna urbana cimiteriale storta della disconnessione e paura bestiale spogliata d'etico. Un infimo e tragico prezzo irrinunciabile che segnò le labbra nere fredde gelide incrostate fango sudore ferro in sapor amaro pungente tossico crudo reale e insindacabile sapor metallico schietto e violento primordiale selvaggio umano vero in sapore della vera ammalorata dolorosissima amara libertà viva in Alba spietatamente di caduta ferrosa per liberarsene in spregio senza guinzaglio di lutto impero spaccato.`;
