export const chapter16Content = `Macro-Capitolo 16: Il Carico Fantasma
[AUTOSTRADA A2 SALERNO-REGGIO - BIVIO SUD]
L'alba sulla Salerno-Reggio Calabria fu un ammasso informe di nubi violacee e minacciose. La pioggia torrenziale colpiva i vetri del veicolo con la forza di proiettili d'acqua. Il furgone avanzava a settanta chilometri l'ora costanti. Gli pneumatici sibilavano sull'asfalto allagato, sollevando enormi nuvole di vapore.
Il vecchio trasporto medico era un guscio di metallo anonimo e arrugginito. Carlo aveva recuperato il veicolo dai magazzini sotterranei dell'Eur. Sei quintali di piombo massiccio rivestivano il vano posteriore. La schermatura accecava i sensori ad alta frequenza dei droni. ABITES setacciava incessantemente i cieli degli Appennini con i suoi sensori a infrarossi di precisione orbitale.
Laura bloccò i gomiti sul volante screpolato. Era vigile, ogni fibra del suo corpo tesa allo spasmo. Le spazzole dei tergicristalli lottavano inefficacemente contro la forza della tempesta. L'abitacolo sapeva di formaldeide, polvere e muffa antica. La donna non distolse mai lo sguardo dalla strada scura.
Claudio bruciava nel retro del mezzo, in preda a una febbre altissima. Le cinghie di contenzione lo tenevano fermo sulla barella arrugginita. La febbre da necrosi aveva invaso i linfonodi ascellari. L'ustione sul braccio scatenava contrazioni muscolari involontarie e dolorose. L'ingegnere tremava nel delirio più cupo. Emetteva suoni rauchi che perforavano il divisorio blindato del furgone. Lottava contro il collasso biologico finale.
«Quaranta chilometri allo svincolo campano,» gracchiò improvvisamente la ricetrasmittente analogica. Carlo parlava su una frequenza protetta. «Il sistema vi incalza. Posto di blocco pesante a tre chilometri. Fanteria e controlli chimici avanzati.»
Laura premette con forza il pedale del freno, rallentando la corsa.
«Non possiamo permetterci di sfondare le barriere,» rispose lei tra i denti. «Il carico posteriore non reggerebbe l'impatto frontale.»
«Ho inserito una priorità medica di livello quattro nel server di zona,» riferì Carlo con calma. «Risultate come un trasporto ufficiale di rifiuti radio-biologici ad alto rischio. Accetta il controllo. Devono solo validare la tua matricola digitale.»
Il posto di blocco apparve improvvisamente sotto l'ombra di un cavalcavia in cemento. Quattro blindati lealisti ostruivano completamente la carreggiata. C'erano filo spinato, coni luminosi e barriere elettrificate. Quindici soldati veterani di ABITES presidiavano l'area. Indossavano kevlar scuro e visori tattici integrati nel casco. Tenevano i fucili d'assalto pronti all'impiego. Due droni rotativi volteggiavano bassi sopra le loro teste, emettendo un ronzio predatorio.
Laura decelerò lentamente fino a fermarsi. Seguì il raggio laser di puntamento di un soldato e arrestò il grosso veicolo. Spense i fari. Un ufficiale avanzò con il fucile spianato lungo il fianco. Colpì il vetro sporco del finestrino con le nocche guantate. Laura abbassò il cristallo a manovella. Il gelo umido e l'odore della pioggia invasero immediatamente l'abitacolo.
«Codice matricola e identificativo del carico speciale,» impose il militare con voce piatta. La luce della sua torcia cercava aggressivamente le pupille di Laura. L'ufficiale scrutava il suo volto sporco di fango e stanchezza.
La donna presentò il palmo verso lo scanner portatile dell'uomo.
«Matricola Beta-Otto-Quattro,» disse lei senza battere ciglio. «Trasporto radio-biologico urgente da Lamezia Terme. Nessun imprevisto registrato.»
Il sensore emise una luce verde rassicurante. L'inganno informatico di Carlo reggeva ancora. Il soldato, però, non si allontanò istantaneamente. Puntò la torcia verso il divisorio blindato alle spalle della donna.
«Perché state usando l'arteria civile per questo carico?» chiese improvvisamente l'ufficiale. «C'è l'emergenza nazionale di Fase Quattro attiva.»
Laura mantenne una calma sovrumana, nonostante il battito accelerato.
«Obbedisco solo alle tempistiche dettate dalla corporazione,» rispose lei con freddezza. «I reattori di stoccaggio scadranno tra novanta minuti esatti. La contaminazione ambientale scatterà se non arrivo subito al punto di scarico. Chieda pure reclamo alla logistica centrale se ha dubbi.»
Il militare strinse la mandibola, incerto. Annusò con sospetto l'aria dell'abitacolo. Voleva aprire il portellone posteriore per un'ispezione visiva. Fece un passo deciso verso il retro del furgone. Laura sfiorò la pistola celata sotto la coscia destra. Era pronta a ucciderlo istantaneamente se avesse osato toccare Claudio.
Un cicalino acuto interruppe l'ufficiale a metà del passo. Lo scanner sul braccio emise un ticchettio rapido. Una notifica rossa di massima allerta apparve sul display del soldato. Era una priorità biologica assoluta. Il sistema vietava categoricamente il fermo prolungato. L'uomo guardò il dispositivo con rabbia impotente. Si voltò verso i compagni del posto di blocco.
«Libero transito immediato!» urlò sotto la pioggia. «Sganciate le barriere mobili!»
Le recinzioni si aprirono con un clangore metallico. Laura ingranò la marcia con decisione. Il vecchio motore emise un rombo incerto ma potente. Il furgone scivolò via nella burrasca campana. Erano passati oltre le linee nemiche, ancora una volta.`;
