export const chapter38Content = `Prima dell'Assalto, il mondo sembrava trattenere il respiro. Claudio e Laura erano acquattati nell'ombra di un vecchio furgone per le consegne, a pochi metri dal perimetro di sicurezza della Torre. Le luci bianche e violente dei riflettori spazzavano la strada con una regolarità irritante, creando ombre lunghe e nere che si muovevano come fantasmi sul cemento bagnato.
Claudio sentiva il battito regolare del suo cuore martellare contro i tappi nelle orecchie che usava per proteggersi dal rumore bianco emesso dai droni. Il sudore gli colava lungo le tempie, nonostante l'aria fosse gelida e cariche di umidità. Stringeva forte il calcio del suo fucile improvvisato, sentendo il metallo freddo rassicurarlo.
Laura era immobile al suo fianco, una statua di carne e determinazione. I suoi occhi seguivano ogni mossa delle guardie della Vanguard, il corpo d'élite di Julian Vane. Erano uomini scelti, armati con le migliori tecnologie di ABITES, i loro movimenti coordinati da un segnale neurale diretto. Non erano solo soldati, erano estensioni della macchina.
Improvvisamente, un boato scosse la città. Iniziarono le esplosioni ai varchi principali, il segnale che le squadre di distrazione dei Disconnessi avevano iniziato l'attacco. Le sirene iniziarono a urlare, un suono straziante che lacerò il vuoto della notte. I droni si staccarono dai loro supporti, sciami di insetti neri che sfrecciarono verso la battaglia.
"Ora," sussurrò Laura.
Scattarono fuori dall'ombra del furgone. Claudio sentì il dolore alle costole morderlo con ferocia, ma continuò a correre. Il fumo delle prime esplosioni iniziò a invadere la strada, creando una coltre protettiva che li nascondeva alla vista dei sensori rimasti.
Atraversarono la prima barriera di filo spinato. Il metallo graffiò la giacca di Claudio, ma lui non rallentò. Vedeva la porta di accesso del personale di servizio, una piccola apertura di cemento grigio che sembrava un ingresso per l'inferno. Una guardia della Vanguard cercò di sbarrargli la strada, sollevando la sua arma laser.
Laura fu più veloce. Un colpo secco e la guardia cadde a terra senza emettere un suono. Claudio passò sopra il corpo dell'uomo, sentendo il calore che ancora emanava dalla sua armatura. Non c'era tempo per i rimpianti. Solo per avanzare.
Raggiunsero la porta e Claudio inserì il codice di sblocco che Kael gli aveva fornito. I secondi sembrarono ore mentre il processore cercava di bypassare la sicurezza di ABITES. Dietro di loro, il rumore della battaglia si faceva più forte, urla di uomini che combattevano contro il metallo freddo.
La porta si aprì con un sibilo pneumatico. L'aria che uscì dall'interno era fredda e sapeva di ozono e prodotti chimici. Entrarono nel ventre della Torre, chiudendo la porta alle loro spalle. Il rumore dei motori e delle sirene divenne un rombo sordo, ovattato dal cemento rinforzato.
Claudio si appoggiò al muro, ansimando. Le sue nocche erano bianche per lo sforzo. Guardò Laura e vide che era ferita lievemente a una spalla, una scia di sangue scuro che macchiava la sua divisa. Si sorrisero per un istante, un legame di sangue e speranza che nessuna macchina avrebbe mai potuto spezzare.
L'assalto era iniziato. Non c'era più modo di tornare indietro. Iniziavano la scalata verso il cuore di ABITES, portando con sé la speranza di un mondo intero che voleva solo tornare a respirare liberamente.`;
