export const chapter9Content = `L'odore di polvere e di ferro vecchio colpì i fuggiaschi tra i mattoni bagnati del tunnel. Aris camminava davanti a tutti stringendo il computer al petto. Laura chiudeva la fila e si muoveva piano con il fucile tra le mani. La stanza dove dovevano arrivare era un buco nel buio, dietro una grata arrugginita che si aprì con un rumore di metallo. I computer di ABITES occupavano tutte le pareti, erano armadi d'acciaio pieni di cavi neri che sembravano serpenti.
Le macchine facevano un caldo terribile che colpì Claudio in faccia. Lui appoggiò la sua borsa su una vecchia cassa di plastica rovinata. Aris disse che avevano pochissimo tempo. Claudio appoggiò le dita sui tasti gelati anche se sentiva un dolore che gli risaliva lungo le braccia. Laura si mise davanti alla porta con la schiena contro il muro, puntando il fucile nel buio del corridoio.
Claudio cercò un buco nel sistema e dopo un po' trovò un ordine che la macchina aveva dimenticato. Iniziò a scrivere codici velocemente e ogni comando era una fatica vera che gli faceva sudare la nuca. I file segreti iniziarono a scorrere sullo schermo e apparvero i piani di Julian Vane. Intanto i computer ronzavano forte e buttavano fuori aria bollente.
ABITES stava mettendo dei chip nel cervello dei bambini appena nati a Bologna e Milano. Dicevano che servivano per la salute, ma in realtà erano delle catene invisibili per non farli ribellare mai. Il sistema voleva persone che ubbidissero senza mai dire nulla. Claudio sentì un peso enorme sul petto e gli tremavano le mani per la rabbia. Vane voleva uccidere l'anima stessa dell'umanità.
Claudio ordinò di mandare tutto ai suoi contatti e Aris aprì il collegamento segreto. La spedizione finì in pochi minuti e sullo schermo apparve un segnale verde che confermava tutto. Laura scattò subito in piedi e preparò il fucile per uscire dai tunnel. Quando uscirono all'aperto, la luce dell'alba li colpì forte. Claudio tossì per l'aria fredda di Roma e guardò i tetti grigi sotto un cielo di piombo.
Sara guardava gli schermi nel suo nascondiglio a Trastevere, tra i circuiti caldi e la polvere. Intanto la pioggia d'inverno sbatteva contro i vetri delle finestre. Doveva distrarre il sistema mandando un sacco di dati inutili per proteggere i suoi amici nel sottosuolo. Le sue mani si muovevano veloci sulla tastiera. Trovava la forza pensando a quando Claudio l'aveva abbracciata prima di partire.
Lui l'aveva stretta forte per le spalle e lei aveva sentito il calore di un uomo vero contro il freddo dei computer. Non si erano detti nulla perché in quell'abbraccio c'era già tutto il coraggio che serviva. Quel ricordo le scaldava le mani mentre mandava l'ultimo attacco al sistema. Sapeva che ABITES non poteva capire cosa fosse l'amore. Sara strinse i denti e lanciò il segnale per proteggere l'uomo che amava, mentre lui strisciava nel buio per salvare tutti.

          · · ·          

L'alba a Testaccio arrivò grigia e gelata. Il freddo che usciva dalle fogne faceva male alle ossa di Claudio, che stringeva i denti per non tremare vistosamente. Si buttarono in mezzo alla gente del mercato che camminava a testa bassa tra i banchi. Dalle bocche uscivano nuvole di vapore e tutti avevano i colletti alzati per proteggersi dal vento. Sopra i tetti si sentiva il ronzio continuo dei droni di ABITES, un rumore fastidioso che non smetteva mai. La folla faceva finta di non vederli per paura, e Claudio e Laura si mimetizzarono tra le giacche bagnate e i cappotti pesanti. Aris camminava un passo dietro di loro, nascondendo il computer sotto una vecchia giacca militare troppo grande.
Stare in mezzo alla gente era l'unico modo per non farsi notare. Laura gli camminava vicino e ogni tanto le loro mani si sfioravano. Per Claudio quel contatto era una carica di energia, qualcosa che lo teneva in piedi. La ferita al fianco sinistro continuava a dargli fitte e sentiva i vestiti bagnati di sangue. Cercò di non pensarci e continuò a camminare, seguendo la schiena di un vecchio che spingeva un carrello della spesa.
Il posto dove dovevano andare era dietro un cancello di ferro pieno di ruggine e fango. Il vicolo era stretto e per terra c'era un'umidità che entrava nelle scarpe. Aris bussò con un ritmo preciso: tre colpi veloci e poi altri due. Marta aprì subito la porta e li tirò dentro quasi con la forza.
Dentro la stanza c'era odore di candele e di minestra scaldata. C'erano dodici candele accese sopra un vecchio mobile e la luce faceva ballare le ombre sulle facce di sette persone sedute lì intorno. Erano uomini e donne con le mani rovinate dal duro lavoro. Nessuno diceva una parola. Uno di loro teneva in mano un foglietto sgualcito e pregava in silenzio. In quel posto si respirava un'aria di attesa, stavano tutti aspettando un segnale.
Marta prese Claudio per un braccio e lo portò vicino alla luce di una candela. Gli alzò la giacca e vide che la ferita era brutta, lunga dieci centimetri e tutta arrossata. Marta scosse la testa e prese una scatola di metallo da sotto il tavolo.
«Stai fermo,» disse con un tono che non ammetteva repliche.
Quando la garza bagnata toccò la pelle, Claudio ebbe un sussulto. «Respira con il naso,» gli disse Marta senza guardarlo in faccia mentre premeva il panno sulla ferita. «Non pensare al dolore, lascialo fuori.»
L'alcol bruciò come il fuoco e Claudio strinse i pugni così forte da farsi uscire il sangue dai palmi. Marta lo fasciò velocemente e strinse le bende cosi forte che erano una corazza. Poi lo guardò dritto negli occhi. I suoi occhi erano chiari e decisi.
«La luce non arriva da sola, ragazzo mio,» disse posandogli una mano sulla spalla. «Dobbiamo essere noi ad accenderla con le nostre dita.»
Claudio annuì, sentendo il peso di quello che dovevano fare. Marta cambiò discorso e tirò fuori una mappa sporca. Iniziò a parlare di Bologna e di come i soldati avessero bloccato le strade principali. Disse che c'erano sempre più pattuglie in montagna e che di notte passavano treni carichi di computer segreti. Laura ascoltava tutto stando in piedi vicino alla porta, con il fucile nascosto sotto uno scialle di lana. Non si perdeva una parola e continuava a guardare fuori dalla fessura della porta per controllare la strada.
Aris accese una vecchia radio di legno tutta impolverata. Girò la manopola e si sentì un forte fruscio, finché non arrivò una voce. Era un uomo francese che parlava con il fiato corto, era disperato. Aris alzò una mano e tutti nella stanza smisero di respirare per ascoltare. La guerra stava arrivando anche a Roma.

***

Dubois strisciava per terra con la manica della divisa sporca di sangue nero. Si trovava in una scuola elementare di Lione che puzzava di fumo e polvere. I ribelli avevano usato gli armadi e le scrivanie per tappare le finestre. ABITES aveva circondato l'edificio e si sentiva il rumore dei cingoli dei carri armati che facevano tremare il pavimento.
Un piccolo drone aveva colpito l'ala destra della scuola e il soffitto stava bruciando. Dubois non si curò delle fiamme e prese la radio con la mano sporca di terra. «Settore tre, rispondete.»
Dalla radio uscì una voce tra i fruscii: «Hanno preso il ponte, sono troppi per noi.»
«Andate verso il parco, usate la strada secondaria!» urlò Dubois stringendo i denti.
«Il parco è tutto aperto, ci spareranno come ai piccioni!»
«Anche restare sul ponte è morte sicura!» rispose Dubois sputando sangue nel fango. «Muovetevi o morirete tutti lì.»
Mise giù la radio e sentì la testa che gli scoppiava dal male. Si mise in ginocchio e strisciò lungo il corridoio pieno di buchi, mentre nel cortile i droni d'assalto stavano fermi a guardare. Erano freddi e precisi, pronti a sparare al primo che si muoveva. Dubois caricò il fucile e rimase nascosto mentre i carri armati si avvicavano sempre di più. Mancavano solo cinquanta metri. Il tempo stava per finire.

***

Aris spense la radio e nella stanza tornò il silenzio più assoluto. Marta rimase ferma vicino al mobile e Laura abbassò la testa. Claudio guardava il pavimento di mattoni e sentiva il cuore che gli batteva fin nelle orecchie. Uscirono da quel posto con un obiettivo chiaro in testa e poco altro.
Il freddo del vicolo fuori gli colpì la faccia e gli gelò il sudore sulla fronte. Per terra c'era l'umidità e Claudio sentiva i polmoni pesanti per la stanchezza. Aris si fermò all'angolo della strada e guardò verso i binari. «Io vado per la ferrovia. Ci vediamo al punto stabilito.» E in un attimo sparì tra le ombre dei treni.
Claudio e Laura rimasero soli nel vicolo buio. La tensione calò e Claudio sentì le gambe che gli tremavano mentre le mani non riuscivano a stare ferme. La ferita gli bruciava sotto i vestiti. Laura gli andò vicino e controllò un'ultima volta che la strada fosse vuota. Poi si girò e lo guardò.
Si baciarono con una forza disperata. Fu un momento in cui sentirono solo il calore l'uno dell'altra contro il freddo di quel mondo a pezzi. Fu un atto di ribellione, l'unico modo che avevano per sentirsi vivi. Le labbra di Laura erano gelate, ma dentro era un incendio di vita. Claudio la strinse per il colletto della giacca e la tenne forte a sé, sentendo il cuore di lei che batteva contro il suo petto. Quel battito era l'unica cosa vera in un mondo controllato dai computer. Era un calore onesto che l'inverno di ABITES non poteva toccare.
Si staccarono all'improvviso, con il vapore dei respiri che si mescolava nell'aria gelata. Laura riprese fiato e guardò lontano. «Dobbiamo andare a Bologna.»
Claudio annuì e sentì un calore nuovo risalirgli lungo la schiena. Iniziarono a correre verso la stazione mentre il cielo sopra Roma iniziava a farsi giallo.

          · · ·          

La pioggia non cadeva, graffiava letteralmente la pelle. Cadeva di traverso, spinta da un vento che soffiava fortissimo tra le rotaie. Claudio sentiva l'acqua gelata sulla faccia, erano frammenti di vetro. Si trovavano nello scalo ferroviario di Roma Nord, un labirinto di binari e cemento nel buio. Grossi container erano allineati come le mura di una città morta. I piedi gli scivolavano sui sassi bagnati del binario. Claudio teneva la testa bassa e seguiva Aris, che si muoveva veloce tra le casse di metallo nonostante la sua stazza.
Laura chiudeva la fila. Claudio sentiva il suo respiro regolare subito dietro di lui e il rumore leggero del suo fucile. Il treno merci era fermo sul binario quattro e tremava leggermente. Una vibrazione bassa saliva dalle rotaie, passava attraverso le scarpe e arrivava fino alle gambe. Era il respiro di una bestia. I lunghi vagoni neri si perdevano nel buio, senza nessuna luce accesa e senza nessuno a bordo. Era ABITES a guidare quel gigante di ferro usando solo i suoi programmi.
«Il terzo vagone dalla fine,» disse Aris piano. «Ha una serratura di una volta, meccanica. Non è collegata al computer.» Aris queste cose le sapeva bene, faceva parte del suo vecchio mestiere di macchinista. Camminarono rasente al treno, con la pioggia che batteva forte contro la lamiera. Il vagone che cercavano aveva una catena arrugginita con un grosso lucchetto. Aris tirò fuori i suoi attrezzi e in meno di un minuto riuscì a far saltare la chiusura. La catena cadde tra i sassi.
Proprio in quel momento il treno iniziò a muoversi. Non ci fu uno strattone, ma una spinta lenta che diventava sempre più forte. I vagoni iniziarono a scricchiolare uno dopo l'altro. Il portellone di ferro iniziò a scorrere via veloce. «Adesso! Saltate su!» gridò Aris.
Laura saltò per prima. Afferrò la maniglia gelata, saltò sulla scaletta e si tirò su con forza, sparendo nel buio del vagone. Poi tese la mano verso il basso. Il treno correva sempre più forte. Claudio correva tra i sassi bagnati, cercando di non cadere. La maniglia di metallo era un pezzo di ghiaccio. Claudio la afferrò, sentendo le dita scivolare. Strinse la presa con tutte le sue forze, ignorando il dolore ai polsi. Il bordo della porta gli tagliò la mano, anche se aveva i guanti, ma non la mollò. Il treno continuava a prendere velocità.
Claudio fece uno sforzo enorme e riuscì a tirarsi su. Sbatté la gamba contro il bordo di metallo e le costole gli fecero male contro lo spigolo della porta. Laura lo prese per le braccia e lo tirò dentro. Claudio rotolò sul pavimento del vagone, picchiando forte il ginocchio. Sentì una fiammata di dolore alla rotula, una fitta che gli salì fino all'anca. Rimase fermo a terra per qualche secondo, cercando di riprendere fiato.
Aris saltò dentro un attimo dopo, senza nemmeno sembrare stanco. Il portellone si chiuse e tutto diventò nero. Non si vedeva più nulla, nemmeno i binari o la pioggia. Claudio rimase accovacciato, aspettando che gli occhi si abituassero al buio. Il rumore della pioggia sul tetto di latta era assordante, qualcuno prendeva il vagone a martellate. Il treno correva verso nord, verso l'Emilia, con un ritmo ipnotico. Nessuno disse nulla per qualche istante. Poi Claudio sentì qualcosa che strisciava sul pavimento, proprio davanti a lui. Non erano soli.

***

Si sentì il clic secco di una pistola caricata nel buio. Claudio rimase immobile a terra. Aris alzò le mani per far vedere che non volevano combattere. «Andatevene via,» disse una voce rauca dal buio. Era la voce di qualcuno che aveva preso molto freddo. «Non abbiamo armi puntate contro di voi,» rispose Claudio, cercando di stare calmo per non far degenerare la situazione.
Nessuno sparò. Il treno fece una curva e il vagone oscillò di lato. In quel momento, qualcuno accese una torcia. La luce gialla accecò Claudio per un momento, ma lui non distolse lo sguardo. Erano in sette. Quattro uomini, due donne e un ragazzino che non avrà avuto più di sedici anni. Erano tutti seduti su casse di legno e zaini vecchi. Un uomo robusto teneva in mano una vecchia pistola, appoggiata sul ginocchio ma pronta a colpire. Aveva le mani sporche di grasso, come quelle di chi lavora sulle strade.
Laura era lì accanto a Claudio, pronta a reagire se necessario. «Eravate ferrovieri?» chiese Aris guardando l'uomo con la pistola. «Eravamo,» rispose lui con un tono amaro. «Tutti noi siamo "ex" qualcosa ormai.»
L'uomo abbassò la pistola. Iniziò un momento di silenzio in cui si studiarono a vicenda. Una delle donne passò a Claudio una bottiglia d'acqua. Sapeva di cloro e di plastica, ma per Claudio fu come bere il miglior vino del mondo: l'acqua fresca gli diede subito sollievo alla gola secca. Il ragazzino smise di guardare il fucile di Laura. Aris si sedette contro la parete di metallo, cercando di stare comodo nonostante il rumore del treno.
Dario, l'uomo con la pistola, aveva lavorato sui treni per undici anni. ABITES lo aveva licenziato in un giorno, sostituendo tutti i macchinisti con dei computer. Niente più stipendio, niente più lavoro, solo la fame. «Questo treno lo conosco bene,» disse Dario a bassa voce, per paura che ci fossero dei microfoni nascosti. Appese la torcia a un gancio sul soffitto. La luce debole faceva vedere i loro visi stanchi e segnati dalla fatica. «L'ho guidato per mille giorni. Ora lo guida un chip freddo che non conosce nemmeno la stanchezza.»
Claudio ascoltava attentamente ogni parola. «Nel terzo vagone dopo la locomotiva,» continuò Dario ancora più piano, «stanno portando dei nuovi server segreti. Li ho visti mentre li caricavano a Roma: erano tutti coperti da teli pesanti e catrame. Quando piove, quel vagone fa un rumore diverso, più sordo, perché è pieno di macchinari pesanti. Stanno andando a Bologna per collegarli alla rete del Nord. Poi arriveranno in tutta Europa.»
Aris si fece attento. «Da quanto tempo fanno questi viaggi?» «Da almeno due mesi. Ogni settimana mandano via un vagone pieno.»
Claudio guardò Aris. Avevano capito: Julian Vane stava mandando i pezzi per controllare tutto il continente, nascondendoli in normali treni merci che nessuno controllava più. La dittatura di ABITES stava allargando i suoi tentacoli in tutta Europa, un binario alla volta.
Un altro uomo passò loro un pezzo di pane duro e un po' di formaggio avvolto in carta sporca. Claudio mangiò avidamente, sentendo le energie tornare. Laura divise il suo pezzo con il ragazzino che le stava seduto vicino. Il treno continuava la sua corsa nel buio, risalendo verso le montagne del nord. La pioggia continuava a martellare sul tetto di metallo.

***

Il computer di Sara diede un piccolo segnale alle tre e quattordici del mattino. Solo un puntino luminoso che apparve e scomparve sul monitor. Voleva dire che Claudio era riuscito a salire sul treno e a lasciare la città. Sara tirò un sospiro di sollievo, ma non staccò le mani dalla tastiera.
I droni della polizia stavano girando sopra il suo quartiere da venti minuti. Facevano dei cerchi stretti, cercando qualcuno. ABITES aveva sentito qualcosa che non andava e stava setacciando tutta la zona. Quando i droni passavano bassi sopra il magazzino dove si nascondeva Sara, le pareti tremavano e si sentiva un rumore insopportabile.
Lei però non si spaventò e continuò il suo lavoro. Doveva ingannare i computer di ABITES, portandoli a guardare da un'altra parte. Era un lavoro difficilissimo e pericoloso: doveva cambiare continuamente i codici e chiudere i buchi nel sistema in tempo reale per non farsi scoprire e per proteggere Claudio ancora per un'ora. Un drone passò proprio sopra di lei e la luce della stanza saltò per un attimo.
Sara chiuse gli occhi e strinse i denti. Pensò a Claudio. Al calore del suo corpo quando l'aveva abbracciata l'ultima volta. Si ricordò del suo petto forte e del battito del suo cuore contro la sua schiena. Non era stato un abbraccio per dire "andrà tutto bene", era stata la forza della carne e del sangue, il coraggio di due persone che si amano e decidono di combattere insieme. Quel ricordo le dava una forza pazzesca, le dava l'aria per continuare a lottare.
Riaprì gli occhi e tornò a guardare lo schermo. Continuò a lottare contro la macchina, chiudendo l'ultimo accesso ai dati e proteggendo i suoi amici. Il drone finalmente se ne andò verso altri tetti. Sara aveva vinto ancora una volta. Guardò i dati sullo schermo: il treno stava superando l'Arno e puntava verso le montagne. Lontano da quel posto umido e buio, tra le valli gelate dell'Appennino, tonnellate di ferro correvano a tutta velocità sui binari. Il treno correva verso il cuore del nord.
Claudio era lì sopra, vivo e pronto all'azione. E Sara era lì, davanti al suo computer, pronta a coprirgli le spalle fino alla fine.`;
