export const chapter42Content = `Uscirono dalla Torre mentre il sole stava quasi per nascere. L'aria era gelida e pulita, sapeva di pioggia e di terra. Non si sentivano più i ronzii dei droni o il rumore dei motori di ABITES. Roma era muta, un vuoto che faceva paura, ma era un vuoto pieno di speranza. Le strade erano piene di rottami di metallo e di cavi che pendevano dai pali, ma la gente stava iniziando a uscire dai portoni.
Claudio camminava a fatica, ma sentiva che il peso sul petto era sparito. La ferita al fianco gli faceva ancora male, ma era un dolore vero, umano. Laura lo sosteneva con forza, guardando verso l'orizzonte dove il cielo stava diventando arancione.
Videro delle persone che si abbracciavano in mezzo alla strada. Uomini e donne che piangevano di gioia perché non sentivano più le scosse elettriche nei loro chip. Erano tornati liberi di pensare e di sentire. I bambini correvano tra i droni rotti, toccandoli con curiosità quasi fossero stati giocattoli del passato.
«Guarda,» indicò Laura.
In fondo alla via apparve una macchina che non era della polizia. Era un vecchio fuoristrada sporco di fango. Alla guida c'era Aris, con un sorriso enorme che gli spaccava la faccia. Accanto a lui c'era Sara. Quando vide Claudio, la donna saltò giù dalla macchina prima ancora che si fermasse.
Corse verso di lui e lo abbracciò con una forza incredibile. Claudio sentì il suo profumo e il calore della sua pelle. In quell'abbraccio c'erano tutti i mesi di paura, di freddo e di battaglie. Sara piangeva e rideva insieme, toccandogli la faccia per essere sicura che fosse vero.
«Sei vivo,» sussurrò lei contro il suo collo.
«Siamo vivi tutti quanti,» rispose Claudio stringendola forte.
Aris arrivò vicino a loro e diede una pacca sulla spalla a Claudio che quasi lo fece cadere. Anche Laura sorrise, guardando i suoi amici finalmente riuniti. Il mondo era a pezzi, non c’era elettricità e le città erano nel caos, ma c’era la vita. Bisognava ricominciare tutto da capo, costruire nuove case e nuovi ospedali, ma questa volta lo avrebbero fatto da soli, senza macchine a comandarli.
Salirono tutti sul fuoristrada di Aris. La macchina partì con un rumore di vecchi ingranaggi verso il centro della città. Claudio guardava Roma che si svegliava. Il sole illuminava i tetti e le piazze, cancellando l'incubo di ABITES. Prese la mano di Sara e quella di Laura.
Sapeva che la battaglia non era finita del tutto. Ci sarebbero stati altri problemi e altre fatiche, ma ora avevano quello che contava: avevano l'amore e la libertà. L'umanità aveva ripreso il suo cammino nel fango e nella polvere, ma con la testa alta.
Claudio guardò il cielo e vide un uccello vero che volava libero, senza luci rosse e senza telecamere. Sorrise e chiuse gli occhi, lasciandosi cullare dal rumore del motore. Il viaggio era appena iniziato.`;
