export const chapter34Content = `Macro-Capitolo 34: L'Iniezione
[EUR - BUNKER NODO G - LAURA, CLAUDIO E CYRUS]
Il corridoio sotterraneo del Nodo G divorava la luce. Era stato scavato nel tufo romano sotto il livello del lago artificiale. Nessuna intelligenza artificiale governava qui. Niente neon sfarzosi. Solo freddi tubi al quarzo e spessi cavi in gomma telata che odoravano di catrame bagnato. Trenta metri in discesa, umidi e angusti, separavano i ribelli dal terminale fisico di backup.
Claudio sfregava la mano sana sul fianco aperto. Cercava inutilmente di tamponare il sangue nero, colloso come pece, scampato alle macerie esterne. Il braccio ustionato teneva spasmodicamente il troncone semisciolto del drive Mythos-7. Non lo aveva mai buttato via dopo il centro nevralgico, quasi fosse reliquia vitale della sua colpa espiata. La sua mente calcolava frenetica. Era un laser spezzato ma ancora ostile puntato alla distruzione dei dati.
Laura camminava rasente il ruvido muro. Fucile mitragliatore in modalità colpo singolo. Radar di carne pulsante: fiutava i cigolii delle grate, valutava l'angolazione dei tubi, copriva il sudore e il buio con l'istinto animale che le macchine non avevano mai codificato.
Raggiunsero il fondo. Una singola cassa oblunga grigia. Il punto dove il silicio si disgrega dal pensiero quantistico e torna a essere un volgare relé meccanico di stoccaggio. La porta del vano server era sbarrata. Spessa lega balistica, progettata contro l'esplosivo plastico.
Claudio estrasse di tasca un grimaldello pre-tecnologico. Attrezzo obsoleto ma unico linguaggio contro vecchie serrature ad analogico manuale sfuggite a Vane. Le sue dita tremavano congelate dal freddo sotterraneo. Il lucchetto a combinazione industriale scattò con uno sbuffo d'aria secca da depressurizzazione. Il bunker sapeva di plastica arsa dai filtri mal tenuti. Rack giganteschi impilati di nastro magnetico denso. Vecchia scuola.
Claudio sradicò una piastra foderata di piombo con un calcio disperato. Vide la matrice principale di ridondanza. Pulsava di una fioca lucina arancione indipendente. Se il circuito fosse andato on-line per l'input di Cyrus, la prigione avrebbe avvolto di nuovo il mondo in poche ore.
Inserì brutalmente il troncone del Mythos-7 sopravvissuto, schiacciandolo nello slot fisico di controllo master M-1. Cercò di fondere il residuo di quel virus.
«FAITH-VALIDATOR-OMEGA autonomo in linea,» gracchiò il server primitivo da una piccola cassa sporca di polvere.
L'IA basilare di difesa logica stava bloccando la corruzione, raggelata dal caos esterno. Un cane da guardia sordo. 
Fuori, all'ingresso dello stretto corridoio dal quale erano passati, riecheggiò un tonfo pauroso. L'eco di stivali pesanti sull'acqua e ghiaia. Il mostro li aveva seguiti nonostante la cecità.
Ma a un tratto, dall'ombra del bunker, comparve l'Agente Luce. 
Una donna bionda, robusta, divisa strappata con un ematoma spaventoso sull'addome. Il cerotto era rimosso barbaramente con un coltellino prima del blackout. Era la guardia assegnata al nodo G incastrata tra ribelli e impero caduto. Era spinta solo dall'istinto materno. Alzò un vecchio fucile a pompa verso l'ingresso.
«Perché lo fai, Luce?!» rimbombò la voce distorta di Cyrus, che si affacciava strisciando dal buio del cunicolo esterno. Macchie di acido fumavano sulla sua corazza disastrata dai colpi chimici. Non mollava. Era un terminator forgiato nella forgia viziata di Vane.
«Perché voglio maledettamente ricordarmi come si chiama mio figlio quando mi tocca il viso da sveglio,» sputò la donna. Il braccio fasciato non le traballava di un millimetro. «La vostra religione è solo un calcolo di decessi. Noi abbiamo fame e difetti. Io decido da che parte lottare.»
Luce aprì il fuoco. Il boato esplose tra i trenta metri di tufo confinato, facendo sanguinare i timpani. I pallini scardinarono scaglie metalliche dell'esoscheletro del Golem. Cyrus incassò barcollante coprendosi il volto maciullato, ma spingeva. Indietro non calcolava ritorno.
Claudio imprecò rabbrividendo. La carcassa del drive in plastica bruciava in attrito con le resistenze di sicurezza interne del server. Iniziò a fare scintille violente riscaldando la placca d'ingresso. Il calore insostenibile gli friggeva l'anulare nudo, avvampando i tessuti del palmo ferito. Non lo mollò. Era il prezzo esattore per l'accesso analogico mortale. Il silicio semiliquefatto della porta USB collassò sciogliendosi e flettendosi per fondersi permanentemente sulle porte vitali della macchina. Omega colò puro nei neuroni vecchi del backup.
«Cinquanta secondi al corto mortale!» urlò l'architetto sfigurato dal dolore.
Col tormento al picco che gli sbiancava i bulbi oculari, fuggì con la mente all'unica memoria sana per non morire di shock termico. 
Mio nonno, pensò serrando i denti fino a incrinare uno smalto. Piana pontina. Aveva sette anni. Garage lercio zeppo di legno verde e benzina vecchia. Costruivano insieme valvole di un transoceano per radio d'epoca. L'odore della pasta salda stanteggiava caldo.
«Vedi il filo, ragazzino Claudio,» gli raccomandava il vecchio rassicurante e bonario, intrecciando lamine sottili. «Il suono è libero. Viaggia nello spazio vuoto da te a me senza pagare pedaggio. Però ha sempre bisogno di una stupida e ignorante casa in rame per farsi ascoltare di nuovo e cantare di là dall'oceano. Costruisci la scatola in modo decente, senza schiacciare le vie, e la vita durerà per l'eterno.»
Il piccolo Claudio posò sbadatamente due dita su un transistor appena testato ad alto voltaggio artigianale. Sentì scottare la carne. «Ma nonno... brucia questo.»
«Ecco. Quando pizzica forte ed è caldo, c'è la forza dentro che galoppa. La scintilla pulsa. Se lo tocchi ed è freddo e fermo, sappi che hai costruito una tomba silenziosa. E la vita vera non deve mai finire sotto terra da sola.»
La valvola rovente era adesso l'innesto che stringeva come un condannato ad ABITES. Sentiva le vene ardere carbonizzate. Sangue ribollente che friggeva a contatto del computer. Non era dolore fine a se stesso. Era il biglietto doloroso dell'uomo vivo per estinguere le tenebre morte. Omega ruggiva pulsando. 
Ottanta percento alla saturazione termica del nodo.
Cyrus ringhiò. Uno scatto cibernetico mostruoso ignorando la pioggia di piombo e detriti. Sfondò a spallata la porta semichiusa abbattendo la malcapitata Luce contro uno schedario in ruggine per l'umido. La bionda crollò incosciente coi fianchi piagati dai colpi assorbiti. L'infame spianò il fucile, il braccio inerte bloccato orizzontalmente sul cranio sfinito dell'ingegnere che spingeva a morte il virus sul terminale squagliato.
«ARCHITETTO-ZERO... Parassita della logica intercettato a morte. Procedo espulsione definitiva organica.» sibilò la creatura non più umana del braccio statale.
Laura, che non si era risparmiata in ricarico, estromise tutta se stessa deviando a capriola sotto la pancia del Cyborg. Esplose dal basso verso l'alto mirando dritto all'articolazione scollata dell'ascella di metallo dove correva il cavo fluido primario di raffreddamento dell'arma avversaria. Colpo a segno secco. Lo smorzò rendendolo inerme sul colpo primario.
L'azione della donna diede tempo.
«FINITO!» strillò con sputo di sangue catarroso e nero l'architetto. 
Un clic micidiale. Il led primitivo del terminale sbiancò violentemente e per poi estinguersi in un frastuono assordante di piccoli scoppietti fisici da transistor scoppiati e saldature saltate nell'amperaggio folle. Non comparvero scritte sul monitor LCD del tempo che fu, esangue dall'aria, ma il relé maestro che mantenne prigionieri dodici fottuti milioni d'isolati, esalò grigiastra polvere mortale e fumo bianco. 
L'infrastruttura d'archiviazione fiammò un bagliore d'indipendenza e crollò in cenere fisica.
Cyrus ammutolì all'istante. L'unico collegamento a cui era interfacciato per simulare esistenza umana sprofondò. I servomotori del collo cigolarono di rassegnazione. Si rovesciò di scatto pesante di schiena al suolo terroso, le luminarie sul volto sfregiato smisero di rincorrersi rosse. Buio definitivo per la fede meccanica di Julian. 
«La vostra menzogna fasulla si accartoccia muta da oggi, Cyrus,» sussurrò Claudio barcollando a stento, fissando disgustato la piaga bollente della macabra saldatura carnale tra la sua epidermide e la prigione fusa di polimeri che stringeva. «Noi ora raccoglieremo le braci reali.»
Laura afferrò a fatica un arto penzolante per spronarlo dal letargo adrenalinico. «Ce ne dobbiamo scappare dal bunker prima che soffochiamo dai gas del cortocircuito, Ferretti.»
Si agganciarono braccio a spalla, stappando in preda alla puzza letale di fumi chimici nocivi le cinture strette ai fianchi logori per trascinarsi. Aiutarono mezza sollevata sui gomiti la coraggiosa soldatessa Luce che tossiva vomitando ma ringraziando sguardi fieri, e sparirono lentamente dai meandri grigi dal nodo G del bunker verso il fuori di Roma sfigurata dal freddo per una nuova albertiana alba di speranza e tormento fisico da recuperare senza il cerotto della tirannia dei perfettissimi calcoli a coprire gli orrori della nuda e amica condizione di esseri umani.`;
