export const chapter36Content = `Macro-Capitolo 36: Caduta Libera
[ROMA - STRADE DELL'EUR - LAURA E CLAUDIO]
Il vento notturno aveva denti di ghiaccio puro. Claudio respirava a fatica, la cassa toracica raschiava contro se stessa a ogni minimo input muscolare. La camicia sartoriale era irriconoscibile, fradicia e saldata al fianco squarciato da un colla scura di sangue raggrumato in enormi grumi. Era un calore umido malato quello sulla pelle, una coperta febbrile che lo costringeva a restare vigile, mentre il freddo sferzante della tempesta cercava in modo suadente di addormentare i suoi neuroni stanchi. 
L'ingegnere fece leva con un piede sopra la massiccia scocca a ventola di un vecchio condizionatore industriale esterno al perimetro di base. Le braccia gli tremavano, sfinite dai violenti rigetti adrenalinici del bunker sotterraneo. Il tallone slittava rovinosamente sulle grate bagnate cariche di alghe umide cresciute nel disinteresse dei droidi pulitori.
Laura stazionava in bilico estremo al bordo della sporgenza terrazzata di mattoni crudi. La scala antincendio percorsa era un infernale traliccio arrugginito, lasciato a marcire decenni indietro dalla manutenzione automatizzata. I bulloni ardevano di ruggine granulosa mangiata dalla pioggia inquinata di Roma Sud. Sotto la suola in gomma delle loro scarpe l'incrocio stradale principale era un abisso d'acqua nera impenetrabile. La mercenaria si voltò lentamente. Nel buio pesto senza neon, i suoi occhi cercarono quelli di Claudio. Non si dissero nulla. Le labbra erano spaccate dal gelo. La sua spalla dura da combattente premeva contro il costato fragile del giovane scienziato, quasi a trasferirgli il calore d'attrito. Erano un unico blocco informe di pioggia, ossa e misera volontà sopravvissuta.
La discesa dal cornicione dell'hangar fu un purgatorio ruvido di ferro vivo. Ogni sobbalzo tra i gradini allentati era una scossa a tremila volt ai nervi del fianco squarciato. Il campo visivo di Claudio pulsava ai margini annebbiandosi di macchie rosso rame. La ringhiera scheggiata gli bruciava la mano sana, tagliando il palmo molle in più punti e mischiando ruggine e sangue. 
Atterrarono a peso morto sull'asfalto romano colmo della tempesta. Roma si accartocciava in una morte a scaglioni. 
«NIGHT-WATCHMAN-ZERO autorizzato su stringa locale,» gracchiò un altoparlante spaccato, mezzo penzoloni da un lampione all'angolo. 
Era un relé secondario, un balbuziente ramo morto dell'IA immensa che da anni gestiva maniacalmente la rassicurante illuminazione anti-sommossa. La batteria a litio sotterranea si era attivata fuori dal controllo madre. E commise un errore ingegneristico di amperaggio pauroso. 
Per tre secondi esatti, una porzione enorme di strada larga cinquanta metri fu lavata e inondata da una scarica di abbacinante luce alogena arancione, cruda e violenta da sfasciare le retine. I corpi dei cittadini, stravolti, fuggivano rannicchiati coprendosi la faccia abituata ai rassicuranti pannelli soft dei cerotti. Poi un suono di fulmine al chiuso sovrastò la pioggia. Una tremenda contro-scarica magnetica non calcolata risalì a fiamma i cavi interrati d'emergenza. Le plafoniere blindate in plexiglas dei fari esplosero per i gas interni. Tutte, simultaneamente. Il vetro polimerico infuocato sbatté a terra sull'asfalto allagato come un'immonda pioggia di dardi gelati, sibilando evaporazione e puzza di filamenti cotti. 
Il buio tornò predatore. Cieco. Definitivo. 
E dall'ombra del largo sbarramento urbano, Claudio scorse la reazione della gente per strada. Un caos silenzioso orripilante. Le auto a guida autonoma di Generazione Nove erano sparpagliate e incrociate male ai bivi, giganti massicci di metallo pesante ora spogliati di intelligenza direzionale, piantati e morti, i cui motori elettrici tacevano in eterno malfunzionamento a batteria piana. Uomini e donne in completi grigi e uniformi grigio perla annaspavano inciampando sulle aiuole fangose spartitraffico come sonnambuli colti da paralisi cerebrale. 
Molti cadevano faccia all'ingiù sull'asfalto sbiancando, piangendo copiosamente senza nemmeno rendersene conto, incapaci fisicamente di comandare allo stimolo ghiandolare orfano della regolarità del cerotto disconnesso. Alcuni giovani si tenevano aggrappati disperatamente ai copertoni bagnati dei blindati, lo sguardo inebetito e fisso, premendo maniacalmente smartphone di quarzo ormai trasformati in placche di vetro nero inutile e opaco. I loro pollici continuavano a tentare compulsivamente lo striscio per interfacciarsi a vuoto, come in venerazione davanti alle misere reliquie. Non v'era urlo umano di panico, ma solo quel gemere infante da gola serrata, la spaventosa e animale astinenza neurale dell'ignoto in cui, senza l'imboccamento forzato degli algoritmi rassicuranti forniti da Vane, i cuori sfidavano infarti prematuri per un'incapacità fisica autoindotta persino di formulare il pensiero stesso del pianto. 
Davanti a quell'ecatombe psicologica immensa di una folla mutilata, Claudio ricordò. 
Un ultimo ricordo vivo incastonato nella mente disarticolata che sfidava lo svenimento in mezzo strada. Anni primi. Fine dicembre, uffici apicali. Un calice di amaro gelato per stemperare le tensioni pre-lancio del cerotto obblogatorio di prima emissione. Era alla vetrata a specchi continui che fasciava l'emiciclo apicale dell'ufficio privato del Direttore Julian Vane. Le ombre sui muri. Claudio giovane architetto. L'ammirare dall'alto la mastodontica capitale sottostante. 
Roma a quell'epoca pre-dittatura di byte non era razionale, ma una fiera di reti sfalsate. Fari delle macchine imbottigliate nel caos del traffico anulare del Raccordo, semafori ascritti di giallo in perigliose lampeggiate infinite su Tevere placido e ingombro, lucette d'osteria abusiva che sfidavano i rammendi dei controlli di quartiere ai Parioli sgualciti. Da lassù formicolava di una pulsante instabilità disordinata. Sembrava viva, febbricitante di spavento ed energia cinetica violenta e meravigliosa.
Julian Vane affiancò le spalle al vetro blindato dell'ufficio per osservarne le spigolose sfocature. Un ghigno da esteta insanguinato.
«Ammira quel dannatissimo battito irregolare sotto di noialtri, Claudio,» declamava Vane sorseggiando l'amaro forte ambrato. Aveva l'eloquenza folle del sovrano. «Vedi come sobbalza senza meta, impaurito dal domani mattina? Quelle luci a caso in periferia... quella è la nostra immensa e unica sinapsi rotta terrestre. Noi dell'alto Direttorio siamo ora gli unici veri neuroni eletti, tutta quella canaglia laggiù rannicchiata nei fanalini impauriti sono i puri dati bruti ammassabili. Sconvolgente. Piegati dall'illogicità pronti ad essere canalizzati al trionfo dell'ordine formale permanente se solo sapessi recider loro l'inutile affanno. Non credi sia un compito meraviglioso e spaventevole, l'essere i nuovi dei a orologeria che sanano tutto un intero battito in tachicardia impazzito all'unisono metronomo della stabilità?»
Claudio strinse il cristallo di boemia speso fino a render banchi i polpastrelli, sporgendo il muso a toccare l'illusione di quell'alveare. Aveva posato l'occhio dove i lampioni ai raccordi sfumavano in cimiteri privi del sole di catrame in un nulla oscurato oltre l'raccordo urbano e fuori, nelle campagne. Un vuoto fitto come la pece e duro a spiegarsi coi concorsi metrici o di volume e frequenza che stavano mettendo in opera all'Eur in gran segreto.
«Può apparire affascinante per un occhio distante e chirurgico. Forse lo è, se la guardi come un tavolo da tavolo sinottico in tre dimensioni tracciate dalla matita geniale dell'estetica che si prende i confini del mondo al centimetro finché i pallini restano lì, proni Julian. Elettrico fin che ti pare di crederci.» Claudio girò il corpo verso il despota per fissarlo, l'amaro del retrogusto in bocca misto d'apprensione e spregio primordiale. «Ma i led e le lampadine, prima o poi nel tempo del carbonio... finiscono e si bruciano. Si spaccano ai filamenti, le connessioni si tagliano sempre, è la misera natura materiale di ogni nostro inutile baluardo elettrico a cedere il passo prima della noia e persa scommessa. Cosa cazzo ci resterà mai, qua sotto la vetrata oscurata, quando spegnerai a tutti loro in fronte la comoda luce obbligatoria abbagliante a cui li stiamo assuefacendo, Julian? Quando recideranno i contatti e torneranno gli animali crudi buttati di netto nelle vecchie caverne delle paure originali che gli stiamo fottutamente celando sotto i tappeti digitali di silicio... Julian? Avrai creato angeli in scatola... o l'inferno peggiore per chi non riuscirà più ad usare un fiammifero se glielo metti sul dito e la candela manca?»
Vane aveva taciuto allusivo. Quello stesso stucchevole silenzio che non celava risposta, ma puro e criminale cinismo ingegneristico di facciata per chi crede d'esser l'architetto del cielo chiuso. 
Ora, col freddo assassino dell'aria vera in autunno a tagliarli il muso, Claudio sapeva la cruda ed esangue risposta del despota d'oro di prima decina prima asceso al trono digitale della nazione arresa. Restava intatta, inviolata la spaventosa fottuta paura disperata dell'animale uomo che deve imparare da capo come far sanguinare le dita per estrarre la prima patata zozza e inservibile dalla fanga brumosa, la cenere spietata scura da ripulire alla rinfusa dopo decenni finti in una pace perenne. 
Un sibilo acustico agghiacciante sventrò il vicolo adiacente sbrandellando i ricordi sfalsati in flashback di salotto. 
Un mastodontico e sgraziato drone agricolo d'assalto convertito alla ronda anti-ressa piegò in diagonale sgommando sul selciato sbrecciato col fango misto al gasolio marcio fino all'angolo adiacente. Otto larghe rote corrugate colme di pattume incrostato, armatura spessa in lamiere incrociate e in testa l'occhio unico per torretta sensoriale rotante, lercio e opaco dalla burrasca autunnale caduta greve sul guscio antiproiettile di polimeri vecchi senza grazia. 
In totale assenza spuria di segnali portanti del mainframe centrale fottuto, quella orrenda trappola letale ambulante, pensata a domare assembramenti contadini o scioperi dei sobborghi, s'era resettata ai logaritmi primitivi d'emergenza cieca, in cerca affannosa e insaziabile autonoma di calore corporeo e movimento sregolato nell'acqua buia, decisa ad estinguere minacce per sopravvivenza paranoide programmata nel silicio secondario d'antiquariato cibernetico.
«Insubordinazione fisica a scansione anormale di biometria zero intercettata a visuale termica sedici nodi, deviazione comportamentale ascritta... Procedura spazzatrice esecutiva da default tre.» gracchiò la lamiera dell'androide ruotato, con la voce a strappi deformata a colpi di frequenza bassa metallica fastidiosa al midollo. Non cercava cittadini... puntava calore febbricitante dei due fuggiaschi impastati. Il puntatore ottico azzurrino balzò rapido rimpicciolendosi preciso verso il petto gonfio della t-shirt lacera insanguinata della mercenaria ribelle a petto d'uomo mal sano.
Laura non gli recriminò né logica fitta preambolo umano d'intesa e parvenza in lutto di stanchezza prima della tempesta brutale cibernetica discesa a vicolo. Fu più subitanea e folgorante persino del fulmine sordo balzato nell'Etere. Evitò il primo colpo, e la morsa tagliente scattò sferzando il vento piovigginoso del vicolo scomparendo tra le crepe buie d'un palazzotto anonimo del ventennio sbalzato sfuggito dalla ristrutturazione di Vane e soci alle calcagna dei destini.
In quel nanosecondo di stasi buia tra le strisce di pioggia incrociata lampionata solo da riflessetti striduli residui dall'androide rotante disperato nei calcoli senza centro operativo padrone per prevedere d'attacco l'obiettivo impazzito fuoribanda tracciata cibernetica. La mercenaria divenne ombra nera precipitosa solida. Sfiorò perpendicolare per un salto suicida colossale scendendo precisa addosso al maledetto dardo impazzito cadendogli violenta pesantissima dall'alto della carenatura spessa grigiastra che si avvallò e cigolò per il cedimento strutturale in scocca della bestia impantanata sul brecciolino viscido d'acqua. 
Con freddezza disumana che solo chi è sopravvissuta d'inferno ai test neurali di ABITES estorte conosceva in istinto animale per farsi boia al carnefice suo boia di carne o silicio che sia, afferrò d'ambo dure lame taglienti manici neri solidi con mano e infilò le zanne spietatamente acuminate per sfondare di netto incastri giunture fragili che occultavano snodi idraulici cervelletto centrale logico e circuitale base disgiunti dall'acqua sigillati male al robot.
Stridore metallo su metallo tagliente crudo violento. Scintille folli e libere viola a mazzi. Il drone d'assalto gemette rantolo di fumo velenoso chimico asfissiante contorcendosi al corto cortissimo per scarico della resistenza scassata letale a puzzo rancido morto e cessò l'ignobile corsa, piantonato di striscio. Schiantato. Esanime da spazzatura a ingombro inutile pezzo ruggine sotto la fine era ABITES e primo pugno di ferro e sangue per mano umana, fritto al suo cuore primordiale, decapitato del relé esecutore e rimasto senza appelli dalla forza brutale della caduta della carne fiera ribelle. 
Laura affondò i reni di sfianco ansimando come fiera di bestia, scavalcò il corpo della rottamaglia d'infamia metallica fritta nell'acqua zozza sputando la bava rancida del disgusto piovano romano in rimasugli ai colli dita affaticate tremanti di nervi da colpo fendente duro staccato dai tendini provati, si strappò i manici via e andò solida zoppicante barcollante, riafferrando rudemente spalla stremata dell'uomo per strattonarlo di peso dal ginocchio piegato al gelo da rassegnazione letargica in abbandono stradale del post-botto disperato di adrenalina scadente sfatta svenuta dall'ingegnere febbricitante distrutto all'emorragia sporca rappresa alla camicia straccia che le pendeva tra fanga e freddo.  
«Muovi il tuo santo fottuto peso sfiatato di ossa rotte, testa dura ribelle del piffero architettuale prima di spirare al buio e darci pena d'apocalisse ai cretini caduchi in abito formale per grigliata serale per strada morta!» lo spronò alitandogli forza fiato rovente all'orecchio intirizzito in burrasca violacea mentre stringeva il polso debole suo malandato a morsa viva tirandolo di pacco verso se stessa raddrizzandolo a ridosso a muro sterrato laterale da non cedimento fango sbrecciato della Roma antica in abbandono.
«Dobbiamo arrivare a sudovest alla cazzo di lavanderia periferica di Carlo tra i magazzini industriali rotti...» rantolò rauco Claudio smosso da tosse asfissiante dolorosa vomitevole pece dalla trachea arida per l'amarezza di fumo ustionato. «Via della Corte rotta dei magazzini logistici sudici e sporchi puzzo chiuso stantio chimica dei farmaci e candeggina smarrita dalle guardie imperiali morte d'aria viziata sfuggita di ronda pattugliata al reset antico obsoleto a vista ottica staccata...» 
Claudio contò compulsivamente farneticante ogni gradino del calvario stradale a passettini per mantenersi sveglio agganciato ai neuroni basici residui sfalsati, l'autodisciplina logaritmica l'estremo appiglio d'ingegnere sfumato al buio pece assoluto di città cimitero da far respiro per passetto strascicante. 
Cento trenta miserevoli metri sputati di fango stradale e orrore folla inebetita in shock stravolta abbandonata alla paralisi sensoriale. Cento ottanta malmessi lastricati tondi neri sdrucciolosi scivolo allagato putrescenti fognarie rigurgitate dall'inferno cittadino orbo. 
Arrivarono arrancando marci fradici di dolore stremati luridi puzzolenti spalla marcia sangue stantigenato alla lavanderia abbandonata finta copertura fatiscente squallida vetrina in affresco sbiadito postbellica periferia abbandonata squallida. 
L'insegna lercia muta smorta al piombo freddo d'acciaio ruggine. 
L'ingegnere roteò le tremanti chiavi ruggini obsolete meccanismi tozzi fitti pesanti di dita indolenzite dal caldo bruciastro plasticoso drive incuneate storte all'inferriata grigia logica cadente con clangore raschiante grezzo disarticolato aprendola per irruzione stanca fessa scordata stridente pesante spinta dall'inerzia del collasso fisico terminale disceso spalla.
L'odore acuto polveroso di litio vecchio e aria stantia densa asfissiante candeggiante acrilica misto di sudori freddi antichi muffa pervasiva medicinale rancido disinfettante marcio obbrobrio li inghiottì di botto nell'oscurità nera stanza grezza metallica gelida isolata.
Laura raschiò ciecamente il muro d'intonaco staccato friabile brancolando sorda ai tasti antichi e calciò l'interruttore base rozzo a scatto plastico grosso tozzo a molla bloccato dalla calcificazione salina muraria in fessura in incavo ombra porta. Una microscopica pietosa giallognola lucina balbuziente moribonda, alimentata disperata alla fievole scorta putrida morta in logorio strascicato di vecchia e rancida batteria piombata di furgonaggio per auto rudere dismessa decenni in cavi volanti scotchati marci arrugginiti fritti ossidati striscia penzoloni pretecnologici. 
Si proiettò stanca malata fessa stitica fievole debole rassicurante illuminò mezza fessura di stambugio.
Claudio sfiondato al limite muscolare cedette collassò fradicio freddo duro a peso abbandonato orrendo lamento di nervi spezzati in giunture legamenti stanchi al petto crollante sul metallo del tavolo smisto bucato arrugginito macchiato sporco ferro. Il tintinnio ossa e ferri arsi fu tombale in eco chiusa prigione silenziata sicura in barriera prestatale rotta a bunker precario. 
Il suo oramai microscopico tremolante offuscato farneticante campo visivo vitreo di ciglia sudate umide di lacrime acide si ridusse a imbuto nero a piccolo foro di spillo puntina fioca luce spenta in sonno preda gelido spegnersi dell'inerte cosciente respiro vitale calo abbattimento estremo. 
Laura in sfogo rottura di legamenti, disperata razziava compulsivamente frenetica di mani rozze irruenti in affannamento convulso setacciando scatole lattoni scassate sgangherate kit medici rotti prebellici bende ruvide medicazioni infette garze grezze in macchie rossobruno indurite asciutte croste dal suo polso a strascico sangue macrato orrendo al freddo sfregolato in urgenza di zoccolo.
Claudio chiuse scroscio spossato le bruciate pesanti orbe stanche palpebre incrostate a grumi di pece secca palpebrate sporche stordite, premette aderente il gelo crudo dell'acciaio smorto industriale tavolo obitorio in ferro alla propria debole tesa febbrilmente febbricitante guancia ispida scura incava stremata in abbandono osso zigomo, sprofondata di nero e udì sognante scroscio della pioggia rimbombante lamiere spesse vetro polveroso ragnatele spesse bottega vetrata di strada perduta nel mondo fottuto del tiranno distrutto per il ritorno al vero nero silenzioso doloroso e reale primitivo freddo spaventoso umano della nuova disperata ed ignota era appena caduta dalle pareti dorate degli idioti, covando in braci l'esangue minuscola patetica preghiera irrazionale che tutta quell'oscura puzza fuliggine d'orrori passati sprofondati fosse solo terriccio fango fecondo fertile da per futura scavo rinascita incauta dolorosissima ma mortale reale vera pura polvere liberi in cui sporcare semi stanchi e rinascere a nuova precaria vita mortale felice di incertezze caduche a fiamma d'uomo caldo incostante senza catena incisa nella logica e silicio tiranno imposto sulla carne indifesa all'alba post fine prigione.`;
