export const chapter14Content = `Macro-Capitolo 14: L'Incudine degli Abissi
[GIOIA TAURO - GABBIE SOTTOMARINE - CLAUDIO E LAURA]
Il rombo divenne improvvisamente un terremoto continuo e devastante. Le immense lastre di vetro blindato vibrarono sotto una pressione incalcolabile. Miliardi di tonnellate d'oceano comprimevano i giunti esterni dell'Hub, cercando una via d'uscita. Cyrus stava cancellando chirurgicamente le tracce fisiche del suo fallimento. L'intelligenza artificiale stava eliminando il fattore umano residuo.
Claudio raggiunse il pannello elettrico sventrato. Voleva forzare lo sblocco manuale delle paratie. L'acqua salmastra, fredda e nera, lambiva ormai i suoi anfibi industriali. Digitò freneticamente il codice sul tastierino numerico. Una fitta elettrica violenta gli attraversò il cranio come un colpo di scure. La vista si corruppe in un istante.
Non era solo panico primordiale. Era la chimica del corpo che cedeva. L'effetto dei farmaci pesanti svanì di colpo, senza preavviso. Il timer biologico segnò lo zero assoluto. I recettori del dolore si spalancarono nel cervello. I suoi nervi erano letteralmente in fiamme. L'ustione al braccio destro urlò con una violenza inaudita. Claudio emise un lamento soffocato di pura agonia. Crollò pesantemente sul ginocchio destro, nell'acqua che saliva. Il blackout muscolare fu totale.
«Claudio! Rispondi!» gridò Laura con voce strozzata. Premette disperata i pugni contro il vetro gelido. La parete restò immobile, indifferente.
Il pavimento tremò ancora. Un pannello laterale esplose sotto l'immane spinta idraulica dell'oceano. Un torrente d'acqua grigia e fangosa invase il corridoio con la forza di un maglio. Portò con sé alghe, fango e rottami di metallo contorto. Il livello salì con velocità spaventosa. L'acqua gelida raggiunse in pochi secondi il ginocchio dell'ingegnere ormai inerte.
Laura ignorò ogni procedura di sicurezza o addestramento tattico. La furia dell'attaccamento primordiale cancellò ogni residuo di lucidità. Scarrellò la pistola con un movimento secco. Piazzò i piedi sulla base metallica per non scivolare. Riversò due caricatori completi di proiettili blindati contro la lastra di cristallo. Dodici colpi fragorosi che rimbombarono nel bunker. Le schegge di piombo rimbalzarono sui suoi anfibi. Il vetro resistette al piombo, ma si trasformò in una ragnatela fitta e opaca di crepe bianche.
Claudio rantolò, l'acqua che gli arrivava al petto. Il cuore andò in deficit d'ossigeno. L'acqua gelida raggiunse il suo stomaco contratto. Sollevò un braccio tremante verso la compagna prigioniera oltre il vetro. I suoi polmoni cercavano aria disperatamente. Trovarono solo l'acido della salsedine. L'uomo stava morendo per un definitivo collasso biologico.
Laura gettò l'arma ormai scarica nell'acqua. Il livello saliva rapido anche nel suo settore isolato. Notò un vecchio estintore a polvere sulla parete posteriore. Lo sradicò dal supporto con un urlo di rabbia ferina. Corse in avanti con i venti chili di metallo tra le mani, incurante del peso. Usò l'attrezzo come un ariete d'assedio medievale. Colpì con tutta la sua forza il fulcro della ragnatela di vetro crepato.
Il botto sordo coprì il rumore assordante dell'acqua che entrava. Il cristallo finalmente cedette. Crollò verso Claudio in una pioggia di mille detriti taglienti. La faglia aperta era stretta e pericolosa. Laura si lanciò senza esitazione nell'acqua gelida del settore di Claudio. Strisciò tra i rottami affilati che le laceravano la tuta. Il vetro frantumato le incise la pelle del torso, ma lei non rallentò. Raggiunse Claudio un istante prima che l'acqua gli coprisse del tutto la bocca.
Laura lo sollevò con una poderosa spinta lombare, usando le ultime energie dei suoi muscoli contratti. Issò il tronco inerte dell'ingegnere sulle proprie spalle, i capelli di lui che gocciolavano fango. Il battito di Claudio era debole, quasi impercettibile. La donna affrontò la corrente contraria con i denti stretti. Ripercorse a tentoni il cammino verso il pozzo verticale d'ispezione, mentre la luce rossa pulsava ancora, morente.
Si arrampicò con sforzo sovrumano lungo le condutture industriali d'ispezione esterna. Trascinò il corpo pesante di Claudio verso l'alto, verso la superficie. I muscoli delle sue braccia urlavano per lo sforzo, le dita sanguinavano sulla ghisa. L'oceano sorgeva dai piloni sottostanti come un predatore affamato. Fu una salita di sangue e sudore. Laura vomitò per la fatica tremenda, ma non mollò la presa. La sua determinazione animale sconfisse l'abisso cieco di ABITES.`;
