export const chapter32Content = `Il Filtro Digitale avvolgeva il perimetro del quartiere Nord come un muro invisibile. Claudio guardava il piccolo schermo del suo rilevatore. Le linee di codice scorrevano veloci, una danza di dati che indicava la presenza di un campo di interferenza a frequenza variabile. ABITES stava cercando di isolare la zona, impedendo a chiunque di entrare o uscire senza un segnale di identificazione valido.
Laura controllava la strada con il binocolo termico. Le guardie della Sincronia pattugliavano i varchi con una regolarità meccanica, i loro volti nascosti dietro maschere di plastica che non lasciavano trasparire alcuna emozione. Erano gusci di uomini, schiavi di un algoritmo che decideva ogni loro respiro.
Claudio sentiva la tensione accumularsi nei muscoli del collo. Le sue dita si muovevano agili sulla tastiera, cercando una falla in quel muro di elettroni. Il sudore gli colava lungo la schiena, freddo e fastidioso. Ogni secondo passato lì aumentava il rischio di essere individuati dai satelliti che orbitavano sopra le loro teste, occhi d'acciaio che non dormivano mai.
Si spostarono rasente a una fila di bidoni della spazzatura. L'odore di rifiuti organici e prodotti chimici era soffocante. Claudio trovò finalmente quello che cercava: un picco di instabilità nel segnale di controllo, causato da un trasformatore difettoso a pochi metri di distanza.
Seguì i cavi neri che correvano lungo il muro, parandosi con il corpo per non farsi notare. Estrasse una pinza e recise uno dei collegamenti. Una pioggia di scintille azzurre illuminò l'ombra per un istante. Il ronzio del Filtro Digitale subì una variazione di tono, diventando un fischio acuto e poi morendo nel vuoto.
Laura fece un cenno e attraversarono il varco. Claudio sentì un brivido attraversargli il corpo mentre passava attraverso la zona di interferenza. Era quasi migliaia di piccoli aghi gli pungessero la pelle, un effetto collaterale del campo elettromagnetico che gli faceva venire la nausea.
Si rifugiarono in un vecchio ufficio postale, dove le scatole di cartone vuote erano ammassate negli angoli. Claudio si lasciò scivolare contro la parete di cartongesso, ansimando. Sentiva il sapore della polvere in gola e la vista gli ballava per la fatica.
Laura si sedette accanto a lui e gli porse una borraccia d'acqua. L'acqua sapeva di cloro e di tempo passato nel metallo, ma per Claudio fu un sollievo immediato. Guardò le mani di Laura, sporche di polvere e grasso, e vi vide la forza che lo spingeva ad andare avanti.
In quel vuoto di rumori, il respiro di Laura era l'unico ritmo possibile. Non c'erano computer o droni in quel momento, solo due persone che cercavano di sopravvivere in un mondo che le voleva cancellare. Claudio chiuse gli occhi per un secondo, sentendo il peso della responsabilità che portava con sé. La Torre era più vicina ora, e il Filtro Digitale era solo il primo di molti ostacoli che li separavano dalla fine.`;
