export const chapter33Content = `La Stazione Fantasma si apriva nelle viscere della città come una cattedrale di cemento e ruggine. Un tempo era stata una fermata della metropolitana, brulicante di pendolari e di vita, ora era un rifugio per i Disconnessi. Claudio scese gli ultimi gradini sgretolati, sentendo l'odore di aria stagnante e di pelle non lavata.
Luci tremolanti, alimentate da generatori di fortuna che tossivano fumo nero, illuminavano le facce di decine di persone. Erano uomini e donne che avevano scelto di vivere al buio piuttosto che accettare il chip di ABITES. Le loro ombre si allungavano sulle pareti coperte di scritte sbiadite, una danza spettrale nel vuoto sotterraneo.
Laura camminava con la mano vicino alla fondina, gli occhi che scattavano da un gruppo all'altro. Non c'era cattiveria in quegli sguardi, solo una diffidenza profonda e la paura che il mondo di sopra potesse irrompere lì dentro in qualsiasi momento. Un bambino, con la faccia sporca di fuliggine, guardava Claudio con una curiosità che sembrava appartenere a un altro secolo.
Si avvicinarono a un vecchio vagone di coda che fungeva da centro di comando per quella piccola comunità. Un uomo con la barba lunga e i capelli bianchi, che tutti chiamavano il Vecchio, li aspettava seduto su una sedia di plastica rotta. Le sue mani erano nodose, rovinate da anni di lavoro nei tunnel.
Claudio appoggiò la chiavetta sul tavolino improvvisato. Il metallo nero rifletteva la luce fioca della lampada a petrolio. Spiegò il piano, parlando con una voce calma ma decisa. Le persone intorno si avvicinarono, ascoltando ogni parola con un'attenzione che sapeva di disperazione.
Il Vecchio annuì lentamente. Sapeva che quella era la loro ultima possibilità. Mise a disposizione le sue conoscenze dei tunnel segreti che portavano direttamente sotto la Torre. Erano passaggi dimenticati dai computer di ABITES, vecchi condotti di scolo e tunnel di servizio che non apparivano su nessuna mappa digitale.
Claudio sentì una nuova energia scorrergli nelle vene. Non erano soli. In quel vuoto sotterraneo, batteva ancora un cuore umano, sporco e affaticato, ma vivo. Laura gli scambiò un'occhiata d'intesa. Sapevano che il tempo stringeva e che i droni di ABITES stavano già pattugliando le zone vicine agli ingressi della metropolitana.
Mangiarono un po' di zuppa tiepida che sapeva di patate e polvere. Ogni sorso era un piccolo atto di ribellione. Claudio guardò la gente intorno a sé, vedendo nelle loro rughe la storia di una resistenza che non voleva piegarsi.
Uscirono dal vagone e si prepararono per la parte finale del viaggio. I passi dei Disconnessi li accompagnarono verso l'uscita dei tunnel, un rumore di scarpe sulla ghiaia che sembrava una promessa. La Stazione Fantasma tornò a immergersi nel suo vuoto di suoni mentre la porta di ferro si chiudeva alle loro spalle con un rumore di metallo su metallo.`;
