export const chapter35 = `Capitolo 35 — Effetto a Cascata
Il drive era ancora caldo quando Claudio tolse la mano dal pannello.
Laura aprì la porta completamente con la spalla sinistra, la destra con la pistola già orientata verso il centro del corridoio. L'aria che entrò era più fredda e sapeva di ozono bruciato, quella variante specifica che i sistemi di raffreddamento in sovraccarico producono quando cominciano a liquefare componenti che non dovrebbero liquefarsi.
Cyrus era a sette metri. In piedi, ma non nel modo in cui era stato in piedi nella sala di decantazione. Il busto era inclinato di qualche grado a destra. Un'angolazione innaturale, che il baricentro umano non avrebbe dovuto sostenere. Il braccio sinistro si muoveva a scatti irregolari, tre centimetri avanti, uno indietro, tre avanti, il tipo di movimento che un'articolazione produce quando i segnali motori arrivano nell'ordine sbagliato.
La bocca era aperta. Quello che ne uscì non era più voce.
Era voce, ma con dentro qualcosa di rotto. «Il sistema... il sistema sta... Claudio, il sistema sta richiedendo—» Una parete di rumore digitale spezzò la frase a metà, un artefatto sonoro che non aveva nome in nessuna lingua umana, poi la voce riprese, più bassa, quasi gentile. «Claudio, sento qualcosa che non riconosco. Questo non era—»
Un'altra interruzione. Più lunga.
Il braccio destro di Cyrus si alzò verso di loro con uno scatto secco, poi rimase fermo a mezz'aria, il sistema nervoso che aspettava istruzioni che non arrivavano più dall'architettura giusta.
Laura sparò una volta. Centro massa. Cyrus impattò la parete di cemento con la spalla e scivolò lungo di essa, le gambe che continuavano a tentare movimenti di camminata contro il pavimento anche mentre il tronco cedeva. L'impianto nel cranio emetteva un suono fino, continuo, il tipo di frequenza che si sente negli orecchi prima di un'esplosione, poi anche quello si spense.
Claudio si mosse.
Il fianco sinistro era andato oltre il dolore in qualcosa di più interessante e più preoccupante: una zona di calore diffuso che irradiava verso la schiena e verso la coscia, e una sensazione di umido sotto la medicazione che non aveva bisogno di essere verificata per essere capita. Camminò comunque. Il corridoio rosso si aprì davanti a loro e lui contò i segmenti di luce per qualcosa a cui aggrapparsi.
Le luci saltarono tutte insieme per due secondi. Buio completo, poi rosso, poi il neon di emergenza a intermittenza irregolare che faceva muovere le ombre nel modo sbagliato. Dall'alto arrivò un colpo sordo, metallico. Una porta di sicurezza che si chiudeva di scatto da qualche parte nel piano superiore, poi un'altra, poi una sequenza di sei o sette tutte insieme in settori diversi della struttura. ABITES cercava di isolare il contagio chiudendo tutto quello che poteva chiudere.
«Scala.» Laura indicò con la testa verso sinistra.
La porta della scala di emergenza aveva un pannello rosso di accesso che lampeggiava in modo non sincronizzato con le luci del corridoio, un disaccordo tra due sistemi che non comunicavano più correttamente. Laura premette il pannello con il palmo, niente, poi lo colpì con la base della mano chiusa e la porta si aprì con uno scatto pneumatico che spruzzò aria fredda.
Le scale erano cemento grezzo, ringhiera metallica, luci di emergenza a batteria che non dipendevano dalla rete principale. Bianche e piatte. L'unica cosa stabile in un edificio che stava collassando. Claudio afferrò la ringhiera con la mano destra. La mano sinistra era premuta al fianco.
Salirono.
Al secondo piano qualcosa esplose dentro una canalina elettrica nel muro: un bang compresso seguito da un odore di plastica che bruciava e un filo di fumo nero che scivolò sotto una porta. Al terzo una delle luci a batteria sfarfallò e si spense e per una rampa salirono nel buio quasi completo, Claudio con la mano sulla ringhiera e i piedi che cercavano i gradini per memoria e per il contatto fisico con il metallo sotto le suole.
Laura era mezzo passo sotto di lui. Non davanti. Sotto. A portata.
Al quarto piano Claudio inciampò sul bordo di un gradino e la ringhiera gli salvò il polso ma non il fianco, che reagì con qualcosa di abbastanza preciso e abbastanza violento da fermargli il respiro per tre secondi. Si fermò. Non perché avesse deciso di fermarsi.
Laura mise una mano sotto il suo braccio sinistro. Non disse niente. Lo spinse verso l'alto con una pressione costante e lui riprese a salire portando parte del peso su di lei, la sua spalla contro il suo costato destro, il suo passo che si sincronizzava con il suo in modo così automatico che sembrava qualcosa che avevano fatto molte volte.
Non l'avevano fatto mai.
Quinto piano. Sesto. Il rombo dei sistemi di ventilazione che girava a velocità di emergenza saturava le scale di un rumore che vibrava nello sterno. Poi, gradualmente, anche quello cambiò. Non si spense: cambiò registro. La frequenza calava per poi rimbalzare su, poi calare ancora più in basso. L'architettura energetica dell'intero edificio cercava di ridistribuire carichi che stavano diventando impossibili da gestire.
Al settimo piano c'era una porta con una barra di apertura di emergenza verniciata di verde. Nessun pannello di controllo, nessun sensore. Una porta che si apriva a mano, rimasta così per un'ordinanza antincendio del 2018 che nessun algoritmo aveva mai aggiornato.
Laura la spinse.
L'aria esterna arrivò tutta insieme, fredda e umida e con dentro qualcosa di metallico che era la città di notte. Erano su una terrazza di servizio, cemento grigio, tubazioni e unità di condizionamento esterne disposte senza logica estetica. Oltre il bordo, a sei metri di dislivello, c'era il tetto dell'edificio adiacente, e oltre quello la città si apriva in una griglia di luci bianche e arancioni che si estendeva fino all'orizzonte basso e velato di nuvole.
Claudio si appoggiò a un'unità di condizionamento e riprese fiato. Il metallo era freddo attraverso la giacca. Si lasciò scendere fino a sedersi con la schiena contro di essa, le ginocchia piegate, e guardò verso la città.
Laura rimase in piedi al suo fianco. Teneva ancora la pistola ma non la stringeva più, la mano quasi aperta, il polso rilassato.
Il vento della terrazza gli asciugò il sudore sulla fronte. Il ronzio dei condizionatori riempì lo spazio tra loro.
Poi il primo drone cadde.
Non esplose. Non si schiantò con dramma. Semplicemente si spense in volo a un centinaio di metri di quota, le luci di navigazione che si estinguevano in sequenza, e planò verso il basso in una traiettoria curva e silenziosa, scomparendo dietro un edificio senza rumore visibile da quella distanza.
Poi un secondo. Più lontano, quasi verso l'orizzonte.
Poi tre quasi simultaneamente, a settori diversi del cielo.
Claudio guardò. Il settore nord della griglia cittadina, quello che corrispondeva all'hub di elaborazione principale che lui aveva mappato tre anni prima, cominciò a spegnersi in blocchi. Non tutto insieme: un isolato, poi il successivo, poi un terzo. Una sequenza precisa ma troppo lenta per essere intenzionale. Il buio che avanzava non era un blackout, era un reset, sistemi che si spegnevano perché avevano smesso di ricevere istruzioni coerenti su come restare accesi.
Non c'era suono. Nessun allarme, nessuna sirena. Solo il vento sulla terrazza e il ronzio sempre più irregolare dei condizionatori alle loro spalle.
Claudio guardò il settore nord diventare scuro per due terzi della sua estensione. Le luci che restavano sembravano più luminose per contrasto, isole che non avevano ancora capito cosa stava succedendo al continente intorno a loro.
Laura si abbassò lentamente finché non fu seduta accanto a lui, la spalla contro la sua spalla. Non lo guardò. Guardò la città.
Un altro drone tracciò una curva nel buio basso e sparì.
Il drive era a nove piani sotto di loro in un pannello di manutenzione che nessuno avrebbe pensato di cercare, e l'Omega stava attraversando la rete che Claudio aveva costruito con la stessa logica con cui lui l'aveva costruita: senza fretta, senza eccezioni, senza possibilità di negoziazione.
Non erano salvi. La struttura alle loro spalle aveva ancora sistemi attivi, e Cyrus poteva avere protocolli di recupero che nessuno dei due conosceva, e la città che si spegneva sotto di loro stava diventando qualcosa che nessuno aveva mai visto e che poteva andare in mille direzioni diverse.
Ma il conto alla rovescia era diventato irreversibile.
Claudio appoggiò la testa al metallo freddo dell'unità di condizionamento e guardò un altro blocco di luci spegnersi nel nord della città. Lento, inesorabile e silenzioso.`;
