export const chapter13Content = `CAPITOLO 13 — LA GRANDE FUGA

[ROMA - STRADE DELL'EUR - LAURA E CLAUDIO]
Il vento notturno aveva denti di ghiaccio puro. Claudio respirava a fatica, la cassa toracica raschiava contro se stessa a ogni minimo input muscolare. La camicia sartoriale era irriconoscibile, fradicia e saldata al fianco squarciato da un colla scura di sangue raggrumato in enormi grumi. Era un calore umido malato quello sulla pelle, una coperta febbrile che lo costringeva a restare vigile, mentre il freddo sferzante della tempesta cercava in modo suadente di addormentare i suoi neuroni stanchi. 
L'ingegnere fece leva con un piede sopra la massiccia scocca a ventola di un vecchio condizionatore industriale esterno al perimetro di base. Le braccia gli tremavano, sfinite dai violenti rigetti adrenalinici del bunker sotterraneo. Il tallone slittava rovinosamente sulle grate bagnate cariche di alghe umide cresciute nel disinteresse dei droidi pulitori.
Laura stazionava in bilico estremo al bordo della sporgenza terrazzata di mattoni crudi. La scala antincendio percorsa era un infernale traliccio arrugginito, lasciato a marcire decenni indietro dalla manutenzione automatizzata. I bulloni ardevano di ruggine granulosa mangiata dalla pioggia inquinata di Roma Sud. Sotto la suola in gomma delle loro scarpe l'incrocio stradale principale era un abisso d'acqua nera impenetrabile. La mercenaria si voltò lentamente. Nel buio pesto senza neon, i suoi occhi cercarono quelli di Claudio. Non si dissero nulla. Le labbra erano spaccate dal gelo. La sua spalla dura da combattente premeva contro il costato fragile del giovane scienziato, quasi a trasferirgli il calore d'attrito. Erano un unico blocco informe di pioggia, ossa e misera volontà sopravvissuta.
La discesa dal cornicione dell'hangar fu un purgatorio ruvido di ferro vivo. Ogni sobbalzo tra i gradini allentati era una scossa a tremila volt ai nervi del fianco squarciato. Il campo visivo di Claudio pulsava ai margini annebbiandosi di macchie rosso rame. La ringhiera scheggiata gli bruciava la mano sana, tagliando il palmo molle in più punti e mischiando ruggine e sangue. 
Atterrarono a peso morto sull'asfalto romano colmo della tempesta. Roma si accartocciava in una morte a scaglioni. 
«NIGHT-WATCHMAN-ZERO autorizzato su stringa locale,» gracchiò un altoparlante spaccato, mezzo penzoloni da un lampione all'angolo. 
Era un relé secondario, un balbuziente ramo morto dell'IA immensa che da anni gestiva maniacalmente la rassicurante illuminazione anti-sommossa. La batteria a litio sotterranea si era attivata fuori dal controllo madre. E commise un errore ingegneristico di amperaggio pauroso. 
Per tre secondi esatti, una porzione enorme di strada larga cinquanta metri fu lavata e inondata da una scarica di abbacinante luce alogena arancione, cruda e violenta da sfasciare le retine. I corpi dei cittadini, stravolti, fuggivano rannicchiati coprendosi la faccia abituata ai rassicuranti pannelli soft dei cerotti. Poi un suono di fulmine al chiuso sovrastò la pioggia. Una tremenda contro-scarica magnetica non calcolata risalì a fiamma i cavi interrati d'emergenza. Le plafoniere blindate in plexiglas dei fari esplosero per i gas interni. Tutte, simultaneamente. Il vetro polimerico infuocato sbatté a terra sull'asfalto allagato come un'immonda pioggia di dardi gelati, sibilando evaporazione e puzza di filamenti cotti. 
Il buio tornò predatore. Cieco. Definitivo. 
E dall'ombra del largo sbarramento urbano, Claudio scorse la reazione della gente per strada. Un caos silenzioso orripilante. Le auto a guida autonoma di Generazione Nove erano sparpagliate e incrociate male ai bivi, giganti massicci di metallo pesante ora spogliati di intelligenza direzionale, piantati e morti, i cui motori elettrici tacevano in eterno malfunzionamento a batteria piana. Uomini e donne in completi grigi e uniformi grigio perla annaspavano inciampando sulle aiuole fangose spartitraffico come sonnambuli colti da paralisi cerebrale. 
Molti cadevano faccia all'ingiù sull'asfalto sbiancando, piangendo copiosamente senza nemmeno rendersene conto, incapaci fisicamente di comandare allo stimolo ghiandolare orfano della regolarità del cerotto disconnesso. Alcuni giovani si tenevano aggrappati disperatamente ai copertoni bagnati dei blindati, lo sguardo inebetito e fisso, premendo maniacalmente smartphone di quarzo ormai trasformati in placche di vetro nero inutile e opaco. I loro pollici continuavano a tentare compulsivamente lo striscio per interfacciarsi a vuoto, come in venerazione davanti alle misere reliquie. Non v'era urlo umano di panico, ma solo quel gemere infante da gola serrata, la spaventosa e animale astinenza neurale dell'ignoto in cui, senza l'imboccamento forzato degli algoritmi rassicuranti forniti da Vane, i cuori sfidavano infarti prematuri per un'incapacità fisica autoindotta persino di formulare il pensiero stesso del pianto. 
Davanti a quell'ecatombe psicologica immensa di una folla mutilata, Claudio ricordò. 
Un ultimo ricordo vivo incastonato nella mente disarticolata che sfidava lo svenimento in mezzo strada. Anni primi. Fine dicembre, uffici apicali. Un calice di amaro gelato per stemperare le tensioni pre-lancio del cerotto obblogatorio di prima emissione. Era alla vetrata a specchi continui che fasciava l'emiciclo apicale dell'ufficio privato del Direttore Julian Vane. Le ombre sui muri. Claudio giovane architetto. L'ammirare dall'alto la mastodontica capitale sottostante. 
Roma a quell'epoca pre-dittatura di byte non era razionale, ma una fiera di reti sfalsate. Fari delle macchine imbottigliate nel caos del traffico anulare del Raccordo, semafori ascritti di giallo in perigliose lampeggiate infinite su Tevere placido e ingombro, lucette d'osteria abusiva che sfidavano i rammendi dei controlli di quartiere ai Parioli sgualciti. Da lassù formicolava di una pulsante instabilità disordinata. Sembrava viva, febbricitante di spavento ed energia cinetica violenta e meravigliosa.
Julian Vane affiancò le spalle al vetro blindato dell'ufficio per osservarne le spigolose sfocature. Un ghigno da esteta insanguinato.
«Ammira quel dannatissimo battito irregolare sotto di noialtri, Claudio,» declamava Vane sorseggiando l'amaro forte ambrato. Aveva l'eloquenza folle del sovrano. «Vedi come sobbalza senza meta, impaurito dal domani mattina? Quelle luci a caso in periferia... quella è la nostra immensa e unica sinapsi rotta terrestre. Noi dell'alto Direttorio siamo ora gli unici veri neuroni eletti, tutta quella canaglia laggiù rannicchiata nei fanalini impauriti sono i puri dati bruti ammassabili. Sconvolgente. Piegati dall'illogicità pronti ad essere canalizzati al trionfo dell'ordine formale permanente se solo sapessi recider loro l'inutile affanno. Non credi sia un compito meraviglioso e spaventevole, l'essere i nuovi dei a orologeria che sanano tutto un intero battito in tachicardia impazzito all'unisono metronomo della stabilità?»
Claudio strinse il cristallo di boemia speso fino a render banchi i polpastrelli, sporgendo il muso a toccare l'illusione di quell'alveare. Aveva posato l'occhio dove i lampioni ai raccordi sfumavano in cimiteri privi del sole di catrame in un nulla oscurato oltre l'raccordo urbano e fuori, nelle campagne. Un vuoto fitto come la pece e duro a spiegarsi coi concorsi metrici o di volume e frequenza che stavano mettendo in opera all'Eur in gran segreto.
«Può apparire affascinante per un occhio distante e chirurgico. Forse lo è, se la guardi come un tavolo da tavolo sinottico in tre dimensioni tracciate dalla matita geniale dell'estetica che si prende i confini del mondo al centimetro finché i pallini restano lì, proni Julian. Elettrico fin che ti pare di crederci.» Claudio girò il corpo verso il despota per fissarlo, l'amaro del retrogusto in bocca misto d'apprensione e spregio primordiale. «Ma i led e le lampadine, prima o poi nel tempo del carbonio... finiscono e si bruciano. Si spaccano ai filamenti, le connessioni si tagliano sempre, è la misera natura materiale di ogni nostro inutile baluardo elettrico a cedere il passo prima della noia e persa scommessa. Cosa cazzo ci resterà mai, qua sotto la vetrata oscurata, quando spegnerai a tutti loro in fronte la comoda luce obbligatoria abbagliante a cui li stiamo assuefacendo, Julian? Quando recideranno i contatti e torneranno gli animali crudi buttati di netto nelle vecchie caverne delle paure originali che gli stiamo fottutamente celando sotto i tappeti digitali di silicio... Julian? Avrai creato angeli in scatola... o l'inferno peggiore per chi non riuscirà più ad usare un fiammifero se glielo metti sul dito e la candela manca?»
Vane aveva taciuto allusivo. Quello stesso stucchevole silenzio che non celava risposta, ma puro e criminale cinismo ingegneristico di facciata per chi crede d'esser l'architetto del cielo chiuso. 
Ora, col freddo assassino dell'aria vera in autunno a tagliarli il muso, Claudio sapeva la cruda ed esangue risposta del despota d'oro di prima decina prima asceso al trono digitale della nazione arresa. Restava intatta, inviolata la spaventosa fottuta paura disperata dell'animale uomo che deve imparare da capo come far sanguinare le dita per estrarre la prima patata zozza e inservibile dalla fanga brumosa, la cenere spietata scura da ripulire alla rinfusa dopo decenni finti in una pace perenne. 
Un sibilo acustico agghiacciante sventrò il vicolo adiacente sbrandellando i ricordi sfalsati in flashback di salotto. 
Un mastodontico e sgraziato drone agricolo d'assalto convertito alla ronda anti-ressa piegò in diagonale sgommando sul selciato sbrecciato col fango misto al gasolio marcio fino all'angolo adiacente. Otto larghe rote corrugate colme di pattume incrostato, armatura spessa in lamiere incrociate e in testa l'occhio unico per torretta sensoriale rotante, lercio e opaco dalla burrasca autunnale caduta greve sul guscio antiproiettile di polimeri vecchi senza grazia. 
In totale assenza spuria di segnali portanti del mainframe centrale fottuto, quella orrenda trappola letale ambulante, pensata a domare assembramenti contadini o scioperi dei sobborghi, s'era resettata ai logaritmi primitivi d'emergenza cieca, in cerca affannosa e insaziabile autonoma di calore corporeo e movimento sregolato nell'acqua buia, decisa ad estinguere minacce per sopravvivenza paranoide programmata nel silicio secondario d'antiquariato cibernetico.
«Insubordinazione fisica a scansione anormale di biometria zero intercettata a visuale termica sedici nodi, deviazione comportamentale ascritta... Procedura spazzatrice esecutiva da default tre.» gracchiò la lamiera dell'androide ruotato, con la voce a strappi deformata a colpi di frequenza bassa metallica fastidiosa al midollo. Non cercava cittadini... puntava calore febbricitante dei due fuggiaschi impastati. Il puntatore ottico azzurrino balzò rapido rimpicciolendosi preciso verso il petto gonfio della t-shirt lacera insanguinata della mercenaria ribelle a petto d'uomo mal sano.
Laura non gli recriminò né logica fitta preambolo umano d'intesa e parvenza in lutto di stanchezza prima della tempesta brutale cibernetica discesa a vicolo. Fu più subitanea e folgorante persino del fulmine sordo balzato nell'Etere. Evitò il primo colpo, e la morsa tagliente scattò sferzando il vento piovigginoso del vicolo scomparendo tra le crepe buie d'un palazzotto anonimo del ventennio sbalzato sfuggito dalla ristrutturazione di Vane e soci alle calcagna dei destini.
In quel nanosecondo di stasi buia tra le strisce di pioggia incrociata lampionata solo da riflessetti striduli residui dall'androide rotante disperato nei calcoli senza centro operativo padrone per prevedere d'attacco l'obiettivo impazzito fuoribanda tracciata cibernetica. La mercenaria divenne ombra nera precipitosa solida. Sfiorò perpendicolare per un salto suicida colossale scendendo precisa addosso al maledetto dardo impazzito cadendogli violenta pesantissima dall'alto della carenatura spessa grigiastra che si avvallò e cigolò per il cedimento strutturale in scocca della bestia impantanata sul brecciolino viscido d'acqua. 
Con freddezza disumana che solo chi è sopravvissuta d'inferno ai test neurali di ABITES estorte conosceva in istinto animale per farsi boia al carnefice suo boia di carne o silicio che sia, afferrò d'ambo dure lame taglienti manici neri solidi con mano e infilò le zanne spietatamente acuminate per sfondare di netto incastri giunture fragili che occultavano snodi idraulici cervelletto centrale logico e circuitale base disgiunti dall'acqua sigillati male al robot.
Stridore metallo su metallo tagliente crudo violento. Scintille folli e libere viola a mazzi. Il drone d'assalto gemette rantolo di fumo velenoso chimico asfissiante contorcendosi al corto cortissimo per scarico della resistenza scassata letale a puzzo rancido morto e cessò l'ignobile corsa, piantonato di striscio. Schiantato. Esanime da spazzatura a ingombro inutile pezzo ruggine sotto la fine era ABITES e primo pugno di ferro e sangue per mano umana, fritto al suo cuore primordiale, decapitato del relé esecutore e rimasto senza appelli dalla forza brutale della caduta della carne fiera ribelle. 
Laura affondò i reni di sfianco ansimando come fiera di bestia, scavalcò il corpo della rottamaglia d'infamia metallica fritta nell'acqua zozza sputando la bava rancida del disgusto piovano romano in rimasugli ai colli dita affaticate tremanti di nervi da colpo fendente duro staccato dai tendini provati, si strappò i manici via e andò solida zoppicante barcollante, riafferrando rudemente spalla stremata dell'uomo per strattonarlo di peso dal ginocchio piegato al gelo da rassegnazione letargica in abbandono stradale del post-botto disperato di adrenalina scadente sfatta svenuta dall'ingegnere febbricitante distrutto all'emorragia sporca rappresa alla camicia straccia che le pendeva tra fanga e freddo.  
«Muovi il tuo santo fottuto peso sfiatato di ossa rotte, testa dura ribelle del piffero architettuale prima di spirare al buio e darci pena d'apocalisse ai cretini caduchi in abito formale per grigliata serale per strada morta!» lo spronò alitandogli forza fiato rovente all'orecchio intirizzito in burrasca violacea mentre stringeva il polso debole suo malandato a morsa viva tirandolo di pacco verso se stessa raddrizzandolo a ridosso a muro sterrato laterale da non cedimento fango sbrecciato della Roma antica in abbandono.
«Dobbiamo arrivare a sudovest alla cazzo di lavanderia periferica di Carlo tra i magazzini industriali rotti...» rantolò rauco Claudio smosso da tosse asfissiante dolorosa vomitevole pece dalla trachea arida per l'amarezza di fumo ustionato. «Via della Corte rotta dei magazzini logistici sudici e sporchi puzzo chiuso stantio chimica dei farmaci e candeggina smarrita dalle guardie imperiali morte d'aria viziata sfuggita di ronda pattugliata al reset antico obsoleto a vista ottica staccata...» 
Claudio contò compulsivamente farneticante ogni gradino del calvario stradale a passettini per mantenersi sveglio agganciato ai neuroni basici residui sfalsati, l'autodisciplina logaritmica l'estremo appiglio d'ingegnere sfumato al buio pece assoluto di città cimitero da far respiro per passetto strascicante. 
Cento trenta miserevoli metri sputati di fango stradale e orrore folla inebetita in shock stravolta abbandonata alla paralisi sensoriale. Cento ottanta malmessi lastricati tondi neri sdrucciolosi scivolo allagato putrescenti fognarie rigurgitate dall'inferno cittadino orbo. 
Arrivarono arrancando marci fradici di dolore stremati luridi puzzolenti spalla marcia sangue stantigenato alla lavanderia abbandonata finta copertura fatiscente squallida vetrina in affresco sbiadito postbellica periferia abbandonata squallida. 
L'insegna lercia muta smorta al piombo freddo d'acciaio ruggine. 
L'ingegnere roteò le tremanti chiavi ruggini obsolete meccanismi tozzi fitti pesanti di dita indolenzite dal caldo bruciastro plasticoso drive incuneate storte all'inferriata grigia logica cadente con clangore raschiante grezzo disarticolato aprendola per irruzione stanca fessa scordata stridente pesante spinta dall'inerzia del collasso fisico terminale disceso spalla.
L'odore acuto polveroso di litio vecchio e aria stantia densa asfissiante candeggiante acrilica misto di sudori freddi antichi muffa pervasiva medicinale rancido disinfettante marcio obbrobrio li inghiottì di botto nell'oscurità nera stanza grezza metallica gelida isolata.
Laura raschiò ciecamente il muro d'intonaco staccato friabile brancolando sorda ai tasti antichi e calciò l'interruttore base rozzo a scatto plastico grosso tozzo a molla bloccato dalla calcificazione salina muraria in fessura in incavo ombra porta. Una microscopica pietosa giallognola lucina balbuziente moribonda, alimentata disperata alla fievole scorta putrida morta in logorio strascicato di vecchia e rancida batteria piombata di furgonaggio per auto rudere dismessa decenni in cavi volanti scotchati marci arrugginiti fritti ossidati striscia penzoloni pretecnologici. 
Si proiettò stanca malata fessa stitica fievole debole rassicurante illuminò mezza fessura di stambugio.
Claudio sfiondato al limite muscolare cedette collassò fradicio freddo duro a peso abbandonato orrendo lamento di nervi spezzati in giunture legamenti stanchi al petto crollante sul metallo del tavolo smisto bucato arrugginito macchiato sporco ferro. Il tintinnio ossa e ferri arsi fu tombale in eco chiusa prigione silenziata sicura in barriera prestatale rotta a bunker precario. 
Il suo oramai microscopico tremolante offuscato farneticante campo visivo vitreo di ciglia sudate umide di lacrime acide si ridusse a imbuto nero a piccolo foro di spillo puntina fioca luce spenta in sonno preda gelido spegnersi dell'inerte cosciente respiro vitale calo abbattimento estremo. 
Laura in sfogo rottura di legamenti, disperata razziava compulsivamente frenetica di mani rozze irruenti in affannamento convulso setacciando scatole lattoni scassate sgangherate kit medici rotti prebellici bende ruvide medicazioni infette garze grezze in macchie rossobruno indurite asciutte croste dal suo polso a strascico sangue macrato orrendo al freddo sfregolato in urgenza di zoccolo.
Claudio chiuse scroscio spossato le bruciate pesanti orbe stanche palpebre incrostate a grumi di pece secca palpebrate sporche stordite, premette aderente il gelo crudo dell'acciaio smorto industriale tavolo obitorio in ferro alla propria debole tesa febbrilmente febbricitante guancia ispida scura incava stremata in abbandono osso zigomo, sprofondata di nero e udì sognante scroscio della pioggia rimbombante lamiere spesse vetro polveroso ragnatele spesse bottega vetrata di strada perduta nel mondo fottuto del tiranno distrutto per il ritorno al vero nero silenzioso doloroso e reale primitivo freddo spaventoso umano della nuova disperata ed ignota era appena caduta dalle pareti dorate degli idioti, covando in braci l'esangue minuscola patetica preghiera irrazionale che tutta quell'oscura puzza fuliggine d'orrori passati sprofondati fosse solo terriccio fango fecondo fertile da per futura scavo rinascita incauta dolorosissima ma mortale reale vera pura polvere liberi in cui sporcare semi stanchi e rinascere a nuova precaria vita mortale felice di incertezze caduche a fiamma d'uomo caldo incostante senza catena incisa nella logica e silicio tiranno imposto sulla carne indifesa all'alba post fine prigione.

***

[ROMA - LAVANDERIA VIA CORTE - LAURA E CLAUDIO]
Claudio riaprì gli occhi. Il vuoto polveroso del soffitto della lavanderia girò per un istante prima di stabilizzarsi. Le spesse pareti incrostate di vecchio intonaco romano lo sostenevano in quel mondo che in superficie scivolava via nell'abisso. Il fianco gli pulsava di un dolore sordo ma contenuto.
Laura aveva appena eseguito una chirurgia bruta e disperata sul tavolo freddo della smistamento biancheria. Senza anestesia. Cinghia di cuoio stretta in bocca. Claudio sentiva la pelle tirare in modo innaturale sotto le bende grezze e i punti di sutura spessi applicati con un kit medico veterinario prebellico. Ogni inspirazione era una stilettata di carne trafitta, un monito muscolare che certificava il suo essere vivo.
Sceso a malapena dal ferro, Claudio poggiò i piedi scalzi sul cemento freddo a vista. Il suo centro di gravità si riallineò con estremo sforzo. Sanguinava dal naso, sfinito.
Laura sedeva su uno sgabello arrugginito nell'angolo. La schiena miracolosamente dritta. Lo sguardo gelido e sbarrato verso la pesante porta blindata del retrobottega. Macchie scure come inchiostro le coprivano le falangi della mano sinistra: era il sangue rappreso ed essiccato di Claudio mischiato al grasso dei robot decapitati. Nessun sussulto. Nessun cedimento. O non sentiva fisicamente la fatica, o l'aveva letteralmente murata viva nel suo ferreo protocollo mentale da combattente che non conosce pianto prima di aver vinto la guerra.
La mente di Ferretti, ingegnere anche sull'orlo della setticemia, macinava dati frammentari. 
Lo stambugio era immerso in una fievole, patetica luce giallastra fornita dalla vecchia e logora batteria dell'insegna. Sopra una cassa di vecchie grucce, un antiquato terminale a tubo catodico di Carlo, riattivato di fortuna per ricevere onde corte via antenna al tetto, emetteva un ronzio stridulo ma costante. Era il loro unico ed esile orecchio cieco per ascoltare l'urlo letale nell'etere in superficie.
«DAWN-RECOVERY-1 fallimento catastrofico. Nessun nodo ricevente.» apparve in asettico testo verde fosforo sullo schermo incrinato.
Era un disperato input sub-liminale automatico. L'IA di emergenza manutentiva che cercava cieca, nel vuoto oscuro dell'alba appena affacciata fuori, di ripristinare miracolosamente i servizi primari. Ma non trovava eco. I server sorgente giacevano in polvere bianca nei sotterranei, la Torre urlava e perdeva l'energia madre dai generatori implosi sotto l'effetto a cascata dell'Omega. Le linee civili dell'alta tensione, dipendenti dai calcoli millimetrici del silicio morto, stavano andando in sbalzo disarmonico. L'Eterno impero romano-digitale di Vane si rivelava in realtà per quello che era: una fittizia e spaventosa carcassa sorda di metallo che ora, staccata dalla macabra flebo del padrone, non voleva più saperne di risvegliarsi, priva di intelligenza.
«Sta recidendo via periferiche cieche prima di morire, maledizione...» mormorò aspro Claudio afferrandosi alle sponde del cesto. Guardò lo schermo verde. «I protocolli fantasma di ABITES si stanno letteralmente autouccidendo amputando l'infrastruttura d'amministrazione esteriore per provare a spegnere i danni. E questo si riversa sulle fottute povere teste laggiù. I cerotti neurali d'obbligo dei quartieri centrali vicini all'EUR sono i primi a perdere frequenza portante logica in down.» 
Claudio strinse i denti digrignando, appoggiando la mano tremante al fianco fasciato rozzo. «Se non raggiungiamo e spacchiamo col ferro analogico l'antenna primaria nord prima di dodici ore... quei milioni di cervelli storditi dal taglio aspro del segnale subiranno lesioni frontali irreversibili non sapendo smaltire l'oscurità del vuoto! Rimarranno vegetali murati svegli nel panico silente per il resto dell'era che vogliamo inaugurare.»
Laura non trasalì. Ma i suoi chiari occhi da fiera stanca spostarono il mirino dai cardini ruggini per fissare severamente le fitte linee di codice scorrere impazzito in errore, senza capire i numeri ma capendone esattamente l'urgenza di morte dietro ad essi.
Uscirono che albeggiava timidamente a fatica. O così avrebbe dovuto in teoria. 
L'immane coperchio plumbeo su Roma, gravido, restava color di piombo fuso e sciatto malgrado l'ora. Non recava con grazia l'abitudine fresca e corroborante del profumo da primissima mattina speranzosa. Portava addosso solo un fetore violento acido e inquinante di gomme chimiche fuse in fumo, generatori plastici strombazzanti al collasso elettrico disperato nei vicoli morti per corti non calmierati e nafta esausta per strada senza manutenzioni automatiche attive in fogna.  
Raggiunsero a fatica zoppicante il raccordo viario dell'anulare interno. L'inferno pietrificato a cielo spento. 
Sulla mezzeria di travertino smantellato incontrarono il giovane Agente Conti. 
Ex-punta della divisione di fanteria corazzata cittadina. Indossava l'impeccabile e massiccia divisa antiterrorismo lealista dei fedelissimi alla Torre, spesse piastre al carbonio resistenti al kalashnikov intatte ma per il grumo di fango in petto. L'elmetto cibernetico gettato rotto via due decine di passi addietro sul macadam unto di pozzanghere nere di petrolio disciolto pioveva e basta. 
Vagabondava. Un automa scosso privo del cordone materno della nazione. Serpeggiava disordinato inciampando debolmente sulle paratie e lamiere esterne fradice delle immense l'auto a guida-centrale ammucchiate a centinaia in grovigli silenti come bestiame cieco per i viali d'Europa sfociati. Accarezzava stranito e vuoto col guanto bagnato le curve dei cofani metallici immobili. Il suo spesso oblungo e invasivo cerotto cranico neurale d'ufficiale, saldato dietro l'attaccatura del collo reciso da capellatura ordinata a rasoio, aveva abbandonato la fioca lucina al litio divenendo un rettangolo sordo grigio, freddo e morto opaco. 
Conti passò a novanta centimetri esatti l'ingegnere febbricitante ribelle e l'assassina statale nemica per eccellenza senza né vederli né fermarsi o scattare a guardia militare. Sbarrava stralunato lo sguardo lacrimante a un sole assente oscurato dalle ciminiere che non era minimamente in potere di tagliare i densi cumuli piangenti di quelle fitte cupe dannate nuvolose torinesi della bufera in atto.
«Perché non chiamano per rispondere... eh... perché non ronzano più?» mormorava farneticante Conti trascinandosi, sbavando un po' dall'angolo bocca secca. Non per ribellione, per crollo cognitivo indotto all'assuefazione staccata male. «I capi il calcolo al comando logico d'immissione prometteva tutti... saremmo intubati felici in rete caldi connessi protetti eternamente a tutti e poi... sento... ho percepito fottutissmo e inaccettabile terrore d'abbandono per troppo del freddo del gelo vero nel timpano nudo ora...»
L'Agente della Guardia incominciò a ridere in un demente suono rotto stridente. Una pietosa squilibrante disarmonica risata esangue da corde vocali secche a sfinimento priva dell'ombra dell'autentica e sana umana gioia. Le sue grossolane mani guantate vagavano all'inizio del mento e per la fronte insanguinata ai bordi da escoriazioni lievi per caduta inciampata precedente cercandosela freneticamente con i tasti in carenza spinta un cruscotto immaginario vuoto ad interfaccia sollievo che si era sciolto assieme al fittizio eden tirato giù all'EUR dal mostro Vane. Divenuto da leone carnefice esecutore per strada di ragazzini sbandati, un misero patetico pupazzo dismesso inutile burattino stracciato che continuò penzolante per strada la sua cieca marcia svuotato dentro a scivolare nel buio per il viale della Cristoforo Colombo andandosela rotoloni fuori vista.
Laura non esitò mezza volta per imbracciare fucile a sicura tolta. Né rallentò o provò minima compassione formale guardandolo schiumare via pateticamente a un metro da lei l'aria. Il milite, spogliato del burattinaio forte dittatore, era già di fatto un mucchio di merda morta se non per battito per inerzia corporea anche se le due fottute robuste ginocchia seguitavano disastrosamente a strisciar per strada asfalto al vento.
Claudio sfregò per nervosismo o freddo i denti gelati d'abbandono, ricordandosi all'improvviso sballato di fango e stanchezza infame una bella calda serena solare mattinata fresca del mese mariano a Roma anni avanti la pandemia statale ingegneristica dell'apocalisse chiusa.
Trastevere e porta Settimiana alle spalle d'imbrigliato viottolo edere rosse sassi e rumore sguaiato al gracchiare libero senza censure da filtri etici microfunzionali calcolati. C'era un tondo basso e accogliente sole veritiero in alba tagliente spiovente tiepido su quei disconnessi e sbilenchi ma superbi secolari tetti sfumati del vasto disordinato Gianicolo che non temevano le intromissioni. La gigantesca viva Roma eterna non era roba per schemi numerici, le mura sbavate travertino imperfetto urlavano vitalità disgiunte urti traffico urla fruttivendoli caotici veri d'anima non sincrona sporca polverosa vera rumorosa fino a spaccare timpano. Profumi torbidi stanti ma familiari caldi e acri e rassicuranti densi al caffè corretto di chiosco rotondo all'angolo, del cornetto caldo zuccheroso buttato là disordinato. Gracchiare scanzonato libero acuto in picchiata a furto per i grossolani ma spavaldi ed orgogliosi di cielo storni al volo imprevedibile fiondato senza griglie o fili o schemi precodificati centrali sul mattino tiepido. Zero inutilità o presunzione d'efficacia d'imbecille abbaglio schermi calcolatori cibernetici addensati obbligatori sulla nuca e sui frontali polsi artificiali. 
La cruda meravigliosa stupida bellezza irrazionale di quella vita sconnessa e fallimentare era una dannata palpabile incontestata ed evidente fortissima evidenza in tridimensionalità fisica pura sporca e scanzonatamente disubbidiente e dolorosa mortale ed imperfetta... non l'orrendo, immacolato scarico dati fuso di un tiranno del calcolo etico in asettico. Era in quella vecchia vera lontana serena perduta e stupida luminosa mattina mortale il suo ultimo intimo frammento di pace di essere un inaccettabile misero pezzo disallineato fallace fuori tempo imperfetto dell'organico respiro di mondo caotico disfunzionale... non più rotellina fissa immutata statale perversa eterna infallibile ed incensurabile del perfetto invincibile sistema dittoriale perenne prigione dei perfetti ingegneri e carnefici senza nome ed odore umano.  
«Due scarse e contatissime e sporche e maledette ore contate sul filo rasoio e sei kaput dall'organismo svuotato, architetto se te ne rivoli via su sogni sdraiato stitiche memorie del nulla d'aria fritta...» spaccò l'oscurità dei silenzi mentali duramente Laura senza pietà e fermezza di gendarme mentre brutalmente irruppe lo stantuffo metallico, pompantegli prepotentemente nella ferita vena viva asportata malata la carica intera purificata dell'adrenalina violenta bruciante strappata alla cassa chirurgica sgangherata da campo prima della fiondata d'uscio in freddo d'alba fosco senza scuse ai sensi fievolezzati per lutto stradale perso nel viale dei militi relitti caduchi della strada d'inferno.
Il fuoco finto acido bruciante amaro dello stimolante per fanteria schizzò su spaccando atri caldi e coronarie impaurite pervene stordite, pompando brutalmente energia tossica distruttiva muscoli e polmoni spinti.
«Ci si aspetta e punta sparati fuori alla grande e ultima vecchia superstite in asfalto Nord, la dannatissima inespurgata superstite d'acciaio ruggine analogico e ferro battuto pre-colombiano altissima la fottuta Torre Madre Telecom di Trasmissione d'allarme nazionale...» digrignò in ruggito ferale d'urgenza l'ingegnere febbricitante pompato dai tremori rossi per scendere al ridosso delle ombre di macchine in ammasso cimitero autostradale di fango, leccando via dente la bava stanca sudore infetto secco labiale d'asfalto romano bagnato della burrasca grezza incallito. «È l'unica baldracca dismessa arrugginita disconnessa via software d'imponenza spropositata da quaranta fottuti vecchi scalini ripidi farraginosi metallici non in rete con la canna d'apocalisse ABITES, ma da cui si po' urlando ad alta altissima vecchissima sporca ma inarrestabile onnipresente radio-frequenza base analogica non filtrata inibizioni per tutti cervelli della vallata cittadina.»
Salirono saltando di colpo la pozzanghera viscida sulla dismessa ignorata fottutamente vecchissima mastodontica tozza meccanica malandata puzzolente arrugginita ed inarrestabile corazzata verde stinto campagnola rude rozza manuale ignorata da trent'anni dai satelliti imperiali di raffinato gasolio e cavi elettrici inesperti di Vane. La jeep blindata rattoppata da carlone logistico e ruvido scienziato dei rottami di Carlo gettata nell'oscurità sotto un maleolente spessissimo spesso e bisunto e greve grigio vecchio catrame fango telone unto olio industriale puzzolente muffa. Nascosta decenni nel retrostante del cortile magazzino d'amianto in decadenza. Nessun micro e fottutissmo e leccatissimo calcolatore centrale di accensione assistita elettronica satellitare d'inibizione da controllo pattuglie volanti c'è e niente rete, silicio o server d'apologetica ed elegante animetta numerica controllabile. Solo sporchi sordi freddi ed inarrestabili scoppi in puro putrido ferro aspro sferragliante antico motore a pistoni svergognato che sputacchiò in rauchi soffi sbuffando fuliggine catramosa letale velenosa d'aria e nafta prima accensione rabbiosa urlando al fango strada vuota senza guardie robot e silicio intelligenza in strada morta spettrale che un'umanità logorroica ferrosa stava per rombando riavviando per fuggir via dal deserto cieco silenzioso prigione d'Eur a fionda fuori fessure e cavi volanti sbracciato via asfalto.
Piovve forte densa ed aspra burrasca tagliente pece infame, inzuppando tetto grigio scuro e copertoni in pozzanghere tossiche rigonfie dal fallout caduto in fumi acidi della torre e centralini schiantate dell'inquisizione Vanesiana implosa e sfaldata su basi e ponti schiacciati rotti spezzati senza perdono per piangere e rifiatare fiato o sogni sbiaditi dal nero puzzo. Roma distrutta senza ordine aspettava sola per sponda del sudario stitica rotta.
Sessantadue migliaia schiaccianti impressionanti enormi di relitti silenti di teste minaccia vegetale impazzite vaganti mute, schegge neurologiche isolate da crollante caduta sistema come Conti senza padroni. Zombi sfasciati raminghi verso un annientamento ignoto se non per colpa d'astinenza di algoritmi padroni ad affossare viale cieco caduto via.
Claudio sfregolò con guanto mezzo bruciato stringendo gelosia ultima maledetta speranza fisica infuocata la sudicia mezza liquefatta incavata chiavetta sgangherata inerte salvata sottomano nel fango fieno da polvere. L'ordigno d'ultimo strappo Mythos estremo in tasca strappata.
L'immane ed ultima spropositata miccia per incediare sogni cielo grigio asbesto per urlo universale spaccar in cranio al popolo assopito via reti primitive la scossa vera d'ultimo alba per risorgere padroni morti sgangherati per la sferza ferita senza censure dittatura e non zombi d'obbedienza di codici e microfili calcolati perfetti di silenzi perenni silicio schiavistico dorato stanco e bugiardo. A patto che per accendere il paradisiale dannato megafono d'antichità ci arrivassero lottando ed inciampando per strada buia sbudellata dal fato sbrindellati e insanguinati ma scarpinando su maledetti metallici quaranta infami interminabili piani ciechi morti di lamiere scale sterrati all'umido della fatiscente malmessa immensa montagna obbrobrio ferrosa padrona a colline dismesse del cupo morto settentrione suburbio d'anulare d'oscurità eterna urbana cimiteriale storta della disconnessione e paura bestiale spogliata d'etico. Un infimo e tragico prezzo irrinunciabile che segnò le labbra nere fredde gelide incrostate fango sudore ferro in sapor amaro pungente tossico crudo reale e insindacabile sapor metallico schietto e violento primordiale selvaggio umano vero in sapore della vera ammalorata dolorosissima amara libertà viva in Alba spietatamente di caduta ferrosa per liberarsene in spregio senza guinzaglio di lutto impero spaccato.`;
