export const chapter39Content = `Il furgone si era schiantato contro il palo della luce e il cemento lo aveva aperto come una scatola di latta. Il metallo era tutto piegato e il muso del veicolo guardava verso l'alto, con le ruote che giravano nel vuoto. Il logo della televisione era rovinato, un pezzo di vernice blu che si staccava a fette. Claudio sentì la nausea risalire, insieme all'odore di benzina bruciata che rendeva l'aria pesante. Laura camminava davanti a lui, pronta a sparare mentre si sentiva il ronzio dei droni in lontananza. La porta del furgone era aperta. Una telecamera rotta era a terra e dal buio del furgone usciva una mano piccola, con le unghie mangiate. Era immobile e le dita toccavano l'asfalto freddo. Claudio cercò di non guardare. Il fianco gli faceva un male cane e sentiva il cuore battere proprio sulla ferita. Continuarono a camminare.
Sul tetto del furgone c'erano tre buchi netti, fatti dai proiettili. Claudio guardò verso nord per cercare di respirare aria più pulita. Il dolore al fianco non lo lasciava mai, era un peso che lo schiacciava. Laura continuava a camminare e non diceva nulla per non stancarlo ancora di più. Fecero sessanta metri, poi altri sessanta, con gli stivali che facevano rumore sulle pietre. Svoltarono l'angolo. I lampioni erano quasi tutti spenti o rotti, si vedevano solo le luci rosse di emergenza che lampeggiavano sugli edifici abbandonati.
Una donna era ferma davanti a una vetrina rotta. Aveva un pezzo di gesso in mano e scriveva su un cartone nero. Sotto di lei c'era un uomo con il braccio fasciatissimo e sporco di sangue. La donna aveva un camice verde sporco sopra il giubbotto di pelle. Aveva le braccia forti di chi lavora sodo. La sua borsa era aperta a terra e si vedevano bende e medicinali messi in ordine in mezzo al caos della strada. Claudio si fermò, appoggiandosi sulla gamba sana. Respirava a fatica e sentiva la polvere in gola. La donna li guardò arrivare con gli occhi spalancati, ma non sembrava spaventata. Aveva visto troppo sangue per avere ancora paura.
«E' una ferita da arma da fuoco,» disse la donna con voce ferma.
«L'abbiamo già cucita,» rispose Laura senza abbassare la pistola.
«Quanto tempo fa?»
«Sette ore.» La medica finì di fasciare l'uomo con un nodo stretto. Si alzò in piedi e le ginocchia le fecero rumore. Guardò Claudio, notando come camminava male per il dolore. «Sto cercando di andare all'ospedale, ma l'ospedale non esiste più. Non funziona più niente lassù. Verrò con voi, posso esservi utile.» Mara, la medica, si mise in mezzo a loro e la sua borsa sbatteva contro la gamba mentre camminavano. «Ho visto cosa fanno quei droni. So da dove arrivano. Voglio aiutarvi a fermarli.»
Un ronzio brutto arrivò da nord. Era il rumore dei droni che stavano arrivando. Laura si fermò in mezzo alla strada. «Dobbiamo correre!» Mara correva facendo un rumore secco sull'asfalto. Claudio trascinava la gamba e il dolore alla ferita era diventato un fuoco che gli bruciava tutti i muscoli. Il primo drone apparve sopra i tetti come un uccello di ferro. Iniziò a sparare sull'asfalto e i colpi colpirono la strada proprio vicino ai loro piedi.
Claudio si buttò verso destra, dentro un portone aperto. Sbatté la spalla contro il legno vecchio e sentì una fitta che gli arrivò fino al collo. Rotolò sul pavimento e sentì la pelle bruciare. Laura entrò subito dopo con la pistola puntata verso fuori. Il drone passò sopra di loro come un'ombra fredda nell'aria rossa dei lampioni. Poi tornò indietro.
Mara aprì la borsa e le sue mani si muovevano veloci. Controllò subito la ferita di Claudio. Non disse nulla, ma mosse la testa per far capire che la fasciatura teneva ancora per miracolo.
«Sono due,» disse Laura con la voce che sembrava ghiaia. «Forse tre. Aspettano che usciamo fuori.»
«C’è un’uscita sul retro,» indicò Mara verso il buio del corridoio.
«Lo so,» disse Laura. «Ma dobbiamo attraversare cinquanta metri di strada scoperta per arrivare al sottopasso.» Controllò il caricatore della pistola, sentendo il peso del metallo. Era sicura che i proiettili bastassero. «Voi due andate avanti. Io vi copro.»
Uscirono di corsa. La strada vuota faceva paura. Il drone li vide subito e reagì. Claudio spinse le gambe più che poteva, ma il fianco gli stava cedendo e la ferita perdeva sangue nuovo. Il primo colpo esplose a un metro da lui e alzò una nuvola di polvere che gli tolse il respiro.
Il secondo colpo colpì Mara. La dottoressa cadde a terra come un sasso, mentre si sentiva il rumore del drone che si avvicinava. Laura non si fermò. Prese Claudio per il colletto della giacca e lo trascinò avanti con una forza incredibile. Lo portò nell'ombra del sottopasso e il drone perse il segnale perché non riusciva a vedere attraverso il cemento.
Dall'altra parte videro il quartiere Nord: era tutto buio e silenzioso. Alcune persone uscirono dai portoni con le facce sporche e le giacche da pompiere. Lanciarono dei piccoli apparecchi per disturbare i radar dei droni. Iniziarono a sparare con le mitragliatrici e si sentiva il rumore del metallo che colpiva il ferro. Laura guidò Claudio verso l'ombra della Torre che svettava contro il cielo grigio, una croce di metallo nel cuore della città.`;
