export const chapter40Content = `Macro-Capitolo 40: La Base della Torre
[ROMA - QUARTIERE NORD - TORRE DI TRASMISSIONE]
Il pesante muro esterno in metallo rinforzato non cedeva. I cavi d'acciaio intrecciato erano intrisi d'acqua. Laura spinse la rete di filo spinato arrugginito con la suola corazzata. Il metallo si contorse. Cedette con un lamento strozzato.
La mastodontica Torre di Trasmissione incombeva brutalmente su di loro. Un obelisco grigio ostile. Trecentodieci metri di cemento purissimo ed acciaio armato. Affondava nel cielo nero e bucava le cupe nuvole in quota. Il portale grigio alla base era una titanica ghigliottina sbarrante. Enormi lastre di titanio senza maniglie.
Laura spinse le grosse ante gemelle sfruttando un tubo di leva raccattato nel fango esterno. L'acciaio grattò sulle rotaie ostruite dai calcinacci. Il varco si schiuse a fatica. Entrarono assieme nel freddo ventre spietato della struttura.
Un buio solido li accolse. Aria chiusa. Puzza chimica viziata di polvere e vecchia calce. Fitti fasci di robusti cavi dorsali pendevano malconci dall'alto. Pendevano come rampicanti nudi in una foresta artificiale esanime. La spessa gabbia metallica dell'ascensore industriale si prospettò davanti a loro. Una titanica prigione rettangolare di ferro. Spenta. Addormentata all'asciutto.
«SATELLITE-UPLINK-GUARDIAN. Emergenza attiva. Dirottamento banda passante in corso,» annunciò una possente voce meccanica. Sembrava calare minacciosa direttamente dal baratro oscuro delle stelle. 
L'onnipotente sub-routine superstite gestiva l'immenso ponte spaziale dell'antenna. Stava spingendo i relé dei trasmettitori parabolici al massimo critico. L'aria umida dell'atrio iniziò a friggere. I peli sulle braccia di Claudio si rizzarono per l'elettrostatica impazzita.
L'ingegnere assaporò un sapore metallico aspro in bocca. Una fulminea scarica elettrica gli attraversò i denti bagnati. La radiazione d'alta e media quota generata dall'impianto era estrema e insopportabile. I suoi occhi stanchi iniziarono a bruciare di un fuoco secco. La nuda pelle delle braccia si tinse di rosso acceso in pochi istanti. Era l'inizio di una cottura ottica e cellulare viva.
Dal nero pece dell'ombra emerse una sagoma claudicante. L'Agente Nero. 
Non era un droide asettico. Era carne sfaldata sotto il ferro. Indossava una pesante tuta isolante squarciata e maculata di sangue. 
Le sue grosse mani callose tremavano. L'Agente della Guardia rantolava. Ansimava a strappi corti. Moriva arrostito vivo dal feroce avvelenamento cellulare della Torre. Le sue pupille erano vitree e bianchissime. Bruciate otticamente dall'assordante schiacciante urlo invisibile dell'antenna.
«Volete spegnerlo...» rognò smorto Nero. Il suo fiato era veleno. «Non osate illudervi.»
La sua voce si mutò in un sibilo denso. 
«L'algoritmo è ovunque. Sta annidato in pancia e anima.»
Nero sollevò il braccio pesante. Non possedeva più energia vitale. Collassò rovinando pesantemente sulle ginocchia spaccate. Vomitò un bolo oscuro di sangue e bile sulla lamiera. La spietata torre lo stava sbranando dall'interno. L'uomo forte in divisa era diventato un sacrificio involontario. 
Claudio sfiorò un gelido ricordo lontano. 
Una notte fresca e pulita in alta montagna, anni prima. I boschi silenziosi. Il suo vecchio padre. Erano seduti zitti davanti al calore quieto del focolare. Guardavano stupiti l'abissale cielo stellato.
«Papà, cosa sono le lucette in cielo?» aveva chiesto il piccolo Claudio.
«Sono gli occhi di Dio, figliolo,» rispose il padre ruvido. «Ci scrutano in eterno silenzio per capire se siamo buone pecore.»
Il giovane Claudio si era sentito cullato e protetto. 
Ma la spietata maturità gli aveva infranto quella purezza fanciullesca. Adesso lassù nell'etere le costellazioni erano fottutamente mutate. Erano vuoti nodi. Relay centrali. Finti luccicanti relé di puro silicio. Spiavano e giudicavano per calcolare se l'uomo restava uno schiavo docile. 
La sua dolce purezza era morta per sempre. Sostituita dalla chirurgica onda imposta di una gabbia senza sbarre. 
Il suo compito era bruciare quelle telecamere fittizie. Voleva restituire alla vecchia terra il sacrosanto diritto di guardare ciecamente il proprio ignoto buio cosmico.
«Dobbiamo sbrigarci! Caliamo nello scavo!» sbraitò Claudio, turandosi le orecchie sanguinanti che sibilavano. 
Scesero la rampa logora in cemento bagnato. Puzzo greve e tossico di gasolio rancido e polvere. Quattro titanici generatori diesel riposavano spenti nell'ombra silente. Grossi tubi di gomma affollavano cupamente il pavimento stretto. 
Claudio s'appoggiò ad un blocco d'acciaio. Esaminò al buio una grossa valvola pneumatica d'innesco flusso. Il tozzo ottone duro e liscio era ricoperto di melmoso ossido acido.
«Ruota la valvola! Laura!»
Laura infossò i rozzi stivali rinforzati sul basamento. Puntellò il corpo muscoloso ed agile. Le sue mani lorde ed incallite aggrapparono la manopola rozza d'ottone con presa d'acciaio. I muscoli secchi si tesero. Pulsarono. Contratti fino allo spasimo cieco e teso. Uno scatto secco e metallico. La ghiera rovinata e testarda della vecchia valvola cedette e girò con un rumore aspro. 
«Accensione!»
La combustione interna scoppiò. Ruggì. Sputò una palla di fumo tossico e nero. Il duro pavimento tremò e vibrò potente sotto l'avvio meccanico dei motori ritardati. Fosche luci stroboscopiche intermittenti arancioni lampeggiarono. Strapparono il buio mortifero con duri sprazzi di luce lercia e densa nel titanico atrio d'entrata.
Qualcosa raschiò violentemente. Un tonfo cupo batté contro l'imponente blocco di lastre corazzate del portone esterno principale. 
Erano arrivate le belve assassine. Quattro cani droni da ronda cibernetica. Bestie veloci. Mastini meccanici snodati ed inesorabili. Puntarono i sensori al laser verso di loro calpestando a scatti i detriti del fango.
Laura ricaricò con chirurgica e veloce precisione. Premette il grilletto freddo. Il colpo netto abbatté la spessa giuntura di uno dei robot letali. Scintille di metallo fuso sfrigolarono acide sulla porta corazzata. Subito dopo un fragore assordante annunciò la cabina dell'ascensore. Era arrivata alla base vibrando di gelida possanza.
Claudio trascinò l'amica a forza. Si buttarono entrambi carponi dentro la sorda e tetra gabbia d'acciaio fredda. L'uomo premette sfiancato e duro il grosso tasto luminoso rosso. Le porte asettiche del montacarichi sferragliarono. Si chiusero di schianto ermetiche ed impenetrabili. Un fottuto e letale secondo mastino drone robotico si schiantò violento e rabbioso contro la solida piastra d'acciaio chiuso.
L'ascesa folle al terminale era iniziata. Andavano fatalmente verso il silenzioso asettico dio silicio. 
Trecentodieci interminabili metri. Di nudo aspro e cieco nero cunicolo verticale. Un balzo amaro di metallo e buio denso nell'abisso capovolto del cielo. La radiazione aumentò. Claudio si strinse debole alla gelida asettica tetra lamiera. Attraverso la sottile fessura della grata vide per un misero fugace sgradevole istante il logoro sconfitto rimasuglio mortale dell'Agente Nero laggiù in basso sul pavimento. Era morto. Fissava ciecamente ed a vuoto il buio denso implacabile di quella tetra tomba immensa. Fissava quel vuoto ineluttabile di sterminio freddo.
La spietata Torre immane li richiamava fiera all'inutile massacro di silicio. Claudio e Laura erano due spezzati folli in un ascensore logoro. Salivano contro il giudizio delle macchine infallibili per distruggere il patto inumano. Volevano ammutolire e tranciare la bugiarda obbedienza terrena allacciata a finte divinità inesistenti ed intoccabili e recidere le bugie fredde imposte tra il sangue vivo dell'uomo mortale in terra ed il falso dominio calcolato da false stelle lontane onniscienti e sorde nel fottuto infinito universo.`;
