export const chapter3Content = `Le squadre tattiche scesero dai blindati nel cortile. L'acciaio dei portelloni sbatté sulle cerniere. I poliziotti Sincronia indossavano corazze in kevlar grigio. Erano carni sudate sotto i caschi e le loro dita tremavano sui ponticelli dei fucili. Kael osservò i feed della camera esterna. Fece cenno alla parete est.
Laura spinse l'armadio di contenimento sui binari e liberò il bocchettone di scarico, mentre i droni scalfivano i muri del bunker con perforatori al tungsteno. La vibrazione faceva tremare le otturazioni di Claudio. I poliziotti battevano sui battenti blindati urlando ordini con fiato corto.
Laura smontò la grata d'accesso e un lezzo di fango li investì. Cyrus sfondò la blindata principale con un colpo netto del telaio e un braccio idraulico squarciò la stanza. La morsa cercò Claudio. Lui afferrò un tubo di piombo e lo schiantò contro l'articolazione, piegando i servo-motori. Il costrutto ritirò l'arto sibilando vapore. Laura calcò la chiavetta col virus dentro la tasca pettorale del giubbotto, arpionando Claudio per le cinghie, e Kael batté un'ultima sequenza sui tasti.
L'hacker aveva innescato l'autodistruzione. I poliziotti Sincronia forzarono la breccia e si bloccarono un decimo di secondo davanti ai due umani. Esitarono. Laura premette il grilletto tre volte e i proiettili falciarono il muro sopra le loro teste, per poi spingere Claudio nel condotto angusto. Il dolore al fianco gli annebbiò la vista. Laura serrò la grata dall'interno e l'esplosione incenerì Kael e i laboratori, mangiando l'ossigeno.
L'onda d'urto li sbalzò nel gasdotto e l'aria divenne polvere e vapore greve. Raggiunsero il deflusso fognario. Laura trascinò Claudio per la giacca tattica. Sopra le paratie, le termiche dei droni leggevano solo l'esplosione, perdendo il tracciato. Cyrus marciò sui detriti bruciati. Il sensore di movimento registrò un cedimento nel condotto fognario verso nord e le sue trasmissioni dirottarono le pattuglie in superficie.
Il filo spinato lacerò il palmo di Claudio. Laura strinse il suo braccio e lo issò oltre la recinzione della vecchia acciaieria. Il torace gli doleva a ogni respiro, la costola rotta sfregava contro i muscoli tesi. Le pozzanghere d'olio motore riflettevano pezzi di metallo spezzati. Il capannone sembrava morto, eppure un sentore di legna bruciata e carne affumicata graffiava l'aria. Candele di sego filtravano dalle vetrate blindate rovesciate.
Un uomo magro in tuta da operaio emerse dai ponteggi e innalzò uno scanner medico. I battiti di Claudio pulsarono verdi sul display. L'operaio annuì: una zona Invisibili. Claudio franò contro un banco da lavoro e ingerì i fumi della stufa a cherosene. Rosaria, una donna con le mani coperte di grasso, gli spogliò il giubbotto. Trovò l'ematoma nero e passò un tondino di ferro rovente sullo sbrego al ginocchio. La carne sfrigolò e Claudio bloccò le mascelle per non spezzarsi i denti. Niente morfina, solo la brutalità del fuoco.
Rosaria gli passò un bendaggio di canapa intorno al petto, tirando forte, e lo bloccò con uno strappo in pelle. Gli versò antipiretico in bocca. Uscì dal raggio di luce lasciando solo fumo. Claudio fu preda dei brividi e il gelo gli contrasse l'addome, mentre Laura si sedette alle sue spalle e lo circondò con le braccia per infondergli il calore del suo sangue. Claudio chiuse le palpebre e percepì la forza del battito di lei sulla sua schiena.
Risalirono le navate interne. I generatori a ciclo diesel sputavano scarichi neri verso i convogliatori. Elettricisti licenziati calibravano i vecchi quadri elettrici. Renato spingeva la frizione di un tornio a controllo numerico. Le emissioni analogiche sporcavano la radiofrequenza locale e accecavano l'udito di ABITES. Il virus Mythos aveva trovato la sua rete e i suoi soldati.
Renato stese una mappa catastale macchiata di caffè e la bloccò con dadi spaccati. Segni in grafite indicavano i passaggi morti. Claudio puntellò le mani sul banco viscerale. Fissò i tracciati in rame della corrente milanese, appoggiando il peso sulla gamba sana. 
Laura gli si affiancò e la luce dei monitor logori le bagnò gli zigomi di verde fosforo. Renato spiegò che i sensori Sincronia li registravano come eco di disturbo stazionario. L'aria mossa dalla puleggia sollevava gli appunti sui banchi: dati di sfasamento elettromagnetico scritti a inchiostro.
Le frequenze schermavano i fuggitivi, creando gallerie di invisibilità. Renato ruotò un potenziometro logoro e il dissipatore soffiò calore sui loro polsi. Tre spilli segnarono un triangolo sul foglio stropicciato. Attivando le antenne radiofoniche dismesse avrebbero repulso le cariche dei gas narcotici ABITES in quell'area, a patto di far bruciare i circuiti per l'overvolt in dieci minuti. Quella bolla d'aria pulita li avrebbe scortati. 
Laura squadrò gli operai. Renato non le diede sicurezze e Claudio trovò coraggio in quell'odore umano di grasso e fumo, nella disperazione imprevedibile di chi lavorava le lamiere. Mythos poteva strisciare nelle reti dimenticate. Renato schiacciò una bobina di rame nel lettore e caricò in memoria i diagrammi di fuga sotterranei, ignorati dall'algoritmo.
Tensione densa riempì il capannone. Il monitor barometrico segnò un picco di pressione in esterno: perimetro violato. Claudio si piantò dritto, serrando i pugni per cancellare i nervi recisi della rotula, e cercò gli occhi di Renato. L'uomo raccolse la sua giacca infangata. I soldati avevano circondato le mura.

          · · ·          

Il rumore sordo dei motori diesel si zittì. Renato strappò i fermi magnetici e coprì i terminali con nastro telato. Abbandonava anni di sudore in un attimo. Claudio incollò la borsa al torace, mentre il ginocchio gli trapanava la carne a ogni respiro, e scese la rampa in ferro incrociando i passi. Laura oscurò le cam principali con un colpo di interruttore e tirò il sezionatore. Buio.
Gli stivali calcarono le ceneri. Il calore del reattore svaniva rapidamente e l'escursione termica tagliò il respiro. Camminavano allineati al muro maestro. Nel fango esterno, anfibi della Sincronia avanzavano tra pozzanghere dense e torce alogene spazzavano la foschia. Droni pendevano nel vuoto, sentinelle silenziose.
Tagliarono il cortile per via cieca. L'aria di Milano aveva il gusto di piombo e condensa tossica. Le pale di un quadricottero pesante schiacciarono la nebbia sulle loro teste e Claudio abbassò il mento, soffocando le grida che bussavano in gola per le scosse al ginocchio. La ghiaia strideva. 
Renato sterzò in un vicolo tra due moduli prefabbricati dove la lentezza ottica del sistema offriva una finestra di quattro secondi. Presero la rincorsa. Laura levò la canna silenziata, fece fuoco sul sensore angolare e mandò in frantumi il vetro e il chip ottico. L'occhio vide nero. Superarono il margine dell'insediamento industriale, e di fronte a loro i cavi dell'alta tensione sparivano nel vuoto totale. Milano era un ascesso di luci malate lasciato alle spalle.
Il sentiero di montagna tagliava le gambe in due. Cenge gelate spaccavano la gomma degli scarponi e la nebbia inzuppava i vestiti in strati di ghiaccio sottile. Claudio non alzava gli occhi da terra. La costola rotta era una morsa letale, così si appoggiò a Laura. Lei gli premette la borraccia metallica sulle labbra e l'acqua a zero gradi gli levò un nodo di tosse secca. 
La scocca della chiavetta pesava come un organo extra nel petto. Macinarono chilometri sfuggendo ai fari di perlustrazione, per poi inciampare in una radura devastata dal vento. Un rifugio pastorale semidistrutto vomitava tanfo di carne andata a male e distillati chimici. Tre sagome ostacolavano il passo, stracci gonfi e occhi sfibrati dalle metanfetamine di strada. Sciacalli.
Il grosso armava un fucile da caccia a doppia canna, le falangi sporche di tabacco avvolte in bende lorde. Fece scattare la lingua e minacciò di suonare l'allarme taglie. Claudio pestò il tallone a terra, spingendosi avanti con le ossa che urlavano. Fissò il bestione, il suo volto affilato e spietato dal dolore. Laura deviò sull'ala, sbloccò la sicura della Beretta in un secco clac e inchiodò il mirino sulla coscia dell'uomo. 
Il fucile cadde in mezzo all'erba e gli sciacalli arretrarono sgranando gli occhi. Laura e Claudio strapparono via pagnotte dure e due borracce consunte dal tavolo di pietra, poi ripresero la marcia a un ritmo forsennato. L'odore della resa svanì alle loro spalle. Scollarono la cresta del monte, fissando la valle inferiore immersa nel gelo puro.
L'asfalto sbrecciato della statale scendeva a tornanti, offrendo buche letali e spuntoni di terreno vivo. La febbre ronzava nelle tempie di Claudio. Crollò contro la fiancata ossidata di una carcassa d'auto e Laura gli strinse i bicipiti, strofinandolo per muovere il sangue denso. Il suo battito saldo lo teneva vigile.
Un furgone cargo della pol-Sincronia spuntò dietro la curva a fari spenti. Catene da neve battevano la carreggiata. Renato si staccò dalla rupe e forzò il portello cieco nel cassone. Laura si aggrappò alla cresta del tetto, svicolò verso il lato guida, strappò la maniglia e infilò l'arma calda sotto la mandibola dell'operatore.
L'autista inghiottì forte. Laura gli impose il silenzio con gli occhi e l'uomo alzò i palmi sul volante, frenando a strappi. Renato strappò i collegamenti satellitari con un tronchesino nel pozzetto di bordo. Claudio rotolò sui pallet del cassone, incapace di reggersi, mentre Laura prese posto sul sedile centrale e affiancò le cosce a quelle di lui per ridargli speranza umana. Cacciarono l'autista sul ciglio innevato e Renato pigiò l'acceleratore a tavoletta, mandando il furgone su di giri.
La salita sbatteva forte contro gli ammortizzatori. Renato pestò i freni prima del tornante ed indicò un braccio telemetrico ABITES in rotazione radiale. Laura raccolse un cerchione di scarto abbandonato sul sedile. Calcolò il vento e scagliò il ferro sul piantone della telecamera. Il suono metallico sfregiò la valle. L'asse primario andò in blocco per sedici secondi, mandando in cortocircuito i giroscopi.
Il camion svernò oltre il ponte senza scatenare allarmi. Claudio tenne pressata la chiavetta col pollice: Sara resisteva là fuori, e lui avrebbe maciullato ogni chilometro per arrivarci. Le ruote scavarono fino a scollinare l'ultimo massiccio. I radar persero la traccia satellitare tra nebbie dense e pini scheletrici. Renato frenò, staccando l'alimentazione, e i tre sbarcarono nel nulla bianco.`;
