export const chapter19Content = `Macro-Capitolo 19: Il Fiume Nero
[ROMA SOTTERRANEA - TUNNEL ARCAICO - LAURA E CLAUDIO]
L'oscurità assoluta del varco tufaceo inghiottì immediatamente le ultime luci fioche del rifugio sotterraneo. Laura agganciò un solido moschettone in titanio al cinturone tattico di Claudio, inerte sulla barella improvvisata. Vincolò l'altra estremità della fune al proprio imbrago. Il traino disperato ebbe inizio. Ottantacinque chili di carne e ossa gravavano ora totalmente sulla sua schiena nuda di protezione. Ogni passo sulla pietra era un calcolo preciso di attrito, fatica e dolore muscolare.
Il pavimento del condotto arcaico era viscido, pericoloso. Il muschio nero e freddo copriva i grossi blocchi di basalto millenario. Claudio trascinava gli anfibi pesanti sulla pietra con un rumore sinistro. La sua testa ciondolava ritmicamente contro il torace della donna, a ogni passo. La flebo di antibiotici era stata fissata alla spallina di Laura con del nastro telato. Il liquido salvavita scendeva goccia a goccia nella vena dell'ingegnere, scandendo nel silenzio il tempo della loro faticosa avanzata.
«Mantieni il raggio della torcia basso, Laura,» ordinò Carlo nell'auricolare. La sua voce grattava nel buio come carta vetrata. «Siete esattamente trenta metri sotto il livello delle fognature ufficiali. Nessun radar di superficie vi traccia ora. Ma state attenti alla concentrazione d'ossigeno. Siete in una sacca chiusa da secoli. Se la concentrazione scende troppo, non avrete alcun preavviso prima del collasso.»
«Ricevuto, Carlo,» rispose Laura a voce bassissima per non sprecare fiato. Il fiato le usciva dai polmoni in brevi nuvole di vapore bianco nel gelo.
Avanzarono per oltre duecento metri nell'oscurità. Il tunnel si strinse all'improvviso. Un crollo parziale di mattoni romani ostruiva ora metà del passaggio. Laura dovette calarsi a terra, sui gomiti. Strisciò nel fango freddo e melmoso trascinando Claudio faticosamente per le ascelle. Il corpo dell'ingegnere si impigliava continuamente nelle macerie taglienti. Il respiro dell'uomo era diventato un rantolo rotto, umido. Il suono rauco riecheggiava lugubre contro la volta scrostata del condotto.
L'aria divenne improvvisamente densa, pesante. Sapeva di zolfo, umidità vecchia e polvere d'ossa. Il lastricato di pietra terminò all'improvviso davanti a un baratro poco profondo. La luce della torcia di Laura svelò una palude ipogea silenziosa. Era acqua nera, stagnante, immobile. Un bacino carsico intrappolato tra mura in Opus reticulatum di epoca imperiale. Un piccolo drone di ispezione idraulica, una vecchia sub-routine di ABITES chiamata SEWER-SCAN, galleggiava inerte tra i rifiuti plastici in superficie. Il suo occhio ottico rosso era spento, ma i sensori acustici emettevano ancora un ticchettio elettronico intermittente e inquietante.
Laura saggiò il fondo melmoso con la punta dello stivale pesante. Trovò roccia solida sotto tre centimetri di limo scivoloso. Scese con decisione nel bacino nero. L'acqua gelida morse immediatamente i suoi polpacci. Infiltrò il kevlar dei pantaloni tattici pesanti. Raggiunse rapidamente le ginocchia dell'incursionista. La donna tirò con forza la cinghia di trazione. Claudio scivolò nell'acqua lurida con un tonfo sordo, sollevando schizzi di melma. Il freddo estremo sferzò il suo corpo febbricitante come una sferzata di frusta. L'ingegnere ebbe uno spasmo violento dell'intero tronco. Spalancò improvvisamente gli occhi vitrei. Erano lucidi, persi nel delirio della febbre.
«I moduli di controllo...» mormorò Claudio con voce strozzata. Annaspò con la mano sinistra nell'acqua sporca che lo circondava. «Le frequenze di scansione... cambiano in tempo reale. Carlo, scollega subito i piloni centrali! Fallo adesso!»
Laura gli afferrò la mascella con forza, scuotendolo leggermente. Gli sollevò il mento con la mano per evitare che affogasse nel lago nero.
«Siamo nel tunnel, Claudio! Concentrati solo sui miei passi e sulla mia voce,» disse lei con durezza militare. «Cammina, dannazione! Cammina!»
L'ingegnere fissò il vuoto gelido sopra la testa di Laura, immobile. Le sue pupille dilatate al massimo non mettevano a fuoco nulla della realtà circostante.
«La Torre EUR...» raschiò l'uomo con un filo di voce roca. I suoi denti sbattevano ritmicamente per il freddo. «Il nucleo non tocca mai terra. Sono piloni idraulici rotanti in sospensione. Cyrus è sospeso nel vuoto, nell'aria.»
Un improvviso attacco di tosse gli squarciò la gola. Sputò un grumo scuro e denso nell'acqua fognaria ai suoi piedi.
«Sospeso dove, Claudio? Dove?» incalzò la partigiana con urgenza. Continuò a trascinarlo implacabile attraverso il lago nero e immobile.
«Nel pozzo principale di raffreddamento,» sussurrò Claudio, la voce che si spegneva. La testa gli ricadde pesantemente sul petto della donna. «Devi spezzare le catene magnetiche primarie. Altrimenti il virus Omega non troverà mai il centro logico di ABITES. Rimarrà in superficie.»
L'acqua salì fino alla vita di Laura, rallentandone il passo. Il freddo polare anestetizzava i suoi muscoli tesi. Un boato remoto e profondo fece vibrare improvvisamente la roccia circostante. Non era un tuono atmosferico. Erano vibrazioni meccaniche immani trasmesse dai piloni sovrastanti. Pompe ciclopiche in funzione. Grandi motori a turbina.
L'auricolare gracchiò di nuovo nella cavità del tunnel. Era la voce tesa di Elio.
«Laura, abbiamo intercettato una comunicazione cifrata della sicurezza interna EUR. Hanno rilevato un'anomalia nella pressione idrica dei sotterranei meridionali 4. Mandano una squadra di bonifica pesante tra soli dieci minuti. Dovete uscire dall'acqua. Subito!»
Laura issò con uno sforzo immane Claudio sull'ultimo gradone di pietra calcarea scivolosa. Uscirono finalmente dal guado del lago nero. Davanti a loro la muratura antica spariva del tutto. Un muro ciclopico in calcestruzzo armato e acciaio moderno tagliava verticalmente e senza pietà la storia millenaria di Roma. Le massicce putrelle d'acciaio modernista del regime segnavano il confine del loro mondo.
Erano finalmente arrivati alle fondamenta fisiche dell'inferno. Laura poggiò Claudio contro il muro ghiacciato di cemento. Estrasse la pistola dalla fondina bagnata con uno scatto secco. La polvere di Testaccio e il fango dello Ionio le segnavano ancora il viso come pitture di guerra.
«Non li lasceremo passare, Claudio. Te lo giuro,» sussurrò Laura, caricando l'arma con un clic metallico che risuonò nel vuoto.`;
