export const chapter17Content = `Macro-Capitolo 17: Febbre e Asfalto
[AUTOSTRADA A1 - SEICENTO CHILOMETRI A NORD]
Ore 14:00. Il vecchio furgone blindato divorava l'asfalto della A1 con un rombo costante e affannato. Il confine con il Lazio era ormai vicino. La pioggia incessante del centro Italia dilavava l'orizzonte, riducendo la visibilità a meno di cento metri. Un sudario di nebbia densa nascondeva completamente le vette degli Appennini circostanti.
Laura tirò il freno a mano con una violenza improvvisa. Nascondette l'autocarro nella boscaglia folta vicino a un'uscita autostradale in disuso da anni. L'abitacolo esalava puzza di freni incandescenti e gomma bruciata. La donna si slacciò rapidamente l'imbragatura balistica del sedile. Spense il motore ed entrò nel vano posteriore attraverso il piccolo passante blindato.
L'aria dentro la cella di piombo era densa, insopportabile. Sapeva di carne malata, sudore e ferro rugginoso. Claudio si dibatteva debolmente tra le cinghie di contenzione della barella. Non era più lucido. I brividi incontrollati scuotevano il suo corpo magro. Gridava ordini a nemici invisibili con le labbra incrostate di sangue secco. L'effetto degli ultimi farmaci analgesici era terminato da ore.
Laura appoggiò la mano sulla tempia scottante dell'ingegnere. La pelle era rovente, quasi intoccabile. La febbre superava certamente i trentanove gradi. Il bendaggio del braccio destro era ormai saturo di pus e siero scuro. Il gonfiore violaceo circondava minacciosamente la carne viva dello squarcio. La sepsi totale minacciava la sua stessa vita. Mancavano ancora trecento chilometri alla base della Torre EUR.
La donna non concesse alcun spazio all'esitazione. Strappò con un colpo secco i resti della manica della giacca di Claudio. Espose il cratere infetto dell'ustione. Il muscolo tricipite era tumefatto, deformato. C'erano bolle purulente e nere sul muscolo esposto. Afferrò la garza sterile con dita ferme. Affilò una lama in tungsteno. Sterilizzò l'acciaio freddo con la fiamma azzurra di un piccolo saldatore portatile.
Claudio mormorò suoni rochi e incomprensibili di ribellione. Laura lo bloccò con tutto il suo peso contro le sbarre della barella. La lama scese decisa nella carne malata. Squarciò le sacche settiche con la precisione di un chirurgo da campo. Il siero inquinato colò sul pavimento di metallo rigato. Claudio sussultò violentemente. Si inarcò in uno spasmo per il dolore atroce. L'urlo di agonia morì nei suoi polmoni troppo stanchi per gridare. Laura gli mise un blocco di cuoio robusto tra i denti. Raschiò via la carne morta e necrotica con forza bruta. Fu un'azione necessaria di pura sopravvivenza.
Tamponò finalmente la ferita aperta con lo iodio puro. L'odore sterile dell'ospedale sostituì quello dolciastro della cancrena. Era un intervento misero, brutale, ma assolutamente essenziale per non farlo morire lungo la strada. Claudio si afflosciò esausto sulla barella. Il suo petto iniziò ad abbassarsi con regolarità. Restò incosciente in un sonno profondo di shock. Non sarebbe entrato nella capitale sulle proprie gambe. Sarebbe arrivato protetto solo dal piombo e dalla volontà di Laura.
La soldatessa asciugò il sudore freddo dalla propria fronte con il guanto sporco. Richiuse la cella di piombo. Ingranò la prima marcia. Il rombo sordo del motore inghiottì il silenzio delle colline laziali. Roma era ormai a un passo.`;
