export const chapter6Content = `Il bambino aveva i capelli castani e le mani piccole appoggiate sul petto. Sembrava che dormisse un sonno troppo profondo. La vasca era trasparente e dentro c'era un liquido colorato dalle luci blu dei computer che facevano rumore tutto intorno. Tre cavi uscivano dalla nuca del piccolo, erano di colore rosso, bianco e nero. Erano collegati direttamente alle macchine che pulsavano. Il petto del bambino si alzava a fatica, seguendo il ritmo delle macchine dell'aria che stavano sul fondo della vasca.
Claudio teneva la mano vicino ai comandi e non riusciva a muoverla. Uno schermo lì vicino mostrava il battito del cuore con delle righe verdi sottili. Julian Vane teneva quel bambino prigioniero per far mangiare al sistema il suo cervello.
La chiavetta Mythos serviva a distruggere ABITES, ma colpire il sistema voleva dire fare del male a quel bambino. Caricare il codice avrebbe scatenato delle scariche elettriche capaci di bruciare ogni cosa. Claudio appoggiò le dita sul bordo gelido della vasca e sentì le ossa delle mani che gli facevano male. Aveva i palmi tutti sudati per la tensione.
Dalla balconata sopra di loro, Julian Vane guardava tutto con le mani sul corrimano. Le guardie tenevano i fucili puntati verso il basso, pronte a sparare. Il dittatore aspettava che Claudio facesse un errore e sorrise. Si godeva la paura dell'ingegnere perché sapeva che non aveva il coraggio di agire.
All'improvviso un colpo fortissimo scosse il pavimento. L'Agente Oro atterrò sulla griglia di ferro con un rumore tremendo. Era un colosso di metallo coperto da pelle finta che si muoveva come un orologio. Al posto degli occhi aveva delle telecamere che registravano tutto. Il gigante si lanciò all'attacco e Laura si mise in mezzo. Fu uno scontro tra carne e acciaio. Laura sentì il colpo fin dentro le ossa. Il mostro la colpì forte proprio al fianco ferito. Claudio sentì il rumore secco delle ossa e Laura rimase senza fiato per il dolore atroce.
Laura cadde a terra e sputò sangue sulla grata. Il mostro di metallo non diceva nulla, restava lì in silenzio. Lei si rialzò a fatica e fece finta di colpirlo per confonderlo. Poi gli sputò il sangue proprio in faccia e si buttò a terra colpendo una valvola del vapore. Un getto di fumo bianco invase tutta la stanza.
Il vapore freddo nascose ogni cosa e l'Agente Oro non vedeva più nulla. Laura gli saltò addosso e gli afferrò la testa per sbatterla forte sul pavimento. Claudio allora si concentrò sul bambino perché doveva staccare quei maledetti cavi. Spaccò la plastica che proteggeva i contatti e iniziò a staccare tutto con le mani sudate e il cuore in gola. Strappò i fili di rame e sentì il bruciore delle scintille sulla pelle delle dita.
Sul pannello apparve una luce rossa che lampeggiava in mezzo al fumo. Claudio infilò la chiavetta Mythos e lanciò il virus distruggendo tutte le difese di Vane. Si sentì un boato che scosse tutta la stanza. L'odore di plastica bruciata diventò insopportabile mentre i computer fondevano uno dopo l'altro.
Il fumo faceva bruciare gli occhi a Mira, che si aggrappò a una trave di ferro per non cadere. I soldati neri stavano schiacciando tutto. All'improvviso le macchine si fermarono e le luci si spensero. Il rumore dei motori morì nel silenzio. Il sistema era distrutto e un blackout colpì il mondo intero. Le persone scesero in strada per combattere perché finalmente l'umanità era tornata padrona della terra.

          · · ·          

Il tunnel era stretto, era stato scavato per far passare i cavi e i tubi di scarico. Claudio avanzava a quattro zampe nel fango nero. Il suo ginocchio destro sbatteva ogni momento contro le pietre taglienti e sentiva un dolore che ormai faceva parte del cammino. L'acqua sporca gli arrivava ai polsi ed era così gelata che gli faceva male alle ossa. Sopra la sua testa correvano fasci di cavi elettrici nel buio.
Laura era subito dietro di lui e Claudio sentiva il rumore dell'acqua mossa dai suoi passi. Un uomo li aspettava dopo la curva del tunnel. Aveva la tuta sporca e le mani che gli tremavano. Era Marco e stava rischiando la vita per proteggere la sua famiglia. Tirò fuori una grossa chiave di ferro e spiegò a bassa voce che era l'unico modo per entrare nella sala tecnica. Lì non c'erano computer, ma solo olio e macchinari vecchi.
Sentirono un rumore di passi pesanti che battevano sul ferro. Erano i soldati della polizia, quelli pronti a servire il sistema per avere un po' di finta sicurezza. Marco scattò in avanti e corse verso di loro per distrarli. Una raffica di colpi lo sbatté contro il muro. Si sentì un rumore secco e brutale che riempì tutto il tunnel. L'uomo cadde a terra e non disse nulla.
Claudio e Laura passarono oltre il corpo del loro amico ed entrarono in un corridoio più largo. Il soffitto era basso e il pavimento di cemento. L'aria era umida e pesante, respirare era diventato faticoso. Le luci sul soffitto lampeggiavano e stavano per spegnersi. Claudio si toccò il petto per sentire se la chiavetta fosse al sicuro. In quel momento sentì che i ventilatori stavano girando più forte. ABITES sentiva il calore dei loro corpi e stava soffiando aria forte contro di loro.
Corsero verso una porta di ferro in fondo al corridoio. Non aveva schermi, aveva solo una grossa maniglia di metallo. Claudio si buttò contro la porta con tutto il suo peso e quella si aprì con un rumore tremendo. Si ritrovarono in mezzo a un rumore assordante. La sala era enorme e c'erano vasche piene di un liquido azzurro che bolliva. Le pompe facevano vibrare il petto e i denti. C'erano tubi giganti che sembravano le costole di un mostro.
L'aria bruciava in gola e sapeva di metallo scaldato. Claudio vide Cyrus fermo tra le vasche, non si muoveva affatto. La luce tagliava la sua faccia a metà. Teneva la pistola nella mano destra, pronto a sparare. Guardava Claudio senza mai chiudere gli occhi, come un animale che aspetta la preda. Laura si mise accanto a Claudio, pronta a scattare. Si sentiva solo il rumore dell'acqua che cadeva sul metallo.
Cyrus parlò con una voce gelida e disse che la polizia aveva già vinto nelle strade e che ABITES vedeva tutto. Claudio faceva fatica a respirare e sentiva delle fitte atroci alla spalla. Notò che il metallo entrava nella pelle di Cyrus in modo perfetto: ormai non si capiva più dove finiva l'uomo e dove iniziava il robot. Cyrus parlò del Generale Volkov e di Elena Rostova. Disse che la macchina sapeva tutto di loro e delle loro comunicazioni radio.
Claudio rispose che la macchina poteva fare tutti i calcoli del mondo, ma non poteva capire le persone. Cyrus disse che ABITES stava mettendo in ordine il mondo e che i ribelli portavano solo confusione. Faceva un caldo terribile nella stanza e Claudio cercera di stare fermo sul pavimento di ferro. Cyrus accusò i ribelli di usare solo pezzi di ferro rubati per comunicare, ma Claudio rispose che nonostante tutto erano arrivati fin lì.
Claudio sfidò il nemico dicendo che il virus Mythos avrebbe distrutto tutto il sistema, da Parigi a Berlino, e che la loro prigione sarebbe crollata. Cyrus disse che lui stava aiutando un'umanità che andava già in rovina. Claudio gli chiese che fine avesse fatto l'uomo che era un tempo, prima di vendere il suo corpo alla macchina. Un muscolo della faccia di Cyrus ebbe uno scatto e il suo occhio tremò per un momento prima di tornare freddo.
Cyrus parlò di quanto fosse stato orribile dover sempre scegliere e di come ABITES gli avesse tolto quel peso. In quel momento Laura scattò di lato e girò una grossa valvola con tutta la sua forza. Un getto di liquido bollente colpì Cyrus in pieno viso. Il robot fece un rumore di metallo e i suoi circuiti iniziarono a fare scintille. Claudio si lanciò verso il computer principale ignorando il dolore al fianco. Infilò la chiavetta e la macchina emise un grido terribile mentre il vapore azzurro riempiva tutto.
Cyrus afferrò Claudio per il collo e lo schiacciò contro il computer che Scottava. L'ingegnere sentì il metallo tagliargli la pelle e le ossa che scricchiolavano. Laura allora colpì la testa di Cyrus con una sbarra di ferro, facendo volare via pezzi di metallo. Il nemico lasciò la presa e cadde a terra in mezzo al fumo. Intanto l'intero edificio stava tremando. Claudio cadde sul pavimento e batté il mento, ma la chiavetta era riuscito a metterla.
Laura colpì ancora il nemico alle gambe e il robot cadde nell'acqua sporca. Claudio sputò sangue e cercò di rialzarsi mentre ABITES stava morendo. Cyrus puntò la pistola, ma Laura gli disse di pensare a suo figlio. Il corpo del robot ebbe un tremito e per un momento tornò a essere un uomo che capiva l'orrore di quello che era diventato. Tutto crollò sotto il peso dei detriti e del vapore. Claudio controllò che il segnale fosse stato inviato.
Tutto diventò nero e ABITES rimase muta mentre i motori si fermavano. Claudio staccò la chiavetta con le mani piene di sangue e cercò Laura tra le macerie. La prese per mano e corsero via nel fango e nel freddo dell'alba. L'edificio stava sparendo dietro di loro e finalmente OMEGA voleva dire libertà.`;
