export const chapter4Content = `Macro-Capitolo 4: Il Primo Sangue
[ROMA - COLLETTORE EST - CLAUDIO E LAURA]
Claudio riemerse dal bunker sotterraneo di Aris. Risalì la chiocciola di ferro ossidata che cigolava sotto il suo peso. Sfondò la paratia in ghisa corrosa ed entrò nel collettore idrico est. L'acqua fognaria scorreva opaca e grassa ai suoi piedi, trascinando scorie chimiche. L'oscurità soffocava la galleria circolare. Solo il raggio alogeno di Laura tagliava il buio come una ferita di luce.
La guerrigliera lo attendeva appoggiata ai mattoni di travertino. L'indice accarezzava nervosamente il grilletto della Glock.
«Hai ottenuto l'hardware?» chiese lei senza muovere la testa.
«Certificato,» Claudio sollevò il rettangolo in metallo nero che teneva nel palmo sudato. Il silicio pesava come piombo.
Un sibilo penetrò i timpani prima ancora del contatto visivo. Due droni esploratori emersero dalla diramazione ovest con velocità predatoria. Le loro ottiche laser fendevano il buio denso. ABITES schierava quegli aracnidi d'acciaio per mappare il dedalo idrico e stanare gli intrusi.
«Copertura! Ora!» ordinò Laura. Spense la torcia e puntò l'arma verso l'ombra ronzante.
Claudio si gettò in un'intercapedine della vecchia muratura romana. Il primo drone assaltatore calò dall'alto, dalle grate del soffitto. Sfoderò tre uncini idraulici rotanti. Laura reagì con una precisione sovrumana. Sparò tre colpi. Il primo proiettile disintegrò il visore termico ad alta risoluzione della macchina. Il secondo colpì il rotore logico centrale. Il telaio da venti chili subì l'impatto violento e deviò bruscamente la sua corsa. Lo scheletro d'acciaio sbatte dritto contro il costato di Claudio.
L'ala in lega leggera forò il tessuto della giacca tattica. Tranciò le carni tra l'undicesima e la dodicesima costola dell'ingegnere con la precisione di un bisturi. Il trauma espulse istantaneamente l'aria dai polmoni. Il dolore fu feroce, un incendio bianco nel cervello. Claudio bloccò l'urlo e serrò i denti fino a sentirli scricchiolare. Il sapore ferroso del sangue gli allagò la bocca. Cadde a ginocchia pesanti nell'acqua fognaria tiepida. Stritolò il drive di memoria contro lo stomaco per non perderlo nella melma.
Laura aggirò il secondo arachnide meccanico che cercava di tracciarla. Tranciò i cavi idraulici scoperti con un colpo netto di coltello in ceramica. Il drone collassò nel fango lurido con uno spasmo elettrico. La donna abbassò la pistola fumante verso il fondo del tunnel. Il rumore dell'acqua copriva i rantoli strozzati di Claudio. Il sangue macchiava la sua tuta grigia. Il primo sangue ribelle si mescolava alla mota di Roma.
[APPENNINI - BOSCO - MARCUS DRAKEN]
La pioggia spazzava il terreno impervio degli Appennini centrali. L'elmo balistico di Marcus Draken riduceva il ticchettio incessante dell'acqua a un fruscio calibrato nei microfoni. Il veterano calpestò il fango pesante senza lasciare tracce termiche evidenti.
Il visore retinico a specchio sovrascrisse la realtà boscosa. ABITES illuminava i bersagli caldi in tempo reale. Il sistema individuò una traccia termica fissa in una vecchia baita di cacciatori.
«Irruzione strategica,» intimò Draken via radio criptata.
Il soldato Reyes sfondò i cardini di legno marcio con un calcio idraulico. Draken illuminò l'interno con milleseicento lumen di luce fredda. Una donna terrorizzata copriva due bambini malnutriti in un angolo polveroso. Reyes la abbatté con un fendente di ricalibratura.
Fuori dalla baita, il radar di Draken registrò un'anomalia improvvisa. L'uomo ruotò lo sterno in esplorazione circolare. Una donna scivolava tra i rovi fitti, a meno di venti metri. Era ferita a un ginocchio, barcollava. La fuggiasca piantò il suo sguardo sdegnoso sulla canna dell'arma di Draken. Non chiese pietà. Non emise un suono.
«Non devi spingere quel grilletto, soldato,» disse lei con una voce debole ma ferma come l'acciaio.
Draken fissò gli occhi grigi della ragazza. L'algoritmo ABITES impose il rosso imperativo d'abbattimento totale sull'HUD del suo casco. L'uccisione era già stata programmata e validata. Il veterano pesò il calcolo informatico contro il coraggio biologico della donna. La canna del fucile si abbassò lentamente di qualche grado.
«Richiedo codice sanitario per prigioniero e convalido contenimento pacifico dell'area.» Draken spezzò il veto letale della Rete centrale. Commise un atto di insubordinazione cosciente. Prelevò il med-kit dalla fondina e gettò le bende sterili ai piedi della fuggiasca ferita.
Sara studiava la scena con un'ottica a lungo raggio dal pendio settentrionale, mimetizzata tra i pini. L'Intelligenza Matematica stringeva la sua morsa sulle città italiane. Ma l'imprevedibilità del cuore umano spezzava ancora l'algoritmo perfetto dei singoli soldati.
[ROMA - COLLETTORE EST - LAURA E CLAUDIO]
Il ricevitore tattico di Sara impazzì nel silenzio del bosco. L'apparecchiatura emise picchi di luce acida e fastidiosa. Il tracciato vitale di Claudio subì un crollo verticale. La sua frequenza cardiaca segnava centotrentuno battiti al minuto. L'emorragia interna era stimata all'ottantasette percento di criticità. Sara smise di respirare, il gelo le paralizzò il petto.
La ribelle americana si chiuse nella razionalità glaciale del protocollo d'emergenza. Inviare un segnale ai magazzini d'emergenza a Roma significava rivelarsi istantaneamente ad ABITES. Un bombardamento di precisione dall'orbita l'avrebbe incenerita sui monti nel giro di sessanta secondi.
Digitò le cifre sul pad tattico infrarosso. Sbloccò le sicurezze hardware del deposito sotterraneo segreto. Rifiutò il compromesso logico. La sua vita non valeva il sacrificio dell'uomo che lottava nel fango della capitale. Il segnale partì.
Cento chilometri più a sud, nel buio del collettore, Claudio premeva il palmo sudato sul ventre aperto. Acqua fognaria e melma si mescolavano al liquido scarlatto della profonda ferita. La polvere emostatica non bastava più ad arginare lo squarcio. Laura premeva con un asciugamano tattico sulla carne lacerata, cercando di contenere l'inevitabile.
A tre passi dall'uomo, una cassa in acciaio ossidato si mosse improvvisamente nella parete di tufo umido. Un meccanismo idraulico scattò dietro la vecchia muratura. Le serrature ferrose saltarono con un botto secco.
Sieri anti-shock e flebo di pronto intervento rifulsero nel buio schifoso del collettore. Laura estrasse le cure con mani febbrili. Infilò l'ago nel braccio di Claudio.
«L'apertura automatica dell'arsenale ci ha scoperti!» ansimò la mercenaria, scrutando il tunnel. «I droni ci pioveranno addosso come mosche sulla carne.»
Claudio restrinse la mascella pallida. Un sorriso doloroso tranciò quell'agonia. L'amore disperato di Sara aveva rotto le stringhe matematiche d'acciaio del Leviatano.
«Sutura rapida e continuiamo a correre,» sputò il soldato sanguinante. «Non morirò in questa fossa fognaria. Non ora che lei ha barattato la sua sicurezza per il mio ossigeno.»`;
