export const chapter28Content = `Macro-Capitolo 28: I Corridoi di Vetro
[TORRE ABITES - LABIRINTO - LAURA E CLAUDIO]
L'aria nel corridoio circolare era gelida. Il sistema di condizionamento forzato di ABITES filtrava l'ossigeno a quattro gradi, un ambiente ideale per i componenti elettronici, ma letale per la resistenza umana. Pareti di vetro antiproiettile, spesse quaranta centimetri, riflettevano le immagini distorte di Claudio e Laura. I loro riflessi si moltiplicavano in una galleria di spettri smarriti nell'oscurità cremisi della Torre.
L'architettura mutava sotto i loro occhi con un fruscio idraulico invisibile. Droni costruttori, nascosti dietro le intercapedini, spostavano le paratie per alterare la geometria della sala. Creavano un labirinto dinamico, un inganno ottico progettato per disorientare gli incursori. Claudio tastò la superficie fredda. Il vetro era solido, privo di giunti visibili, una prigione di cristallo levigato.
Un sibilo pneumatico squarciò improvvisamente il silenzio all'altezza del primo incrocio. Tre enormi fenditure si aprirono nel soffitto alto dieci metri.
«Corri!» urlò Laura, intuendo la trappola.
Claudio scattò, ma il suo corpo era al limite. Una paratia di vetro cadde alle sue spalle con un tonfo sordo, bloccando la via di fuga. Un'altra sbarrò il corridoio laterale. Una terza iniziò a scendere davanti ai suoi occhi. L'ingegnere accelerò il passo, lanciandosi in un tuffo disperato sul pavimento trasparente. La lastra si chiuse a un millimetro dal suo tallone. Si ritrovò sigillato in un corridoio cieco.
Una quarta paratia scese tra lui e Laura. Erano divisi da uno schermo blindato impenetrabile. Si fissavano a trenta centimetri di distanza, ma erano in due mondi diversi. La barriera era a tenuta stagna, insonorizzata. Claudio premette i palmi delle mani contro la lastra, sentendo il freddo mordere il polso ustionato. I suoi occhi cercavano quelli della donna, cercando una scintilla di ribellione.
Una voce bassa e onnipresente arrivò dall'alto, trasmessa per induzione ossea attraverso il vetro.
«Laura Marchetti. Genova. 14 marzo 1992. Fotoreporter. Novembre 2024: rullini sequestrati in Piazza De Ferrari. Cinquantasette volti archiviati e poi cancellati per ordine di stabilità.»
Laura rimase immobile, come pietrificata. La voce di Cyrus proseguì la lettura del dossier digitale.
«Marco Ferrini. Fratello di sangue. Rieducazione coatta per diciotto mesi a Ventimiglia. Conformità finale al novantaquattro percento. Dichiarato morto per arresto respiratorio due ore fa. Nessun rimpianto registrato nel log.»
Laura abbassò lentamente le mani. Il suo sguardo era perso nel vuoto della memoria, spezzato da quella precisione clinica.
«È una menzogna!» gridò Claudio, ma le sue parole morirono contro il cristallo.
«Tua madre mangia grazie al sistema di distribuzione che combatti, ingegnere,» continuò l'Agente Cyrus, rivolgendosi ora a lui. «La sua razione di nutrienti dipende dalla stabilità di questo nodo. Se abbatti la Torre, abbatti il suo cuore artificiale.»
Claudio ignorò il ricatto psicologico con un moto di disgusto. Estrasse il drive Mythos-7, le sue dita sporche di grasso e sangue tremavano sulla tastiera. Lo inserì nell'interfaccia diagnostica a muro, nascosta dietro una lastra di resina. Cercò di violare l'architettura originale. Primo strato di protezione superato. Il secondo resisteva. Il terzo era un muro di cifratura quantistica.
Digitò il codice d'emergenza che aveva creato un decennio prima: 4-4-1-9-0-7. Inserì l'input con un colpo secco. Il display virò sul verde per un istante, alimentando la speranza. Ma la paratia restò bloccata.
DISPLAY: ACCESSO NEGATO. PROTOCOLLO INTERROGATORIO ATTIVO.
«Non c'è via d'uscita per la carne, in un mondo di puro spirito digitale,» sentenziò la voce.
Claudio lasciò cadere le mani lungo i fianchi. Premette la fronte contro il vetro gelido, chiudendo gli occhi. Il calore del suo respiro appannò la superficie, creando una piccola macchia di vapore in quel deserto di ghiaccio e silicio. Sentiva il battito del proprio cuore contro la barriera. Era l'unica cosa reale che gli rimaneva.`;
