export const chapter7Content = `La porta di ferro era quasi del tutto coperta dalla terra. Renato riuscì a trovarla scavando con le mani nel buio della scarpata. Trovò il punto giusto e iniziò a fare leva con un attrezzo pesante. Il metallo era arrugginito e faceva un rumore terribile. Claudio era poco distante e cercava di non scivolare tra le rocce. Sentiva un fischio continuo nelle orecchie per colpa della febbre che non voleva passargli.
Finalmente l'ultimo bullone si ruppe e la porta si aprì. L'aria che uscì dal bunker era pesante e puzzava di olio vecchio e umidità. Claudio entrò in quel posto buio, sapendo che lì sotto i satelliti di ABITES non avrebbero mai poteva trovarlo. Renato accese una vecchia lampada a olio e la luce gialla illuminò quello che chiamavano il Fiume Nero.
Sotto i loro piedi, in una profonda trincea scavata nella roccia, scorreva una massa enorme di cavi neri. Erano unti di olio e brillavano sotto la luce della lampada. Renato ordinò di non toccare assolutamente le pareti perché c'era il rischio di morire folgorati. Videro il corpo di un poliziotto della Sincronia incastrato tra i cavi. La sua armatura era bruciata e il casco era diventato nero per l'elettricità. Era morto cercando di spegnere quel sistema.
Camminarono uno dietro l'altro sopra una passerella di griglia metallica che sembrava poco sicura. La chiavetta che Claudio portava nel giubbotto iniziò a vibrare forte quando arrivarono vicino ai grandi trasformatori. Sembrava quasi che quel pezzo di metallo stesse respirando insieme a lui. Le piccole luci rosse della chiavetta lampeggiavano seguendo il ritmo dell'elettricità che scorreva sotto di loro. Laura la sfiorò con le mani gelate e Claudio capì che dovevano andare ancora più in profondità.
Passarono davanti a un grande pannello di controllo dove un grosso cavo era stato tagliato con la forza. Qualcuno aveva fatto un sabotaggio a mano. Sopra quel taglio, scritto con del sangue secco, c'era il simbolo Omega. Era il segno della resistenza. Gli operai che ABITES aveva cacciato erano passati di lì e avevano distrutto tutto per impedire ai robot di avanzare, sacrificando la propria vita.
Il passaggio diventò strettissimo. Claudio doveva camminare di lato per non sbattere contro le pareti di ferro gelido. Le sue gambe si muovevano solo per miracolo e sentiva il calore dell'elettricità che gli faceva ribollire il sangue. Il sudore gli colava negli occhi, ma non poteva alzare la mano per asciugarlo perché aveva paura di perdere l'equilibrio e cadere nel vuoto dove i cavi lo avrebbero ucciso all'istante.
Renato camminava avanti a lui, attento a non inciampare e controllando sempre che la griglia tenesse il loro peso. All'improvviso sentirono uno scatto metallico. Claudio si bloccò subito. Dal fondo della galleria arrivava un calore fortissimo che puzzava di bruciato. Si fermarono entrambi perché sentirono un rumore strano, come se qualcuno stesse respirando pesantemente attraverso un tubo. Claudio appoggiò la mano su una conduttura e sentì una vibrazione regolare che non gli piaceva affatto.
C'era qualcosa che bloccava il passaggio dell'aria. Proseguirono nel rumore assordante dei motori. Arrivarono a un incrocio dove una scala di ferro portava a una botola sul soffitto. Renato vide della polvere di metallo fresca sui bulloni: qualcuno aveva preparato una trappola. Se i soldati avessero cercato di uscire da lì, sarebbero stati risucchiati dalla pressione e lanciati dritto sui cavi ad alta tensione.
Evitarono quella trappola mortale e continuarono a camminare sulla passerella. Il passaggio si stringeva sempre di più e Claudio sentiva un dolore atroce al petto, come se avesse un ferro da stiro rovente contro le costole. Si fermò un istante con le gambe che gli tremavano. La chiavetta nel suo giubbotto brillava di una luce rossa cattiva e sembrava urlargli di andare avanti, verso il cuore di quel bunker. Presero a camminare più veloci sulla griglia che tremava, senza sapere cosa li aspettasse nel buio più profondo.`;
