export const chapter4Content = `Lo scalo dei treni di Roma-Nord era pieno di metallo arrugginito e le pareti erano grigie e sporche. Claudio si schiacciò contro un grosso container e trattenne il respiro, sentendo il dolore al ginocchio che pulsava sotto la benda. Laura era poco distante, nascosta dietro un carrello, e gli fece cenno di stare fermo perché i droni stavano controllando la zona.
Claudio guardò fuori con prudenza. Oltre ai robot, si sentivano i passi dei poliziotti della Sincronia. Erano uomini stanchi che camminavano con le torce in mano e le dita che tremavano. La luce rossa di un drone passò sul pavimento proprio vicino a loro. Appena la luce si spostò, Laura scattò in avanti. Claudio la seguì, ma sentì una fitta tremenda alla gamba. Strinse i denti per non urlare perché sapeva che se l'avessero preso per lui sarebbe stata la fine.
Raggiunse Laura nel buio. Lei stava calcolando quanto tempo avessero prima che le telecamere tornassero a inquadrare quel punto. Sapevano che non potevano farcela da soli perché la rampa del treno era troppo illuminata.
All'improvviso si sentì un fischio basso. Un vecchio lavoratore con la tuta sporca d'olio stava nella sua cabina. Non li guardò nemmeno, ma mosse velocemente delle leve per aiutarli. La porta di un vagone si aprì di colpo con un forte rumore di aria compressa e le luci di quel settore si spensero per pochi secondi.
Claudio e Laura saltarono dentro il vagone buio. Si sentirono le urla dei poliziotti che si erano accorti che qualcosa non andava. Puntarono le torce contro la cabina del vecchio, ma lui non cercò di scappare. Restò lì e sorrise amaramente mentre i poliziotti gli correvano incontro. Uno sparo ruppe il vetro della cabina e il vecchio cadde a terra nel suo sangue. Aveva dato la vita per permettere a loro di scappare.
Il treno partì all'improvviso verso nord, portando Claudio e Laura lontano da Roma. Nel vagone c'erano molte persone sedute che sembravano addormentate. Avevano gli occhi vuoti perché il sistema gli dava delle medicine per calmarli e non farli ribellare. Claudio cercò di non farsi notare e controllò che la borsa con i file fosse ancora al suo posto. Il treno correva veloce nella nebbia verso Milano, dove Kael li stava aspettando.
Il treno frenò di colpo per tre volte e Claudio rischiò di cadere in avanti. L'ultima frenata gli fece male alle costole e dovette respirare piano per non soffocare. Il convoglio si fermò finalmente in mezzo a una nebbia fitta e grigia che copriva tutto. Erano arrivati a Milano.
I capannoni delle fabbriche sembravano scheletri giganti sotto la pioggia gelata. Laura aprì una porta di servizio e l'aria fredda di Milano entrò nel vagone, sapendo di fumo e di metallo. Claudio scese sui binari sentendo i sassi che scricchiolavano sotto i suoi stivali. Il ginocchio gli faceva ancora male, ma pensò a Sara e trovò la forza di camminare dritto.
Camminarono a lungo tra le vecchie fabbriche di Bovisa che ABITES aveva lasciato andare in rovina. Laura controllava sempre che non ci fossero droni, ma la zona sembrava deserta. Arrivarono all'edificio dove dovevano incontrare Kael e Laura forzò una porta di metallo arrugginito spingendola con tutta la sua forza.
Entrarono nella fabbrica e Laura trovò una botola nascosta sotto il pavimento. Spostò una pesante piastra di ferro e si sentì un rumore di motori e odore di caffè e aria bruciata. Scesero lungo una scala di ferro ed entrarono in un bunker sotterraneo pieno di schermi che facevano una luce fredda.
Sui monitor si vedeva quello che stava succedendo nel mondo: Julian Vane stava affamando la gente e spegneva la luce nelle città per costringere tutti a obbedire. Si vedevano i droni che lanciavano gas sopra la folla che protestava. Vane stava distruggendo tutto e Claudio guardava quegli schermi con rabbia mentre Kael rimaneva seduto alla sua scrivania.
L'hacker si girò e Claudio gli passò la chiavetta nera. Kael la inserì subito nel suo computer e sullo schermo apparvero migliaia di codici che iniziarono a scorrere veloci. Il programma stava controllando che tutto fosse pronto per colpire ABITES. Claudio fissava quella luce che pulsava nel buio, sapendo che era la loro ultima possibilità.
Intanto, una macchina nera correva velocissima verso Milano. Dentro non c'era nessuno al volante perché l'auto si guidava da sola seguendo gli ordini di ABITES. Cyrus sedeva sul sedile posteriore e non sentiva dolore o fatica perché il suo cervello era collegato direttamente ai computer. Lui vedeva tutto in modo diverso, i suoi occhi erano telecamere.
Il sistema gli mostrò che a Bovisa c'era un consumo di energia strano. Era una zona dove non doveva esserci nessuno. Cyrus controllò le telecamere e vide due ombre che si muovevano tra le fabbriche. Un'altra di quelle ombre camminava male, la gamba era ferita.
Cyrus capì subito che erano Claudio Ferrante e Laura Voss. Mandò subito le coordinate alla polizia di Milano per circondare la zona. La macchina rallentò mentre lui controllava i dati di Claudio sul suo schermo. Sapeva che portavano con sé un virus pericoloso per il sistema e doveva fermarli prima che lo usassero. Controllò anche i dati di Sara Ferrante a Firenze e vide che era molto agitata.
Scese dalla macchina in mezzo a una piazza e la sua armatura di metallo faceva rumore sul selciato. La gente intorno a lui sorrideva in modo strano, parevano robot. Cyrus vide un uomo che sembrava nervoso e gli sbarrò la strada. Controllò il suo polso e vide che l'uomo era agitatissimo perché pensava a suo figlio.
A Cyrus non importava dei sentimenti dell'uomo, gli importava solo che il sistema rimanesse calmo. Ordinò che all'uomo venisse data una dose di medicina per calmarlo e poi ripartì verso Bovisa. L'uomo tornò a sorridere in modo finto e Cyrus risalì in auto, chiudendo la portiera con un rumore secco. Stava arrivando a prendere Claudio.`;
