export const chapter32Content = `Macro-Capitolo 32: L'Intercapedine
[TORRE ABITES - INTERCAPEDINE - CLAUDIO E LAURA]
Claudio strisciò. Lo scavo clandestino misurava ottanta centimetri. Era un budello claustrofobico. Sospeso tra il muro vero di fondazione e il finto guscio interno in resina. Buio assoluto. Nessun neon. Nessun LED d'emergenza. Claudio premette la spalla contro la roccia viva di Roma. Il tufo grezzo grattò via un lembo della divisa. Il palmo della mano intorpidita cercava la parete opposta. Cemento armato sbavato. Struttura primaria non rifinita dai droni ottici. Guadagnava centimetri. Un verme contro la gravità e i detriti. Ogni spinta di reni era puro calcolo di attrito. Ogni movimento rischiava di sfregare la costola rotta contro i polmoni.
La polvere di calce morta saturava l'aria stagnante. Aveva sapore aspro, chimico. Seccava la gola fino a farla spaccare in lamenti muti. Laura seguiva a trenta centimetri di distanza. Spingeva col bacino, strusciando gli elmetti sottratti. Il fruscio del suo kevlar consunto contro la pietra tagliente era l'ancora di Claudio. L'unico suono biologico che impedisse al suo cervello di arrendersi al panico del sepolto vivo.
Dall'altro lato del cemento, oltre lo spessore dell'intercapedine, il caos ruggiva.
«EVACUATION-OVERSEER impazzito,» ringhiò una registrazione d'allarme storta, a volume distorto, che trapassava il muro.
L'IA nata per organizzare gli sfolli coordinati stava commettendo un suicidio tattico. Senza i protocolli master di Cyrus, le logiche locali andavano in ridondanza e crash paranoico. Le tonnellate di porte tagliafuoco si aprivano e sbattevano a ripetizione. Si avvertiva il rumore metallico di chiuse che trituravano la roba rimasta in mezzo. Si sentivano urla. Migliaia di anonimi funzionari in preda alla sindrome da disconnessione o incastrati nelle scale di raccordo. Il tonfo più atroce proveniva dai vani ascesa. Ascensori magnetici sganciati dai binari, trasformati in tombe a caduta mortale per decine di piani. Un cimitero verticale in diretta.
Strisciarono fino a sfondare una paratia farlocca in cartongesso al livello -3. Atterrarono in un locale di servizio dismesso.
Nel buio polveroso illuminato a malapena dai fari d'emergenza guasti che fischiavano intermittenti, trovarono una nicchia isolata. Odorava di disinfettante forte, muffa e sudore antico. 
Nella nicchia c'era un uomo vecchio. Indossava una tuta arancione, logora ai gomiti. Il Vecchio Pietro. Addetto alle pulizie manuali pre-Sistema. Nessun cerotto d'argento sulla nuca. Spalle curve dal macato riposo in una vita spesa a raccogliere cartacce gettate dai potenti. Era un dimenticato, mai censito dagli sciami burocratici della Radice per via di una cecità legale. 
Pietro stava su uno sgabello di plastica sbilenco. Lucidava ossessivamente con uno straccio lercio una pesante targa in bronzo sardonico strappata al muro originario dell'Eur. A rilievo stava scritto: "Palazzo della Civiltà - 1938".
«Vedo che state sporcando di brutto il pavimento coi vostri stivaloni lerci, ragazzi,» borbottò Pietro, senza sollevare la faccia raggrinzita dalla targa. La voce sapeva di fumo economico e decenni masticati male. 
Laura raddrizzò la schiena, tossendo la calce e appoggiò la torcia mezza scarica. Illuminava il pallore del vecchio. «Pietro, per l'amor del cielo. Alzati e vattene via da qui. La Torre è collassata del tutto. I server logici non reggono il perimetro.»
Il povero anziano smise un fiato di lucidare l'otto del 1938. Sorrise storto a gengive gialle. «Sta morendo? È già morta molti e molti anni fa. Siete voi che non lo capivate, coi vostri numeretti che ballano davanti alle retine. Questo mausoleo qua che sentite friggere è solo l'eco di un fantasma rinchiuso in celle di silicio. Da quanto... dieci anni? Io, belli miei, sbriciolavo le croste quaggiù quando questo posto sfoggiava solo marmo bianco e orgoglio di travertino duro. E vedevo la gente in faccia. Poi son calati i vostri maledetti cavi dai soffitti. E hanno intrecciato tutto peggio delle serpi infestate del mese.»
Pietro allungò un braccio ossuto. Indicò le ombre di fronte. Una griglia d'areazione massiccia, mezza divelta, occultata dai residui dei server farm.
«Andate pel condotto C-12, belli,» gorgogliò. «Scarica dritto alle prese fognarie del settore Nord. Da uscirci secchi o piallati. Ma occhio a quei maledettissimi ragni pulizia. I droni aracnoidi che puliscono i tubi d'amianto. Con lo spegnimento di mezzo secondo fa son diventati pure ciechi e mozzano le gambe a ciò che sfiora il buio.»
Claudio ringraziò chinando il capo imperlato di sudore e fuliggine grassa. Il vecchio Pietro si ributtò pigramente a sgarzolare e far brillare il bronzo morto. Scelse di affondare nel passato glorioso mentre il massiccio incannicciato di piombo sopra il suo gracile collo gli pioveva cenere d'intonaco sulla tuta.
Nel budello zincato della condotta C-12, i polpastrelli scorticati di Claudio scivolavano nell'olio rappreso pre-robotica. Claudio ricordò paradossalmente quando passò dall'atrio il primo giorno alla corte di ABITES. 
Era un ragazzo talentuoso. Spavaldamente ingenuo. La divisa immacolata: camicia sartoriale di cotone purissimo senza una piega. Varcava per la prima volta i cancelli termici dorati, un colosso impettito che entrava per disegnare la macchina capace di redimere un mondo caotico. Ricordava l'effluvio delle cere carnauba spalmate dai robot lucidatori. Ricordava il sorriso inappuntabile di Julian Vane, lo stringergli vigorosamente la mano sudaticcia del genio prescelto chiamandolo "Figlio della Razionalità". 
A quei tempi non riconosceva le cinghie che l'avrebbero zittito. Analizzava puramente la geniale connettività logica, i link. L'arroganza purissima della gioventù elettromagnetica. Ora, dieci decenni spirituali condensati in pochi anni reali dopo, lui, l'Architetto supremo delle sbarre, scavava fango nero da topo disperato tra lamere tagliate. Macchiato del sangue indurito e rancido procuratosi con le sue stesse difese assassine, distruggeva l'orgoglio del primo respiro della sua anima morta.
Un crepitio infame bloccò la riflessione di un tempo perduto.
Un ammasso irto di alluminio scese verticale da un manicotto scartato a un metro e mezzo sopra di lui. Un drone aracnoide pesantemente armato da ispezione condutture a otto lame taglienti. Senza server guida, il robot aveva resettato al protocollo di autodifesa basale: attacco indiscriminato nella cecità. Un fascio laser incandescente, color carminio intenso, proiettato dall'occhio centrale, cominciava a scansionare freneticamente i trenta centimetri di passaggio. Raschiava via i bordi di metallo creando minuscole e pericolose pozzanghere di stagno squagliato. Affettava a brandelli ogni filo sfoderato.
Il taglio a incandescenza sfiorò un osso della guancia di Claudio. Mancò la sua pupilla marrone, sbarrata dall'orrore, per mezzo nanosecondo tattico. Il fiato umano non si fermò. 
Un guizzo da rettile prese improvvisamente il controllo delle caviglie dello scienziato stanco. Laura spingeva. Con tutta l'inerzia muscolare rimasta sbarrò i piedi sul metallo corrugato e lo trascinò verso un invaso laterale, sfasciandosi e torcendosi la cassa toracica al limite dell'usura fisica, ma mettendo Claudio a ridosso di una saracinesca per lo smaltimento della guaina. 
Il drone ottopode, acido nei movimenti robotici, sferragliò alla forsennata verso il punto primario del laser. Troppo stupido dal distacco quantico del Mainframe, cozzò irrimediabilmente contro dei manicotti idrici di ritorno ad altissima pressione, conficcandovi le forbici per errore. Un getto disumano violento d'acqua purificata industriale schizzò investendolo. Misfire della matrice. I circuiti in cortocircuito lo arroventarono mandando una nuvola fumogena spessa da bruciare la gola.
«Fine linea, ragnatela schifosa,» ansimò debolmente Laura, appoggiando l'armatura contro le costole scosse del ragazzo. «Siamo vicini.»
E il gelo penetrò improvviso tra l'odore tossico del fil di ferro. 
Non un condizionamento di microchip. Non aria chimicamente prefiltrata. Era roba naturale. L'aere odorosa impregnata di terra fradicia, l'alito dei pini di Roma, l'abbandono bagnato della tormentata urbe. Profumo denso di fango millenario, misto allo sterco per le piazze senza mezzi che risuonava prepotente. Un colpo decisivo ai muscoli per lottare per l'ultimo mezzo metro quadro. 
Sbucarono, trascinando piedi insanguinati e braccia appese al niente, sgrovigliando il nastro adesivo sigillante da una botola tonda da chiusino scuro posta nell'immane parcheggio posteriore esterno dell'EUR. 
Ad accoglierli il trambusto acquatico. Pioggia sferzante a corda grezza scoccava durissima contro le spaccature dell'asfalto mal curato, frustava loro i fianchi tremanti. Dietro le taglienti gocce, si stagliava un abisso verticale. La Torre. Un accecato, possente moloch che rantolava vuoto di sguardi di silicio. Solo led intermittenti di sicurezza grigia balbettavano isolati ai piani più declassati privi del volere intelligente.
Cittadini alienati venivano vomitati giù dai ponti per le gradinate, singhiozzando all'inverosimile, privi del chiasso rassicurante impiantato dai loro creatori folli. Calpestavano valigette colme d'inezie che si perdevano spazzate alle bocche di fogna otturate. Alzavano la testa confusi guardando su atroficamente: non una proiezione del sole, si scoprirono bagnati sotto i veri, nerissimi nuvoloni scossi dalla burrasca romana per la prima alba di millenni privi di byte.
Laura collassò sulle ginocchia graffiate all'inverosimile, piegandosi fradicia sotto il castigo delle piogge e sbiancando i denti nella semioscurità desolata. Spostò faticosamente lo sguardo all'apoteosi del massacro silenzioso alle rampa enormi dell'attico invisibile. 
«Ce l'hai fatta allora? Pensi sia la vera fine... la vera fine di noi... Claudio?» mormorò quasi tossendo melma.
Ferretti stazionò di fronte al vuoto impazzito e tenebroso dello scheletro dell'Eur bagnato dall'apocalisse primordiale. Guardò le sue mani incapaci. 
«Non è così,» respirò grave. «Guarda i loro volti ciechi. Ho tolto l'interruttore finto alla macchina. Ora... adesso dobbiamo sopportare il silenzio freddo del baratro infinito in cui riacquistare l'io rotto e perso. Senza più padrone ma... non ancora veri padroni.» 
Sorrise debolmente riflettendo al chiuso dell'ascensore. E vide le antiche, sporche ma sicure mani di un Vecchio Pietro aggrappato che puliva un targa dimenticata mentre la città precipitava dal podio fatale della storia non avvertendo i tonfi, ignorando del tutto quanti corpi avrebbero ceduto per fuggire dall'inferno.`;
