export const chapter39Content = `Macro-Capitolo 39: Danni Collaterali
[ROMA - VIE DEL NORD - LAURA, CLAUDIO E MARA]
Il furgone bianco era conficcato nel palo dell'alta tensione. Il metallo della scocca era accartocciato. Le ruote posteriori giravano a vuoto nell'aria piovana. Emettevano un fischio idraulico stridente. Claudio osservò il relitto. Il logo statale di TeleNord era sfigurato. Litri di denso olio sintetico luccicavano sull'asfalto sbrecciato. Era il sangue nerastro delle macchine distrutte.
Avanzarono febbrilmente rasenti al muro grigio. Laura faceva da avanguardia. La spessa lamiera dello sportello era divelta. La grossa mano di una giovane donna pendeva da fuori. Morta. I droni militari sciolti dai server avevano colpito il veicolo con cariche cinetiche d'alta quota. Una brutale repressione post-blackout. Claudio guardò verso nord-est. Il tracciato a quattro corsie era desolatamente vuoto. Era una grande ferita fumante di ceneri velenose cittadine.
«BROADCAST-GUARDIAN-7 riattivazione d'emergenza,» gracchiò l'altoparlante moribondo impastato d'acqua fangosa.
La colossale intelligenza artificiale di zona era orba ma testarda. Proteggeva passivamente la Torre Madre. Nella cecità operativa del distacco server forzato, la possente entità stava erigendo lo scudo elettromagnetico estremo per isolare la struttura. L'aria carica d'acqua attorno a loro iniziò a vibrare ferocemente. 
Claudio sentì un prurito insopportabile e pizzicante come aghi sottili. La nuda pelle martoriata del viso madido bruciava. I polmoni gonfi di farmaci divennero grezzi e stanchi macigni. Respirare a fondo lì dentro era come ingoiare mercurio gassoso. Era lo spietato effetto neuro-vascolare della massiccia ionizzazione dell'aria. Un raggio d'azione compresso dall'invalicabile barriera letale del costrutto d'allarme. Il mostro morto meccanico stava disperatamente cercando di arrostire i componenti elettronici degli invasori. Senza alcun discernimento o scrupolo morale filtrava i passanti e friggeva vivi per asfissia arteriosa anche i vasi sanguigni umani infiammandoli.
Sbandarono sfiniti a bocca aperta in cerca d'aria pura nel tunnel di scarico rovinato. Qui incrociarono la figura di Mara.
Mara era un coraggioso chirurgo vascolare metropolitano. Una profuga dal quadrante ospedaliero Ovest esploso ore prima e raso al suolo dalle truppe fisse automatiche. Era fiera e saldamente inginocchiata nel duro fango. Scriveva pragmatica appunti clinici con un mozzicone di gesso sull'asfalto sbrecciato. Un giovane operaio magrissimo ferito mortalmente al torace giaceva debole vicino alla fessura cieca di scolo.
Mara indossava lo sgualcito camice ospedaliero consunto. Buttato sopra pantaloni jeans strappati. Le strette maniche sudate lasciavano esposte le braccia graffiate al gelo autunnale.
La sua borsa giaceva slegata al suolo. Ogni benda, cerotto emostatico e siringa era perfettamente squadrato e speculare. Un ordine clinico freddo, ostinato e maniacale. Un fiorire di dura logica in questo caotico e letale disastro stradale.
«Ferita emorragica obliqua da frammenti di muro a basso potenziale cinetico,» sentenziò clinica la dottoressa Mara guardando Claudio. «Fegato rovinosamente contuso. La febbre emorragica ti asfissierà. Svuoterà e annienterà le tue funzioni in due brevi misere ore di vita.»
«Scappate da qui, fuggite andate via,» incalzò fredda Laura impugnando l'arma.
«Io sudo, opero, freno l'emorragia e resto qui alla disperata,» mormorò la dottoressa Mara con caparbietà senza alzarsi dal paziente. 
Claudio ingranò zoppicando verso la galleria ferroviaria di fuga per schivare il mirino ottuso del drone in picchiata.
Il letale drone piombò cacciatore in planata verticale. Il rapido fuoco chirurgico automatico piovve cinetico sul selciato.
Il primo colpo proiettile bucò l'asfalto fradicio a vuoto.
Il secondo colpo cinetico infallibile sventrò in pieno la fiera schiena dritta della coraggiosa dottoressa Mara.
Il respiro del giovane caduto si stroncò. Il corpo inerme di Mara crollò pesantemente svuotato nel fango gelido cittadino. Una morte ingiusta sul campo.
L'algida e chirurgica Laura oltrepassò cinica la tragedia umana di quel lutto, tirando rudemente il braccio dello stanco compagno ingegnere. Trascinò Claudio verso il buio portone della mastodontica centrale elettrica di Trasmissione. L'ultimo assalto nel cuore del mostro.`;
