export const chapter39Content = `Il furgone era conficcato nel palo della luce, un montante di calcestruzzo armato che lo aveva aperto come un barattolo di carne in scatola. Il metallo si increspava attorno al cemento in pieghe violente, cangianti dal grigio al nero, mentre il muso del veicolo puntava verso il cielo, le ruote anteriori che oscillavano nel vuoto, sospinte solo dalla tensione del paraurti stritolato. Il logo dell'emittente—TeleNord—era sfigurato, una sagoma irriconoscibile di pittura blu staccata a lamine, una reliquia di un’era informativa che non riusciva più a pronunciare sillabe complete. Claudio sentì il voltastomaco riemergere, mescolandosi al sapore di carburante bruciato che rendeva l'aria densa, viscida sulla lingua. Laura procedeva a mezzo passo avanti, le braccia tese in una geometria di difesa che rispondeva al ronzio dei droni in lontananza. La porta laterale del furgone era aperta, un invito squarciato verso l'oscuro. Una telecamera con il tri-obiettivo schiacciato dal telaio piegato giaceva al suolo, e una mano—piccola, nervosa, con le unghie mangiate—usciva dal buio del vano, immobile, le dita che toccavano l'asfalto senza più trasmettere impulsi. Claudio non allungò lo sguardo. Il fianco pulsava, un martello che batteva a ritmo di cuore sul suo costato. Continuarono a camminare.
Sul tetto del furgone, i segni dell'irruzione erano incisi nella lamiera come cicatrici di un bisturi chirurgico: tre fori equidistanti, i bordi ripiegati verso l'interno, netti, denotando l'impatto secco di proiettili cinetici a saturazione. Claudio girò la testa verso nord, le narici che cercavano aria meno satura della distruzione recente. Il dolore al fianco non era un dato, era una presenza che pesava quanto il piombo. Laura teneva il passo, senza una parola ad alleggerire la fatica del movimento. Sessanta metri di asfalto, poi altri sessanta, le suole degli stivali che grattavano pietre e scorie. Svoltaro in via Pradella. I lampioni, mezzo esplosi o spenti da un comando remoto, lasciavano spazio solo alle luci di emergenza che pompavano un rosso ciclopico, pulsante, un battito cardiaco artificiale che tingeva gli edifici abbandonati di un rubino malato.
Una donna era ferma contro una vetrina infranta. Teneva il gesso in mano, un bastoncino bianco che strisciava contro un pezzo di cartone nero accostato al telaio della vetrina. L'uomo seduto sotto di lei aveva il braccio avvolto in strati di bende che sembravano aver visto più sangue che cotone. La donna indossava un camice verde, sporco, sopra il giubbotto di pelle logora. Le maniche rimboccate rivelavano avambracci segnati dalla fatica. La borsa di tela ai suoi piedi era aperta, un arsenale clinico disposto con una logica che ignorava il caos della strada. Claudio si fermò, il peso del corpo spostato tutto sulla gamba sana. Il fiato gli usciva in piccoli sibili, la gola rivestita di polvere e rame. La donna li fissò mentre si avvicinavano, i bulbi oculari dilatati, privi di esitazione. Non c'era traccia di terrore in quegli occhi, solo il ricalcolo freddo di chi ha visto abbastanza carne aperta per non temere più l'ignoto.
«Ferita da arma.» La voce era ferma, intrisa di una stanchezza che non cercava consolazione.
«Suturata.» Laura risposte senza abbassare la Glock.
«Quante ore fa.»
«Sei, forse sette.» La medica finì di fissare la garza sul braccio dell'uomo con un nodo secco. Si rialzò, le ginocchia che scricchiolavano. Guardò Claudio, lo studio dei muscoli tesi, del modo in cui portava il peso, della piega di dolore che segnava la mascella. «Sto andando verso il Civile. Ma il Civile non esiste più. I sistemi di triage sono in stasi. Vengo con voi finché posso essere utile.» Mara, la medica, si fiondò tra loro, la borsa medica che sbatteva ritmicamente contro il fianco. «Ho visto cosa fanno quei droni. So da dove vengono. Chiunque stia andando a fermarlo, non voglio essere dall'altra parte.»
Un ronzio roco arriverà da nord-east. Era la frequenza della morte incapsulata in cromo e sensori termici. Basso, multiplo, la sovrapposizione di ronzii che facevano vibrare la spina dorsale. Laura si piantò sull'asfalto. «Corriamo.» Il rumore di Mara che correva suonava stridente, inadeguato alle asfaltate di guerra. Claudio trascinava il fianco, il calore della ferita che diventava un fuoco vivo che bruciava l'intera muscolatura. Il primo drone bucò la linea dei tetti come un predatore astrale. Sputò fuoco sull'asfalto, un impatto che grattò la pietra a pochi passi dai loro piedi.
Claudio scartò verso destra, buttandosi attraverso l'apertura di un portone socchiuso. La spalla impattò contro il legno fradicio, una fitta che si espanse fino alla base del collo. Rotolò sul pavimento di quel vano atrio, la pelle che bruciava per lo sfregamento. Laura entrò un battito di ciglia dopo, la Glock puntata verso l'esterno. Il drone passò sopra di loro, un'ombra meccanica, fredda, che oscurò per un istante il rosso dei lampioni. Virò. Tornò indietro.
Mara aprì la borsa. Le mani si muovevano come scattate da molle — una ricerca rapida, precisa. Controllò la fasciatura di Claudio. Non disse una parola, la sua testa si inclinò di un grado, un segno che il lavoro era tenuto insieme dal filo, dalla fortuna e dalla chimica.
«Due,» disse Laura, il tono che raschiava come ghiaia. «Forse tre. Stanno aspettando che usciamo.»
«C’è un'uscita sul retro.» Mara indicò l'oscurità del corridoio interno.
«Lo so,» disse Laura. «Dobbiamo attraversare la strada aperta per cinquanta metri. Dalla porta al sottopasso.» Laura controllò il caricatore — il peso del metallo nella mano, la certezza dei proiettili. «Voi due davanti. Io dietro.»
Uscirono. Il vuoto della strada aperta li inghiottì. Il drone reagì prima che potessero contare fino a due. Claudio spinse le gambe, il fianco che gli mandava segnali di fallimento imminente, la ferita che pompava sangue nuovo. Il primo impatto scoppiò a un metro da lui, una nebbia di bitume e detriti che si schiantò contro i suoi polmoni togliendo il fiato.
Il secondo impatto solcò l'aria e trovò Mara. Il corpo della medica si schiantò sul selciato con la precisione di un peso morto, il rumore del contatto con l'asfalto coperto dallo stridore di un motore metallico in avvicinamento. Laura non rallentò. Afferrò Claudio per il colletto della giacca, la forza del suo braccio che lo costrinse a mantenere un ritmo insostenibile per la sua carne lacerata. Lo trascinò nell'ombra del sottopasso, il drone che perse il segno, il tracciamento che vacillò di fronte ai muri di cemento armato che bloccavano i sensori.
Dall'altra parte, il quartiere Nord apparve come un miraggio pallido, una serie di ombre stese in un silenzio tombale. Sette persone emersero dai portoni, visi sporchi di fuliggine, giacche da pompiere che nascondevano i giubbotti antiproiettile di una resistenza che giocava d'azzardo con la vita. Lanciarono i distruttori di frequenze verso nord-est. I droni-esca, scagliati in aria, iniziarono la loro danza verso il ronzio dei cacciatori. Una manovra disperata, una melodia di richiamo per la morte. Il fragore delle mitragliatrici iniziò a battere, martelli di ferro su incudini di pietra, mentre Laura guidava Claudio verso la sagoma scura della Torre che svettava verso un cielo color piombo, una croce metallica conficcata nel petto della città.`;
