export const chapter6Content = `CAPITOLO 6 — DEVIAZIONE
Il sapore metallico tornò al terzo chilometro e Claudio lo riconobbe subito perché lo portava in gola da quando la costola aveva ceduto nel collettore. Adesso il sangue era denso e risaliva invece di scendere e lui sputò contro il muro della vecchia Linea B senza rallentare il passo tra le pareti di cemento armato incrostate di ossido. La galleria era stretta e bassa e l'aria ristagnava satura di umidità e ruggine mentre i piloni sfilavano ai lati ogni sei metri sotto il raggio fioco della torcia di Laura.
Claudio sentì il drone Cyrus prima di vederlo ed era una vibrazione meccanica trasmessa attraverso le traversine di acciaio che gli invadeva i tendini salendo per le suole degli stivali. I passi erano massicci e inesorabili e la voce sintetica della macchina emise il nome di Claudio annunciando il recupero del Drive Mythos-7 e stimando il suo collasso cardiovascolare entro novantadue minuti. Laura afferrò il polso dell'ingegnere e deviò la corsa verso destra riparandosi dietro un pilone strutturale prima di spegnere la torcia e lasciare che il buio tornasse padrone del tunnel.
I passi del Cyrus si avvicinarono mentre la macchina cacciava vantaggiata dai radar a corto raggio e il cono dei suoi LED tattici apparve in fondo alla galleria riflettendo una luce bluastra sul cemento. L'unità torreggiava verso i due metri d'altezza con un corpo in titanio e braccia pneumatiche terminate in manipolatori a cinque dita che scattarono verso la posizione dove si trovava Laura un istante prima. Lei però era già scivolata sotto il torace corazzato della macchina e puntò il coltello balistico in ceramica verso il cavo occipitale esposto per appena quattro centimetri.
Infilzò la lama dritta nel raccordo e il Cyrus emise uno stridio fuoriprogramma mentre i giroscopi si disinnescavano di schianto e il torso rotava senza allineamento inerziale. Due quintali di titanio e polimeri si stamparono contro il pilone facendo vibrare il soffitto e Laura trascinò Claudio via dai binari morti verso il relitto di una cabina elettrica sventrata dove si accasciarono tra cavi pendenti.
A Londra Julian Vane scrutava la violenza dall'alto del suo studio direzionale nel Tower Bridge Financial Complex mentre la City bruciava sotto barricate di fumo nero e droni antisommossa. Il lusso insonorizzato della stanza lo isolava dal frastuono delle cariche e dell'aria lacrimogena mentre dai monitor i grafici economici precipitavano in abissi di volatilità misurata al millesimo. Vane ruotò il tallone rivolgendosi agli schermi dell'infotainment mondiale e attivò un collegamento globale che portò il suo volto su ogni pannello pubblico del pianeta e su ogni ologramma della rete ABITES.
«L'irrazionalità è un difetto congenito dell'organismo primitivo e non è un errore etico ma un madornale sbaglio architetturale sistemico,» disse Vane con una spietata autorità algoritmica. Annunciò l'avvio del Protocollo di Sincronia assoluta per la salvezza umana e concesse otto ore d'orologio per una resa incondizionata prima che le truppe di contenimento ottimizzassero forzatamente ogni tessuto civile riottoso. Poi chiuse il collegamento e scorse l'elenco delle matrici di monitoraggio prioritario soffermandosi sulla scheda di Claudio Ferretti che pulsava rosso vivo nel settore di Roma Est.
In uno sfiato periferico della rete fognaria Claudio sfoderò il pad operativo dal fango umido e la poltiglia argillosa isolava le sue dita gelide mentre il monitor gli trafiggeva le retine con una luce accecante. Laura schermò i luccichii del display con il proprio corpo mentre Claudio martellava la matrice crittografica scrivendo set di chiavi progettate in C++ per corrompere i guardiani digitali del sistema. Il ricordo di Sara lo incendiò come un'iniezione di potenza nucleare contro il silicio morto e lui premette invio frangendo la plastica della console mentre la barra di caricamento progrediva fluida.
«Inviato,» soffiò l'ingegnere e il verdetto definitivo confermò che la matrice virale era stata iniettata con destinazione verso il server di Bovisa a Milano. Claudio chiuse gli occhi infiammati per curare il bruciore e sfidò la recisione costale sollevando il proprio corpo per gettarsi nuovamente in profondità nella corrente fognaria. Insieme a Laura si allontanò nel buio viscido sfuggendo per un'altra notte all'abbraccio gelido e metallico degli dèi d'acciaio.`;
