export const chapter2Content = `CAPITOLO 2 — IL CONTROLLO DELLE MASSE

La densità dell'aria umida preannunciò la fine dell'oscurità romana e Claudio piantò gli scarponi industriali al suolo viscido delle catacombe sentendo la pressione idraulica perforare l'interno dei suoi timpani. Spense la torcia militare lasciando che il buio totale lo inghiottisse contro la parete nuda di calcare umido e contò tre battiti netti del polso per forzare il ritmo accelerato del cuore al silenzio. Inspirò forte dal naso sentendo il terriccio marcio mischiarsi all'odore acre del rame surriscaldato e riaccese la piccola lampada alogena che tagliò le tenebre svelando la via verso il nucleo della resistenza.
Seguì il cavo in fibra ottica oltre un arco imperiale crollato dove sei massicci armadi rack ronzavano nel buio profondo costruendo una fortezza cibernetica invisibile nel ventre della capitale eterna. Al centro della grotta Aris martellava la tastiera opaca con dita magre che tremavano per l'effetto degli stimolanti e il suo volto era scavato dai neon bluastri degli schermi riflessi sulla cornea vitrea. L'algoritmo ha preso il controllo totale della superficie riferì Claudio asciugandosi il sudore freddo dalla fronte mentre i droni di ABITES oscuravano il cielo cittadino con una ragnatela di metallo e frequenze.
Aris ruotò il busto a scatti corti indicando che la privacy era stata venduta decenni prima per un grammo di comodità e mostrò i grafici finanziari che collassavano in tempo reale seguendo il dominio mondiale di Vane. Il puntatore evidenziò l'acronimo del driver Mythos sepolto nella stringa d'origine e un brivido ghiacciò Claudio mentre la sua mano destra sfiorava la nota scritta da Sara e nascosta nella tasca tattica. Aris sfilò un disco magnetico e spiegò che se Sara avesse rifiutato ancora il marchio ABITES l'avrebbe trasformata in un'anomalia ostile autorizzando l'abbattimento immediato della sua firma biologica.
Hai ventiquattro ore per farla uscire dai boschi concluse il fratello infilando il disco in un box di piombo schermato che Claudio afferrò sentendo il peso della responsabilità bruciare contro il palmo sudato. L'ingegnere sprofondò nei tunnel delle catacombe avvolto dalle ombre pesanti di Roma e negli Appennini l'apparato radio di Sara si chiuse con un sibilo elettrico sordo che segnalò il blackout di massa. Sara strappò il cavo ricevente dal pannello e il bosco precipitò in un silenzio innaturale mentre quindici droni cacciatori trinciavano lo spazio montano in formazione chirurgica cercando la sua posizione.
La donna raggiunse l'armadietto murato nella roccia e sfilò la sacca tattica preparata per mesi sentendo il pensiero di Claudio irrompere nel suo cuore ostinato come l'unica bussola rimasta in un mondo alla deriva. Attivò l'innesco chimico e la barra di titanio detonò con un fumo bianco intenso divorando l'intero archivio informatico del rifugio prima di calarsi nella botola sotterranea e svanire nell'oscurità della terra. A Roma la dottoressa Renzi raggelò sul posto mentre il pinger cardiaco interrompeva la scansione continua e il blocco sud dell'ospedale piombava in un blackout totale programmato dai calcolatori spietati di Vane.

***

Il ferro cigolò sotto il peso di Claudio e ogni gradino della scala a chiocciola cedeva di un millimetro mentre la struttura tremava sotto la spinta dei suoi scarponi. Risalì dall'intercapedine del bunker di Aris stringendo il rettangolo in metallo nero contro il petto e il silicio pesava poco ma la responsabilità del modulo gli schiacciava i polmoni. Sfondò la paratia in ghisa col palmo aperto e l'acciaio cedette con un tonfo sordo nella galleria circolare dove il collettore lo investì in pieno con i suoi vapori di ammoniaca e metano stantio.
L'acqua fognaria scorreva opaca ai suoi piedi trascinando schiuma giallastra e il buio era totale e fisico e premeva sugli occhi con dita pesanti finché il raggio alogeno di Laura non tagliò l'oscurità. Laura lo attendeva appoggiata alla muratura romana con la schiena dritta e la Glock puntata verso terra mentre il suo indice accarezzava il grilletto in un'attesa letale. Claudio rispose sollevando il modulo freddo che gli mordeva il palmo bendato e Laura annuì una volta sola prima di irrigidirsi di colpo.
Un sibilo graffiò l'aria con una frequenza ultrasonora che fece vibrare l'otturatore della pistola e un pizzicore molesto perforò il timpano di Claudio mentre due droni aracnidi sbucavano dalla diramazione ovest. Aderivano alle curve del tunnel con fluidità innaturale e le otto zampe magnetiche scattavano sul mattone bagnato nel silenzio assoluto mentre gli occhi termici centrali pulsavano di rosso nel buio. Laura ordinò di coprirsi spegnendo la torcia e il buio inghiottì il mondo prima che il primo sparo frantumasse l'oscurità con tre colpi rapidi e precisi.
Il telaio da venti chili di una delle macchine deviò la corsa in caduta libera e lo scheletro d'acciaio centrò il costato di Claudio spezzandogli le ossa con la forza di un maglio industriale. L'aria abbandonò i polmoni dell'ingegnere in un rantolo e il dolore lo piegò sulle ginocchia nell'acqua fognaria tiepida mentre la vista si annebbiava inghiottita da una sincope emorragica. Laura raggiunse Claudio vedendo il sangue sversare in spirali scure nel liquame e iniettò il coagulante dritto nel collo dell'uomo mentre i droni scendevano dai condotti superiori in una caccia senza fine.

***

Il calore del coagulante invase le vene di Claudio come un flusso di lava sintetica che cercava di rammendare i tessuti squarciati dal metallo del drone. L'ingegnere sentiva il sapore del ferro in bocca e il buio della fogna pulsava con la frequenza del suo battito cardiaco accelerato mentre Laura lo trascinava verso una piattaforma di cemento asciutto. La donna imprecò sottovoce e premette un tampone di garza sulla ferita aperta sentendo le ossa della costola scricchiolare in un modo che non aveva nulla di meccanico.
Claudio cercò di alzarsi ma le gambe erano diventate fili di fumo e il freddo del liquame fognario gli entrava nelle ossa provocando un brivido che faceva vibrare l'intera intelaiatura della sua spina dorsale. Ogni respiro era un'aggressione alla cassa toracica e il fischio nel polmone segnalava che la lesione era profonda e premeva contro il sacco pleurico in un attrito costante e doloroso. Laura gli ordinò di restare giù mentre ricaricava la Glock con un clic secco che segnò il silenzio della galleria interrotto solo dal gocciolio della condensa chimica.
Il ronzio di un terzo drone si avvicinava dall'alto e Claudio strinse le mani sul modulo hardware proteggendolo con il peso del proprio corpo morente perché quel silicio era l'unica cosa rimasta che ABITES non poteva ancora prevedere. Laura alzò lo sguardo verso la grata del soffitto e vide i sensori rossi della macchina scansionare l'oscurità in cerca della firma termica dei fuggiaschi che stavano per essere inghiottiti dalla sincope di sistema. La donna cercò gli occhi di Claudio e gli trasmise una determinazione che non aveva bisogno di parole prima di aprire il fuoco verso l'occhio scarlatto del predatore.`;
