export const chapter34Content = `Il Crollo Imminente si annunciò con un sibilo sottile, un rumore di polvere che scivolava tra le fessure del cemento. Claudio e Laura stavano percorrendo il tunnel di servizio numero sette, una galleria stretta che correva parallela alla linea principale. Le pareti vibravano sotto la pressione di ABITES, che stava inviando onde d'urto nel terreno per stanare i possibili infiltrati.
Claudio sentì il pavimento tremare sotto i suoi piedi. Una crepa si aprì all'improvviso sul soffitto, lasciando cadere pezzi di intonaco e detriti. Laura lo spinse avanti con prepotenza. "Corri!" gridò, la sua voce che rimbalzava contro le pareti di metallo.
La corsa fu una danza frenetica contro la morte. Ogni passo era una scommessa, ogni respiro un lusso in quel vuoto che si riempiva di polvere soffocante. Claudio sentiva il dolore alle costole infiammarsi a ogni sobbalzo, una pugnalata costante che gli toglieva il fiato. Le sue mani cercavano appigli nel buio, tra cavi scoperti e tubi che perdevano vapore bollente.
Dietro di loro, il tunnel stava cedendo. Un boato sordo indicò che una parte della volta era crollata, bloccando la strada da cui erano venuti. L'aria divenne una nebbia di polvere bianca e grigia che toglieva la vista e bruciava i polmoni.
Claudio cadde in avanti, inciampando su una trave di ferro divelta. Sentì il colpo al ginocchio e la pelle che si spaccava contro il metallo. Laura lo afferrò per la giacca e lo trascinò verso una nicchia laterale proprio mentre un'altra sezione del soffitto veniva giù.
Rimasero immobili, schiacciati contro la roccia fredda e umida. Il rumore del crollo morì in un vuoto assoluto, interrotto solo dal fischio di una valvola rotta in lontananza. Claudio tossì a lungo per liberare la gola dalla polvere. Sentiva il sapore del sangue fresco in bocca e il battito del cuore che gli martellava nelle orecchie.
Laura lo guardò attraverso lo strato di polvere che le copriva il viso. I suoi occhi erano lucidi e decisi. Controllò che la borsa con i file fosse intatta. Nonostante il disastro, il segreto era al sicuro.
Dovettero scavare con le mani nude per liberare un passaggio tra le macerie. Il cemento era tagliente e le unghie di Claudio si spezzarono, ma il dolore era solo un rumore di fondo. La necessità di sopravvivere era l'unico pensiero che occupava la sua mente.
Riuscirono a infilarsi in un condotto di aerazione laterale. L'aria era gelida e sapeva di metallo vecchio, ma era respirabile. Si trascinarono lungo il condotto, con le spalle che strisciavano contro le pareti di lamiera. Ogni centimetro guadagnato era una vittoria contro il peso del crollo imminente che ancora minacciava di schiacciarli.
Sbucarono in una vecchia sala macchine, dove grandi trasformatori elettrici giacevano immobili come monumenti a un passato industriale scomparso. Claudio si sedette a terra, con le gambe che gli tremavano. Guardò le sue mani ferite e vi vide il segno di una lotta che non ammetteva sconfitte. La Torre era ancora lì, invisibile sopra di loro, ma la loro determinazione era più solida del cemento che era appena crollato.`;
