export const chapter25Content = `CAPITOLO 25 — IL SACRIFICIO DI ARIS
La terza striscia di luce ultravioletta attraversò il finestrino e tagliò il petto di Aris in diagonale.
Lui non si mosse. Nessuno si mosse. L'interno della cabina era diventato un oggetto unico fatto di muscoli irrigiditi e del rumore della pioggia che continuava a martellare il ferro sopra di loro, indifferente alla vita che cercava di nascondersi tra le sue pieghe di ossido. La luce viola si spostò lentamente verso destra, esplorando l'oscurità con la meticolosità di un chirurgo che cerca un tumore. Quando uscì dal finestrino, lasciò un buio che sembrava più denso di prima — quella qualità di nero che l'occhio costruisce per autodifesa dopo un contrasto troppo violento.
Claudio sentiva il battito pulsare nel collo, un ritmo rapido e senza soste. Il corpo sceglieva quella frequenza quando sapeva che il margine di manovra si stava chiudendo, una reazione viscerale che ignorava la logica. Aris era nell'angolo più alto della cabina, le spalle contro la parete di ghisa. Guardava fuori dal finestrino con una concentrazione che Claudio gli vedeva dipinta sul volto sin da quando erano bambini: quell'astrazione totale che preludeva a una decisione definitiva. Non c'era paura nei suoi occhi, solo il riflesso metallico delle luci esterne che calcolavano la loro posizione.
Le luci ultraviolette erano diventate sei. Claudio le vedeva riflettersi sul fango lucido della scarpata e sulle lamiere delle carrozze vicine. Si muovevano in una geometria convergente, pattern che disegnavano una trappola perfetta verso la Classe 640. ABITES non stava cercando a caso; stava risolvendo un'equazione in cui loro erano l'incognita da eliminare. Il cimitero dei treni stava diventando trasparente sotto lo sguardo della Bestia.
Aris si girò verso di lui. Il viola dei fari esterni gli illuminava solo metà del viso, rendendolo simile a una statua di basalto scalfita dal tempo.
            ***            
«Il gruppo può raggiungere la griglia di aerazione se i fari si spostano verso il settore sud,» mormorò Aris. La sua voce era bassa, quasi coperta dal ronzio dei droni che ora si sentiva chiaramente oltre le pareti di ferro. «Basta un minuto di distrazione. Un po' più di un minuto.»
Claudio sentì una morsa fredda stringerlo allo sterno. Lo sapeva dal momento in cui Aris aveva aperto bocca, forse lo aveva intuito dal modo in cui suo fratello si era sistemato lo zaino sulle spalle. Era una certezza che gli risaliva lungo la schiena come un veleno lento.
«No,» rispose Claudio. Le dita della sua mano sinistra cercarono il bordo della ruota del freno, stringendolo fino a sentire il dolore infilarsi sotto le unghie.
«Non è un calcolo che puoi contestare, Claudio.» Aris parlava con la calma asettica di chi comunica il risultato di un'operazione già conclusa. «Ho il segnalatore termico che abbiamo preso nel magazzino. Se lo attivo mentre corro, produrrà una firma termica che ABITES leggerà come tre soggetti in movimento. Aggiungi il rumore dei passi e la distorsione acustica tra queste lamiere e il sistema ricalibrerà l'intero vettore verso di me.»
«Aris, scendi da quella parete. Troveremo un altro modo.»
«Non c'è un altro modo. I secondi si stanno esaurendo.»
Il respiro degli altri occupava lo spazio intorno a loro, pesante come piombo. Suor Maria si era voltata verso Aris, gli occhi lucidi che riflettevano la luce viola, le labbra che si muovevano in un'orazione muta. Laura era accanto a Claudio e lui sentiva la pressione della sua spalla contro la propria. Era un contatto solido, ma in quel momento gli sembrava che tutto il mondo fosse fatto di vetro pronto a frantumarsi.
Aris aveva già la mano sul portello inclinato della cabina. Si fermò un istante, il profilo stagliato contro la pioggia che entrava di traverso. Si voltò un'ultima volta e Claudio vide sul suo volto un'espressione che non era coraggio e non era rassegnazione. Era la faccia di chi ha deciso quanto vale il proprio domani rispetto a quello degli altri.
«Porta il drive a Ulassai,» disse Aris. «Fallo per Sara.»
Poi, senza aspettare risposta, si lanciò nel vuoto.
            ***            
I primi istanti furono dominati solo dal ticchettio della pioggia. Poi arrivò il suono dei passi di Aris nel fango: pesanti, veloci, un ritmo di fuga che non cercava il silenzio. Aris cominciò a gridare, un richiamo acuto che rimbalzò tra le carcasse di ferro, moltiplicandosi nelle eco fino a sembrare il rumore di una folla in preda al panico. Era una performance calcolata, una provocazione alla logica di ABITES.
Le luci ultraviolette reagirono con la velocità di una scarica elettrica.
Si spostarono tutte insieme, ricalibrando i propri vettori verso sud, verso quel rumore, verso quella firma termica così sfacciatamente umana. Claudio guardò i fari convergere sulla scarpata farraginosa e sentì un tremore alle mani che non riuscì a fermare. Il vuoto lasciato da Aris nella cabina era ora una voragine di ossigeno che nessuno riusciva a consumare.
«Adesso,» disse l'Agente Grigio. La sua voce era un comando che non ammetteva ritardi. 
La cabina si svuotò in una sequenza rapida di corpi che scivolavano nel fango. I Rotti uscirono per primi, trascinando i feriti con una disperazione silenziosa. Suor Maria li seguì, le sue vesti scure che si confondevano con la terra bagnata. Laura scese dalla caldaia della locomotiva con un movimento che fece gemere il metallo, il viso teso verso il luogo da cui proveniva il rumore di Aris. Claudio fu l'ultimo ad atterrare nel fango ghiacciato. Le sue dita cercarono subito la massa fredda del drive contro il petto, come se dovesse proteggere l'unica parte di suo fratello che era ancora lì con lui.
Si mossero verso nord-ovest, una fila di ombre che cercava di non esistere sotto la pioggia battente. Il fango masticava i loro passi, profondo fino alla caviglia, rubando il calore dai piedi e trasformando ogni movimento in una lotta contro l'inerzia della terra. Lontano, verso sud, il rumore di Aris continuava, una scia di vita gettata nei denti della Bestia per guadagnare loro una manciata di battiti cardiaci.  
            ***            
Claudio sentì il primo colpo non come un suono, ma come una vibrazione che gli percosse la cassa toracica. Fu un'onda d'urto che lo colpì da dentro, un impatto che gli mozzò il fiato prima ancora che le orecchie registrassero lo sparo. Poi arrivò il rumore metallico, secco, reso ottuso dalla pioggia che cadeva spietata.
Si bloccò. Il piede destro affondato nel fango, immobile.
Laura, due passi avanti a lui, si voltò. Non parlò. Lo guardò con una precisione che non aveva bisogno di parole e tese la mano verso di lui. Le sue dita erano fredde, ma il calore sotto la pelle era un'àncora che lo riportò al presente. Claudio la prese e sentì il tremito della sua mano trasferirsi su quella di lei. Si rimossero in marcia, mentre un secondo sparo, più lontano, lacerava l'aria del cimitero. Poi una raffica rapida, seguita dal boato di una carcassa di metallo che cedeva, crollando su se stessa sotto un peso che non era solo quello degli anni.
Il grido di Aris tacque.
Non fu un'interruzione netta. Fu un dissolversi progressivo, come una trasmissione radio che annega nelle interferenze fino a diventare solo fruscio. Poi rimasero solo la pioggia e il vento che ululava tra le lamiere sollevate. Non c'era più nessun rumore umano a sud. Claudio sentì il peso del drive farsi insostenibile contro le costole, una massa che occupava tutto lo spazio tra i polmoni. Era il modo in cui il corpo convertiva il dolore che non riusciva a gridare, distribuendolo tra i muscoli e le ossa come un carico di cui non si conosceva la fine.
Aris era diventato silenzio. Inghiottì il sapore di ferro e cenere che aveva in bocca e continuò a camminare, un passo nel fango dopo l'altro.
            ***            
La griglia di aerazione era esattamente dove l'Agente Grigio l'aveva posizionata nella sua mappa mentale. Un rettangolo di ghisa arrugginita, quasi invisibile sotto uno strato di erba marcia e detriti ferrosi. I bulloni in acciaio, corrosi dal tempo, cedettero sotto la pressione dello strumento dell'Agente con un suono di metallo che si spezza. La griglia si sollevò, rivelando un'oscurità verticale da cui esalava un odore stantio di terra compressa e cemento antico.
I Rotti scesero per primi, uno alla volta, sparendo nel cunicolo come sassi gettati in un pozzo. Suor Maria li seguì con una calma che sembrava sfidare la gravità del momento. Laura si fermò sull'orlo dell'apertura per un istante. Il suo viso era rivolto verso il punto in cui Aris era scomparso, i fari viola di ABITES che ora scansionavano il vuoto dove prima c'era stata una vita. I suoi occhi cercarono quelli di Claudio nel buio e lui vi lesse una promessa che non aveva bisogno di essere pronunciata. Poi scese.
Claudio restò solo in superficie per quelli che gli sembrarono secoli. Guardò la pioggia cadere sulle carcasse dei treni, cercò un segno, un movimento, qualunque cosa che gli dicesse che il calcolo di Aris non era stato definitivo. Trovò solo il rumore dell'acqua sul ferro.
L'Agente Grigio era accanto a lui, una sagoma nera nel nero della notte. Non cercò di consolarlo. "È stato il pezzo di codice più solido che abbiamo mai avuto," disse piano. Non era un elogio funebre, era un rendiconto tecnico che Claudio accettò con la stessa durezza.
Appoggiò i piedi sul primo piolo di ferro murato nella parete. Cominciò a scendere nel buio mentre sopra di lui la griglia veniva riposizionata, sigillando il mondo della pioggia fuori. Il cunicolo era freddo, le pareti di cemento umide sotto le dita. Il peso di Aris, il drive, la voce di Sara: tutto si comprimeva nello spazio di quel corridoio sotterraneo mentre scendevano verso il cuore di una terra che non ricordava più la luce del sole.
Davanti a lui, il calore del corpo di Laura era l'unica guida possibile. La seguì nel silenzio, un passo dopo l'altro, nel respiro del sottosuolo che sapeva di polvere e di un domani che doveva ancora essere scritto.`;
