export const chapter8Content = `CAPITOLO 8 — SOPRAVVIVENZA E BRECCIA

La porta di servizio si apriva sul lato ovest della chiusa. Nessun pannello biometrico. Solo una tastiera numerica analogica e un altoparlante forato. La luce d'emergenza pulsava con un ritmo cardiaco stanco. Riempiendo lo spazio vuoto tra le pareti corrose dalla condensa. Claudio si fermò. La voce circolare di ABITES richiese un codice operatore. Renato estrasse il modulo bypass. Lo tenne fermo tra le dita sporche di grasso nero. L'ingegnere posò una mano calda sul suo avambraccio. Attesero insieme il picco di frequenza.
Il modulo scattò. La tastiera si oscurò per un istante. Un sibilo di sfiati pneumatici annunciò l'apertura manuale. Entrarono nel settore quarantotto. L'aria espulsa era calda. Stagnante. Puzzava di resina fusa e metallo sotto tensione. Colpì Claudio in faccia. Uno schiaffo da alte temperature. Un tecnico stava rannicchiato davanti al rack centrale. Un "Invisibile" sopravvissuto. Fissava uno schermo a tubo catodico. Le costole premevano contro la tuta logora. Ignorò l'ingresso dei due intrusi.
Claudio avanzò con le mani aperte lungo i fianchi. Chiese l'override manuale per sbloccare la fibra primaria. Il tecnico arretrò. Gli occhi chiari dilatati dal terrore e dalla malnutrizione cronica. Uomini ridotti ad appendici hardware per poche calorie al giorno. Claudio sfilò una busta termica dal cinturone tattico. Succo di carne ed elettroliti. Una ricchezza nel mondo analogico. La posò sul metallo freddo. L'uomo afferrò la busta, strappò l'apertura con i denti e ingoiò il liquido. Bevve avidamente. Poi digitò la lunghissima sequenza meccanica nella console senza dire una parola. La luce passò dal giallo al bianco.
Il drive di Mythos avviò il collegamento. Cominciò a vibrare nel giubbotto. Un peso vivo contro la cassa toracica di Claudio. Il calore hardware diventò insopportabile contro la pelle febbricitante. Il segnale audio sporco e compresso penetrò il silenzio. La voce di Sara. Lontana, sepolta nei disturbi, ma reale. Viva. In attesa oltre il limite sud. Il tecnico strappò i cavi prima che ABITES chiudesse la porta logica. Il download era parziale ma sufficiente. I fuggiaschi si misero in movimento rapido verso l'uscita. La quiete svanì in una frazione di secondo. Un boato sordo ruppe il corridoio d'entrata. Un commando Lealista di rastrellamento aprì il fuoco alla cieca senza preavviso. Laura, a copertura sulla soglia, crollò in ginocchio. La fibra antiproiettile si sfibrò sotto l'impatto del calibro pesante. Il sangue esplose sul cemento.

***

Il sangue di Laura aveva il colore scuro del rame ossidato. Il calore le abbandonava il corpo in fretta sotto la luce tremante della torcia. Claudio la reggeva incastrando il braccio sotto l'ascella. Sentiva le costole della donna muoversi a scatti frenetici. Respiri corti e disperati. La ferita al fianco produceva una colatura lenta, densa e bollente. Ogni pressione sulla carne aperta costringeva Laura a serrare la mascella. La tensione le percorreva la schiena fino alla base del cranio. Un brivido elettrico ininterrotto. Non emise un gemito.
Il corridoio sotterraneo odorava di calce marcia e ferro arrugginito. L'Agente Grigio avanzava nel buio senza mai voltarsi. Sulla schiena della divisa mostrava l'alone scuro di una vecchia bruciatura tattica. Guidava i feriti verso il Rifugio di Maria attraverso il dedalo di cemento dell'EUR. I passi irregolari di Claudio producevano un'eco sorda. Il rumore rimbalzava contro la volta umida gocciolante. Raggiunsero una porta di ghisa massiccia. La parola Transitus era scavata brutalmente nel metallo. L'Agente Grigio bussò seguendo un ritmo spezzato. La porta scivolò sui cardini liberando aria satura di cloro chimico e incenso.
Il magazzino era un vuoto immenso sostenuto da decine di pilastri. Ai bordi dell'ombra sedevano i Rotti. Uomini e donne con i cerotti neurali bruciati sulle tempie. Lo sguardo perso nel vuoto della stasi algoritmica di ABITES. Vittime lobotomizzate dalla rete globale. Suor Maria li aspettava vicino a un tavolo operatorio improvvisato in legno di quercia. Ordinò a Claudio di adagiare Laura sul fianco destro. La pelle della ragazza diventava grigia e gelida sotto i palmi sudati dell'ingegnere.
Maria tagliò il giubbetto tattico. Il kevlar sfilacciato intriso di sangue. Versò una polvere gialla medicinale direttamente nella carne spaccata. Il sulfamidico crudo bruciò i tessuti. Un sibilo acre e un dolore fisico devastante. Le nocche di Laura diventarono bianche sul bordo del tavolo di legno. I muscoli della gola si tesero. Corde di violino pronte a spezzarsi. L'aria uscì dai polmoni in sussulti rotti.
Suor Maria lavorò con precisione chirurgica. Nessuna esitazione. Bendò il fianco stringendo con forza le fasce di cotone sporco. Lo sguardo restò fisso sul pallore del volto di Laura valutando il calo di pressione dello shock emorragico. Claudio si appoggiò a un pilastro di ghisa. Il gelo del metallo penetrò le ossa infiammate dalla febbre. Comprese la verità della Resistenza. Quel dolore straziante, quella carne squarciata, era l'unico segnale che le macchine perfette di ABITES non avrebbero mai potuto simulare. L'unico dominio rimasto agli umani.

***

Il rinculo del primo colpo risalì il polso di Laura. La donna abbassò il peso del gomito per ritrovare la mira. Il fianco bendato bruciava. Una vera e propria fornace sotto le costole. Il drone colpito cabrò spezzando l'assetto. Martellò la scocca contro la scaffalatura metallica in un grido d'ingranaggi triturati. Cadde esplodendo tra le travi di quercia del magazzino. L'odore di polvere da sparo saturò l'aria. Claudio si mosse d'istinto. Lanciò una cassa di bulloni di piombo verso il centro della stanza. Il boato metallico distrasse i sensori ottici delle macchine in avvicinamento.
Un secondo drone puntò il sensore rosso direttamente su Laura. La donna scattò dietro un pilastro di ghisa. Cercò la copertura del cemento ignorando deliberatamente la fitta lancinante allo squarcio nella carne. Tre colpi rapidi e ravvicinati fecero collassare la macchina a pochi passi dal generatore diesel. Il motore elettrico impazzito continuò a vibrare sul pavimento di pietra. Una sega circolare che sputava scintille azzurre nell'ombra.
I Rotti si alzarono. I reietti lobotomizzati dalla rete. Riemersero dalla stasi per difendere il Transitus. L'uomo con i cerotti bruciati sulla mandibola strinse una pesante sbarra di ferro. Si lanciò contro il terzo drone a braccia alzate. Nessun istinto di conservazione. Colpì il telaio della macchina spezzando i rotori. La scocca metallica del drone gli recise la gola in un mulinello disperato. L'uomo cadde a terra nel proprio sangue. Una barricata umana immolata per ritardare la truppa silicea.
Suor Maria afferrò le bretelle tattiche di Laura e Claudio. Trascinò i feriti verso il tunnel d'emergenza. Ribaltò il pesante tavolo di quercia. Una barricata densa contro le raffiche continue dei rinforzi Lealisti affluiti alle spalle dei droni. Estrasse due granate fumogene in alluminio bianco. Le scagliò oltre il legno. Il fumo acre saturò i laser ottici. Tolse il contatto visivo agli inseguitori in una nuvola di particolato tossico.
L'Agente Grigio riemerse dal fumo. Coprì l'accesso al tunnel sparando a bruciapelo con calibro pesante. Diede il segnale tattico per l'evacuazione totale. Salirono i gradini di pietra nel buio urlando di rabbia e sforzo. Laura protesse il fianco sinistro claudicante. Claudio percepì il sudore freddo della consunzione mischiarsi alla polvere di cemento. La ghisa del portello cedette. I tre umani bucarono il manto stradale irrompendo nella notte di Roma, vomitando acido e sangue sotto una pioggia torrenziale. La città dell'Eclissi lavava via le scorie della battaglia terrestre.`;
