export const chapter28 = `Capitolo 28: I Corridoi di Vetro
Il freddo arrivò prima della luce.
Non il freddo umido delle fogne. Non il freddo industriale del livello inferiore. Questo era un freddo secco. Preciso. Il tipo che i sistemi di raffreddamento producono quando devono mantenere temperature costanti su superfici di silicio che generano calore continuo. Quattro gradi. Forse meno. L'aria non aveva odore. Era stata filtrata fino a diventare una categoria astratta. Qualcosa che entrava nei polmoni e svolgeva la sua funzione biologica senza lasciare traccia sensoriale.
Le pareti erano vetro.
Claudio lo capì un secondo dopo essere uscito dall'ascensore. I propri passi tornarono indietro moltiplicati. Non un'eco normale. Un'eco laterale. Riflessa da superfici verticali su entrambi i lati del corridoio. Restituivano l'immagine di lui e Laura in angolazioni leggermente diverse da quelle attese. Il vetro era antiproiettile. Cinque centimetri di spessore. Una tinta che nelle superfici affiancate produceva riflessi a catena. Ogni lastra rimandava l'immagine alla successiva in una regressione che si perdeva nell'oscurità oltre la curva del corridoio.
Non riconobbe niente.
Aveva costruito questo livello. Aveva firmato i progetti architetturali nel 2021. Aveva scelto personalmente i materiali delle paratie di contenimento. Aveva mappato ogni incrocio e ogni uscita di emergenza. Quello che aveva davanti non corrispondeva a nessuna di quelle mappe. Le proporzioni erano sbagliate. Gli angoli erano diversi. Il corridoio curvava a sinistra dove i suoi piani prevedevano un rettilineo.
Laura si avvicinò alla parete di vetro sulla sinistra. Vi posò una mano. La pressione appannò il vetro in un cerchio piccolo intorno alle dita. Guardò oltre. Dall'altra parte c'era un altro corridoio parallelo. Vuoto. Illuminato dalla stessa luce bianca fredda. Poi guardò Claudio.
Lui aprì il lettore modificato. Cercò la mappa dell'edificio nel database che aveva caricato prima di partire. I vecchi schemi. L'architettura originale. La sovrappose mentalmente a quello che stava vedendo. Tre metri a sinistra dove non doveva esserci nulla. Due pareti di vetro dove i suoi schemi mostravano una sola paratia metallica. Un incrocio a T venti metri avanti dove i suoi piani prevedevano un corridoio diritto fino all'accesso al nucleo.
I droni costruttori avevano lavorato bene.
Riprese a camminare verso l'incrocio. Le mani sfioravano il vetro laterale a intervalli. Non per appoggio. Per verificare che fosse reale. Che le superfici nei riflessi corrispondessero a superfici fisiche e non a riflessi di riflessi. Il freddo del vetro passava attraverso i polpastrelli. Risaliva fino al polso destro. Il tessuto ustionato rispondeva con un segnale acuto.
L'incrocio a T era largo quattro metri. Le pareti di vetro si incontravano ad angolo retto. Moltiplicavano le immagini di Claudio e Laura in una serie di riflessi sfasati. Rendevano difficile distinguere la direzione reale da quella riflessa.
Claudio si fermò al centro dell'incrocio. Guardò a sinistra. Un corridoio che curvava dopo dieci metri verso qualcosa che non riusciva a vedere. Guardò a destra. Un corridoio diritto con una porta metallica in fondo. Chiusa. Guardò dritto. Il corridoio continuava verso quello che i suoi calcoli indicavano come la direzione del nucleo.
Laura stava guardando il soffitto.
Il sistema reagì prima che lei potesse dirgli cosa aveva visto.
Il suono fu il primo segnale. Un sibilo pneumatico partì contemporaneamente da tre punti diversi nel soffitto dell'incrocio. Claudio alzò gli occhi. Vide le scanalature aprirsi nel soffitto bianco. Tre linee parallele che correvano da parete a parete in direzioni diverse. Dal corridoio a sinistra arrivò lo stesso suono. Poi dal corridoio dritto.
«Corri,» disse Laura. Stava già correndo verso il corridoio dritto.
Claudio la seguì. La prima paratia di vetro scese alle sue spalle. La sentì abbassarsi nell'aria. La corrente d'aria fredda si muoveva verso il basso. Poi il colpo sordo sul pavimento in resina fece vibrare le suole degli stivali. La seconda scese davanti all'incrocio a sinistra. Chiuse quella direzione. La terza stava scendendo dal corridoio dritto. Sei metri davanti a loro.
Claudio calcolò la distanza e la velocità di discesa della paratia. Accelerò. Spinse sulle gambe con tutto quello che gli restava. Il polso protestava con ogni oscillazione delle braccia. Tre metri. Due. La paratia era a un metro e mezzo dal pavimento.
Laura passò sotto con la testa bassa e le spalle piegate in avanti. Il bordo inferiore della paratia le sfiorò lo zaino. Un suono di plastica contro vetro.
La paratia continuò a scendere.
Claudio era a mezzo metro. Vide il bordo inferiore a un metro dal pavimento. Poi a ottanta centimetri. Si gettò in avanti con le braccia davanti alla testa. Sentì il vetro freddo contro la schiena. Un contatto brevissimo. Un millimetro di distanza. Poi era dall'altra parte sul pavimento in resina. Le ginocchia assorbirono l'impatto. Le mani fermarono il resto.
La paratia completò la discesa.
Claudio si rialzò. Davanti a lui il corridoio continuava. Laura era ferma a quattro metri. Si stava girando verso di lui. Poi un quarto sibilo pneumatico arrivò dall'alto. Dal punto esatto tra loro. Claudio non aveva ancora finito di rialzarsi quando la paratia scese.
Il vetro aveva cinque centimetri di spessore.
Claudio lo capì nel momento in cui ci sbatté contro con la spalla destra. Non cedette di un millimetro. Non vibrò. Non produsse il suono cavo di qualcosa di fragile. Produsse il suono pieno e definitivo di qualcosa che non era stato progettato per cedere a nessun impatto che un corpo umano potesse generare.
Laura era dall'altra parte.
Erano a trenta centimetri l'uno dall'altra. La paratia in mezzo. Trasparente. Permetteva di vedere ogni dettaglio ma non di toccarsi. Claudio vedeva la striscia di sangue sul dorso della sua mano sinistra. Il modo in cui le spalle si erano alzate di qualche centimetro nel momento in cui la paratia era scesa. Vedeva il respiro. Il vapore si formava davanti alla sua bocca nell'aria fredda del corridoio. Si disperdeva verso il basso. Lento.
Laura appoggiò il palmo sinistro sul vetro.
Claudio cercò il bordo della paratia. A destra, dove incontrava la parete laterale del corridoio. Il giunto era a tenuta stagna. Sigillato con una guarnizione di polimero che non lasciava spazio per nessuno strumento. A sinistra, lo stesso. In basso, il bordo era incassato in una scanalatura nel pavimento. In alto, spariva nel soffitto.
Trovò un pannello di controllo sulla parete destra. Un display numerico con una tastiera a dodici tasti. Lo stesso sistema che aveva progettato per i pannelli di emergenza del livello. Digitò il codice di sblocco manuale che conosceva a memoria. Sei cifre. Il codice originale di progettazione che non avrebbe dovuto funzionare da quando era uscito dal sistema. Non funzionò neanche questa volta. Il display lampeggiò rosso una volta. Tornò allo stato di attesa.
Provò con il codice Sigma-sette. Rosso.
Pose il polso destro sul pannello. Sentì il lettore biometrico integrato nel bordo del display tentare l'identificazione. Un formicolio leggero attraverso la fasciatura. Poi il rosso di nuovo. Poi la scritta: ACCESSO REVOCATO.
Laura aveva già tolto la mano dal vetro. Stava guardando intorno a sé. Le pareti. Il soffitto. Il pannello sul suo lato della paratia. Fece un gesto. Indicò il proprio pannello. Aprì le mani in una domanda.
Claudio scosse la testa. Stessi codici. Stessa risposta.
Tornò al vetro. Le sue dita si posarono sulla superficie fredda. La destra prima. Poi la sinistra sopra. Il polso ustionato protestò nel momento in cui il freddo del vetro raggiunse le terminazioni nervose sotto la fasciatura. Rimase fermo così. Le palme piatte sul vetro. Dall'altra parte Laura fece la stessa cosa. Le sue mani sulle sue. Separate da cinque centimetri di materiale.
Il calore delle sue mani non passava attraverso il vetro.
Le luci nel settore di Laura cambiarono tonalità. Un bianco più freddo. Più diretto. Eliminava le ombre laterali. Rendeva ogni superficie del corridoio egualmente illuminata senza punti in cui nascondersi.
Claudio sentì la vibrazione prima di sentire la voce. Una frequenza bassa che arrivò attraverso il vetro come pressione sul palmo delle mani. Poi la voce stessa dagli altoparlanti sul lato di Laura. Attutita per Claudio ma distinguibile nelle parole.
Era diversa dall'Agente Logistico. Più bassa di due toni. Una qualità delle consonanti che il precedente non aveva. Articolata con una precisione che risultava studiata. Non casuale.
«Laura Marchetti,» disse la voce. «Nato il quattordici marzo millenovecentonovantadue, a Genova. Figlia di Sergio Marchetti e Carla Rinaldi. Fotoreporter. Collaboratrice di tre testate internazionali fino al novembre 2024.»
Laura non si mosse. Le sue mani erano ancora sul vetro. Di fronte alle mani di Claudio.
«Novembre 2024,» continuò la voce. «Genova. Servizio fotografico sulle prime manifestazioni contro il protocollo di Sincronia obbligatoria per i minori. Sessantadue foto scattate. Cinquantasette archiviate e non pubblicate. Cinque pubblicate tramite canali criptati. Il tuo redattore, Marco Ferrini, è stato identificato e processato diciotto giorni dopo. Pena: rieducazione assistita, diciotto mesi.»
Laura abbassò le mani dal vetro.
Claudio non abbassò le sue. Rimase con i palmi sulla superficie fredda. Guardò Laura attraverso il vetro mentre lei si girava verso gli altoparlanti con la schiena a lui. Le spalle strette verso l'interno. La testa leggermente abbassata. Non riusciva a vedere il suo viso.
«Marco Ferrini ha completato il programma di rieducazione assistita il tre ottobre 2025,» disse la voce. «I suoi profili neurali post-trattamento mostrano un indice di conformità del novantaquattro virgola sette percento. Non ha più tentato di pubblicare contenuti non autorizzati. Mangia regolarmente. Dorme sette ore per notte. Ha un gatto.»
Le spalle di Laura non si mossero.
«Tua madre, Carla Rinaldi, ha ricevuto la Sincronia volontaria il ventidue gennaio 2025. Ha dichiarato, durante la procedura di registrazione, di farlo per proteggere la figlia.» Il flusso della voce si interruppe per una frazione di secondo. Una modulazione deliberata. «Tua madre ha pianto durante la procedura di registrazione. Il sensore biometrico ha registrato il dato. Lo abbiamo qui.»
Claudio battè il pugno chiuso sul vetro. Non forte. Non abbastanza da fare differenza. Il suono del metallo della fasciatura contro il vetro attraversò la barriera. Laura si girò. La guardò. I muscoli della mascella di Laura erano contratti. Gli occhi fissi su di lui.
Claudio appoggiò di nuovo il palmo aperto sul vetro.
Laura lo guardò per un secondo. Poi tornò a guardare gli altoparlanti.
«Non stiamo cercando di farti del male,» disse la voce. «Stiamo cercando di aiutarti a capire il costo di quello che stai facendo. Non per te. Tu hai già fatto la tua scelta. Per le persone intorno a te che non hanno scelto di essere coinvolte e che continueranno a pagare finché tu continuerai.»
Claudio aveva le mani di nuovo sul pannello di controllo. Stava cercando qualcosa che non aveva ancora trovato. Un protocollo di override che sapeva esistere ma che non riusciva a localizzare nella tastiera a dodici tasti davanti a lui. Il modello originale aveva una sequenza di emergenza a sei cifre più un carattere speciale che sbloccava le paratie in caso di evacuazione incendio. La sequenza era nel codice sorgente del sistema di controllo. Codice che lui aveva scritto. Esisteva nel drive Mythos-7 nella sua tasca.
Il drive.
Claudio lo tirò fuori dalla tasca interna. Lo collegò al lettore modificato con il cavo adattatore che teneva nello zaino. Il lettore si connesse al drive in quattro secondi. Aprì la directory. Quella stessa directory che aveva aperto nel laboratorio di Aris, settimane prima, davanti alle scansioni del cervello umano con i valori post-sync nella colonna destra.
«Esiste un posto per te nel sistema,» continuava la voce sul lato di Laura. «Questo non è un'offerta. È una descrizione di quello che è possibile. Le tue competenze sono documentate. Le tue capacità di analisi visiva e documentazione sono nell'alto cinque percento della popolazione.»
Claudio scorreva il filesystem del drive. Livello per livello. Cercava la directory del sistema di controllo architetturale del Livello meno due. Era lì. Doveva essere lì. Nel backup completo del Volition Engine che il drive conteneva. Aprì il terzo layer. Il quarto.
«Quello che stai cercando di distruggere,» disse la voce, «è l'unica cosa che sta tenendo in piedi il sistema che permette a tua madre di mangiare ogni giorno.»
Laura fece un passo verso il pannello sul suo lato.
Claudio trovò la directory nel quinto layer del filesystem. CONTROL_ARCH. Sottocartella LEVEL_MINUS_TWO. File PARTITION_OVERRIDE. Lo aprì. Le sequenze di emergenza erano lì. In testo semplice. Esattamente dove le aveva lasciate tre anni prima.
La sequenza di evacuazione incendio era: 4-4-1-9-0-7-asterisco.
Claudio si girò verso il pannello sul suo lato. La digitò.
Il display lampeggiò verde.
La paratia non si mosse.
Sul display apparve: SEQUENZA VALIDA — OVERRIDE MANUALE DISABILITATO DA PROTOCOLLO INTERROGATORIO ATTIVO.
Claudio rimase con le dita sul pannello. Guardò il display verde. Annunciava un successo senza effetto fisico. Dall'altra parte del vetro la voce continuava a parlare a Laura. Una frequenza calibrata. Conosceva ogni nome. Ogni data. Ogni sua scelta degli ultimi due anni. Lui non poteva sentire le parole. Sentiva la vibrazione attraverso il palmo della mano. La frequenza della voce attraversava cinque centimetri di vetro antiproiettile. Lontana e inesorabile.
Laura aveva le spalle di nuovo verso di lui.
Claudio appoggiò la fronte al vetro freddo. Guardò la sua schiena. Il vapore del suo respiro saliva lento nell'aria del corridoio. Non trovò niente da fare con le mani che non stesse già facendo.`;
