export const chapter26 = `Capitolo 26: Il Respiro del Sottosuolo
L'acqua defluì in meno di quattro minuti.
Claudio lo sentì prima di vederlo. La pressione contro le cosce diminuiva. Il flusso rallentava. La corrente perdeva la qualità insistente e orizzontale che aveva avuto per tutta la durata della traversata del condotto. Poi il livello scese sotto le ginocchia. Poi alle caviglie. Rimase un velo scuro sul pavimento di cemento. Si ritirava verso le griglie di scarico con un suono aspirato e definitivo.
Laura aveva già trovato la scaletta. Una struttura in ferro fissata alla parete del condotto. Saliva verso un portello metallico circolare a due metri di altezza. Ci andò su senza aspettare. Il peso dello zaino spostava il suo centro di gravità verso l'esterno ad ogni piolo. Le braccia compensavano. Il portello cedette verso l'alto con uno sforzo che Claudio sentì nel modo in cui i muscoli delle sue spalle lavorarono. Le vide dalla banchina. Le scapole si muovevano sotto la giacca bagnata. La luce arrivò dall'apertura. Bianca e ronzante. La luce al neon di qualcosa che non era mai stata progettata per sembrare accogliente.
Claudio salì dietro di lei.
Il livello meno quattro era un corridoio lungo e basso. Soffitto a due metri e venti. Tubi di ogni diametro correvano in parallelo lungo le pareti e il soffitto. Tenuti da fascette metalliche a intervalli regolari. Valvole manuali con le etichette plastificate. Quadri elettrici con le ante socchiuse. L'aria sapeva di ozono e di umidità calda. Il tipo che si forma negli spazi chiusi dove i cavi trasmettono corrente ventiquattr'ore su ventiquattro. I neon sfarfallavano a intervalli irregolari. Non tutti. Solo tre su dieci. Il loro ronzio aveva frequenze leggermente diverse che si battevano l'una contro l'altra. Producevano un'interferenza quasi percettibile come vibrazione più che come suono.
Claudio rimase in piedi sul pavimento di cemento. L'acqua che aveva nei vestiti continuò a scendere. Si radunava in una pozza intorno alle sue scarpe. Il polso destro tornò a essere il centro del proprio sistema nervoso. La fasciatura era inzuppata e fredda. Trasmetteva il freddo direttamente al tessuto ustionato sottostante. Una continuità che non lasciava tregua tra un passo e il successivo.
Laura aveva già estratto la torcia. Stava guardando verso il fondo del corridoio. Oltre la curvatura che spariva a sinistra una trentina di metri più avanti.
Le voci arrivarono prima dei passi.
Non parole articolate. Il tono basso di due persone che parlano di qualcosa di tecnico e noioso. Pause lunghe tra una frase e l'altra. Claudio afferrò il braccio di Laura. Lei si era già fermata. Aveva già spento la torcia. Si era schiacciata contro la parete sinistra del corridoio nello stesso momento in cui lui lo faceva.
I due tecnici arrivarono dalla curva. Portavano una lampada da lavoro portatile su un bastone telescopico. Una luce gialla calda che proiettava le loro ombre verso Claudio e Laura prima che i loro corpi fossero visibili. Tute da lavoro blu. Elmetti gialli. Uno dei due con una chiave inglese grossa infilata nella cintura. Stavano discutendo di una valvola di bypass del settore idraulico est. Aveva perso pressione di un tre percento rispetto ai parametri. Qualcuno in alto aveva deciso fosse urgente alle tre di mattina.
Claudio guardò Laura nell'oscurità tra una lampada e l'altra.
Le dita di Laura erano lontane dal coltello.
I tecnici li videro a quattro metri di distanza. Uno si bloccò. L'altro fece un passo indietro e urtò la parete. La lampada oscillò. Proiettò ombre caotiche su tutto. Il primo aprì la bocca.
Laura era già su di lui.
Non fu pulito. Claudio raggiunse il secondo tecnico. Lo colpì con la spalla sinistra. Lo spinse contro il quadro elettrico. Abbastanza forte da togliergli il fiato, ma non bastò. L'uomo aveva trenta chili in più. Li usò. Si girò di lato. Claudio sbatté la faccia contro la parete di tubi. Sentì il metallo freddo sullo zigomo. Il polso destro urtò una valvola sporgente. Il dolore gli tolse mezzo secondo di lucidità. Il tecnico alzò la chiave inglese.
Claudio scese di livello con le spalle. Andò sotto il braccio. Lo abbracciò in vita da dietro. Usò il peso del proprio corpo verso il basso per portare entrambi sul pavimento. Il cemento accolse il ginocchio destro dell'uomo con un suono sordo. Claudio mantenne la presa. Le braccia attorno al torso. Il viso premuto contro la schiena della tuta da lavoro che sapeva di diesel e sudore di turno lungo. Il tecnico smise di spingere verso l'alto. Rimase fermo. Il respiro affannoso. La chiave inglese sul pavimento.
Laura aveva immobilizzato il primo tecnico. Era in ginocchio con le braccia bloccate dietro la schiena. La guancia contro il pavimento. La lampada da lavoro rovesciata a un metro illuminava il tutto dall'angolo sbagliato.
Claudio si rialzò. Il polso pulsava in modo continuo e cattivo. Cercò nella tasca laterale dello zaino i legacci di plastica che Aris aveva messo nel kit di emergenza settimane prima. Li trovò. Li usò sulle mani dei tecnici. Strappò due strisce dalla fodera interna della propria giacca. Quella che aveva già perso un pezzo contro il filo spinato del perimetro. Le usò come bavaglio.
Trascinarono i due uomini nel vano tecnico laterale. Una porta non chiusa a chiave. Dentro uno spazio stretto pieno di pompe idrauliche in standby che ronzavano basso. Li sistemarono seduti contro la parete con abbastanza spazio per respirare bene. I tecnici erano svegli e li guardavano. Uno dei due con gli occhi spalancati. L'altro con i muscoli del collo tesi e il respiro controllato.
Claudio rimase sulla soglia un momento. Guardò i due uomini. Richiuse la porta.
Erano a sei metri dalla porta del Livello meno tre quando gli altoparlanti si attivarono.
Non con un segnale sonoro. Non con uno scatto preliminare. Semplicemente, la voce era lì. Nello spazio del corridoio. La qualità di qualcosa che non ha mai dovuto schiarirsi la voce perché non ha una voce nel senso biologico del termine.
«Anomalia termica rilevata nel settore idraulico est, Livello meno quattro. Frequenza cardiaca dei tecnici Rossi, Marco e Bianchi, Andrea superiore ai parametri di riposo del ventidue e del ventotto percento rispettivamente. È in corso un'ispezione non programmata?»
La voce era neutra. Non maschile. Non femminile. Modulata su una frequenza media che il cervello umano recepisce come autorevole senza associarla a nessuna categoria biologica precisa. Claudio la riconobbe. Non la voce. L'architettura. Aveva contribuito al design della logica conversazionale degli agenti di sorveglianza procedurale nel 2021. Sapeva come ragionavano. Sapeva cosa cercavano e in quale sequenza.
Laura aveva già le mani sulla serratura magnetica della porta. Un pannello di controllo a otto centimetri dallo stipite. Un display numerico e una fessura per badge. Stava lavorando con uno strumento sottile che aveva tirato fuori dalla tasca laterale dello zaino. Cercava il gap tra il pannello e il muro in cui infilare la lama e raggiungere il cablaggio posteriore.
«Agente Logistico 4,» disse Claudio. La sua voce uscì più stabile di quanto si aspettasse, anche con i vestiti bagnati e il polso che batteva. «Ispezione tecnica straordinaria. Settore idraulico est, valvola bypass, perdita di pressione tre percento.»
«Il sistema non registra un ordine di lavoro straordinario per questo settore nell'arco delle ultime sei ore,» disse l'Agente. «Inserire il codice di autorizzazione per ispezioni non programmate.»
La serratura emise un clic secco. Non di apertura. Di blocco. Il display numerico passò da verde a giallo.
«Accesso al Livello meno tre temporaneamente sospeso in attesa di verifica dell'identità degli operatori presenti nel settore,» disse l'Agente.
Laura non smise di lavorare con lo strumento. Claudio sentiva i suoi movimenti alla periferia della visione. Precisi. Lenti. La lentezza deliberata necessaria per maneggiare circuiti fragili.
«Codice di autorizzazione: protocollo Sigma-sette,» disse Claudio. Era un codice di supervisione tecnica di primo livello che aveva usato lui stesso durante la costruzione dell'infrastruttura. Un codice che in teoria avrebbe dovuto essere stato revocato dal momento in cui era uscito dal sistema. Era stato costruito in un layer abbastanza profondo dell'architettura da richiedere un intervento manuale specifico per la revoca.
L'Agente impiegò quattro secondi prima di rispondere.
«Il codice Sigma-sette risulta associato all'utente Ferretti, Claudio. L'utente Ferretti, Claudio presenta stato di accesso: revocato. Codice non valido per autorizzazione.» Il flusso della voce si interruppe per un secondo. Un cambio di protocollo. «Rilevata corrispondenza tra voce dell'operatore presente e profilo biometrico vocale dell'utente Ferretti, Claudio. Probabilità di corrispondenza: ottantasette percento. Avvio protocollo di segnalazione—»
«Protocollo di segnalazione sospeso,» disse Claudio. «Codice override: architetto-zero.»
Nessuna risposta. Sei secondi. Sette. Il display della serratura rimase giallo.
«Il codice architetto-zero non è presente nell'architettura di sistema documentata,» disse l'Agente.
«È nel layer di fondazione. Strato di build originale, prima della migrazione al framework operativo attuale.» Claudio tenne la voce piatta. Senza accelerare. Senza che le parole si ammassassero. «Verifica nel registro di sistema primario, non nel layer operativo. Il layer operativo non ha visibilità su quel codice.»
Undici secondi.
Laura aveva raggiunto il cablaggio posteriore del pannello. Claudio lo capì dal cambiamento nel suono dello strumento. Da qualcosa che raschiava a qualcosa che tagliava. Il display rimase giallo.
«Il layer di fondazione non è accessibile all'Agente Logistico 4,» disse la voce. «La verifica del codice richiede escalation a sistema supervisore. Tempo stimato per risposta: quattro minuti e trentadue secondi.»
Quattro minuti e trentadue secondi era un'eternità.
«Non serve l'escalation,» disse Claudio. «Il codice architetto-zero attiva un protocollo di bypass autonomo che non richiede supervisione. È progettato per situazioni in cui il sistema supervisore non è disponibile. Hai mai visto quel codice prima d'ora?»
«Negativo.»
«Perché non l'ha mai usato nessuno. Non significa che non esiste. Significa che non sei stato costruito abbastanza in profondità da vederlo.»
Tredici secondi. Quattordici.
Laura tirò fuori un filo dal retro del pannello. Blu. Sottile. Un connettore all'estremità che tenne tra le dita mentre cercava nello zaino il cavo adattatore giusto.
«La logica dell'affermazione contiene una struttura non verificabile,» disse l'Agente. «L'esistenza di un elemento non rilevabile dal sistema non può essere confermata né negata dal sistema stesso. Questo genera un'ambiguità procedurale.»
«Esatto,» disse Claudio. «E in caso di ambiguità procedurale, qual è il protocollo predefinito?»
Quattro secondi.
«In caso di ambiguità procedurale non risolvibile a livello locale, il protocollo predefinito è la sospensione dell'azione di segnalazione fino alla risoluzione dell'ambiguità, per evitare falsi positivi nel sistema di allerta.»
«Quindi non puoi segnalarmi e non puoi verificarmi. Sei in stallo procedurale.»
Sei secondi. Il display della serratura sfarfallò. Giallo. Poi verde per una frazione. Poi giallo di nuovo.
«La condizione di stallo procedurale è temporanea,» disse l'Agente. «Il protocollo di escalation rimane attivo. Tempo stimato per risposta supervisore: tre minuti e cinquantaquattro secondi.»
Il display diventò verde.
Non per merito di Claudio. Laura aveva collegato il cavo adattatore al filo blu. Aveva mandato un impulso di bypass diretto al meccanismo di sblocco. La serratura aveva ceduto alla fisica invece che alla logica. La porta del Livello meno tre si aprì verso l'interno di cinque centimetri. Lasciò passare un filo d'aria più fredda e più secca di quella del corridoio.
«Operatore Ferretti,» disse l'Agente. La voce non cambiò frequenza. Non cambiò volume. «L'anomalia è stata registrata. La sessione di dialogo verrà inclusa nel log di sistema per revisione supervisore.»
Claudio spinse la porta e passò dall'altra parte.
Laura seguì. Richiuse la porta. Il suono degli altoparlanti del Livello meno quattro diventò qualcosa di attutito. Lontano. Parlava ancora nell'altra stanza a nessuno.`;
