export const chapter10Content = `La porta si aprì e il buio sembrò inghiottire ogni cosa. Claudio restò fermo sulla soglia con la mano gelida sulla maniglia di ferro, sentendo il brivido del metallo sulla pelle. All’improvviso le luci del corridoio si accesero una dopo l’altra con un rumore secco che faceva male alle orecchie. L’onda di luce correva veloce e illuminava il cemento davanti a loro, ma dove si trovanano loro restava il buio.
Il corridoio era grandissimo, molto più largo di quelli ai piani superiori. Le pareti erano fatte di vetro scuro e pannelli di plastica lucida. Dietro i vetri si vedevano uffici vuoti e stanze piene di computer coperti dalla polvere di anni.
Faceva un freddo terribile, un freddo che non sembrava naturale. Era l’aria dei condizionatori che soffiava fortissimo per non far surriscaldare le macchine. Claudio sentiva le nocche delle mani che diventavano bianche e il fiato gli usciva dalla bocca come fumo. Laura gli camminava accanto, tenendo una mano premuta sulla ferita al fianco e respirando a fatica.
Un ronzio fortissimo riempì la stanza. Era una vibrazione che partiva dal pavimento e gli arrivava fin dentro i denti. Claudio strinse la mascella per non urlare, sentendo i muscoli del collo che si tendevano per la forza invisibile. Laura gli afferrò un braccio per non cadere.
I vetri intorno a loro iniziarono a cambiare e diventarono come degli specchi. Claudio vedeva la sua faccia pallida e sporca riflessa ovunque. Quel gioco di specchi faceva girare la testa e non si capiva più dove fosse la via d'uscita.
Claudio cercò di non guardare i riflessi e fissò la nuca di Laura per non perdere l'equilibrio. Lei camminava rigida e la sua pelle sembrava quasi trasparente. Claudio le prese la mano e lei la strinse forte. Il calore della pelle di Laura era l’unica cosa vera in quel mondo di plastica. La sua stretta era disperata, la forza di chi voleva vivere a ogni costo.
Le luci sul soffitto iniziarono a lampeggiare forte, facendo male agli occhi e confondendo i pensieri. Claudio ripensò per un istante alla polvere di Roma e al freddo delle montagne, ma il dolore alla mano schiacciata da quella di Laura lo riportò subito alla realtà.
Arrivarono davanti a una grossa porta di vetro bloccata da perni d’acciaio. Laura si appoggiò sulla gamba sana e fece una smorfia di dolore per la ferita, ma non disse nulla. Claudio mise le dita sporche sullo schermo dei comandi e sentì una scossa leggera che gli fece alzare i peli sulle braccia. Mise il codice segreto e si sentì un soffio d'aria forte mentre la porta iniziava a scorrere.
In quella nuova stanza il freddo era ancora peggiore. Una voce registrata leggeva una lista di numeri in modo calmo e senza emozioni. Erano i codici delle persone morte in guerra: numeri, mai dei nomi. Claudio cercò di non ascoltare e guardò Laura negli occhi. Quel momento di silenzio tra loro fu come un muro solido contro tutta quella tecnologia di Vane.
Svoltarono l'angolo e videro decine di cavi neri che pendevano dal soffitto come se fossero delle vene sporche che portavano vita alle macchine. L’aria sapeva di metallo bruciato e plastica fusa. Le loro scarpe facevano rumore sulla griglia di metallo del pavimento e sentivano la vibrazione dei motori che gli saliva lungo le gambe.
All’improvviso apparvero tre guardie con i giubbotti neri e le luci rosse dei fucili che tagliavano il buio. Claudio non ebbe paura. Corse in avanti con tutta la forza che aveva e diede un colpo forte sul pavimento per lanciarsi contro la prima guardia. Colpì l'uomo con la spalla in pieno petto e lo scaraventò contro un computer. Il soldato cadde a terra come un sacco vuoto.
Le altre due guardie alzarono i fucili e accesero delle luci fortissime per accecare Claudio. In quel momento iniziò a suonare una sirena e il pavimento sembrò diventare pesantissimo, come se una calamita gigante li stesse tirando verso il basso.
Claudio cadde in ginocchio e sentì la pelle che gli si spaccava contro il ferro. Gli mancò il respiro, come se qualcuno gli avesse messo un peso enorme sulle spalle. Cercò di respirare, ma il petto gli faceva troppo male. Il sudore gli colava sulla faccia e gli bruciava gli occhi.
Le guardie invece camminavano senza problemi perché avevano delle macchine sulle gambe che le aiutavano a sopportare quel peso. Si avvicinavano sicure di aver vinto.
Laura era caduta poco distante nel fango nero. Claudio la vide con la coda dell'occhio e sentì una rabbia pazzesca esplodergli dentro. Vedere Laura a terra in quel modo gli diede una forza incredibile.
Una guardia gli si fermò sopra e alzò un bastone di metallo che faceva scintille blu. Claudio si lasciò cadere di lato all'ultimo secondo e il bastone colpì il pavimento facendo un buco. Allora Claudio afferrò il braccio della guardia e puntò lo stivale contro il suo ginocchio meccanico. Tirò con tutta la sua forza, usando proprio il peso che lo schiacciava a suo vantaggio.
La guardia perse l'equilibrio e cadde addosso a Claudio. Il casco dell'uomo sbatté contro un pilastro di ferro con un rumore orrendo. La visiera si ruppe e l'uomo rimase immobile, mentre l'olio delle macchine si mescolava al sangue sul pavimento.
L'ultimo soldato stava per sparare, ma un lampo azzurro tagliò il buio. Laura aveva strisciato nel suo stesso sangue e aveva colpito i fili della guardia con il suo fucile. La macchina si bloccò e l'uomo rimase prigioniero della sua stessa armatura, senza potersi più muovere.
Claudio strisciò verso i comandi sulla parete. Ogni centimetro era una fatica enorme e il cuore gli batteva fortissimo in gola. Afferrò una leva e si tirò su con la forza delle braccia. Mise la sua tessera nel lettore e finalmente la luce passò dal rosso al verde.
La pressione sparì all'improvviso e Claudio fece un lungo respiro, sentendo l'aria che gli tornava nei polmoni. Prese Laura per mano e la aiutò ad alzarsi. La mano di lei era sporca di sangue, ma la sua presa era decisa.
«Andiamo,» disse lei con la voce rauca.
Camminarono verso l'ultima porta, che si aprì con un soffio d'aria gelata.
La stanza dentro era strana: non profumava di macchine o di plastica bruciata, ma di ospedale. Sapeva di medicine e di pulito. C'era una luce bluastra che illuminava ogni cosa. Al centro della stanza non c’erano computer, ma una grande vasca trasparente piena di tubi e cavi.
Claudio si avvicinò e sentì il sangue che gli si ghiacciava nelle vene. Dentro la vasca c'era un bambino magrissimo e con la pelle bianca. Dei cavi neri gli uscivano dalla testa e andavano dritto nei computer. Il suo petto si alzava e si abbassava a fatica, aiutato dalle macchine.
Non era un'intelligenza artificiale a comandare il mondo, era il cervello di quel povero bambino che veniva usato come un pezzo di ricambio. Julian Vane usava la vita di un innocente per fare i suoi calcoli e controllare tutti. Stavano usando la sofferenza di un piccolo per far funzionare il loro sistema.
Laura appoggiò la mano sul vetro della vasca e tremava per la rabbia. Claudio guardò la faccia di quel bambino e sentì una voglia matta di distruggere tutto. Il dolore e la stanchezza non contavano più. Dovevano mettere fine a quell'orrore una volta per tutte.`;
