export const chapter37Content = `L'Ultimo Piano era steso sul tavolo di metallo sgraffiato, un insieme di diagrammi e mappe che Claudio aveva elaborato durante le lunghe ore di fuga. Non era solo una mappa della Torre, era il percorso vitale del virus che doveva infettare ABITES. Claudio indicò con il dito sporco di fuliggine il punto di ingresso principale: il server di nodo alfa, situato al trentaduesimo piano.
Laura ascoltava con le braccia incrociate sul petto, i muscoli delle braccia tesi sotto la giacca. Ogni dettaglio era fondamentale. Un errore di millimetri o di secondi avrebbe significato la fine di tutto. Il ronzio della ventola del computer di Claudio sembrava scandire il tempo che rimaneva prima dell'assalto.
"Dobbiamo entrare dal condotto di aerazione," spiegò Claudio. "Le guardie della Sincronia controllano gli ascensori, ma il condotto è considerato troppo stretto per un uomo. Dovremo strisciare per cinquanta metri in un vuoto assoluto di luce e aria."
Laura annuì. Non c'era paura nel suo sguardo, solo la concentrazione fredda di chi ha già deciso di vincere. Controllò il caricatore della sua pistola, facendo scattare il metallo con un suono secco che risuonò nella stanza vuota.
Il piano prevedeva una distrazione esterna. Le squadre di Disconnessi avrebbero attaccato i varchi di sicurezza alla base della Torre, attirando l'attenzione dei droni e delle guardie. In quel momento di caos, Claudio e Laura avrebbero iniziato la loro scalata vuotosa verso il cuore del sistema.
Claudio sentiva il sapore del ferro in bocca. Il dolore alle costole e al ginocchio era un compagno costante, ma la sua mente lo aveva relegato in un angolo buio. Esisteva solo l'obiettivo. Esisteva solo il virus e il codice che doveva essere iniettato.
Prepararono gli zaini con cura metodica. Ogni cavo, ogni attrezzo doveva essere a portata di mano. Claudio sentì il calore della chiavetta contro il fianco, un peso che ora gli sembrava quasi leggero, quasi la responsabilità si fosse trasformata in certezza.
Uscirono dal nascondiglio mentre il primo chiarore di un'alba grigia iniziava a filtrare dalle finestre alte del capannone. L'aria era gelida e sapeva di cenere e pioggia imminente. La Torre svettava in lontananza, un gigante di vetro e acciaio che dominava la città con la sua presenza minacciosa.
Si scambiarono un ultimo sguardo prima di dividersi dai compagni che avrebbero condotto la distrazione. Non servivano parole. Il loro legame era scritto nelle ferite che portavano sul corpo e nella determinazione che leggeva negli sguardi dell'altro.
Claudio inspirò profondamente l'aria gelata. Il suo polmone sinistro sembrava bruciare, ma non importava. Era arrivato il momento di passare dalle mappe all'azione. L'ultimo piano era pronto. Ora toccava alla carne e al sangue dimostrare di essere più forti del metallo di Julian Vane.`;
