export const chapter35Content = `I Segnali Disturbati facevano ballare l'immagine sullo schermo del terminale di Claudio. Erano entrati nel Settore Nero, il cuore della zona di disturbo di ABITES. Qui la tecnologia era un'arma a doppio taglio: troppo rumore digitale per i droni, ma anche un vuoto di informazioni per chi cercava di orientarsi tra i tunnel.
Claudio premette i tasti con una forza controllata. La sua mente cercava di filtrare i dati utili tra migliaia di bit di spazzatura inviati dal sistema per confonderlo. Sentiva il calore che proveniva dai circuiti del terminale surriscaldato, un odore di plastica calda che si mescolava a quello della pioggia che filtrava dal soffitto.
Laura teneva d'occhio i corridoi laterali. Le luci di emergenza, di un rosso cupo e pulsante, davano alla galleria l'aspetto di una gola sanguinante. Ogni ombra sembrava nascondere un nemico pronto a scattare. Il ronzio della ventola del computer era l'unico suono in quel vuoto che sembrava inghiottire ogni altro rumore.
"Abbiamo una traccia," sussurrò Claudio. Aveva trovato un tunnel che portava direttamente alla base della Torre. Era un vecchio condotto di scolo, ormai secco, che non veniva monitorato dai sensori termici di ABITES perché troppo profondo.
Si mossero velocemente, cercando di non fare rumore sulla griglia di metallo del pavimento. Claudio sentiva il peso del virus nella sua borsa, una massa fredda e pesante che sembrava quasi attirare la sfortuna. In quel luogo, i sogni di gloria erano stati sostituiti dalla nuda necessità di compiere un passo dopo l'altro.
Un'improvvisa variazione nella frequenza dei segnali disturbati fece scattare un allarme vuotoso sul dispositivo di Claudio. Il sistema stava ricalibrando i sensori della zona. Dovevano sparire, e in fretta.
Si calarono in un pozzo di ispezione. La scala di ferro era arrugginita e ogni piolo scricchiolava sotto il loro peso, un rumore che sembrava risuonare per chilometri in quel vuoto sotterraneo. Claudio sentiva il freddo del metallo entrargli nelle ossa, un brivido che non dipendeva solo dalla temperatura esterna.
Raggiunsero il fondo del pozzo, dove l'aria era più densa e sapeva di muffa. Una luce azzurra pulsava in fondo al tunnel, segno della presenza di un server di nodo di ABITES. Era il loro prossimo obiettivo: disattivare quel server avrebbe spento metà dei sensori della Torre, aprendo finalmente la strada per l'assalto finale.
Claudio guardò Laura e vide la sua determinazione riflessa negli occhi. Non c'erano parole per descrivere quello che provavano. Erano due esseri umani contro una macchina infinita, due anomalie in un sistema perfetto che non ammetteva errori.
Si avvicinarono al server, muovendosi come ombre nel buio. Claudio estrasse la chiavetta e la inserì nel terminale di accesso. Sentì lo scatto elettrico della connessione e vide le prime righe del codice virus iniziare la loro opera di distruzione. In quel vuoto di segnali disturbati, la loro piccola vittoria era un segnale di speranza che iniziava a risalire verso la luce della città.`;
