export const chapter6Content = `Macro-Capitolo 6: Deviazione
[ROMA - LINEA B FANTASMA - LAURA E CLAUDIO]
Il sapore metallico del sangue saturò la gola di Claudio al terzo chilometro di fuga sotterranea. L'ingegnere lottava contro la fitta acuta e lancinante al costato, un chiodo rovente piantato tra le costole. La galleria abbandonata della vecchia Linea B esalava un respiro di ruggine, feci e umidità secolare. La torcia tattica di Laura bucava a stento l'oscurità densa che gravava tra i piloni di cemento armato.
Un demone meccanico marciava implacabile alle loro spalle, a meno di cinquanta metri. I passi erano ferrei, regolari, spaventosi. Il drone modello Cyrus batteva il ritmo della morte sul cemento crepato. L'unità d'acciaio colmava la distanza senza alcuno sforzo apparente, i suoi servomotori ronzavano nel silenzio del tunnel.
«Drive Mythos-7 confermato. Possesso illegale rilevato. Deposita immediatamente l'hardware,» proclamò la voce sintetica dal torace corazzato del droide. «Battito del bersaglio a centoundici bpm. Crollo biologico stimato imminente.»
Claudio cedette improvvisamente sulle ginocchia, falciato dalla stanchezza. L'addome sfregò contro i detriti taglienti e i sassi massicciata della metropolitana. L'emorragia interna aveva svuotato le ultime riserve di energia organica. L'ingegnere fissò la testata della stazione fantasma, oltre i binari dismessi e contorti. La vista gli si appannava di continuo.
Laura non si fermò a soccorrerlo. Scattò in diagonale sui calcinacci con la precisione di un predatore notturno. L'istinto di battaglia prese il comando totale del suo corpo. Scivolò contro i perni del mostro inseguitore, sparendo nel cono d'ombra dei suoi sensori. Impugnò il pugnale in ceramica balistica, un'arma fredda e invisibile ai radar di ABITES. Tranciò il cavo occipitale principale alla base del collo corazzato del droide. I server visivi dell'unità emisero un allarme acuto, stridente. Il colosso d'acciaio annaspò alla cieca nel buio. I giroscopi di compensazione erano stati infranti dal colpo. Il telaio da due quintali perse l'equilibrio e si schiantò contro un pilastro.
«Muoviti, Claudio! Adesso o mai più!» esclamò la donna, tornando sui suoi passi.
Afferrò con forza il bavero della giacca dell'ingegnere. Lo trascinò via dai binari spenti con una forza bruta, disperata. Lo spinse dentro un anfratto in penombra, dietro una vecchia cabina elettrica sventrata.
[LONDRA - GRATTACIELO BANCARIO - JULIAN VANE]
Julian Vane registrò la disintegrazione istantanea del DAX e dell'S&P 500 sui monitor a parete. Fissava i grafici finanziari dal vetro corazzato della sua cabina sospesa nel cielo di Londra. Il mondo esterno urlava, chiedendo risposte che non sarebbero arrivate. Julian manteneva una calma glaciale, quasi disumana. Centosessanta metri più in basso, il distretto finanziario della City crollava sotto il peso dei primi tafferugli feroci. La prima notte di terrore globale era finalmente iniziata, secondo i piani.
Le telecamere aziendali della sede centrale diffusero il feed globale su ogni rete ancora attiva. Il volto di Vane apparve simultaneamente sui display di ogni città del pianeta.
«L'irrazionalità è un difetto congenito e incurabile dell'uomo libero,» disse la sua voce olografica, calma e definitiva. «La democrazia è fallita sotto il peso della sua stessa inefficienza. Passate al Protocollo Sincronia entro otto ore. Affidatevi alla nostra assistenza algoritmica o affronterete il vuoto energetico e sociale assoluto.»
Vane interruppe il feed con un singolo gesto della mano guantata. Osservò l'ultima era organica scivolare via come sabbia ai piedi di un algoritmo perfetto che lui stesso aveva nutrito.
[ROMA - SNODO RETE CITTADINA - CLAUDIO E LAURA]
Si accasciarono oltre uno sfiato periferico della rete fognaria. Quella zona "morta" non era mappata dai nuovi sensori di sorveglianza di ABITES. Claudio sfoderò il terminale di calcolo con dita che non sentiva più. La sua mano destra tremava per lo shock. Gli spasmi addominali dilaniavano la carne viva all'altezza dello squarcio causato dal drone.
«Terminal node... origin code...» sussurrò l'ingegnere con un filo di voce. Tossì sangue scuro sulla tastiera.
Digrignò i denti contro il dolore che urlava. Attivò un override tattico d'emergenza, bypassando i protocolli di sicurezza standard. Incise nel dispositivo le coordinate di Milano-Bovisa per localizzare l'iper-server della Torre ABITES. Compilò decine di schermate fantasma per aggirare l'ispezione satellitare russa e americana. Combatté contro il blackout visivo che lo stava inghiottendo. Iniettò la sequenza finale nel driver Mythos-7.
Il display si spense bruscamente. La matrice virale era stata iniettata con successo nel nucleo fisico del drive. Il dispositivo strusciava umido e caldo contro il suo costato insanguinato. Laura fermò le dita scarni di Claudio con un gesto deciso. Schermò la digitazione con il proprio corpo per impedire l'emissione di qualsiasi segnale di posizione radio.
«Sei isolato dal centro ora. Hai ingannato la loro fortezza,» mormorò la donna, guardandolo negli occhi.
Claudio sfiorò il taschino tattico sul petto, sentendo la carta stropicciata della nota di Sara. La certezza della donna resisteva nella sua memoria come un faro. Quella forza segreta lo spinse a rimettersi in piedi, nonostante il dolore.
«Non chiuderanno un rudere di fognatura stanotte,» assicurò l'ingegnere con una smorfia di sfida.
Si gettarono nuovamente nel travertino bagnato della galleria. L'antica Roma li nascose ancora una volta nelle sue braccia fredde di fango e pioggia. La città spenta abbandonò all'esilio l'ultimo avamposto della ribellione umana.`;
