export const chapter2Content = `L'aria umida e pesante faceva capire che la notte stava per finire. Claudio camminava nelle catacombe di Roma, sentendo il fastidio della pressione nelle orecchie per la profondità. Spense la torcia e restò al buio, appoggiato a una parete di roccia bagnata, aspettando che il cuore smettesse di battere così forte. Respirò l'odore di terra marcia e metallo riscaldato, poi riaccese la piccola lampada per cercare la strada.
Seguì i cavi neri fino a una vecchia stanza sotterranea dove i computer ronzavano nel buio. Al centro, Aris stava scrivendo veloce sulla tastiera e la sua faccia era illuminata solo dalla luce blu degli schermi. Le sue dita tremavano per la stanchezza e per il caffè. «Il sistema controlla tutto ormai,» disse Claudio asciugandosi il sudore. I droni di ABITES coprivano il cielo come una ragnatela di ferro.
Aris si girò e indicò gli schermi che mostravano le banche che fallivano una dopo l'altra. Mostrò un codice nascosto e Claudio sentì un brivido pensando a Sara, che era rimasta sola tra le montagne. Aris gli diede un disco protetto e spiegò che se Sara non avesse accettato il marchio della Sincronia, la polizia l'avrebbe trovata e uccisa subito.
«Hai poco tempo per portarla via di lì» disse Aris. Claudio prese il disco sentendo quanto pesasse quella responsabilità. Mentre scendeva di nuovo nei tunnel, tra le montagne l'apparato radio di Sara si spense con un fischio. Lei strappò i cavi e il bosco divenne improvvisamente vuoto di suoni. Le guardie stavano già arrivando, uomini che vendevano i propri amici per un po' di cibo artificiale.
Sara prese lo zaino che aveva preparato da mesi e pensò a Claudio. Quell'immagine le diede la forza di non arrendersi. Distrusse tutto il suo laboratorio con una piccola esplosione per non lasciare tracce e scappò nel buio sotto terra. A Roma, in un ospedale, la dottoressa Renzi rimase ferma al buio quando i computer di Vane decisero di spegnere tutto il reparto, lasciando i pazienti senza aiuto.
Claudio risalì una vecchia scala di ferro che cigolava sotto i suoi stivali. Stringeva la scatola nera anticancer contro il petto e sentiva quanto fosse importante quel segreto. Sfondò una porta pesante aiutato da un operaio delle fogne, uno di quegli uomini che lavoravano al buio e non si piegavano al sistema. Entrò in un tunnel dove l'aria puzzava di uova marce e sporcizia.
L'acqua gli arrivava alle caviglie, scura e schiumosa. Il buio era così forte che sembrava di poterlo toccare, finché una luce bianca non apparve davanti a lui. Era Laura. Stava appoggiata al muro con la pistola in mano, pronta a sparare. Claudio le fece vedere la scatola e lei annuì, ma poi si bloccò all'improvviso.
Un fischio acuto fece tremare le orecchie di Claudio. Due piccoli robot a forma di ragno spuntarono dal tunnel, seguiti dai passi pesanti di una pattuglia della polizia. I robot correvano sui muri con le loro zampe di metallo e gli occhi rossi brillavano nel buio. Laura spento la torcia e ordinò a Claudio di nascondersi. Il primo sparo lacerò l'aria, un lampo di luce che colpì dritto la telecamera di uno dei robot.
Uno dei robot cadde e colpì Claudio al fianco con una forza tremenda. Gli mancò il respiro e cadde in ginocchio nell'acqua sporca, sentendo un dolore fortissimo. La vista gli si annebbio e sentì il sapore del sangue in bocca. Laura lo raggiunse e gli fece una puntura nel collo per fermare il dolore e l'emorragia, poi lo trascinò verso un passaggio segreto per non farsi trovare.
Il medicinale bruciava nelle vene di Claudio come fuoco. Sentiva il sapore del ferro e il buio sembrava battere insieme al suo cuore. Laura lo portò su una piattaforma di cemento asciutta che i netturbini tenevano pulita di nascosto. Lei imprecò a bassa voce e premette una benda sulla ferita. Claudio sentì le costole scricchiolare in un modo che faceva paura.
Cercò di alzarsi, ma le gambe erano troppo deboli e il freddo dell'acqua gli entrava nelle ossa. Ogni respiro gli faceva male al petto. Laura gli ordinò di stare fermo mentre ricaricava la pistola. Intanto, si sentiva il rumore dei manganelli della polizia che sbattevano contro i muri del tunnel.
Si sentiva il ronzio di un altro drone sopra di loro. Claudio strinse forte la scatola nera, proteggendola con il suo corpo: quel pezzetto di metallo era l'unica cosa che ABITES non poteva ancora controllare. Laura guardò verso l'alto e vide le luci rosse dei droni che cercavano il loro calore. Cercò gli occhi di Claudio e gli fece capire che non si sarebbe arresa, poi prese un coltello e si preparò a combattere per proteggerlo.`;
