export const chapter7Content = `CAPITOLO 7 — IL PASSAGGIO ARCAICO

La porta era sepolta fino alle spalle nel tufo e Renato ne trovò il contorno raspando con le dita nel buio della scarpata finché non individuò il punto di debolezza. L'ossido copriva i cardini in una crosta nera e continua ma il logistico inserì l'estrattore contro la prima staffa colpendo con la base del palmo in modo sordo. Claudio stava a poca distanza dalla parete rocciosa con il tallone piantato contro una radice esposta per non perdere l'equilibrio mentre il fischio ai timpani tornava costante e acuto.
L'ultimo bullone cedette e la porta si aprì verso l'interno bloccandosi sui cardini ossidati finché la leva non la spinse a fondo con un gemito metallico sepolto nella roccia. L'aria che uscì era densa di olio rancido e umidità stagnante e Claudio varcò la soglia entrando nel buio totale del bunker dove nessuna scansione di ABITES poteva giungere. Renato scese per primo sulla passerella metallica con la lanterna a carburo e la fiamma gialla proiettò ombre lunghe sulle pareti di tufo rivelando il Fiume Nero che scorreva sotto la griglia.
I cavi riempivano il fondo della galleria da parete a parete con un isolamento in piombo che trasudava olio e rifletteva la luce come la pelle bagnata di un predatore. Renato raccomandò di non toccare le pareti perché la struttura non era messa a terra e la carica residua attiva poteva folgorare chiunque violasse l'isolamento della passerella d'acciaio. Procedettero tra le sezioni incerte della griglia e il drive di Claudio si attivò nella camera dei trasformatori con una vibrazione meccanica che risalì le costole dell'ingegnere come una scarica elettrica.
L'ambiente carico di elettromagnetismo stava inducendo una risposta nel circuito e i led rossi del drive lampeggiavano in sincronia con la frequenza regolare del segnale di Carlo. Laura toccò il bordo del case con le nocche gelate e Claudio interpretò la sequenza che ordinava di procedere ancora più all'interno verso il cuore pulsante del sistema. Trovarono un cavo sezionato poco più avanti con un taglio netto che indicava un sabotaggio recente effettuato con strumenti pneumatici e sopra il quadro di comando spiccava il simbolo Omega.

***

La passerella si restrinse drasticamente e Claudio ne misurò lo spazio con la spalla destra sentendo il metallo gelido dello stipite sfregare contro la fibra della tuta logora. Le gambe si muovevano per un ordine diretto del sistema nervoso mentre il Fiume Nero emetteva una pulsazione elettromagnetica costante che faceva ribollire il sangue dell'ingegnere febbricitante. La fronte grondava condensa e gocce pesanti bruciavano negli angoli dell'occhio ma Claudio non alzò la mano per non perdere l'equilibrio nel corridoio che pendeva sopra l'abisso dei cavi.
Renato camminava poco avanti con le spalle curvate per evitare i condotti del soffitto e controllava i riflessi della lanterna con una scansione ritmica della griglia d'acciaio. La struttura slittò improvvisamente costringendo Claudio a spostare il baricentro con un riflesso istantaneo mentre il calore dei cavi risaliva attraverso l'apertura come il respiro di una macchina viva. Si fermarono entrambi quando un suono organico di respiri lunghi filtrò dalle valvole di deflusso e l'ingegnere pose la mano piatta sul condotto rilevando una vibrazione ritmica e inquietante.
Qualcosa bloccava il condotto principale e avanzarono nel silenzio mentre i sospiri continuavano a premere sui timpani con una cadenza che ricalcava l'attività di un sistema autonomo. Raggiunsero una giunzione dove una scala di alluminio portava al soffitto e Renato notò polvere di grafite fresca sui bulloni segno di un'installazione progettata per essere trovata dai cacciatori. La trappola era il portello che avrebbe causato un'uscita violenta della pressione e lasciarono la scala riprendendo il cammino nella passerella che si restringeva ulteriormente sopra la pulsazione dei cavi.
Il dolore arrivò come un oggetto rovente premuto contro la cavità sternale e Claudio si fermò con le gambe rigide sentendo il drive bruciare sotto il giubbotto in sincronia con i respiri della galleria. I led rossi lampeggiavano seguendo la frequenza indotta dall'elettrostatica e lo strumento ordinava di procedere ancora più all'interno verso la sorgente del segnale nascosta nel buio. Accelerarono il passo sopra la griglia vibrante mentre il drive ardeva contro la clavicola dell'ingegnere e il corridoio dei sospiri pareva respirare insieme a loro in quella discesa nel ventre della terra.`;
