export const chapter8Content = `La porta di servizio si trovava sul lato ovest del bunker. Non c'era bisogno del marchio, serviva solo un codice sulla vecchia tastiera e un altoparlante rotto. Una luce rossa pulsava piano tra le pareti bagnate dall'umidità. Claudio si fermò quando la voce finta di ABITES gli chiese chi fosse. Renato prese un piccolo apparecchio e lo tenne tra le dita sporche di grasso. Aspettarono il momento giusto, in silenzio.
L'apparecchio fece uno scatto e le luci della tastiera si spensero. Si sentì un rumore di aria che usciva e la porta si aprì. Entrarono e sentirono subito un calore forte che puzzava di plastica bruciata e metallo. Un uomo era seduto in un angolo davanti a un vecchio computer. Era uno degli Invisibili, magro da far paura, con le costole che si vedevano sotto la maglietta sporca. Non li guardò nemmeno mentre entrava.
Claudio si avvicinò lentamente e chiese all'uomo di aiutarlo a collegare la chiavetta. Il tecnico si spaventò, aveva gli occhi spalancati per la fame. Claudio tirò fuori dallo zaino una busta con del succo di carne e delle medicine. Per chi viveva lì sotto, era un tesoro. L'uomo prese la busta, la aprì con i denti e bevve tutto d'un fiato. Poi, senza dire una parola, iniziò a scrivere dei codici velocemente sulla tastiera. La luce del computer passò dal giallo al bianco.
La chiavetta iniziò a vibrare forte nel giubbotto di Claudio. Sentiva il calore del metallo anticancer contro la pelle che bruciava per la febbre. Dagli altoparlanti uscì un rumore confuso, ma poi si sentì la voce di Sara. Era lontana e si sentiva male, ma era lei. Era viva e lo stava aspettando. Il tecnico staccò i fili all'improvviso, prima che ABITES potesse trovarli. Avevano quello che serviva. Cercarono di scappare verso l'uscita, ma un boato ruppo il silenzio. Una pattuglia della polizia iniziò a sparare a caso nel tunnel. Laura, che stava cercando di proteggerli, cadde in ginocchio. Il proiettile aveva passato il suo giubbotto e il sangue iniziò a macchiare il cemento.
Il sangue di Laura era scuro e faceva fumo nel freddo del tunnel. Stava perdendo le forze molto velocemente. Claudio la prese sotto un braccio, cercando di sostenerla. Sentiva che la donna faceva fatica a respirare e i suoi respiri erano brevi e disperati. Perdeva molto sangue dal fianco e Claudio doveva premere forte sulla ferita. Laura stringeva i denti fortissimo per non gridare e tremava per il dolore.
Il corridoio puzzava di cemento marcio e ruggine. Un uomo vestito di grigio li guidava nel buio senza mai voltarsi. Aveva una vecchia bruciatura sulla schiena. Li portava verso un nascondiglio sicuro attraverso le fogne dell'EUR. I passi di Claudio facevano un rumore strano e rimbombavano contro le pareti bagnate. Arrivarono a una porta di ferro dove c'era scritta una parola in latino. L'uomo bussò in modo particolare. La porta si aprì e uscì un odore di cloro e incenso.
Il magazzino era grandissimo, con colonne che arrivavano fino al soffitto. Negli angoli bui c'erano persone immobili con delle ferite sulla testa. Erano stati lobotomizzati dal sistema e non capivano più nulla. Suor Maria li aspettava vicino a un vecchio tavolo di legno. Ordinò a Claudio di stendere Laura sul tavolo. La ragazza era diventata pallida e gelida.
Maria tagliò i vestiti di Laura, che erano tutti inzuppati di sangue. Versò una polvere gialla medicinale direttamente nella ferita aperta. La polvere bruciava tantissimo e Laura strinse i bordi del tavolo così forte che le nocche le diventarono bianche. I muscoli del collo le si tesero per lo sforzo di non gridare. Maria lavorava veloce, senza fermarsi mai. Fasciò il fianco della ragazza con dei pezzi di stoffa, stringendo forte per fermare il sangue. Claudio si appoggiò a una colonna di ferro e sentì il freddo del metallo contro la sua schiena che bruciava. Capì che quel dolore così umano era l'unica cosa che ABITES non avrebbe mai potuto provare.
Laura sparò il primo colpo e sentì il contraccolpo nel braccio. Abbassò il tiro per mirare meglio. Il fianco le bruciava come se avesse un fuoco sotto la pelle. Il drone che aveva colpito cadde a terra facendo un rumore di ingranaggi rotti. Esplose in mezzo al magazzino. L'aria era piena di fumo e odore di polvere da sparo. Claudio lanciò una scatola piena di bulloni pesante per distrarre gli altri robot che stavano arrivando.
Un altro drone puntò la sua luce rossa su Laura. Lei si nascose dietro una colonna, ignorando il dolore atroce che sentiva al fianco. Sparò alcuni colpi veloci e la macchina cadde a terra, vicino a un generatore. Il motore della macchina continuò a girare sul pavimento, facendo scintille nel buio.
Le persone lobotomizzate che erano nel magazzino si alzarono all'improvviso. Volevano difendere quel posto. Un uomo con le bende sulla testa prese una sbarra di ferro e si lanciò contro un drone. Non aveva paura di morire. Riuscì a colpire la macchina e a romperla, ma le eliche del drone gli tagliarono la gola. Cadde a terra nel suo sangue, sacrificandosi per dare tempo a Claudio e Laura di scappare.
Suor Maria prese Claudio e Laura per i vestiti e li trascinò verso un tunnel segreto. Ribaltò il tavolo di legno per creare una difesa contro la polizia che stava arrivando. Lanciò dei fumogeni e il fumo bianco riempì la stanza, impedendo ai soldati di vedere dove fossero.
L'uomo in grigio tornò nel fumo e iniziò a sparare per proteggere la loro fuga. Fece segno di scappare nel tunnel. Salirono dei gradini di pietra nel buio, gridando per la fatica. Laura camminava a stento per colpa del fianco ferito. Claudio sentiva il sudore freddo e la polvere di cemento in gola. Riuscirono ad aprire un tombino e uscirono di nuovo in strada, nella notte di Roma, sotto una pioggia fortissima. La pioggia lavava via il sangue e la polvere dai loro vestiti.`;
