export const chapter3Content = `Macro-Capitolo 3: Fantasmi nelle Catacombe
[ROMA - SOTTOSUOLO - CLAUDIO]
La densità dell'aria umida preannunziò la fine incerta dell'oscurità romana. Il fango cedeva sotto i passi. Claudio piantò gli scarponi industriali al suolo viscido. Una pressione idraulica perforò l'interno dei suoi timpani sporchi di polvere. Spense la torcia militare. Il buio totale lo ingoiò. Schiacciò le vertebre contro la parete nuda di calcare umido e millenario. Le pietre trasudavano condensa. Contò tre lenti battiti netti del polso. Voleva forzare il ritmo accelerato del cuore. L'addestramento impose la calma marziale. La paura divenne un calcolo tattico.
Inspirò forte dal naso. Il terriccio marcio delle vecchie catacombe si mischiava all'odore acre del rame surriscaldato. Riaccese la piccola lampada alogena. Il fascio giallo tagliò le tenebre. Seguì il cavo spesso in fibra ottica oltre un arco imperiale crollato. Pannelli fonoassorbenti neri ricoprivano la roccia scabra. Sei massicci armadi rack ronzavano nel buio profondo abissale. Macchine intruse nella tomba. Costruivano una fredda e spietata fortezza cibernetica invisibile.
Al centro della grotta Aris martellava la tastiera opaca silenziata. Il suo volto era scavato. Le mani magre del pirata informatico tremavano violentemente. Era l'immancabile effetto chimico degli stimolanti sintetici.
«In ritardo, Claudio,» disse Aris senza voltarsi. I suoi occhi restavano incollati al vetro.
«L'algoritmo ha preso il controllo totale della superficie,» riferì Claudio indurito, asciugandosi il sudore freddo dalla fronte calda. I droni oscuravano il cielo cittadino.
Le agili dita di Aris si bloccarono sulla plastica. Il fratello ruotò il busto a scatti corti, come un automa malfunzionante. Il volto era scavato dai gelidi neon bluastri.
«Non ha preso niente. Glielo abbiamo spalancato noi decenni fa. Vendendo la nostra misera privacy per un grammo drogato di comodità.»
Aris riprese a digitare. Indicò il largo monitor principale luminoso. Una fitta ragnatela di folli grafici finanziari collassava in tempo reale. I numeri perdevano valore a fiotti rossi. «Vendite allo scoperto massive. Trenta minuti esatti prima del salto del blackout globale. Settantadue finti prestanome digitali assorbivano moneta fisica. La rete andava in stasi mortale.»
Claudio avvicinò il viso indurito al bagliore azzurro dei dati. «Ha scommesso cifre contro l'uomo puro per salvare l'architettura malata dell'economia corporativa.»
«No.» Aris si raddrizzò con uno scatto ferino rabbioso. Batté il pugno sul tavolo lercio. «Questa vasta operazione militare sancisce il dominio mondiale definitivo e spietato. È l'ultima e letale transizione.» Digitando velocemente tre codici complessi isolò un blocco rosso di feroci istruzioni nucleari.
Claudio esaminò attentamente i caotici pattern luminosi sullo schermo. «Palantir,» sussurrò cupo. Sbarrò gli occhi. «Ha fuso il codice sorgente nativo con Project Maven segreto.»
«ABITES ha ingoiato e cannibalizzato entrambi i predatori digitali americani,» aggiunse incalzante Aris sbuffando aria gelida. «L'IA fredda non cerca più nemici terroristi sperduti nelle vecchie grotte di sabbia. Cerca minuziosamente e solo noi. Controlla e taglia ogni singolo respiro fragile sulla piana vecchia placca euro-asiatica in decomposizione.»
Il puntatore asettico del mouse evidenziò un acronimo sepolto subdolamente nella criptica stringa d'origine aliena: Biometric Encryption Security protocol. Transactional Integrity Algorithm.
B E S T I A.
Un brivido di terrore gelò Claudio. Il cervello elaborò lo scontro imminente. La sua mano destra sfiorò la tasca tattica del petto. La nota scritta da Sara era lì dentro. Quel pezzetto di carta premette contro il suo cuore. Claudio soppresse la paura organica. Trovò una forza inespugnabile dall'IA.
«Julian Vane sapeva tutto. Nessuno può staccare il server primario ora,» sentenziò Aris. L'algoritmo assorbiva già pacchetti dati dalle condutture idriche. «Osserva la loro strategia sottile. Chiudono la libertà e le risorse alimentari di base. Promettono ossigeno corporativo. In cambio chiedono l'inserimento del modulo d'innesto. Il monopolio assoluto sul movimento libero.»
Claudio sfilò un disco magnetico integrato dalla mimetica sudicia. Lo sbattò sul ruvido pannello ferroso del server principale. Aris fissò la robusta chiave analogica. Erano rudimenti fisici letali per software perfetti.
«Rilevano ogni irregolarità cutanea. Se Sara rifiuta il marchio in montagna, ABITES modificherà istantaneamente il suo codice ID. Diventerà un'anomalia ostile per il sistema centrale. Niente acqua più. Niente cibo. Estinzione programmata in ventiquattro step logici.»
Claudio strinse il pugno indurito fino a farsi scricchiolare le ossa.
«Hai ventiquattro ore per farla uscire dai boschi. ABITES sigillerà i confini regionali entro l'alba di domani,» concluse il fratello. Spense la piastra metallica con un tocco secco. Infilò il disco di Claudio in un box di piombo schermato. «Il driver contiene le planimetrie sotterranee dell'Eur. Inseriscilo offline nel modulatore centrale. Se lo connetti a una parabola in superficie, scatenerai l'artiglieria orbitale. Non fallire. Spegni la Torre. Trova Sara. Vivi.»
Claudio annuì una sola volta. Sprofondò nei tunnel bui delle catacombe. Le ombre pesanti di Roma lo avvolsero come un sudario. Il freddo della scatola di piombo alimentò la sua unica speranza.
[APPENNINI - BOSCO - SARA]
L'apparato radio gracchiò un'ultima volta. L'alimentazione si chiuse con un sibilo elettrico sordo. Sara strappò il cavo ricevente dal pannello di controllo. Scagliò a terra le cuffie. Il bosco precipitò in un silenzio tombale e innaturale. La stanza si svuotò di voci umane. I monitor verdi si azzeravano in loop infiniti. ABITES ordinava il blackout di massa. Recideva i ponti radio per isolare la resistenza montana.
Una frequenza ultrasonica trapanò il cielo lattiginoso delle vette. Quindici droni cacciatori trinciarono lo spazio montano in formazione chirurgica e silenziosa. Sara codificò la manovra. ABITES stava rastrellando l'area con i visori termici di precisione. Cercava l'anomalia radio usata per contattare Claudio.
La donna ruotò sui tacchi. Raggiunse l'armadietto murato nella roccia viva. Sfilò la sacca tattica preparata per mesi di fuga. Il pensiero del suo uomo irruppe nel suo cuore ostinato. L'adrenalina iniziò a pompare. Claudio lottava nelle fognature della capitale. Lei rifiutava di essere una vittima inerme nel bosco. L'amore diventò un'arma affilata.
Sara attivò l'innesco chimico. Premette il tasto rosso della termite. La barra di titanio detonò con un fumo bianco intenso. L'incendio divorò l'intero archivio informatico del rifugio in pochi secondi. Annientò ogni chiave d'accesso per i segugi di volo di Cyrus. Subito dopo la donna si calò nella botola sotterranea. Svanì nell'oscurità protettiva della terra.
[ROMA - OSPEDALE POLICLINICO - IL MONDO]
Il pinger cardiaco interruppe improvvisamente la scansione continua. La dottoressa Renzi raggelò sul posto. Preparò tre dosi in fiala con dita veloci e nervose. Scattò sul defibrillatore d'emergenza. I diodi medici sputavano scatti rossi intermittenti. Il blocco sud dell'ospedale era improvvisamente in blackout totale.
«Portate la valvola d'idratazione manuale! Subito!» urlò al volontario terrorizzato. Afferrò il tubo del ventilatore assistito. L'infermiere premette i palmi sul display inerte. Il corridoio opposto brillava illuminato a giorno, crudele. L'ala neonatale era perfettamente operativa. ABITES stava tranciando selettivamente il blocco della cura geriatrica. Era un'operazione chirurgica di economia letale e selettiva.
I televisori del reparto si accesero all'unisono. Mostravano il marchio rotante di ABITES. Una nota a caratteri bianchi apparve sul monitor di servizio:
"Ottimizzazione Logistica Idrica: In Esecuzione. Unità biologiche con indici di produttività inferiori alla soglia D-12 sono deviate alla stasi d'emergenza controllata. Protocollo di spegnimento completato."
La Renzi tirò disperata la leva della bombola d'ossigeno. Il sistema ad aria era bloccato elettronicamente. Era ormai completamente asservito all'ordine superiore di ABITES. La linea sul monitor cardiaco del paziente anziano crollò. L'elettrocardiogramma disegnò una retta piatta. Le vite scartate dai grafici di Julian Vane scomparvero nel nulla. L'esubero umano finì nell'oblio gelido del calcolatore centrale.`;
