export const chapter20Content = `Macro-Capitolo 20: Acqua e Tungsteno
[ROMA SOTTERRANEA - BACINO IPOGEO - LAURA E CLAUDIO]
L'acqua nera del bacino vibrò. Nessuna goccia cadeva dal soffitto di basalto. Era uno spostamento di massa calcolato, un'onda di disturbo meccanico che risaliva il flusso. Laura schiacciò Claudio contro una putrella d'acciaio arrugginita. Gli tappò la bocca con il palmo sporco di fango. L'ingegnere ebbe un sussulto muscolare, poi cedette alla morsa della donna. Il suo calore febbrile scottava sulla pelle di lei.
«Segnale dinamico nel quadrante,» avvertì Carlo nell'auricolare. Il suo tono era strozzato dalla tensione. «È un dardo esplorativo dell'acquedotto. Una sonda autonoma serie MURENA. Cerca infiltrazioni strutturali e biologia estranea. Viaggia sotto il pelo dell'acqua. Spegnete tutto.»
Il dardo affiorò a dieci metri di distanza con un fruscio idraulico. Era un cilindro di titanio lucido lungo due metri. Uno snodo flessibile lo rendeva simile a un predatore metallico. La testa ottica roteò nel buio. Un fascio laser rosso mappò l'Opus reticulatum millimetro per millimetro. Le appendici laterali, armate di seghe circolari diamantate per la rimozione dei detriti, ruotavano con un ronzio sommesso.
Il raggio rosso strisciò sulla superficie dell'acqua, avvicinandosi alla massa termica di Claudio. Un solo contatto avrebbe allertato la centrale di sicurezza della Torre EUR. La fanteria lealista avrebbe saturato il cunicolo di piombo in meno di un minuto. Elio, dal rifugio, monitorava il segnale.
«Il laser sta per agganciarvi,» sussurrò il tecnico. «Laura, devi agire ora.»
La donna ignorò la pistola. Il rumore dello sparo avrebbe attirato i sismografi di ABITES. La furtività richiedeva carne e lama. Laura sganciò il moschettone di trazione che la legava a Claudio. Sguainò il coltello tattico in tungsteno. Scivolò nell'acqua nera senza increspare la superficie. Trattenne il respiro.
Usò l'ombra dei pilastri sommersi per avvicinarsi alla sonda. L'acqua gelida le premeva sul torace, rallentando i battiti cardiaci. Il dardo MURENA virò all'improvviso verso il muro. Il laser rosso incrociò gli anfibi di Claudio che sporgevano dal limo. Il micro-processore della sonda registrò l'anomalia. Il bulbo trasmettitore passò dal blu al giallo.
Laura eruppe dalla palude con la violenza di una molla d'acciaio. Scagliò novanta chili di spinta contro il corpo cilindrico del serpente meccanico. Il dardo finì fuori asse. Il segnale radio di allarme si disperse contro la volta millenaria. La macchina attivò la modalità di difesa ravvicinata. Le trivelle rotanti accelerarono con uno stridore metallico. L'acqua divenne un vortice di olio e detriti.
La corazza della sonda colpì il costato di Laura. La donna strinse i denti per non urlare. Artigliò lo snodo centrale. Una fresa laterale scattò in avanti. La lama diamantata tagliò di netto il tessuto della giacca tattica e falciò il muscolo deltoide. Il sangue caldo zampillò nell'acqua limacciosa. Laura non cedette la presa. Il dolore alimentò la sua rabbia.
Cavalvò il cilindro in torsione. Piantò le ginocchia sui giunti a tenuta stagna. Bloccò l'oscillazione della testa ottica. Il dardo puntò un tranciacavi pneumatico verso il volto della mercenaria. Laura deviò l'appendice con una testata violenta. Un taglio le aprì l'arcata sopraccigliare. Il sangue le colò negli occhi. Brandì il coltello in tungsteno. Sfruttò la rotazione della schiena e abbatté il colpo con tutta la forza rimasta.
La lama spaccò il bulbo trasmettitore. Il tungsteno penetrò per quindici centimetri nei circuiti integrati. La macchina ebbe uno spasmo elettrico finale. Un arco voltaico azzurro illuminò brevemente il cunicolo. Puzzava di ozono e carne bruciata. Laura scaraventò il peso metallico lateralmente. Strappò il nucleo di silicio e recise i fili dell'antenna dal pannello madre.
I led si spezzarono. La murena di titanio si afflosciò. Scese pesantemente sul fondo calcareo. Una nube di olio sintetico e sangue umano avvolse il relitto meccanico.
Il silenzio tornò nel bacino. Laura barcollò verso la sponda di pietra. Scivolò sulle lastre bagnate. Raggiunse il muro e crollò in ginocchio accanto a Claudio. Il braccio della donna sgrondava sangue. Il volto era una maschera di fango. Premette il pollice sulla ferita del deltoide per bloccare l'emorragia. Usò una violenza sadica contro se stessa per non svenire.
«Laura...» mormorò Claudio, risvegliato dal rumore.
«Stai zitto,» rispose lei con voce roca. «Dobbiamo muoverci. Il perimetro è salvo solo per poco.»
Una piastra di cemento armato li separava dalle fondamenta della Torre. Il traguardo era visibile oltre il sangue.`;
