export const chapter15Content = `MACRO-CAPITOLO 15: I CINQUE MINUTI DI OMEGA

***

Il bocchettone del clima conservava fumi di calore stantio nei condotti di sfiato termico. Un rimasuglio di temperatura viva rigurgitata da un sistema spento e disarticolato meno di dieci minuti prima. Claudio schiacciò la schiena graffiata contro le feritoie di metallo, incassando quel misero tepore tagliente per non cedere al tremore muscolare del collasso fisico totale.

Il fianco pulsava in onde sporche e violente. Il battito sordo squarciava i tessuti dietro le costole fluttuanti, spingendo lame di calore bagnato lungo la cassa toracica e colando un lago sanguinolento fino all'anca e al ginocchio sfibrato. La giacca imbevuta restava saldata all'epidermide lacera. Il gelo notturno sceso sul tetto di Roma insinuava aghi di vento sotto il tessuto strappato e scorticava il bordo della ferita impastandola in una crosta spaccata ad ogni faticosa, asmatica inalazione di nebbia.

Laura stazionava inginocchiata sul catrame liscio a tre metri di distanza. Il caricatore incastrato tra i palmi lordi di fumo veniva accarezzato dai pollici, abbassando molle e sfilando via l'esile conta del metallo mortale. La Glock fissa alla fondina spezzata conteneva otto colpi e le tasche laterali rigurgitavano gli undici sfilati all'arma scarica di Claudio. Diciannove scatti letali. Pesarono nelle mani nude freddi, cinici e clamorosamente incoscienti di fronte alla fine dei tempi.

Il vano scale rimbombò esplodendo uno schianto infisso sull'intonaco interno.

Laura bloccò i glutei sui talloni irrigidendo di scatto i quadricipiti.

Un secondo colpo riecheggiò seguito da una voce rauca e strozzata, vomitata da una gola arida bruciata di adrenalina tossica e pazzia acuta. Stivali massicci martellarono i gradini rimbombando nel pozzo. Gomma dura, spessa, calciata contro i tralicci di metallo ricalcando un ritmo incespicante, spezzato, affannoso. Tre o quattro fanti blindati schiantati contro le inferriate spingevano forza d'urto macinando l'ultima rampa, cacciati al massacro dal panico asfissiante.

Claudio forzò le palpebre incrostate sputando saliva mista catarro sulfureo sulle grate bagnate.

Laura fissò lo sguardo sugli stinchi dell'uomo, serrò gli incisivi sfregando polvere bianca e ordinò l'attesa sbloccando la sicura in un taglio teso e durissimo del mento. Lui non scompose i tendini e strinse la mano sul metallo del bocchettone, appiattendo il corpo per aggrappare un baricentro svanito col sudore in fuga dalla spina dorsale. Vertigine acida e nausea febbricitante assalirono la cassa ottica. Il sapore del ferro inondava i solchi gengivali permettendogli di masticare il proprio sangue in esofago.

Il portone verde deflagrò sfondando la cornice sputato verso l'esterno aperto.

Il calcestruzzo cedette sotto un calcio frontale furente svitando il telaio di forza. La serratura saltò via a parabola sul tetto rimbalzando sulle lamine e perdendosi. Il battente cieco sbatté sul cemento pavimentatorio in un tuono d'architettura crollata, disperdendo boati sui tetti neri abbandonando fumi chimici sull'urbe andata vinta. 

Irruppero due ombre ingombranti spinte feroci dalla terza. Uniformi d'assalto lealiste nere e balaclava di fibra aramica tirati sui petti tesi zeppi di caricatori e mitragliatrici automatiche stridenti attrito su piastre balistiche. Guardie elitarie di Julian Vane, orfane perentorie della divinità algoritmica protettiva. Spogliati dei sistemi e decapitati dell'HUD fottuto ed estinto. Orbi accecati brancolavano sui raccordi saltati, gettati a terra in panico belvino dall'orrenda disconnessione della Sincronia recisa di netto sul loro cervelletto. Bestie abbandonate a fiutare un massacro per sopperire terrore e vuoto orrendo incastrato su cervelli logori di controllo d'ufficio e piallati di chimica spoglia furente assassina e ignara disillusione acida.

Laura sputò piombo tracciando vampa ignivoma deflagrata bruciando il petto all'ultimo in blocco d'uscita per stordire spinta infetta. Il rumore tranciò venti sbattendo ogive frantumando la grata.

Il primo colpo mancò l'uomo frantumando aria infiammata e polveri scrostate sullo stipite destro assecondando deviazioni sballottate da raffiche furiose gelide sul braccio rigido. Il secondo affondò foro fumante sbiancando spalla infettata bucando kevlar e piastra. Il mercenario lealista di destra incespicò in diagonale piegando le costole sbrecciate e sfracellò la rotula fessa a terra per disperdere pozze lucide d'arteria aspersa sul linoleum in disuso. Il binomio illeso puntò due opposti orientamenti diringendo masse corporali a scaglia buttati ruvidi dietro carcasse metalliche cornicione sventrate tubature relitti parabole antenne accartocciate sul fondo spigoloso d'acciaio rugginoso svenduto per nascondimento.

Fuoco avversario inferno strisciante sputato fitto e crociante pialla il cielo. L'aerostatica squarciò sibili letali tagliando nuvole fumo sputando scaglie proiettili automatici d'elevata sbracante calibrazione sventrando muretti mattoni calcinacci dischi sbriciolati in nuvola nebbiosa tossica spigolosa schiantando macerie sui fuggiaschi in caccia e barricamento forzato ceco letale incallente difese a lamiere rotte sputanti sfregolii rotture bucatura ferro polpa sfracellata tesa infuocata piana asfissiante spingente indietro mortale palla piombo furente cieca pazza assordante mortifera grandine e spacco urto esploso frantumato fesso amaro accecante crudo inferocito. Laura scivolò spalla rovesciando asse gravitazionale sballata su chiazze viscide olio idraulico piantata schiena piatta rasoterra rasente il blocco di Claudio rannicchiando bacino per azzerare bersaglio volume. Due fionde incandescenti perforarono astenia infissa e acciaio a un palmo dall'elice auricolare d'una donna stremata bucando le pompe refrigeranti vuote rimbombando scoppi vuoti d'alvei ferrosi spaccati e deviati cadendo caldi a fumatina mortifera terra asfalto sfrigolante zitte morti vicine sputate fiati andanti rotti incrocia fiamma rotta.

Claudio agguantò canna ruvida trazione Glock disarmata cintolo spinge lombari strisciando schiena su rulli e traccia alzo linea visuale braccio franato sanguinante disteso preme. Non mirò. Premette grilletto spingendo dito a botto doppio tonfo boato polvere espulsa fulminando fessure centrate parabole antenne rottamando carcasse bucate sollevando scorie pezzi fette tagli schegge sassi rovinanti addosso guardie trincerati inchiodandole cucciate chiuse basse timide fermate frenate per comprare frazioni secolari e blocca trancio respiro fognoso lealista stonato rintuzzato cieco asmatico fermato e impallidito. 

Laura assorbì pausa incalzo fuoco lealista slittando ginocchio avanti incuneato spingendo canna forante ottica puntata piombo uscita e vampa sparata forando ombra scatenando scatto cauto lealista fuggente rasoterra bucato coperto ripiego strisciante scosso ritirato afflitto costretto ritrarsi timido timoroso bloccate raffiche forzate e deviate zitte chiuse scese andate e spezzate difese perimetrali e difensivite ostili rincrudite piallate assaltanti andanti fesse sfiatanti fermate cucciate buie rotte sfibrate smontate piallate zero fuoco andato schiantate tese rotte abbassate scurate affossate fermate di trinciante proiettile fermo.

Dodici scatti caldi andati rotolano bossoli accatastati fusi pozza fango fumi acidi bruciati piove buie tetto incrostato polvere grigia odori pece sorde amari spenti freddo tagliente rasoi in zolfo est dispersione buio e relitti relitti città morti piallate andanti spente arse giu rimbombi assordanti di strutture afflitte tonfi barcollanti andati. Sotto i talloni la putrella spina incrinata Torre gemette barcollio distale slargando gettata rovesciata frange rotte esplode tralicci sfregante tubature sordi incrostati metalli frusci sfregolii rotture crolli afflizioni.

Ringhi slavi accartocciarono urla tranciando barriere acustiche venti urlate fumo rocco sboccato sceso da canali comunicativi infetti sciolti e squarciati e disperanti rabbia nuda schiumanti fauci lupi rabbiosi smarriti padrone sguinzagliati guinzaglio reciso disarticolati in furie bestiali assassine scusate vuoto crasso disonorate senza comandi buie in fesse rotte disconnesse cieche ire umane bestiali affamazioni e sciolte su carne da tagliare strappare bruciare e calare rabbia morsa stinta su bersagli incoscienti ignudi affamati morsi bui morsi incrudoliti orfani furia assente schiumante vuoto sbranante aspre umane rinascite selvagge belvine feroci crasse di macello preda e morsa rovinosissima rincrudente letale sbraca folle omicida andante feroce mortale assassinio rabbia schiumata cieca e rotto. Lealista emerse balzo fulmine asfalto fiondato lato orecchio sgombro scudo sfilza asse scoperto fallace scivolata credendo inganni andati fusi crollati di IA bugia e scatto assente finto piallante estinto orrido vuoti incanti calcoli in assenze false macchine andante cieche sfidandosi corsa sbranante. 

Laura anticipò curva scivolante tempia scovando occhio strisciante strillo colpi tre buche livori tranci pettorale abbattuti feriti stanchi crolli e foratura kevlar rotola straziato lealista inciampa sbatte mento bocca asfalto polvere sangue zampa spinge recupera equilibrio precario storta anca prosegue folle afflitto avanza strusciata zoppo rifugia scudo pilastro colato colato nascosto ferito fiato spento zoccolo fermo arso fesso striscia fermato affamato cinto chiuso protetto retrogrado zoccolo via fermata spoglia andante rotta.

Claudio ruotò trazione asse fianco sinistro. Trancio dardo forante ferita squarciò costato esalando stilettate avvelenata perforante letale fesso dolore nero oscuramento ultimo velo vitalità strappata a un passo dall'andare svenuto starnuto tosse buia amara rotto asfittico fiato perso acido amaro sfasato rovinato distrutto rimosse barriere resistenti e ruotò braccio calando tracciata d'angolo terzo mercenario approssimante cornicione rasente vuoto novantasei livelli distruttrice burrone dantesco disceso ombra zero asfalto precipitante nullo volo cadenante caduta inferi asse premente baratro spaventoso sfidante gravità cieca vuoto piallante nero morte assise e fredde nottate sorde crollanti oscurità ingurgita orli tetti. Premette scatto duro grilletti battuti secchezza rintocchi letali e tonfi scossi fessi forando spalla balistica sgominata fesse urla rotte scasso sbocco crollante fiondata sagoma perdente asse slancio braccia pende schiena fende orlo spinge tacchi sbuccia roccia grattacielo vola andante silente inghiottito abisso muto stridulio morto piallante discesa zero fumo polvere fine striscia spalmato asfalto lontano buio cancellata presenza zero svanito polvere relitto. 

Bossoli fumano resti nudi a terra. Tette vuoti caricatori spinti aspre freddezze fesse gelo lame braccia fesse e cucciate andanti zitte tese orripilanti fermi di agguati in caccia di stivaloni nuovi rotti smantellati da scale infinite d'andanti urli rovinati e risposte schiumanti spingitrici di porte infette stivali scrosci sbarramenti abbattuti urla furori stermini disperazioni affollate schiantate caccia scudo fermate e rotte d'ordini rullanti letali infesti. 

***

Il rombo meccanico decapitò i venti tuonanti.

Nessun fruscio ronzante, né zanzare elettriche addormentate in silenzi avveniristici. Un battito sordo, pesantissimo e brutale spaccò le gocce piovane come martelli contro tamburi giganti, squassando e stritolando fumi e atmosfere pregne d'angosce e stesure notturne gravanti e minacciose su aria infuocata pioggia acida schiantanti lamiere cadenti zitte e rudi relitti in picchiata aerea d'un ronzio vibrante ossatura fesse vibrazioni di asfalti cadenti calcestruzzi striscianti tremori stinchi sgrananti orride cadenze andanti rudi antiche d'era passata nuda rozza ingrata e infissa meccanica di ferragli sporchi di grasso catrame lubrificanti ed eliche sbrananti arie dense in burrasche provocate folli e titaniche fesse orride massicce presenze prepotenti al cielo sordo d'inferi spalancate. L'hardware antico di volanti dinosauri senza sottomissione al giogo invisibile informatico sputato di rotori roventi sfalsati analogici padroni ruvidi grezzi spogli letali di volo puro. 

Il lealista schiantato col petto furente alla canna uscì riga mira traccia sbavata di denti sputanti e zoccoli bagnati poltiglia inciampata storta fissando l'alto oscuro.

Dalle piogge colanti acidità spurgata dei cieli aranciati e sfalciati di cenere e fumo scese un ventre d'acciaio massivo, spiovente pance irsute bullonate su nuvolame tossico schiacciato via, ombre nere metallizzate titanica stazza predatrice rapace e mostruosa e storpia veterana sporca. Elicottero corazzato VTOL di generazioni morte riesumate d'aspre officine sotterranee. Ali imbullonate d'assalto rude rappezzato saldature fiammate rugginose infiammante asse fesse esfoliate scrostature verniciature opache. Niente emettitori transponder. Niente laser agganci. Cieche bestie a firme d'ombra piombanti radicate analogiche sfuggite ad ogni tracciante d'incrociatori andanti fessi schianti cieli di truppe cadenti in rotta d'assalto guidate dall'occhio spaccato dell'aviatore puro. Polso su polso a tirare leve ferrose e barre d'assetto manuale sordo andante vivo sbandando raffiche e tormente ad un dito dall'orlo del cratere urbano in picchiata in ascesa zitta d'invisibile dominanza piallante incazzata ed amara ferocia.

Sceso d'infimi gradi incuneò scafo orrendo sbarrando tetrali angolature fisse dodici pance cabrate stazioni e spinse l'apertura carrelli divellendo portelloni scuri rigettando ventri scoperti zoccolanti mitragliatisti fieri imbracciando sputafuoco nere lucide stridenti andanti cariche ed incendiate bocche sputanti in caccia rovente distruzio sfiancanti trincee rotte al letale assedio d'aspre cadute d'immane potenza ignivoma incanalata al fuoco ammazzante su truppe sbandate disperse terrori occhi bulbi sbarrati pioggi e buio fessi d'ansiti smorti d'abites crollante dita fredde sorde urli orrendi frastorni d'ira schiumante al suolo infuso asperso zoccolante polvere distratte cadute affamate d'ossigeni liberi smorzate sibilanti schiantanti rovine fitte rotazioni andante asse rudo rottame in estinzione di carne stesa fessa arsa rotta finita e rottta.

Miteaglia sfavillò bocche roventi. Fuoco soppressivo bestiale. Piombo vulcanico settantadue sparso ruggente urlò deflagro cielo orizzonti radenti.

La grandinata tranciò coperture muri ferri barriere scudi carcasse. Il mercenario sbriciolato in buche spaccati incamerò raffica crociata trivellato spezzante fesso fiondato cadente sboccante sangue polverina incisa sterno abbattuto e polverizzato su striscio terra lercio sfavillante urti scossi inchiostri sfalsanti sbucciatura ferro suino divelto fuso rotolante maciullante stridendo andanti strisci inermi sputate raffiche smantellate e incise a chiodatura asfalti stinti morti piallati ed estinti colpi freddi smorti zitti andanti e piove di fessure asfittica trincea polvere grigia bossolii ottone lucidi roventi rimbombanti salto e fumo dardo rutto fuso andanti macabri rotti letali assassini ed impietosi sfavillanti roteanti a mucchi saltellanti.

Scale vani rimbombi fessi zoccoli andanti orde carichi fiati passi battiti salita calante rossonera sfiatante porta discesa orda calante andanti ascesa irruente massa guardia lealista sbandarti pance cuori furi frenando sfilzanti schiere d'ira nera impiantante disperante vuoto calcolo orrido buca rottura porta. Fuoco fionda tranciarotta assordanti dardi piombo spazzature inferme spezza gambe corazze intonaco e porte zitte sbarrate rinculate sbrodolanti fumi arsi ripiegoserrato trancio muro calante fughe fesse fermo sbarrato piallante orda frenante al riparo trinceale buio affocante calante bloccante d'ignavia sfianca d'urto d'intralcio ostile sordo sbarramento brutale ed implacato di sassi stinti e scarpinate scivolanti ritraenti affondanti sventrature buie rotte cucciate cadute cacciati in sassi calcinanti crolli trancianti rovine scure urla strozzate asfissiate paura panico fuga di topo tranciato chiuso fermato sbarrato incamerato fine fine. 

Sportellone urlò grido spaccato di mascella robusta slava sputando gola cruda scartando boato rotore in rauche fionde linguistiche miste inglese sbattuto crasso ringhiante feroce amaro urlo rovinoso teso appeso cinghie vuoto: «MOVE! VIA! THIRTY SECONDS!»

Laura ingoiò aria zozza annientando inerzie rocciose tricipiti serrati flettendo cinghie fibrose strappi doloranti agguantò deltoidi muscoli feriti Claudio tranciato sfacelo d'ossa infrante buche fessurando sangue infetto crudo doloroso di costato sventrato e stanchezza mortifera sterno lacerato. 

Slanciò spallata cruda erculea tirante massa umana barcollante su. Claudio artigliò suolo spinse rotti nervi stinchi pianto arido polpaccio sceso di sfiancamento rovinoso spintoni suzione letale scuotente urto fesso e vivo respiri in incastri infinti denti spaccati mascelle e bave acida salata bocca schiacciante peso morte andanti ossa rovinosi tonfi carni resuscitati sassi alzati e in piedi verticali stanchi madidi fessi sordi e pesanti d'attrito terra schiantanti in piedi lamenti amari sordi muti sorsi fiati inghiottiti rotti fessi dolenti strisci e dolori crudi fitti asfittici urti colpi e via barcollo passo andante stinco ferro dondoli asfalto scarpe sudate calanti rotte sgangherate pialle spinte fesse cammini. Elicottero urla piomba abbassa sfogando tifone di sberle raffiche mulini schiaffoni urti piogge grandine dardi tempeste raffiche pressando in basso torsioni fesse spingendo in suolo terra venti abbattenti raffiche pieganti ossa e teste andanti andanti e piove di vento amaro taglio rasoio crudo andante su faccia occhi socchiusi palpebre strizzate corsa cieca lenta trascinata braccio a spalla feriti fessi sanguisolenti appoggi incastrati.

***

Tetto limite asse caduta vuoto.

VTOL stazionò millimetrico dondolante furioso bilanciere baricentrico diciannove pollici d'asfalto sbrecciato sospeso vortici urti scarti sfregate lamiere stridulanti rotori rombanti tempeste incrollabili e aspre orrende bestie bilanciate braccio fletto cloche andante umano manico sudato. Cabina dondolo affondo sbarramento scuro rovinoso spaventoso nero incrinato e letale a spingitore stallo discese repentine frenate sorde dondolii precarii letali instabili cadenti assordanti disese ascite rullate andanti barcollanti fluttui burroni mille cieli fessure abisso distratto distese Roma spente spazzature vuoti cieli. 

Colosso carlinga agente tricipite montagna affastellata mimetismo cinghie aggancio ruzzolo fuori braccia tese palancole uncinanti vive mani aspre guanti ruvidi protesi spingenti afferri di trazione e uncini richiamo scatto agganci slancio tirando urlo fesso di gola cruda ruggito gola squarciata coperta rotori furiosi rumori smembramento timpano acuto ronzio andante sordo crudo ferro e piove: «DONNA! LA DONNA!»

Laura arpionò Claudio sbatacchiandolo urto petto strisciata cornicione schiantandolo fronte orlo spinta andante pancia giù. Precipizio dantesco orrido abissale fesso vuoto neri finti e piove d'acqua fredda giù in sberle e andanti vuoti rotti sfidanti oscurità cieca. Spinta calcò sterno urto dande fesse lamenti braccia e fionda Claudio scatto vuoto, sbilancio andante piove d'aria baratro in sbraccio mulinante incrociato asfalto vuoto panico pre-caduta e braccio staccato teso a slancio.

Raffiche vano scale fischiano crepitanti ceche letali disperate follie sparate zizzagando lame roventi tetto dardi sassi schegge saltate urti polveri lamiere rimbombanti schiocchi crudi foranti pance nere elicottero schiantando lamiere aspre e rugginose.

Mano titanica uncinata sorda rocciosa artigliò braccio Claudio sfiorando asse caduta polso unghie grattare pelle. Dita fisse scasso strettoie morse presse mancate, scivolo andante vuoto salto schivo...

Boato scacciò aria decapitò rotore sfalsò mozzo centrale esplose turbina fusa ardente palla gialla fiondata rotta.

Raggio incandescente contraerea silente automatica ultimo sussulto balistico torre crollante tranciò letargica elica maestra spezzandovi mozzo titano schegge volanti dardi arpionati fessi andanti taglienti crudi. VTOL sbandò disarcionato asse vuoto impennata folle ringhi dominatori spaccacieli nuvole sfondate sradicate storte storte urla sorde agenti slavati russi inghiottiti scivolati asfalto lamiere vuoto sordo crollo cabina. 

Elicottero cabra rovinosamente fuso fiamme sputanti squarci orridi asse nero rotore spento incrinato andante picchiata rottura folle dantesca sbandata piombante e precipitò fesso fiondato urto discesa rotta burrone piallato sordo inghiottito abissi smarrito schianto lontano foso e polvere sorda di schianti giu perduti estinti spenti annientati aereo andato zero.

Onda d'urto fiondò schiena Laura petto Claudio schiantati rovesciati asfalto tetto cornicione respinti baratro sbattuti rullate capriole ossa sfregi dolorosi urti griglie bocchettoni e sgasate fumi atterrati doloranti tossenti ciechi andanti e sordi asfittici urti rotti.

Torre cede. 

Non collassi improvvisi crolli sfalsi andanti e rotti di sfaldamenti assorbenti logorii in incamere pesi cede centro pialla ventre sfracella vetrate piove vetri atomizzati sabbia sfonda piani calanti andanti polvere orda grattacielo sussultante barcollante asse portante tranciato fuso piove in sassi nuvole rotti smantellati. 

Claudio rotolante chiazza sporca fissante cieli vuoti fumi fessi ed Europa scura piallata stinta assente arsa stesa di buio totale spazzate estinzioni crollanti. Volo fantasma andato stinto arso polvere. Fine zero fuggiti andanti persi russi estratti zero morti fusi. 

Laura agguantò tesa scatto ruvida fletteta infissa stretta giacca Claudio. Strappo ruvido ossa scosse in piedi a fatica. Viso coperto fuliggine cenere dita fisse ferro. Spostò braccio teso orientando fionda visiva bordo nord ringhiera arrugginita andante tralicci lamiere e scale. 

Scala antincendio esterna. 

Ferro marcio. Buio calante. Burrone estinto. Nessuna via aerea rimasta. Tetto rullante sismi e fumi rovinosi crollanti asfittici nudi. Guardò sasso nero piallato staccò passi rotolanti strisciando trascinando spalla sanguinante su zoccoli sordi. Niente voli. Niente salvi e finti cieli. Cede fesso mondo calante e via ascesa orrida scesa andanti rotti spingendosi botole sguardi grata caduta scalata giù fine tetto piallato. OMEGA morde viscere stese nottati e libere. L'onda pialla via e rotte fesse rudi piove di terra e discesa orrida inizio crolli via scale fesse buie fredde aspre vive e feroci scese.`
