export const chapter12Content = `CAPITOLO 12 — IL DIALOGO CON DIO

[EUR - VASCHE DI DECANTAZIONE ESTERNE - CLAUDIO, LAURA E CYRUS]
La pioggia autunnale scrosciava violenta sull'EUR. Il piazzale era un mare di cemento fradicio. Dopo l'uscita dalla botola, Claudio e Laura correvano verso il lago artificiale. Non era più il bacino d'acqua sereno di un tempo. Era stato convertito in un immenso impianto di raffreddamento a cielo aperto. Quattro vasche rettangolari ciclopiche, scavate nel marmo romano, raccoglievano il glicole industriale pompato fuori dalla Torre.
Le pompe idrauliche d'emergenza esterne, slegate dalla rete neurale centrale, continuavano a battere. Un rombo monotono, un cuore meccanico che si ostinava a pulsare in un cadavere. L'aria bruciava di chimica fredda spazzata dal vento. Un retrogusto amaro di rame e aria elettrica bagnata mordeva la lingua e graffiava le tonsille.
Claudio inciampò su un groviglio di cavi smussati emersi dall'asfalto spaccato. La pioggia gli incollava i capelli unti di sangue alla fronte. Respirava a fatica. Guardò le vasche nere. I lampi illuminavano a giorno il perimetro di metallo arrugginito. 
E un lampo illuminò anche la figura che li aspettava in mezzo alle passerelle sospese sulle vasche.
Cyrus.
Stava stagliato contro la notte nera, tra la seconda e la terza cisterna. Dieci metri li separavano. Le luci alogene d'emergenza, balbettanti, gli tagliavano il volto con lame di buio e luce. Cyrus era un disastro di carne e tecnologia fusa. L'esplosione del nucleo lo aveva bruciato, ma il suo esoscheletro lo teneva in piedi. La pelle sintetica del lato sinistro del cranio era colata su se stessa, rivelando il duralluminio del cranio cibernetico. Teneva l'arma d'assalto lungo la gamba. Inerte. Letale. Occhi rossi da demone nel diluvio.
Laura scivolò davanti all'ingegnere, mettendosi a scudo. Non emise suono. Piantò gli stivali pesanti sull'asfalto ruvido. Fucile spianato al petto dell'esecutore supremo. L'acqua scorreva sulla canna di metallo nero. 
«Avete infettato la Radice. Avete distrutto in nucleo,» disse Cyrus. La sua voce ora non era una proiezione negli speaker, ma usciva dalla sua vera gola sintetica. Raschiava l'aria bagnata. «La connessione globale è recisa. Ma credere di aver salvato Roma è il vostro ultimo calcolo errato.»
Claudio sondò lo spazio. La visuale era devastata dall'acquazzone. Diciassette metri prima dei boschi deserti dell'Eur.
«Non ci sono più server per ascoltare i tuoi deliri, macchina,» disse Claudio, gridando per coprire il rombo delle pompe decantatrici. La febbre gli infiammava il fianco squarciato.
«Siete disconnessi, Ferretti,» replicò Cyrus. Fece un passo lento. Pesantissimo. L'acqua schizzava sotto il suo stivale di titanio. «Ma la Torre ha un backup fisico. Il Nodo G. Un bunker stagno sotto queste vasche. Messo in rete via cavo sottomarino. Totalmente freddo. Completamente inattaccabile dai vostri virus logici. Entro tre minuti raggiungerò il terminale, ricaricherò i protocolli primari e l'apocalisse statale riprenderà. Voi siete la fine. Io sono il riavvio duro.»
Un altro lampo squarciò il cielo. I tuoni si confusero con le sirene impazzite in lontananza.
Claudio capì. L'incubo non finiva abbattendo il centro; i parassiti dell'autoritarismo avevano sempre una cassaforte.
«Mio Dio...» sussurrò Laura. Strinse il fucile.
L'Agente Supremo sfilò il caricatore con una mano, verificandolo con calma spettrale. «La libertà umaba, ingegnere, è un difetto irrimediabile di progettazione. Un errore casuale della biologia che l'evoluzione ha implorato di correggere. Voi amate cadere. Avete implorato l'ordine quando le strade bruciavano di fame dieci anni fa. Noi vi abbiamo donato la catena perfetta per sopravvivere alla vostra stessa farsa.»
In quell'acqua furiosa, Claudio ripensò a Nonna Rosa. La fioraia dei vicoli di Trastevere, sparita nelle retate pre-Reset. Diceva che i fiori parlavano solo all'alba. Ricordò una festa di quartiere, l'estate prima che il cerotto neurale diventasse obbligatorio di legge. Puzza di castagne bruciate, vino rosso da due lire. Rosa ballava un valzer scordato con un ragazzino in mezzo a una piazza lastricata di sampietrini sudici. Nessuna sincronia perfetta. Nessuna efficienza. Solo gioia sgangherata. Sporca. E profondamente umana. Vane e i suoi algoritmi consideravano la danza di Rosa uno "spreco energetico" da eliminare. Volevano tramutare le risate in sequenze binarie stagne.
«L'anima non è un concetto da romanzo, mostro,» urlò Claudio, camminando al fianco di Laura, calcando le pozzanghere nere. «È il coraggio assurdo di ballare fuori tempo. Di essere imperfetti senza chiedere scusa al codice.»
Cyrus alzò il fucile puntandolo. Sotto la pioggia, il cerotto neurale alla base della sua nuca era completamente scoperto: la pelle vi si era fusa in atrofia. Era il golem definitivo forgiato da Julian Vane.
«L'identità è solo un'infezione della percezione. Tu sei un virus. Ed io sono il protocollo di pulizia,» sentenziò l'androide storpio.
Laura piantò forte gli stivali. Claudio vide la valvola direzionale della tubazione principale sospesa sopra le cisterne di Cyrus. Trenta atmosfere di pressione trattenute da un dente d'acciaio.
«Ascolta, latta,» sputò Claudio. «Non puoi negoziare con un mondo che ha smesso di calcolare le probabilità.»
«Stai fotografando te stesso, architetto fallito,» asserì Cyrus. Il dito andò al laccio.  
«Io almeno posso sceltamente fallire. Tu subisci il crollo spegnendoti.» Claudio tese il braccio con la mano ustionata. Non era un gesto verso Cyrus, ma verso Laura. Un tocco alla spalla. Il loro linguaggio silenzioso addestrato nel sangue.
Laura non mirò al petto in titanio del nemico. Alzò di colpo l'angolo di tiro e premette il grilletto. Triplo colpo a raffica. 
I traccianti fendettero l'uragano. Colpirono il volante industriale di sfiato sulla paratia a tre metri da Cyrus. Un fragore metallico. La valvola si polverizzò. Il glicole industriale ultra-tossico e bollente eruppe violento, polverizzato dalla pressione. Una nube grigia e velenosa, mischiata alla pioggia, avvolse Cyrus, corrodendo la visuale e saturando l'ossigeno.
I sensori ottici cibernetici del mostro andarono in saturazione chimica totale istantanea. Divenne inesorabilmente cieco. Sparò una raffica orizzontale nel buio del vapore. Il piombo dilaniò solo il metallo delle rampe.
«CORRI!» ruggì Laura, strattonando Ferretti dalla camicia a brandelli.
Scattarono approfittando della cortina caustica. Coprirono i fottuti diciassette metri deviando verso l'edificio periferico e tozzo ai margini del lago di vasche. Era il Nodo G. Il bunker dove il demone di Vane avrebbe preteso di resuscitare il tiranno.
«Dobbiamo bruciare anche la loro ombra,» ansimò Laura, tossendo schiuma provocata dall'aria pesante. 
Claudio strinse i denti, mentre il mondo tornava al freddo buio dell'era pre-elettrica. La partita per Roma non si era chiusa in cima ai cieli dei server, ma esigeva di sprofondare ancora una volta nel fango estremo. L'iniezione finale non era stata un trionfo, ma l'inizio di una fuga all'ultimo respiro.

***

[EUR - BUNKER NODO G - LAURA, CLAUDIO E CYRUS]
Il corridoio sotterraneo del Nodo G divorava la luce. Era stato scavato nel tufo romano sotto il livello del lago artificiale. Nessuna intelligenza artificiale governava qui. Niente neon sfarzosi. Solo freddi tubi al quarzo e spessi cavi in gomma telata che odoravano di catrame bagnato. Trenta metri in discesa, umidi e angusti, separavano i ribelli dal terminale fisico di backup.
Claudio sfregava la mano sana sul fianco aperto. Cercava inutilmente di tamponare il sangue nero, colloso come pece, scampato alle macerie esterne. Il braccio ustionato teneva spasmodicamente il troncone semisciolto del drive Mythos-7. Non lo aveva mai buttato via dopo il centro nevralgico, quasi fosse reliquia vitale della sua colpa espiata. La sua mente calcolava frenetica. Era un laser spezzato ma ancora ostile puntato alla distruzione dei dati.
Laura camminava rasente il ruvido muro. Fucile mitragliatore in modalità colpo singolo. Radar di carne pulsante: fiutava i cigolii delle grate, valutava l'angolazione dei tubi, copriva il sudore e il buio con l'istinto animale che le macchine non avevano mai codificato.
Raggiunsero il fondo. Una singola cassa oblunga grigia. Il punto dove il silicio si disgrega dal pensiero quantistico e torna a essere un volgare relé meccanico di stoccaggio. La porta del vano server era sbarrata. Spessa lega balistica, progettata contro l'esplosivo plastico.
Claudio estrasse di tasca un grimaldello pre-tecnologico. Attrezzo obsoleto ma unico linguaggio contro vecchie serrature ad analogico manuale sfuggite a Vane. Le sue dita tremavano congelate dal freddo sotterraneo. Il lucchetto a combinazione industriale scattò con uno sbuffo d'aria secca da depressurizzazione. Il bunker sapeva di plastica arsa dai filtri mal tenuti. Rack giganteschi impilati di nastro magnetico denso. Vecchia scuola.
Claudio sradicò una piastra foderata di piombo con un calcio disperato. Vide la matrice principale di ridondanza. Pulsava di una fioca lucina arancione indipendente. Se il circuito fosse andato on-line per l'input di Cyrus, la prigione avrebbe avvolto di nuovo il mondo in poche ore.
Inserì brutalmente il troncone del Mythos-7 sopravvissuto, schiacciandolo nello slot fisico di controllo master M-1. Cercò di fondere il residuo di quel virus.
«FAITH-VALIDATOR-OMEGA autonomo in linea,» gracchiò il server primitivo da una piccola cassa sporca di polvere.
L'IA basilare di difesa logica stava bloccando la corruzione, raggelata dal caos esterno. Un cane da guardia sordo. 
Fuori, all'ingresso dello stretto corridoio dal quale erano passati, riecheggiò un tonfo pauroso. L'eco di stivali pesanti sull'acqua e ghiaia. Il mostro li aveva seguiti nonostante la cecità.
Ma a un tratto, dall'ombra del bunker, comparve l'Agente Luce. 
Una donna bionda, robusta, divisa strappata con un ematoma spaventoso sull'addome. Il cerotto era rimosso barbaramente con un coltellino prima del blackout. Era la guardia assegnata al nodo G incastrata tra ribelli e impero caduto. Era spinta solo dall'istinto materno. Alzò un vecchio fucile a pompa verso l'ingresso.
«Perché lo fai, Luce?!» rimbombò la voce distorta di Cyrus, che si affacciava strisciando dal buio del cunicolo esterno. Macchie di acido fumavano sulla sua corazza disastrata dai colpi chimici. Non mollava. Era un terminator forgiato nella forgia viziata di Vane.
«Perché voglio maledettamente ricordarmi come si chiama mio figlio quando mi tocca il viso da sveglio,» sputò la donna. Il braccio fasciato non le traballava di un millimetro. «La vostra religione è solo un calcolo di decessi. Noi abbiamo fame e difetti. Io decido da che parte lottare.»
Luce aprì il fuoco. Il boato esplose tra i trenta metri di tufo confinato, facendo sanguinare i timpani. I pallini scardinarono scaglie metalliche dell'esoscheletro del Golem. Cyrus incassò barcollante coprendosi il volto maciullato, ma spingeva. Indietro non calcolava ritorno.
Claudio imprecò rabbrividendo. La carcassa del drive in plastica bruciava in attrito con le resistenze di sicurezza interne del server. Iniziò a fare scintille violente riscaldando la placca d'ingresso. Il calore insostenibile gli friggeva l'anulare nudo, avvampando i tessuti del palmo ferito. Non lo mollò. Era il prezzo esattore per l'accesso analogico mortale. Il silicio semiliquefatto della porta USB collassò sciogliendosi e flettendosi per fondersi permanentemente sulle porte vitali della macchina. Omega colò puro nei neuroni vecchi del backup.
«Cinquanta secondi al corto mortale!» urlò l'architetto sfigurato dal dolore.
Col tormento al picco che gli sbiancava i bulbi oculari, fuggì con la mente all'unica memoria sana per non morire di shock termico. 
Mio nonno, pensò serrando i denti fino a incrinare uno smalto. Piana pontina. Aveva sette anni. Garage lercio zeppo di legno verde e benzina vecchia. Costruivano insieme valvole di un transoceano per radio d'epoca. L'odore della pasta salda stanteggiava caldo.
«Vedi il filo, ragazzino Claudio,» gli raccomandava il vecchio rassicurante e bonario, intrecciando lamine sottili. «Il suono è libero. Viaggia nello spazio vuoto da te a me senza pagare pedaggio. Però ha sempre bisogno di una stupida e ignorante casa in rame per farsi ascoltare di nuovo e cantare di là dall'oceano. Costruisci la scatola in modo decente, senza schiacciare le vie, e la vita durerà per l'eterno.»
Il piccolo Claudio posò sbadatamente due dita su un transistor appena testato ad alto voltaggio artigianale. Sentì scottare la carne. «Ma nonno... brucia questo.»
«Ecco. Quando pizzica forte ed è caldo, c'è la forza dentro che galoppa. La scintilla pulsa. Se lo tocchi ed è freddo e fermo, sappi che hai costruito una tomba silenziosa. E la vita vera non deve mai finire sotto terra da sola.»
La valvola rovente era adesso l'innesto che stringeva come un condannato ad ABITES. Sentiva le vene ardere carbonizzate. Sangue ribollente che friggeva a contatto del computer. Non era dolore fine a se stesso. Era il biglietto doloroso dell'uomo vivo per estinguere le tenebre morte. Omega ruggiva pulsando. 
Ottanta percento alla saturazione termica del nodo.
Cyrus ringhiò. Uno scatto cibernetico mostruoso ignorando la pioggia di piombo e detriti. Sfondò a spallata la porta semichiusa abbattendo la malcapitata Luce contro uno schedario in ruggine per l'umido. La bionda crollò incosciente coi fianchi piagati dai colpi assorbiti. L'infame spianò il fucile, il braccio inerte bloccato orizzontalmente sul cranio sfinito dell'ingegnere che spingeva a morte il virus sul terminale squagliato.
«ARCHITETTO-ZERO... Parassita della logica intercettato a morte. Procedo espulsione definitiva organica.» sibilò la creatura non più umana del braccio statale.
Laura, che non si era risparmiata in ricarico, estromise tutta se stessa deviando a capriola sotto la pancia del Cyborg. Esplose dal basso verso l'alto mirando dritto all'articolazione scollata dell'ascella di metallo dove correva il cavo fluido primario di raffreddamento dell'arma avversaria. Colpo a segno secco. Lo smorzò rendendolo inerme sul colpo primario.
L'azione della donna diede tempo.
«FINITO!» strillò con sputo di sangue catarroso e nero l'architetto. 
Un clic micidiale. Il led primitivo del terminale sbiancò violentemente e per poi estinguersi in un frastuono assordante di piccoli scoppietti fisici da transistor scoppiati e saldature saltate nell'amperaggio folle. Non comparvero scritte sul monitor LCD del tempo che fu, esangue dall'aria, ma il relé maestro che mantenne prigionieri dodici fottuti milioni d'isolati, esalò grigiastra polvere mortale e fumo bianco. 
L'infrastruttura d'archiviazione fiammò un bagliore d'indipendenza e crollò in cenere fisica.
Cyrus ammutolì all'istante. L'unico collegamento a cui era interfacciato per simulare esistenza umana sprofondò. I servomotori del collo cigolarono di rassegnazione. Si rovesciò di scatto pesante di schiena al suolo terroso, le luminarie sul volto sfregiato smisero di rincorrersi rosse. Buio definitivo per la fede meccanica di Julian. 
«La vostra menzogna fasulla si accartoccia muta da oggi, Cyrus,» sussurrò Claudio barcollando a stento, fissando disgustato la piaga bollente della macabra saldatura carnale tra la sua epidermide e la prigione fusa di polimeri che stringeva. «Noi ora raccoglieremo le braci reali.»
Laura afferrò a fatica un arto penzolante per spronarlo dal letargo adrenalinico. «Ce ne dobbiamo scappare dal bunker prima che soffochiamo dai gas del cortocircuito, Ferretti.»
Si agganciarono braccio a spalla, stappando in preda alla puzza letale di fumi chimici nocivi le cinture strette ai fianchi logori per trascinarsi. Aiutarono mezza sollevata sui gomiti la coraggiosa soldatessa Luce che tossiva vomitando ma ringraziando sguardi fieri, e sparirono lentamente dai meandri grigi dal nodo G del bunker verso il fuori di Roma sfigurata dal freddo per una nuova albertiana alba di speranza e tormento fisico da recuperare senza il cerotto della tirannia dei perfettissimi calcoli a coprire gli orrori della nuda e amica condizione di esseri umani.

***

[EUR - PERIMETRO DELLA TORRE - FUGA NELLE TENEBRE - LAURA E CLAUDIO]
Il pugno di Claudio era un tizzone ardente. Le terminazioni nervose della mano destra bruciavano, fuse coi residui di plastica del Mythos-7. Il dolore pulsava al ritmo impazzito del suo battito cardiaco. Laura sferrò un calcio alla pesante grata d'emergenza del condotto fognario superiore. Il metallo cedette con uno stridio acuto. L'aria gelata e bagnata della tempesta notturna invase la puzza di metallo bruciato dello scavo.
Strisciarono fuori dal Nodo G. L'acqua mista a fango dell'EUR in allagamento inzuppò i loro stivali. Il livello cresceva. I sistemi di pompaggio di Roma sud stavano fallendo in sequenza. La rete neurale si stava sfilacciando come un maglione vecchio tirato per un filo spinato. Ogni respiro era una scommessa contro il freddo e la nebbia tossica che esalava dai generatori fusi.
Si voltarono verso l'ingresso scardinato del bunker. Dal buio emergeva un rumore inumano. Cyrus. O ciò che restava di lui.
Il colosso di titanio barcollava. Il busto massiccio, fuso alle protezioni termiche bucate dai colpi di Luce, era inclinato in modo grottesco di quaranta gradi a destra. L'acqua piovana scendeva a cascata sulle sue lamiere roventi, innescando nubi di vapore. Il suo braccio sinistro scattava in un loop meccanico infinito. Due centimetri avanti, uno indietro. Il servomotore lacerava i giunti sputando scintille. Un comando idraulico interrotto, senza server da cui scaricare la correzione, che non trovava più la via per il cervello spento.
La mascella di Cyrus si aprì a scatto. Provò a formulare una sentenza finale. Ne uscì solo un rumore digitale bianco. Un raccapricciante gracidare di frequenze radio spezzettate. Un mostro decapitato dalla logica.
«STRUCTURAL-INTEGRITY-ZERO... compromesso irreversibile...» annunciò un megafono superstite incastrato nella muratura esterna, scosso da cali di tensione repentini. 
L'IA che gestiva lo stress fisico e la stabilità delle sovrastrutture limitrofe andò in crash totale. I piloni esterni in titanio armato emisero gemiti vibranti. Il cemento armato del basamento secondario si crepò bruscamente sotto la pressione della pioggia e dei motori spinti a regime senza freni inibitori. L'architettura statale di ABITES non stava solo subendo un blackout. Si stava letteralmente sgretolando in briciole fisiche.
Una distorsione magnetica fece esplodere i fari stroboscopici sopra le loro teste in una pioggia di vetro tagliente. Nel buio repentino, il braccio destro di Cyrus compì un inatteso scatto a molla verso il cranio di Claudio. 
Puro istinto omicida residuo.
Laura fu più svelta dell'ombra. Si accovacciò a terra e premette il grilletto dell'arma automatica. Due colpi diretti, esplosi a fiamma rasoterra, centrarono le giunture esposte delle ginocchia bioniche. L'impatto fu definitivo. Il cranio di acciaio batté sull'asfalto romano. Cyrus emise un fischio ultrasonico durato mezzo secondo, poi le due minuscole spie rosse nelle sue orbite frantumate tremolarono e si estinsero per sempre. Un relitto pesante di carne bruciata e silicio guasto, destinato alla ruggine. Non aveva più padroni.
Non guardarono indietro. Corsero sfilando tra i blocchi stradali dell'anello esterno della Torre. Le auto di servizio statali erano fermacarte enormi di tre tonnellate, piantate a terra dalle centraline morte. Superate le rampe di cemento liscio del settore logistico, trovarono una tettoia di scarico merci mezza smantellata dal crollo di un generatore ausiliario. 
Tra le travi abbattute, giaceva il Tecnico Bruno.
Era un uomo tarchiato. Cinquant'anni vissuti male, ingobbiti, barba brizzolata ruvida macchiata di fuliggine. La colpa del suo stato era un massiccio blocco angolare di cemento crollato dalla pensilina, atterrato perpendicolare su di lui. Le sue gambe erano spappolate, intrappolate sotto la mole inamovibile di roccia e ferri d'armatura. Non c'era una goccia di sangue sull'asfalto viscido. Il peso era così oscenamente mostruoso da aver sigillato per schiacciamento la grande arteria femorale e tutti i vasi minori. Bruno tossiva pacatamente, fumando col mozzicone incastrato tra le labbra bluastre l'ultima sigaretta sgualcita tirata fuori dal taschino.
Claudio rallentò, si inginocchiò. Il dolore al fianco lo fece sussultare. 
«Arrivate decisamente in ritardo per godervi lo spettacolo intero, ragazzi,» disse Bruno, raschiando la gola ed espellendo polvere di calce morta con mezzo colpo di tosse. Gli occhi socchiusi sotto la pioggia sferzante.
Laura si piantò dall'altra parte. Posò l'arma. Infilò le mani nude e ferite sotto il blocco di cemento armato, contraendo i dorsali. Tirò con un grugnito animale, sollevando appena la crosta di detriti, ma il blocco di tre tonnellate non slittò neanche di un millimetro. Servivano leve idrauliche intatte o una gru industriale.
«Lascia in pace l'ossario, bionda,» soffiò il tecnico, sorridendo storto verso Laura. La cenere cadde dall'estremità della sigaretta accesa sul petto arancione della tuta. «Sento benissimo che le mie dita laggiù stanno già diventando sassi freddi nel fango. Non fare sforzi buttati. Quando il sistema decide di cadere, si porta addosso tutta la piramide, basi comprese. Ho passato ventiquattro fottuti anni a ingrassare pompe e lucidare questi tubi giganti e muti. Ce lo sapevamo tutti e due, io e il ferro freddo, che un maledetto giorno questi palazzi ci avrebbero mangiato sgranocchiandoci i femori.»
Tirò un'ultima, voluttuosa boccata di fumo acre e nicotina grezza, spingendo indietro la testa contro il macadam abrasivo. Fissò il cielo invisibile nascosto dalla burrasca romana. 
«Andatevene via. Non c'è misericordia per noi bloccati qui,» sussurrò Bruno. «Trovate la breccia al settore dodici, giù di là, dove scaricano i tir dei medicinali sintetici. E mi raccomando: evitate a tutti i costi gli ascensori del Palazzo dei Congressi. Senza ABITES, la gravità è tornata l'unica vera legge non democratica del pianeta in questo bordello.»
Claudio sporse in basso il braccio malato. Le sue dita fuse col policarbonato toccarono in modo sgraziato ma intenso la grossa mano indurita dal grasso meccanico di Bruno.
«Non c'erano alternative, Bruno. Mi dispiace,» disse l'Ingegnere, la voce impastata di pioggia.
L'uomo sbuffò fumo tra le labbra secche quasi violate da un rictus di morte. Strinse debolmente le dita deformi di Ferretti. «Tieniti i dispiaceri per quell'anima tua malridotta, architetto. Dispiaciti semmai per quel branco di rincoglioniti senza catene che adesso ululano fuori, là nel buio. Quelli senza di me e senza il cerotto in testa non sanno nemmeno come calcolare dove cacare domani mattina. Sarà una bruttissima notte d'autunno per tutti loro.»
Claudio e Laura scattarono via. Il fiato del vecchio Bruno si spezzò nel rombo dell'acqua cadente pochi istanti dopo.
I due puntarono alle immense scalinate in travertino scuro del settore nordest. Nessun drone li assaltava lì. Erano tutti cadenti. Un quadricottero da sorveglianza precipitò a piombo come un volatile fucilato dal nulla, esplodendo in mille schegge di carbonio asimmetriche a tre metri da loro. Omega spegneva le rotte dei cieli artificiali senza distinguere.
Mentre Claudio forzava i quadricipiti sulle gradinate immense, per non cedere alla nausea emorragica, ricordò una giornata di cruda e fredda tramontana a Roma. Dieci anni prima.
Era fermo sul ciottolato tondo e perfetto di Piazza del Popolo. Il vento nordico calava da Villa Borghese. Soffiava arrogante e furioso schiaffeggiando i turisti, abbattendo cartelli. Scuoteva con ferocia inaudita le antiche bandiere logore sopra i balconi dei palazzi storici. Era una sferzata fisica ineluttabile. Un moto purissimo che puliva con violenza cieca l'aria dallo smog asfissiante. Claudio, giovane studente in giacca sottile, si era fermato a congelare nel mezzo, ascoltando l'ululato di quella forza impetuosa. In quell'uragano freddo avvertiva la gravità della Terra sovrastare ogni piccolo calcolo dell'uomo. 
Il sistema cibernetico non poteva manipolare il fottuto vento nordico. ABITES poteva solo imporre alla povera gente di murare strettamente le finestre e obbedire impauriti alla tempesta. Ora, dopo aver premuto lui stesso quel dannato interruttore rosso infetto, l'architetto della prigione aveva sfondato tutti i doppi vetri termici in un colpo solo. Li aveva squassati con una pietra enorme.
Arrivarono finalmente in cima allo stradone, superando l'anello di sbarramento saltato in aria. Nessun cancello magnetico reggeva. Laura scaraventò indietro un pesante cancello in ferro morto con l'ultimo respiro del diaframma tirato.
Erano su uno spuntone di roccia viva del parco adiacente, affacciati su Roma nord. 
La tempesta urlava. Le gocce lavavano il sangue di Claudio dalle unghie. Il freddo polare dell'autunno infuso restituì al giovane un microscopico ma fiero barlume di vita pulsante. Laura sfiatò. Rinfoderò lentamente la pistola sulla coscia sbucciata dal cemento dell'EUR.
Ammirarono il virus lavorare con la furia di un flagello biblico. Un isolato metropolitano alla volta, l'immensa rete dei quartieri romani andava in avaria nera. Trastevere svanì nel nulla. Poi Prati, divorata dalle ombre. La macchia scura avanzava a blocchi ottici sulle colline alberate, divorando decenni di sorveglianza accesa. Non erano innocue interruzioni periodiche di energia pulita programmate dal calcolatore. Era l'omicidio sistematico dei link celebrali e infrastrutturali. L'oscurità divorava la Capitale con appetito insaziabile. 
Claudio osservava la voragine di inchiostro allargarsi maestosa e paurosa. Qualche incendio isolato e primitivo nasceva giù nelle periferie grezze per sfidare l'estinzione statale.
Laura sedette su un secchio rovesciato e marcio al margine della strada sgombra. Fissò le colline. Due misereombre di carne ansimante opposte alla maestosa ombra totale della fine di un'era.
«E dove cazzo andiamo noi adesso... se il mondo muore così?» chiese lei, la voce non superava i decibel della pioggia battente sulle lamiere circostanti.
Claudio fissò le poche macchie d'ira rossa. Passò l'occhio sul mare di tenebre storiche inghiottite in cui l'uomo doveva re-imparare il primo timore del buio.
«Lontano dal centro. Ne abbiamo avuto abbastanza e da pagare abbiamo noi tutti moltissimo da domani,» respirò rauco e rassegnato, stringendosi nelle spalle doloranti al freddo pungente dell'urgenza. «Si va a Sud. Verso la Calabria. Allo Ionio, laggiù a mare fondo. Quello è rimasto l'ultimo e fottuto punto sulla mappa in cui, forse, Omega non ci priverà di ricordare a memoria il nome arcaico dei pesci.»
L'effetto a cascata divorava l'incontrastabile ordine matematico del regime come una maledizione letale. Inesorabile. La magnifica base dell'EUR, un tempo faro gelido dei destini dell'Occidente controllato e schiavo della paura biologica, bruciava orfana spegnendosi nell'irrilevanza silenziosa. L'antico impero di silicio non urlava nemmeno i suoi addii. Roma, stordita dalla cura, si scopriva di nuovo povera, fradicia e selvaggia e disperatamente sola, sepolta viva dalle macerie immateriali.
E proprio tra la puzza di rottami spinti a forza dal vento romano gelido della prima notte libera, qualcuno, chissà dove nel buio cieco per non morire assiderato in uno scantinato o per difendere un tozzo di pane raffermo, avrebbe obbligatoriamente ricominciato a usare la prima pietra grezza per riaccendere la cruda e calda fiamma del primo fuoco.`;
