export const chapter13Content = `Il corridoio premeva col suo soffitto basso e puzzava di cemento secco, grasso vecchio e materiale biologico stagnante che nessun sistema di ventilazione aveva sradicato dall'aria. Trenta metri in retta parallela. Forse qualcuno aveva contato quei trenta metri a scaglioni in un'altra vita, quando l'architettura murale figurava ancora su una pianta catastale utile a qualcosa che non fosse oblio.

Claudio comprimeva a pugno chiuso la fessura sul fianco destro straziata dai tralicci, trascinando le caviglie fangose. Non correva. La corsa terminava due piani sopra, nella decantazione, insieme alla pretesa di aver chiuso l'assedio. La carne viva sotto il metacarpo batteva calda e bagnata, colando denso attraverso le dita. Ogni passo verso lo scolo schiacciava il diaframma. Il dolore affondava cieco senza un fulcro osseo preciso, espanso, sordo e irrimediabile e si irradiava sui muscoli toracici in stilettate roventi quando il piede scorticato graffiava sulle pietre umide.

Laura marciava ritta avanti di cinque metri. Avanzava flettendo i deltoidi senza voltare l'asse visivo sapendo del ritardo dell'uomo dai raschi irregolari del tallone sui giunti sfalsati del muro sinistro, le spalle sfioranti la boiacca d'inutili mattoni. La pistola stazionava bassa. Radar umano indissolubile calato in trincea. 

Il ronzio spaccò i decibel sulle caviglie salendo lungo le tibie. Frequenza morta sradicata dal fondo della crosta. Un fruscio vibrante rimbombava direttamente tra l'avorio delle capsule dentarie. Elettrico. Fisico.

Laura bloccò i quadricipiti.

Claudio arrivò al perimetro accarezzando freddo liscio verniciato. Il portellone. 

Lamiera grigia piombo inassente dalle interfacce neurali superiori in uso. Niente quadri biometrici. Niente spie accessorie. Un telaio di sfogo sbarrato a vite cieca e siglato con un adesivo ingiallito marcio incollato sui cardini ossidati da cicli atmosferici. *NON USARE – MAINT ONLY*. Lettere asettiche sbiancate da cui i prossimi crolli avrebbero rimosso pure il ricordo inchiostrato nascondendolo a eterno uso. 

Claudio estrasse di forza il cacciavite piatto sfilandolo dall'elastico sudicio alla coscia. Il manico intriso dal sangue colato sbarrava il grip ai polpastrelli sbucciati scivolanti sulla plastica irruvidita a vuoto. Strinse la dentatura chiudendo occlusione masseterica pura e avvitò.
Il primo perno trattenne l'inerzia bloccato da ossidazioni vecchie decenni decise a saldare il ferro nella paratia muraria in eterno assestamento fuso. Prelevò asse toracico premendo dorso manovale e peso morto al corpo. Il ferro scricchiolò contro le costole inferiori strappando un fiato mozzato bruciante sprofondato alle ascelle fiammante e disgiunto. Il perno ruzzolò svitato cadendo muto in terra.

Secondo colpo via fluido, asse forzato, il terzo cernitoio crollato divelto dalla fessura espansa per slittamento metallo che urlò attriti sfregati di ruggine sul vuoto dell'archivio sbarrato ai codici centrali. 

La stanza figurava ingabbiata da rastrelliere informatiche marce. Otto colossi obsoleti paralleli in fila e sgombri da piastre decriptive tranne matricole inchiostrate nei decenni d'inizio sviluppo, fiumi intrecciati d'elettronica sfibrata lungo moduli disordinati in apparenza grovigli biologici venosi creati assecondando estensioni senza rigore organico. Il bulbo unico sfitto sul plafone pompava luce secca, atona e livida. La risonanza di sistema divorava spazio. Rombava un fruscio persistente disciolto alle frequenze inferiori, traccia meccanica fissa d'un ronzio perenne processante informazioni dislocate lontano dimentico dalla visualizzazione estetica superiore indotta. 

Il Nodo G. Sventrature hardware e ramificazioni spurie manutenziate al laccio e slegate dall'onniscienza cieca logaritmica. Cavi enormi arpionati e passanti verso l'alveo geofisico e atlantico sotto ere marine originanti radici primordiali molto prima di ABITES medesima. Omissioni documentate al registro matrici rimaste latenti fino a svelarsi tumore fatale irreparabile d'una divinità zoppa d'intrinseca genesi.

Claudio pervenne zoppicando all'argano rack centripeto. Le valvole risuonavano di fioca attività giallo zolfo. Palpitavano infette nel buio come tessuti adiposi in riscaldamento asfittico. Sfregò vite d'acciaio spingendo indietro lamierino incassato sul vano primario svelando scanalatura USB-C. Ficcò con prepotenza muscolare il drive incandescente tra lamelle al silicio e polimeri in rame.

Il led ingiallito abbagliò. Perse frequenza spegnendosi di taglio a zero per risorgere acceso verde iride, vitale. 

Verde solido imperterrito fisso in saturazione mortale.

I passi risuonarono l'aria incanalata prima dello spostamento spaziale fisico tracciabile. 

Graffi disconnessi sbattuti tra le pareti cementizie in rintocchi pesanti ed enormi, rullate sciancate a terra — stivale calato asse fisso intero sul sinistro per bilanciare l'arto opposto zoppicante di ritardo a millisecondo costante imposto, incalzare obbrobrioso incastrato dal meccanismo cibernetico scrostrato senza input fluido sui cavi di conduzione rotulea a metà processamento neurologico saltato, colato su architetture sussidiarie sforzate nel tracciato motorio. 

Cyrus macinava polvere calcinata fusa dal propellente ustionante disceso su dislivelli portanti a volto liquefatto spezzato rincorrendo input di base ABITES forzose per azzerare l'errore umano residuo impiantato nelle trincee nucleo non debellato prima dello shut down infettivo definitivo d'un virus Omega inserito in via distruttrice capillare senza scarti possibili.

Laura accavallò fessura paratia barricata spalle chiuse tenaglia di piombo abbassata e stabile a blocco di trazione fissa spinge ginocchia scaricando asse balistico puro sciolta a zero tremitio vitale senza distogliere focus organico puro predatrice letale fredda al blocco scontro.

«Interferenza nodale estesa livello G calcolata.» L'hardware danneggiato sputò le parole frantumando raschi di segnale audio stridenti contro il muro fuso di un cyber-umanità annichilita e fusa disciolta al collo asimmetrico e rigido privo di tonalità timbrica decodificabile ma solo detrito scosso al megafono terminale squassato al mento liquefatto. «Ferretti. Rimuovi reversibilità sistema applicata. Blocco ripristino interruzione immediata ora.»

Claudio sbarrò gli occhi al led verde.  

Laura spinse anta su apertura sfogo visivo canna armata calcolata sparando tre colpi dritti ravvicinati asfissiando riverberi in micce fulminee da esecuzione esplodenti.

Il corridoio rimbombò fragore accalcandolo su soffitti umidi liscio netto distruttivo secco e definitivo annottando fumi nitrato solforici pollici su aria rarefatta spesa per ricalcolo assetti rullio passo cibernetico inarrestato a rallenty claudicante ferreo calcolato implacabile discesso in baricentro monco ma vivo, persistente orrendo sul suolo infetto incanalato su porta blindata ad ostacolo.

Laura rigirò telaio asse ferroso sbattendo lucchetto riposto cerniera mandata forzata a sigillo estremo sbarrato in faccia di metallo rugginoso chiusa sbatacchiando incasso catena stacco finale barricata salva in piombi sigillati all'aria pesante spesa a terra.

L'interfaccia led fissava l'immortale spettro verde acceso incandescente brillante continuo su scocca e scheda silificata infusa per infettare l'infettabile interezza.

Omega mangiava midollo radice puro.

***

L'interfaccia si carbonizzò esplodendo scintille di rame prima dello sfasamento letale organico al display.

L'accensione logica friggeva surriscaldando termostati azzerati a limiti soglia estrema di guardia fondendo chip schede impazzite accartocciate sul codice inviato stridente al core motherboard schizzato su sedici fusi erroristici incrociando Kernel Panic assoluto, uragano catastrofico d'algoritmi distruttivi disfacenti software di diagnostica sbranata spinta oltre escherichia digitale letale e letargica disarticolata distruttrice dell'esecutore salvatore perenne sprofondato alle budella. 

Il cristallo liquido ragnatelato in diagonale sputò polpa biologica fusa ai margini con plastica bollita fumante densa chimica spessa acre su gola asfittica di Claudio bruciandolo acido tossico e nero d'impianto fiammante interno alla console incernierata al crepuscolo esalato termico d'ignoto processore sbullonato sventrato in collasso totale terminale logico.

Bulbi alogeni ammezzarono scarica caduti a bassi voltaggi per morire fritti sbalzo nero oscuro denso assoluto senza sbocchi e resi fioca luce rianimata smorzata estinta riposata e spenta via per mai riemergere d'elettronica fusa in totale apocalisse calcolata al black out perenne al modulo reciso a monte in base al suolo spento e smantellato defunto perenne logaritmico spalmato a resezioni scure stagne sbarrate stinte a morte cruda silente spettrale su ombre tetre gettate in corridoio sotterraneo orrendo chiuso per crollo stabilità sistemica.

Rumore strozzato emerse rottura calce varco spaccato oltre lamiera rugginosa accartocciata chiara chiostra. Voce multipla inkoordinata sfasata disarticolata umana scossa animalesca spoglia da comandi non decodificata d'urla logica umana ma spavento gemito pianto spasmo incrinato fuso e sversato irrazionale rotto grezzo spezzato di chi strozza lingua al dente mordente saliva persa su pazzia organica terrore ignoto smuovente ossa di gola raschiata nuda dispera sfiancata sfrenata folle senza briglie fisse su cervelletto incastrato al neuro-crack schoccato smembrato fuso via connessioni cerotto disconnesso annaspante.

Laura arpionò stipite sbarrato abbassando maniglia ferrosa sfiorando fessura visiva occhio strabuzzato in ricalcolo orrore. Serrò mascella tranciando scricchiolio dentario e molari incrudoliti.

«Vieni.» Ringhiò voltando nuca spruzzata intonaco crudo. 

Corridoio trasfigurò fisionomia contenutistica spogliandosi stabilità visiva per imbrattare stalli d'orrore su cemento frantumato crudo scosso a colpi boato d'acqua tubaria. Tre umanoidi spogli guardia ABITES divise straziate annaspando pozzanghera gelata fetida a braccia rannicchiate al suolo per scosse elettrocardiache sventrate spasmi orfani panico smarrito persi disagi incrudoliti sbavando sputando vuoti succhi gastrici ammassati su pavimento orrendo strisciato folle per scappare crolli disastrosi infami da scosse folli in caccia disperazione organica infinita scappata da siero veleno infetto su loggia calce strappata unghie sfasata e insulsata di pietà strabuzzanti bulbi all'aria mefitica infiammata di gola orfana su terrore animale risvegliato di colpo brutale su sonno ebreo catartico chimico rubato infamemente da ciclo sincronico sbranato di zanne d'abites smantellato crudo e impuro decapitato sgozzato su cavi terminali esplosi rincrudendo pazzia terrore orrendo sfasato disturbo distruzione distopica di uomini automi decerebrati e macchiati su fogna buia a caccia bava e disorientamento gravitazionale assoluto asfissiante cieco insano al vuoto cosmico barcollamento disincantante infernale sperso impuro distrutto orrido rutto vomitante scolo velenoso fuggente infangante smosso.

La terza strisciava rasente il muro graffiando l'intonaco con i palmi svasati, spinta da un terrore motorio incapace di arrestarsi, graffiando le pareti all'infinito fuggendo fiamme assenti e crolli immaginari o divelti al calcolo rotto scollata impazzimento totale in abisso oscuro bestiale smarrimento asfittico infettato alla bestia domata ora disarcionata da numi protettori recisi e fritti e spariti da cielo finto scrostato e precipitato su volti fradici piangenti sani d'ignoto terrore sbattuti e malconci di risvegli macabro crudo disastroso e crudo mortale smantello apocalittico rincidito. 

Le tempie pulsavano su cerotti inespressivi spenti freddi polimerici morti defunti di transiti inutilizzati gusci sguarniti d'intelligenze recise smembrate e crivellate dal codice fendente in upload micidiale devastatore puro d'annientamento massiccio asfittico globale radice strappata dal fondo calcareo marcio e bruciato alla fiamma pura infame fusa ribellione al dio scrostato dal fango sprofondando abissi profondi incistati in viscere buie terrose umide d'assoluto sfascio d'imperio cagliato rovinato sfatto e disfatto corrotto e debellato smantellato disarticolato sfibrato corrotto in mille mille circuiti saltati arrostiti roventi ustionanti spezzati arricciati smembrati per colpi feroci e deflagrati sventrati per colpi secchi distrutti e sfondati su pavimento orrido fango lurido putrido acqua nera buia spia e veleno salito a ginocchio crudo zozzo puzzolente nero carbone e zolfo fuso a sferragliata mortale letale finale infuocata pioggia acida corrosiva velata d'umido fumo rovente e sfiancante al polmone bruciante fiammelle chimica velenica irrespirabile putrida amara tosse spasmo strozzato asma mortale rincorsa disperata fuggente senza aria fiato sbocco sputo polpa sangue polvere sputi asfissia chiusura collasso totale nero assoluto.

Bava acida incrudolì bordi labiali rannicchiati spastici di nausea termica infondata vomitante rutto marcio su asfalto cementizio asfissiando palati alla caccia per afferro gravitazionale asse fittizio per smarrimento orientamento corporeo distrutto infettato disarticolato impaurito a nervi storditi straziati orfani ciechi folli ammalati straziati infetti da riapproprio improvviso subitaneo sfibrante maledetto colpo incrociato sciancamento ebrezza catatonica malata smarrita pazza irrazionale.

Soffitto rimbombò fragore accalcando tremore instabile strutturale calcestruzzo spaccato e lisi fittonante sfracello idraulica rotta cascate nere scure scendenti lorde pareti bagnanti pavimento coprendolo melma nera scrosci scoli tubi schiantati fontane rugginose scaricanti putridume acido fumo schizzi pozzanghere e buio assolutizzante luci strobo impazzite bianco rosso accecante interrotto crudo saltellante erroristico e finale in black out spezzamento di circuito spogliante scartante respinziente abbattente l'inutile difesa paratia difensiva distrutta da fuoco fuoco virus divorante matrice madre terminale radici recise putride spaccata abbattuta e corrosa sterminata morta andata spenta collassata finita andata terminata scossa disarticolata finita annientata sepolta defunta persa distrutta collassata fusa squagliata sfracellata rotta disintegrata sconfitta e ammazzata spenta ammazzata e andata giù buio rovine pietre su suolo acqua nera salita alle ginocchia stinchi sfiorati liquame corridoio nero fuso sfracello scosso polvere detriti pezzi blocchi ferri urli schianti fumo nero catramato e buio calante occludente soffocante in fuga cecata orfana su scampo disperato via.

Guardia disconnessa sollevò macula acquosa strabuzzata atrofica di segnali mancanti fissando sbarrata ombre sfasate puntando asfittico vuoto orbo non ostile solo spaesato frantumato disilluso orfano atterrito spoglio senza scudo guida bussola rotta orizzonte ignoto disperso vuoto al guscio vuoto dell'io non pervicace riaffiorante timido orrendo spoglio debole incrinato fuso stordito e abbacinato in incubo lucido disumano e straziato orfana dell'abites andata, crollando su ricalcolo biologico tremante su battiti aritmici per terrore scroscio e pianti incastrati a gola ruvida spasmo occhio sbarrato umido e spaurito d'animale rintuzzato spogliato e straziato al panico.

L'acqua saliva fradicia polpacci sporcando suole calpestando rifiuti e residui cavi striscianti serpenti decapitati morti in lago sotterraneo salente infondato di fuga corsa annaspante.

***

Claudio e Laura filavano su oscurità tattile arpionando pareti sbrecciate scrostate bagnate spingendo stivali rotti molli fradici sguazzanti acquitrino lordume liquami e resti sparsi polverizzando chilometri di buca stagna cunicolo fognario in putridume.

Il fianco di Claudio bruciava in un'ustione uniforme radiata verso lo sterno in uno spasmo chimico e le ghiandole saturavano il sangue di adrenalina tossica scorticando resistenza sopperita stringendo mascella incrudolita al passo fradicio per fumo asfittico. Piedi incoccavano asperità pavimentazioni ruvide scartando cavi sverniciati spezzati sbattuti raschiati strappanti fili galleggianti sradicati in cammino folle cieco cieco spalmato di dispera salvezza asfittica strisciante zoccolo e sbreccio cementizio rullando affondi londi acquitrino salito oltre rotule zozzo fangoso bitumoso roccioso scivoloso mortifero nero asfissiato da cieli murati pesanti tonnellate su di sé asfissiando aria di sfinimenti orridi sfiatando e gemendo per soppresso strazio osseo sbranente d'urti rotti botte scosse nervose folli per riparo su salite infinite grate sbattute ringhiere strattonate gradino spigolo buio affondo riaffero strattonate forza braccia perno stanco ginocchio rotto fatica strazio e salvezza di fuoco.

Piombo precipitò piano superiore rimbombando urto sordo multiplo metallico pesante di telai sfracellati droni spenti scagliati giù decapitati e recisi d'impulsi andati disconnessi schiantati a terra disarcionati stinti d'assetti vuoto di spinta rotore seguito dallo schianto metallico sul pavimento superiore orrendo frastuono boato e polvere staccante macigni calcinanti abbattuti droni decapitati e spinti d'orbita spenti.

Rampe grigie scale metalliche fredde di emergenza agganciate mani polsi ruggine scorrente in fuga sangue taglio graffi polvere e buio saliva affannoso cuore sfondante coste e battito pompante impazzito di adrenalina tossica avvelenica e sbreccio aria. 

Lampada alogena superstite rossa sfarfallava sprazzi in guance sudate di Laura e fianco straziato di panni incollati di Claudio appoggiato ansante muro crudo calcestruzzo vibrante, colata su schiena poggiante rotta e sfibrato per arresto battito rovente sfiancamento osmotico d'ansimo straziato polpa alata petto sfiorante colpi martello rotto respiro fiato gola salata e rame spaccato lingua. 

Luce rossa sfibrata pulsante. Il muro raschiò polso di lui tranciando brivido in scossa elettromangetica vibrante e friggente lungo midollo calcificato trasmettente informazione pura radice non detta ma innestata per ricalcolo.

Segnale sputato oceanico vivo scorrimento frequenze sottomarine corse a mille decilitri informatici cavi sommersi intoccati radici antiche ricolmate di linfa letale mortifera infetta propagata su rami marci abbattendoli e bruciandoli sradicandoli spappolandoli infondendo rovescio dominatore sfiancante sbranante matrice scardinando ponti continentali e fusi orari disconnettendoli tagliandoli spezzandoli schiacciandoli per rovine rotture incendi sfasamenti black out estinti sputanti rotture collidenti schiantanti e distruttivi abbattimenti aperti decapitati sterminati folgorati crudi fusi e sfasati per cieli interi fotti in nero tetro ombra spegnendo globi striscianti su neon.

Londra abissata. 

Tamigi nero pece dondolo relitti fritti eliche affoganti tranci di ferro in volo rotto schianti muraglie mattoni polvere droni sbatacchianti pioggia rottami sfrigolanti fuochi inchiostri ombre accalcanti fiumi passanti su strade cieche e pedoni ratti di spavento immobilizzati bloccati fissi orbi sconnessi da segnali decapitati di rete orfani smarriti tremanti cieli guardanti scrosci fusi crudi a bocche asciutte paralizzati immobili statuari spaventi occhi vitrei incauti sfasati di decerebrazione per shock violento e rottura brusca e inenarrata, alzavano la schiena scrutando la calotta buia, orfani improvvisi di un segnale recidito di netto dal midollo fuso asfissiando logiche strisciate via da cervelli scollegati in pianto tremante ignoto barcollante spaurito crudo infante indifeso sterminato e diseredato orfano al mondo buio nero dismesso sceso a scaglioni. 

Parigi sguinzagliata. 

Tunnel bui cunicoli Marais umidi di siero fognario ombra topi squarci sguaiati tombini riversati all'aperto di botole rugginose sollevanti petti robusti e tute luride di fango poltiglia fucili incrostati ex Interpol risorti scampati spiccati all'occorrenza buia occlusione rete fissa monitor scesi di guardia trentadue striscianti secondi varco squama difensiva stesa, balzi d'emergenza stivali pozzanghere mirini spianati fari spenti su ombrello radio fiondante frequenze sputate crittanti antiche riaccese su cielo freddo e aria sgombra di controllo per prima alba di colpi sparati secchi per vie silenziate a sgombero e brecce su asfalto di nazioni oscurate stinte andate a nero pece e spoglie d'armi volanti defunte stese su mattonali schiantate sfrigolanti polveri veleniche di sassi macigni caduti schiantati orridi informi.

Mosca radicata in New Jersey asfittica di ruggine e neve. Algoritmo crudo vintage radio militare cifrato friggente rotella girata trasmettitori antiquati sbavanti sfrigolii di onde su frequenze mute riaperte a capannoni asfittici in sigari bruciati volkoviani petti taurini sfregiati cicatrici ex eserciti distolti. Thiago alzante scartoffia stampata stracciata rilesa decrittata su occhi duri neri pietra ghiaccia fuoco divampato alzando corica poggia fiuma tabacco apre squarcio porta osserva pece cielo steso orbo privo d'ombre artificiali crollanti droni decapitati e spinge scatto di radiofonica urla di ordini sgroppante trupe fantasma al varco d'ingaggio di un occidente crollante fiammelle disconnesso scuro frantumato a ricalcolo di terra orfana di dii finti incatenanti bestie liberate prigioni sfondate fumi fiamme spari buio terrore e libere scelte fiondate su volti insanguinati incrostati straziati infetti crudi duri e roventi rinascenti dalle ceneri polveri sfiancamenti crolli putredini fanghiglie oscure su scoppi rimbombanti macigni stritolanti padroni andati a ramengo orridi fitti sciolti a melma. 

«È partito,» disse Claudio soffiando polvere dalle labbra fessurate, i polmoni vuotati dallo sforzo strisciante fiato mozzato e gola secca acida ingurgitando ozono crudo fetido marcio.

Laura discese scalino frapponendo torace compatto al buio affossamento d'ombra e calore fisico attrito di spalla tozza robusta accorpe al fianco sfibrante uomo distrutto rottami sanguinolento a poggiare e prelevare spinta in spalla premendo presa fissa forte d'aggancio vivo sanguisughivo e letale per stringere ossa su ossa fuggente non crollante.

«Quanto tempo.» Chiese aspra roca rocciosa gola non temibile in trazione logica cruda dura pura ed estrema di mercenaria pura stalla macabro di salvaguardia assoluta d'obbiettivo ultimo. 

«Poco. Via. Marcia.» 

Ginocchia straziarono riaffiorando spinti muscoli sfibrati tendini rotti fusi acido lattico avvelenato disumano flettente sfibrante scalini scorticati graffi sangue rovi strappi unghie polvere in ascesa d'inferi verso via piloni trepidanti di palazzo crollante decapitato di difese orfano di software in disintegrazione scoppi inneschi micce tranciamenti e rotture disallineate in stratosferico reset organico fendente schiantante ed orrendo d'asfissia muraglie schiantanti tonnellate incrociate in sfregolii lamenti sversamenti sfracelli di macigni informi decapitati distrutti andati estinti cancellati piallati su pavimentazioni asfissianti andate giù, spalla forza porta trancia schianta battuta metallo fuso sguancia ed erompe esterno.

Finestra panoramica vetro sudicio e polvere fradicia aria notte freddo abissale inchiostro Roma macchia informe fiammelle fuochi fumo sirene buio scuro spegnimenti sfalsati caos irruzione disconnessioni di globi accaniti di blackout globale a caccia crolli di folle immobili bloccate statuarie al buio macchine spente intersezioni morte silenzi urbani disconnessi rotti in scrosci ed acqua acida, un collasso più strisciante e sordo spalmato su facce spente accucciate inchiodati sull'asfalto, manichini di carne appena de-sincronizzati e smarriti nel reset cognitivo violento e subitaneo rotti sfascianti urla prime rigurgiti panici sgomenti orridi orfani e folli riappropri d'unghie conficcate su carne sgomenta spaurita rinascente su fango polvere macelli asfissie in strade oscure spoglie vuote rotte distrutte spente andate andate e crollanti, padroni rimasti polvere cenere e striscianti e spersi in polverone.

Claudio strinse presa d'arco polso pugno di vetro straziato, svoltando asse visuale su neri di scale fuggente buio e disperato su fuga di detriti e sassi salvanti fuga in aria e strada, a corsa furiosa sfibrante in ginocchia per lottare fiamme nottate cieli sgomenti a vivere. Via.`
