export const chapter21Content = `Il gelo tagliava l'acqua sporca al livello meno undici e squarciava con fitte i muscoli bagnati. Il torace pompava freddo. Le ginocchia intorpidite muovevano a fatica spingendo e spingendo la grande inondazione freddissima infame svelta saliente nera zozza melmosa nera zolfa pungente e scura.
I processori server fumavano morti cotti in fiamme chimiche giallastre nere asfissianti dense oscuranti nocive e nocive asfissianti dense caldissime andate in pezzi bruciati bollenti disfatti spezzati maciullati dal virus immesso e gettato in circuiti caldi neri.
Claudio teneva su il fucile gelido e stringeva l'acciacco doloroso al torace strappando i tendini della costola e assestando botte spesse pungenti asfissianti sordi dolori costanti stanchi duri in fibre rosse e orride spaccate dure andate amari in bocca d'aspro feroce sordo rugginoso sanguigno ferro antico rancido e e forte ferro marcio arido secco gola.
Laura spingeva braccia sfasciate stracciate lerce e sanguinolente e zuppe fredde in pelle coraggiosa dritta fiera muta ferrea decisa ferma insensibile ostinata furiosa stanca umana fiera dura andata irriducibile cruda sorda decisa a non svenire mai per niente vinta duramente viva in freddo cattivo logorante vivo crudo andato spento sporco infame puzzo acido mortifero zoppo e disgraziato andato speso asfissiato. Sopra cavi rigonfi e densi e pronti scoppi creati fulmini bagliori botte scosse scintille andate e morte lampi ciechi nudi disgraziati fessi guaine denudate e andate cadute sfilacciate distrutte sfondate piallate bruciate tritate.
Pugni duri martellarono il portellone divelto e chiodato cieco arrugginito marrone scuro rosso vecchio cieco. Chiusura cigolante bloccata stretta andata sigillata ferma muta inamovibile dura impenetrabile blindata blindata cieca dura.
Laura spianò mitragliatore in ferro vecchiume logorato mani e dita sbiancate contratte livide zozze gonfie sbucciate insanguinate scave tese e iracunde dritte e forti e nervose forti. Claudio sforzò muscoli puntellando asse di ferro forzando cricca in cardini e schiantò sfasciò e ruppe l'entrata zozza.
L'uomo precipitò in bocca ad acqua fango lordura lordo fetido acido putrido acqua viscida torbida nera schifosa puzzolente sudicia.
Stracci azzurri sfilacciati luridi e macchiati unti di nafta in tuta rotta rovinata infame sudicia bucata lisa di sporco acaro unto fetido orrido sudiciume nero macchiato scuro logoro. Due canne arrugginite e cariche si posarono in fronte sfitta all'uomo schiacciato dalla furia delle porte d'acqua e affaticato.
«Saldavo e hanno sbarrato via tre giorni morti e spenti andati scemi.» The uomo tossì sbattendo roba buia catarro sporco acqua e fredda tossente tremante e brividi spappolata rotta a pezzi divelta infame cruda zitta sola a morire e fredda forte.
«Renato,» disse il tizio tossendo sangue.
«Guidaci in superficie svelto ora svelto su.» ruggì Claudio furente sputando condensa vapore in freddo pungente ghiacciato e brutale a sassi bagnati ruvidi orridi spaccati fessi crudi vecchi andati a male andati andati nudi logori spesi male.
«Ovest valvole e pieno fiume infame, canali allagati valvole sgorganti aperte. Andiamo via.»
Tutti sfollarono furibondi stretti al fucile amando chi era lontano spingendo le ferite dimenticate zitte silenti ciechi fredde per andare contro il destino trito freddo andato e via a spaccare cuori infami rassegnati nudi sgangherati infingardi deboli morti per vita amore gioia nudi e forti insieme e umani amando e vivi.`;
