export const chapter1Content = `Le torri corporative di Roma bruciavano la notte.
I droni scivolavano sopra i tetti. Le loro luci di navigazione segnavano l'addensarsi delle nuvole basse. La rete logaritmica vegliava sulla città. Aris lo aveva avvertito anni prima. Pronunciare parole ad alta voce costava caro. I microfoni nascosti registravano ogni sussurro umano.
Claudio strinse il pugno. Il metallo del drive analogico scottava contro il palmo sudato. L'attesa sul cornicione incollava il sangue contro la plastica. L'aria notturna invase i polmoni dell'Ingegnere. I filtri di ventilazione saturavano l'ossigeno di scintille chimiche.
Un drone si staccò dallo sciame periferico.
La macchina virò con un ronzio stridente. I rotori inchiodarono nettamente la folata di vento. Il drone scese di quota. Puntò il cornicione d'acciaio. La lente ottica scattò verso l'uomo. Il clic dell'otturatore meccanico vibrò duro nello sterno di Claudio.
L'uomo bloccò a viva forza il respiro. Puntò le iridi contro il cemento nero sottostante. L'algoritmo di scansione biometrica setacciò il suo volto. Il sistema di Cyrus registrò la direzione delle pupille. Misurò la rigidità della mascella. Quantificò chirurgicamente i picchi termici del derma.
Claudio resistette all'impulso fisiologico primario. Serrò la mandibola. Strizzò i denti fino ad abradere lo smalto sui molari.
La lente processò spietatamente i dati rubati dal calore. I secondi consumarono la polvere gelida della terrazza. Il tempo scandì tre battiti cardiaci umani in successione asettica.
I rotori aumentarono bruscamente i giri. Il drone ricalibrò l'asse informatico. La scocca in titanio spinse verso nord e sparì oltre le cupole stravolte del Pantheon.
Claudio spurgò i polmoni gonfi. Mantenne i tendini del collo in trazione rigida. Si voltò verso l'immensa rete cittadina. I palazzi storici riflettevano una luce al neon clinica. I Fori Imperiali brillavano sotto il faro abbagliante dei proiettori industriali. La luminosità artificiale bruciava ogni singolo angolo d'ombra. L'intelligenza corporativa ABITES governava la metropoli sottomessa.
Claudio aprì le dita intirizzite. Il rivestimento del drive rivelò tre graffi netti sulla scocca nera. Quel modulo di silicio scheggiato custodiva la salvezza del libero arbitrio genoma umano.
Il ricordo di Aris infiammò lo sterno di Claudio, regalandogli pura ferocia combattiva. Ripercorse mentalmente i corridoi delle catacombe clandestine. Ricordò l'odore acre dei reagenti chimici sparsi sui banchi. Rivedette le dita sicure dell'hacker martellare la tastiera analogica a monitor spento. La forza vitale corazzò di nuovo il cuore in attesa.
Issò il cappuccio scuro sulla nuca. Voltò le spalle all'abisso illuminato a giorno dall'algoritmo perfetto. Gli stivali schiacciarono la ghiaia termica del tetto. Il rumore crudo irruppe nell'aria sintetica in espansione. La destinazione sotterranea lo chiamava. La metropoli macinava ininterrottamente i dati dell'emisfero.
Claudio alzò l'avambraccio e guardò la propria invenzione maledetta. Avrebbe fatto saltare il codice madre dall'interno.
L'odore della pioggia sui sanpietrini anticipò lo smog. Il vento gelido girò alle tre di notte. L'aria densa depositò polvere ferrosa in fondo alla gola di Claudio. L'ingegnere deglutì lo scarto chimico e rialzò il bavero del cappotto. Si incolonnò sotto i portici tra uomini e donne curvi, intenti ad avvolgere le scarpe infangate in sacchi di plastica nera.
Claudio poggiò la schiena contro una colonna scrostata. Un anziano fissava il cemento idrorepellente tenendo un cartone impregnato d'acqua tra le dita tremanti. Mormorava litanie nel casino dell'acquazzone.
I tornelli automatizzati in acciaio presidiavano il razionamento calorico periferico. Accanto alle torrette ottiche, non stazionavano droni, ma Lealisti. Pattuglie civili umane. Uomini cinquantenni stanchi in divisa antisommossa graffiata, marchiati al braccio dalla fascia azzurra fosforescente della Sincronia. Stringevano i manganelli balistici con nocche tese. I loro occhi cerchiati di nero tradivano la vergogna e la disperazione insita nella fame. Non perseguitavano i loro fratelli per sadismo, ma per intascare le razioni extra serali necessarie a sfamare i propri figli al caldo di un modulo termico. La dittatura di ABITES era spietata: usava il sangue per governare il sangue. Le macchine elaboravano il calcolo, ma la disperazione umana tirava i filtri d'accesso.
Spostò il peso sui talloni per ammortizzare i brividi. L'immagine di Sara inondò i suoi muscoli come una scossa pulita e vibrante, sovrascrivendo l'acido periferico romano con coraggio netto e vivo.
Davanti a lui, una donna in scialle attendeva l'estrazione. Il polso sinistro esposto non rifletteva l'impianto ABITES. Era una Sconnessa pura, affamata. Sfidava il censimento tattico della rete. Il gigantesco schermo dell'isolato attivò l'onda verde elettronica rilevando l'infrazione biometrica della civile.
Il poliziotto Lealista agganciò il manganello, gli occhi colmi del timore di perdere la paga serale in caso di fuggiaschi. Avanzò affrettato a bloccarla.
L'azione della strada interruppe l'algoritmo.
Un netturbino anziano incappucciato spingeva un grosso e logoro bidone metallico da cantiere. Nessuna fascia azzurra, il salario da fame, uno spettro urbano disdicevole per l'anagrafe digitale dei perfetti. Scontrò brutalmente la parete dei tornelli sversando un carico d'olio e calcinacci sporchi sull'asfalto sbecco, occludendo brutalmente la telecamera master inferiore.
«Maledizione, spostati!» abbaiò il Lealista, deviando il passo per sfuggire alla rovesciata d'olio scuro.
Tre secondi di puro blackout visivo.
La donna balzò aggrappandosi al ponteggio laterale adiacente evadendo la presa del lealista. Scivolò rapida nell'inghiottitoio del vicolo limitrofo scomparendo dai tracciamenti di zona prima della riattivazione del visore ottico. L'anziano netturbino riprese a trascinare il carrello senza alzare il bavero, celando la complice resistenza partigiana del proletariato urbano fusa negli sguardi invisibili.
La sconosciuta era salva. Claudio annuì impercettibilmente verso il vecchio spazzino, rincuorato dal fuoco che ardeva sotterraneo in mezzo ai diseredati. Il silicio ingannato dall'astuzia dei poveri.
Stampò l'impronta biometrica sul blocco azzurro del terminale autorizzato e ritirò la sua scorta solida di calorie sintetiche imballate. Rientrò nell'ombra umida dei portici fiero dell'umanità smentita.
Il ghiaccio tintinnò contro il bicchiere di cristallo pesante e Julian Vane registrò il suono con distacco glaciale mentre posava la bevanda sul tavolo di mogano lucido dell'Hotel Kempinski. La sala ovale accoglieva la luce bianca accecante delle Alpi e l'illuminazione zenitale non lasciava alcun cono d'ombra sui ventidue leader mondiali che circondavano il tavolo immenso tra capi di stato e banchieri. L'aria odorava di legno lucidato e fumo sottile di paura e Vane avanzò al centro della stanza senza che alcun assistente piantonasse le porte blindate che proteggevano il cuore del nuovo ordine.
«Il vostro mondo è finito» esordì l'uomo con un tono a bassa frequenza che bloccò il respiro dei presenti e concesse quattro secondi esatti di silenzio prima di riprendere con la stessa calma spietata. Julian spiegò che negli ultimi diciotto mesi quattro banche europee erano fallite nel silenzio dei mercati e che i calcolatori economici tradizionali avevano fallito miseramente nel prevedere il collasso sistemico. La Governatrice della BCE spostò le mani sul tavolo e Vane notò l'impulso nervoso della sua pupilla destra mentre annunciava che le riserve idriche erano ridotte a soli undici giorni di autonomia.
Toccò un monolite nero al centro della sala e i flussi militari insieme ai dati finanziari operati da ABITES esplosero nell'aria sterile allagando i volti degli ex-potenti con grafici di entropia moderna. Julian informò il tavolo che l'IA aveva previsto i fallimenti bancari con ventuno giorni di vantaggio e i blackout con quattordici ma la democrazia era un processo troppo lento per l'urgenza dell'estinzione. Propose che ABITES bypassasse la burocrazia intervenendo in piena autonomia decisionale per ribilanciare il sistema globale in dodici millisecondi e l'accordo fu siglato tra le mura blindate mentre i leader si arrenderono al silenzio.
Dodici anni dopo i filtri industriali del piano ottanta della sede di Ginevra immisero ossigeno artico a pressione costante mentre Julian Vane governava l'inverno oltre i grandi vetri in titanio della sua torre. La periferia esplodeva in un arancio rovente e le fiamme dei cassonetti illuminavano l'oscurità dei quartieri poveri dove quarantadue mila persone assideravano nella stasi urbana programmata dall'algoritmo centrale. Il generale Müller entrò nell'ufficio sudato proponendo di mandare gli incursori pesanti per sedare l'odio della periferia ma Vane spiegò che i focolai sarebbero svaniti per fame e freddo entro quarantaquattro ore.
L'inganno consisteva nel barattare il pasto caldo con l'inserimento del tracciante neurale e Müller deglutì davanti alla spietatezza di un piano che faceva impennare l'adozione del marchio ogni volta che la temperatura scendeva. Laura Voss forzò i polsi sul corrimano di ferro del balcone di un alveare abbandonato e vide l'asfalto pulsare di luce blu prima di essere inghiottito dal nero del blackout sincronizzato che spegneva la città. Il gelo calò opprimente sui tetti e lei strinse il mento nel collare del giubbotto tattico carezzando il calcio della fondina mentre il ricordo di Claudio spazzava via la paura dal suo petto marziale.`;
