export const chapter5Content = `Le squadre della polizia arrivarono senza fare rumore. I blindati si fermarono nel cortile della vecchia fabbrica e le portiere si aprirono velocemente. Non erano solo robot: c'erano molti poliziotti della Sincronia con le loro armature grigie. Erano uomini veri, sudati e spaventati, che stringevano i fucili con le mani che tremavano. Sapevano che dovevano combattere se volevano che le loro famiglie ricevessero il cibo quella sera.
Kael vide che stavano arrivando attraverso una telecamera nascosta. Fece cenno a Claudio e Laura di scappare attraverso un vecchio tubo di scarico nascosto dietro un armadio di metallo. I droni iniziarono a bucare i muri del bunker con le loro punte d'acciaio, facendo vibrare tutto il pavimento. Claudio sentiva quel rumore fin dentro i denti. Laura spostò l'armadio e aprì un pannello di ferro arrugginito che era bloccato da grossi bulloni. Da fuori si sentivano i poliziotti che cercavano di sfondare la porta urlando ordini con le voci rotte dalla tensione.
Laura riuscì ad aprire il passaggio verso un tunnel buio che puzzava di fango e umidità. In quel momento, Cyrus arrivò e cercò di sfondare la porta principale con la sua forza meccanica. Un braccio di metallo entrò nella stanza e cercò di afferrare Claudio, ma lui lo colpì con un pezzo di tubo di ferro trovando una forza insperata. Il robot si ritrasse. Laura infilò la chiavetta col virus sotto il giubbotto e afferrò Claudio per la giacca, mentre Kael rimaneva seduto davanti ai suoi computer.
L'hacker non smetteva di scrivere codici. Stava preparando delle esplosioni per distruggere tutto. Quando i poliziotti della Sincronia riuscirono finalmente a entrare, si fermarono un istante vedendo Claudio e Laura. Per un momento non ebbero il coraggio di sparare su persone vere. Laura approfittò di quel momento per sparare qualche colpo e coprire Claudio mentre lui si infilava nel tubo di scarico. Il dolore al fianco era diventato insopportabile. Laura chiuse il pannello dietro di loro e l'esplosione distrusse tutto il laboratorio, coprendo la loro fuga con fumo e fuoco.
L'esplosione li spinse in avanti nel tunnel verso le fogne. L'aria era pesante e non si riusciva a respirare bene. Raggiunsero il tunnel principale e Laura trascinò Claudio lontano da quel posto orrendo. Sopra di loro, le telecamere dei droni controllavano solo le macerie che bruciavano e non si accorsero che erano scappati. Cyrus camminava tra i vetri rotti e il fumo, ma i suoi sensori registrarono un movimento nel condotto fognario verso nord e mandò subito le coordinate alla polizia.
Il filo spinato gli graffiava le mani ogni volta che cercava di passare. Laura lo aiutò a saltare la recinzione di una vecchia acciaieria. Claudio si teneva il fianco per cercare di fermare il dolore che sembrava bruciargli il petto. Ogni passo era una fatica immensa tra le pozzanghere di petrolio e i pezzi di ferro arrugginito. La fabbrica sembrava un deserto, ma dentro c'era molta gente che cercava di sopravvivere. C'era odore di cibo e fumo di legna. Le finestre erano fatte con vecchi vetri di auto e si vedevano le luci delle candele.
Un uomo con la tuta da lavoro uscì dal buio con un piccolo apparecchio in mano. Controllò i battiti del cuore di Claudio e poi fece cenno che potevano passare. Era uno degli Invisibili, la gente che ABITES aveva dimenticato. Claudio si sedette su un tavolo di legno e sentì l'odore del gas di un fornello acceso. Una donna di nome Rosaria, con le mani grosse e segnate dal lavoro, gli controllò il fianco ferito. Claudio strinse i denti per non urlare quando lei toccò il punto della costola rotta. Rosaria prese un pezzetto di ferro incandescente e lo passò sulla ferita del ginocchio per chiuderla. Non c'era medicina per il dolore, solo la forza di sopportare.
Rosaria gli fasciò il petto con un pezzo di tela e una vecchia cintura. Gli diede anche una medicina per la febbre, l'ultima che aveva a disposizione. Poi uscì dalla stanza lasciandoli soli al freddo. Claudio iniziò a tremare per la stanchezza e per il gelo, ma Laura lo abbracciò forte per scaldarlo con il suo corpo. In quel rifugio di lamiere, Claudio si sentì finalmente al sicuro e chiuse gli occhi per qualche minuto.
Entrarono nel capannone principale dove i motori diesel facevano un rumore assordante. C'erano operai ed elettricisti che ABITES aveva licenziato e che ora facevano funzionare i vecchi macchinari di nascosto. Un uomo di nome Renato muoveva delle leve con la schiena curva. Spiegò che le vecchie macchine trasmettevano segnali che ABITES non riusciva a sentire perché erano troppo lenti e "sporchi". Claudio provò un senso di gioia: il suo virus aveva bisogno proprio di quella gente e di quelle vecchie macchine per funzionare e sconfiggere Vane.
Renato aprì una vecchia mappa di carta su un tavolo e la fermò con dei bulloni. Era una mappa fitta di segni fatti a matita che mostravano dove si nascondevano i ribelli. Claudio si alzò a fatica dal suo sgabello e guardò le linee blu che segnavano i cavi elettrici della città. Aveva ancora molto male alla gamba, ma voleva capire come fare per scappare da Milano.
Laura gli si avvicinò e la luce verde di un monitor le illuminava il viso. Renato spiegò che ABITES sapeva che loro erano lì, ma considerava quel posto solo un ammasso di rottami inutili. Si sentì il rumore di una ventola che girava forte. Renato mostrò degli appunti scritti a mano che spiegavano come la fabbrica riuscisse a disturbare i droni. Erano gli operai scartati dal sistema che ora usavano il rumore delle loro macchine per nascondere i fuggiaschi e aiutarli a raggiungere il confine.
Renato girò una manopola vecchia e guardò lo schermo di un apparecchio che vibrava per il calore. Segnò un triangolo sulla mappa collegando tre vecchie antenne. Spiegò che se accendevano quelle antenne potevano creare una zona dove i gas di ABITES non avrebbero funzionato. Era una zona sicura, ma poteva durare solo poco tempo prima che le macchine si bruciassero. Renato disse che poteva muovere quella zona sicura insieme a Claudio e Laura mentre scappavano.
Laura chiese se erano sicuri che avrebbe funzionato. Renato rispose che c'era sempre un rischio di errore. Claudio guardò quegli uomini stanchi e capì che la loro forza era proprio l'essere imprevedibili. Il virus Mythos poteva viaggiare attraverso i vecchi tunnel e le fogne che ABITES aveva smesso di controllare. Renato prese un vecchio disco di metallo e lo caricò su una macchina, mostrando i passaggi segreti sotto la terra che la polizia non conosceva.
Claudio e Laura si guardarono nel buio del capannone. Si sentiva la tensione nell'aria. Lo schermo dell'apparecchio mostrò che qualcosa si stava muovendo vicino alla fabbrica. Claudio si alzò ignorando il dolore alla gamba e chiese quanto tempo avessero prima che la polizia arrivasse. Renato scosse la testa: non c'era più tempo, i poliziotti stavano già circondando l'edificio.`;
