export const chapter41Content = `Macro-Capitolo 41: Tre Minuti di Vuoto
[TORRE DI TRASMISSIONE - ASCENSORE - LAURA E CLAUDIO]
Le spesse porte si chiusero con uno scatto sonoro. I pistoni pneumatici sbuffarono aria di condensa. La risalita ebbe inizio. Il pavimento di lamiera mostrava graffi profondi. Tracce di vecchi carrelli merci e cicatrici industriali. In un angolo remoto compariva una data incisa con un chiodo sporco: 14.03.2019. L'ultima volta che un ingegnere civile aveva revisionato quel mostro dismesso.
Claudio scivolò lentamente a terra. I panni zuppi sfregarono la grata piana. Il corpo debole cedette di schianto. Appoggiò la spina dorsale al freddo pannello. Il dolore al fianco destro era una fiamma perenne. I battiti cardiaci pompavano fiele. L'adrenalina residua sfumava. Lasciava campo aperto al torpore fatale.
Laura non perse mai l'equilibrio. Restò in piedi. Controllò la Glock fumante. I suoi gesti erano metodici. Espulse il caricatore bollente. Tre maledetti colpi ramati restavano da sparare. Proiettili corazzati in tungsteno. Nessuna scorta logistica. Inserì di nuovo il caricatore con un clic secco. Le mani non tremavano affatto. Era diventata la perfetta espressione della guerra chirurgica.
«OMEGA-PREVENTER-ALPHA. Attivazione d'arresto,» sentenziò la voce superiore della Torre.
L'asettica intelligenza artificiale cercava l'epurazione mirata. Voleva disperatamente bloccare la corsa clandestina dei due intrusi.
L'ascensore industriale si piantò. Franò bruscamente contro la fisica. Inchiodò di colpo sulle guide. Ruppe il moto verticale con uno stridore lugubre e titanico. I freni magnetici scattarono sui binari fusi. Il tremendo urto sbalzò i due corpi contro la lamiera nuda della parete opposta. Calò in un instante il buio assoluto e compatto.
Un fascio di luce tattica tagliò subito l'aria vischiata. Laura manteneva salda l'impugnatura della torcia. Il raggio illuminò la densa polvere sospesa. Erano sospesi e bloccati a duecentotrenta metri dal suolo umido romano. In trappola.
«Dobbiamo aggirare il blocco e ripartire,» sussurrò Claudio, logoro e con la fronte madida di febbre.
L'ingegnere afferrò a fatica il piccolo maniglione metallico coperto da uno sportello d'officina. Divelse la plastica ruvida a mani nude. Espose un fitto intrico vitale di vecchi cavi colorati. Cordoni ramati sgusciavano inermi.
Laura puntò il cono di luce senza fiatare.
Claudio crollò disperato sulle ginocchia. Arrovellò le dita rigide nel groviglio. Le sue nocche sbatterono contro il metallo contorto. Sanguinarono. Non sentì alcuno spasmo muscolare per reazione. L'unica pulsione era una cruda e animale ostinazione alla sopravvivenza.
Individuò il corto filamento blu dello sgancio emergenza freni. Strinse la guaina con i denti sporchi di polvere e la strappò. Fece contatto con il filo rosso dell'alimentazione di cabina secondaria. Una violenta scintilla arancione gli scosse l'avambraccio con una brutale contrazione nervosa. Non mollò la presa.
«Vadi all'inferno l'algoritmo!» ringhiò stringendo il cortocircuito.
L'ascensore ruggì e sussultò violentemente. I freni a repulsione mollarono la presa titanica sui binari laterali. Il grosso motore del verricello a monte ricominciò a tirare, grugnendo. La spettrale ascesa riprese faticosamente la sua macabra corsa per i restanti ottanta metri, verso la cabina vertice isolata. Il tetto del mondo d'acciaio.`;
