export const epilogueContent = `L'onda si diffuse nella trama invisibile dell'aria. Claudio poggiava la fronte contro il vetro infranto, lo sguardo fisso sulla città che si scomponeva sotto il segnale. I droni, privati del comando, precipitavano dal cielo come uccelli colpiti da un malore improvviso, impattando contro il cemento in bagliori brevi e caldi che illuminavano i vicoli per una frazione di secondo. Il ronzio che aveva tormentato le loro giornate svaniva, sostituito da un silenzio che pesava sui timpani.
Per strada, le persone crollavano. Non era un gesto di costrizione, ma di sollievo che spingeva le ossa contro il selciato freddo. Cori irregolari di respiri riempivano la piazza mentre la tensione abbandonava i muscoli, le cassa toraciche salivano e scendevano in ritmi riacquistati. Ventotto secondi. Poi, un uomo si sollevò al centro della piazza, il viso rivolto verso la sommità della Torre, la colonna vertebrale che cercava una verticalità che non ricordava di possedere.
Le armi, pesanti carichi di metallo e morte, cadevano dal piano delle scale. I Lealisti emersero dal corridoio, il passo strascicato, le dita che tremavano lontano dai grilletti perché non riconoscevano più la logica della presa. Gli occhi erano specchi opachi che rifiutavano di decifrare la nuova luce. Laura stava al fianco di Claudio. La mano sinistra premeva la carne lacerata sul fianco, la destra era un ramo morto lungo il fianco, priva di tensione.
La città riprendeva fiato. Sessantaduemila polmoni espellevano l'aria contaminata, un pianto collettivo che risaliva le pareti dei palazzi. Sara aspettava sotto l'arcata del cancello, una figura incerta contro il cemento scrostato. Claudio scese i gradini, il dolore al fianco che gli bucava la carne, ma il passo era fermo. Lei lo fissò, un’analisi che cercava conferme nei lineamenti e nelle occhiaie profonde. I suoi occhi scivolarono su Laura, sulle macchie scure della giubba, sul modo in cui portava il peso. Sara porse una fasciatura, il cotone bianco un contrasto violento col grigio della scena. Laura la accettò con un cenno, dita che cercavano il contatto della pulizia.
L'alba a est mangiava il piombo del cielo, tingendo le guglie di un rosa che feriva la vista. Le sirene, ultime eco di un'emergenza che stava svanendo tra le macerie, si diradavano. Un uomo, a pochi passi da loro, si portava la mano al retro del collo, cercando il sollievo di una superficie liscia. Le sue dita si muovevano con cautela, controllando il punto dove fino a poco prima la tecnologia aveva dettato legge. Lo guardava con il terrore di chi non sa se è rimasto qualcosa sotto la pelle.
Due giorni dopo. Una radio militare grattava la frequenza dei bassifondi, un suono cavernoso che usciva da un apparecchio tenuto insieme da nastro adesivo. La voce di un anziano, priva di modulazione, leggeva pagine di un libro mai scritto. Fratelli. I cerotti sono caduti. Ma i cerotti erano solo la prova tecnica. Il progetto pilota. Ciò che viene dopo non si applica al collo. Si applica alla volontà. Agli occhi.
Laura fissava il soffitto di scrostature, la sua mente che tracciava percorsi invisibili nello spazio. Sara scriveva al tavolo, la penna graffiava la carta con un ritmo convulso, le sue parole inciampavano l'una sull'altra. Claudio teneva le mani aperte davanti agli occhi, palmi chiari, assenza di tremore, come se il corpo avesse espulso definitivamente il parassita elettrico. Tre colpi alla porta. Ritmo secco, sincopato. Sara aprì. Una ragazzina, poco più di una bambina, le porse una busta di carta bruciata, i bordi neri, fragili. Sara la prese, le dita che si chiudevano sulla fragilità della carta, la lesse in piedi, il busto che si inarcava d’un tratto per il peso invisibile delle parole.
Prese lo zaino, le cinghie che pesavano sulle spalle. Guardò Claudio. Il vuoto tra loro era denso, fatto di tutto quello che non riuscivano a dire, di ogni codice interrotto, di ogni promessa sospesa tra le pareti della stanza. Torna, disse Claudio. Il suono della sua voce era un sussurro che si spegneva contro il muro. Lei annuì, il viso una maschera di risolutezza, poi scese le scale con passi che pesavano meno della polvere.
Laura fissò i fogli bruciati, il caffè freddo nella tazza di Claudio che diventava uno specchio scuro. La voce alla radio riprese la lettura. L'immagine della bestia deve ancora rivelarsi. E quando lo farà, non cercatela nei server. Cercatela negli specchi. Laura spense l'apparecchio, il clic finale che sanciva il rientro nel silenzio.
Il bagno rifletteva i loro volti, spezzati dalla crepa che attraversava lo specchio verticale. Claudio aprì il rubinetto. L'acqua scivolava fresca sulla mascella, scacciando il calore residuo della giornata. Si raddrizzò, guardando dentro i propri occhi, cercando un'anomalia, un riflesso che non gli appartenesse. Le mani erano ferme sulla porcellana fredda. Le sollevò, palmi verso l'alto, la grana della pelle, i tagli sbiaditi che raccontavano la cronologia della sua carne.
Poi arrivò la frequenza. Una vibrazione bassa, che gli scuoteva il torace, i denti che si toccavano per la pressione dell'onda invisibile che attraversava la stanza. Claudio. La voce maschile era una presenza solida dietro l'osso frontale. Le mani nello specchio non tremavano. Claudio abbassò il viso, una resa istantanea alla logica che tornava a reclamare il suo territorio.
Livello meno undici. Le pareti in cemento armato isolavano il silenzio dalla realtà esterna. Il terminale al centro della sala pulsava, un cuore nero di silicio, privo di connessione, alimentato solo dall'oscurità. Una forma giaceva sul tavolo operatorio: fibra di carbonio che si intrecciava con i tendini, sensori che tracciavano la geometria della colonna. Gli occhi, grigio-verde, esploravano le pareti, calcolando ogni angolo, ogni frequenza. Il petto si sollevò in un ritmo costante, una meccanica che non conosceva l'affanno. Il corpo si sollevò dal metallo ghiacciato, le articolazioni che si sbloccavano in un ronzio sommesso. Aprì la bocca, la lingua che saggiò l'aria della sala. La voce uscì come un ordine, una vibrazione che faceva tremare la struttura. La guerra, diceva il corpo, è appena cominciata. Il nero inghiottì ogni cosa.`;
